/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Realtek npu_pp video m2m and capture v4l2 driver
 *
 * Copyright (c) 2024 Realtek Semiconductor Corp.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 */

#ifndef __NPP_RPC_H__
#define __NPP_RPC_H__

#define S_OK 0x10000000

#ifdef CONFIG_RTK_CACHEABLE_HEADER
/* Ring Buffer header structure (cacheable) */
struct RINGBUFFER_HEADER {
	/* align 128 bytes */
	unsigned int writePtr;
	unsigned char w_reserved[124];

	/* align 128 bytes */
	unsigned int readPtr[4];
	unsigned char	r_reserved[112];

	unsigned int magic;
	unsigned int beginAddr;
	unsigned int size;
	unsigned int bufferID;
	unsigned int numOfReadPtr;
	unsigned int reserve2;
	unsigned int reserve3;

	int	fileOffset;
	int	requestedFileOffset;
	int	fileSize;
	int	bSeekable;

	unsigned char	readonly[84];
};
#else
/* Ring Buffer header is the shared memory structure */
struct RINGBUFFER_HEADER {
	unsigned int magic;	//Magic number
	unsigned int beginAddr;
	unsigned int size;
	unsigned int bufferID;	// RINGBUFFER_TYPE, choose a type from RINGBUFFER_TYPE

	unsigned int writePtr;
	unsigned int numOfReadPtr;
	unsigned int reserve2;	//Reserve for Red Zone
	unsigned int reserve3;	//Reserve for Red Zone

	unsigned int readPtr[4];

	int fileOffset;
	int requestedFileOffset;
	int fileSize;

	int bSeekable;		//Can't be sought if data is streamed by HTTP
};
#endif

enum ENUM_AUDIO_KERNEL_RPC_CMD {
	ENUM_KERNEL_RPC_CREATE_AGENT,
	ENUM_KERNEL_RPC_INIT_RINGBUF,
	ENUM_KERNEL_RPC_PRIVATEINFO,
	ENUM_KERNEL_RPC_RUN,
	ENUM_KERNEL_RPC_PAUSE,
	ENUM_KERNEL_RPC_SWITCH_FOCUS,
	ENUM_KERNEL_RPC_MALLOC_ADDR,
	ENUM_KERNEL_RPC_VOLUME_CONTROL,
	ENUM_KERNEL_RPC_FLUSH,
	ENUM_KERNEL_RPC_CONNECT,
	ENUM_KERNEL_RPC_SETREFCLOCK,
	ENUM_KERNEL_RPC_DAC_I2S_CONFIG,
	ENUM_KERNEL_RPC_DAC_SPDIF_CONFIG,
	ENUM_KERNEL_RPC_HDMI_OUT_EDID,
	ENUM_KERNEL_RPC_HDMI_OUT_EDID2,
	ENUM_KERNEL_RPC_HDMI_SET,
	ENUM_KERNEL_RPC_HDMI_MUTE,
	ENUM_KERNEL_RPC_ASK_DBG_MEM_ADDR,
	ENUM_KERNEL_RPC_DESTROY,
	ENUM_KERNEL_RPC_STOP,
	ENUM_KERNEL_RPC_CHECK_READY,   // check if Audio get memory pool from AP
	ENUM_KERNEL_RPC_GET_MUTE_N_VOLUME,   // get mute and volume level
	ENUM_KERNEL_RPC_EOS,
	ENUM_KERNEL_RPC_ADC0_CONFIG,
	ENUM_KERNEL_RPC_ADC1_CONFIG,
	ENUM_KERNEL_RPC_ADC2_CONFIG,
	ENUM_KERNEL_RPC_HDMI_OUT_VSDB,
	ENUM_VIDEO_KERNEL_RPC_CONFIG_TV_SYSTEM,
	ENUM_VIDEO_KERNEL_RPC_CONFIG_HDMI_INFO_FRAME,
	ENUM_VIDEO_KERNEL_RPC_QUERY_DISPLAY_WIN,
	ENUM_VIDEO_KERNEL_RPC_PP_INIT_PIN,
	ENUM_KERNEL_RPC_INIT_RINGBUF_AO,
	ENUM_VIDEO_KERNEL_RPC_VOUT_EDID_DATA,
	ENUM_KERNEL_RPC_AUDIO_POWER_SET,
	ENUM_VIDEO_KERNEL_RPC_VOUT_VDAC_SET,
	ENUM_VIDEO_KERNEL_RPC_QUERY_CONFIG_TV_SYSTEM,
	ENUM_KERNEL_RPC_AUDIO_CONFIG,
	ENUM_KERNEL_RPC_AIO_PRIVATEINFO,
	ENUM_KERNEL_RPC_QUERY_FW_DEBUG_INFO,
	ENUM_KERNEL_RPC_HDMI_RX_LATENCY_MEM,
	ENUM_KERNEL_RPC_EQ_CONFIG,
	ENUM_VIDEO_KERNEL_RPC_CREATE,
	ENUM_VIDEO_KERNEL_RPC_DISPLAY,
	ENUM_VIDEO_KERNEL_RPC_CONFIGUREDISPLAYWINDOW,
	ENUM_VIDEO_KERNEL_RPC_SETREFCLOCK,
	ENUM_VIDEO_KERNEL_RPC_RUN,
	ENUM_VIDEO_KERNEL_RPC_INITRINGBUFFER,
	ENUM_VIDEO_KERNEL_RPC_SETRESCALEMODE,
	ENUM_VIDEO_KERNEL_RPC_SET_HDMI_VRR,
	ENUM_VIDEO_KERNEL_RPC_CONFIGURE_GRAPHIC_CANVAS,
	ENUM_VIDEO_KERNEL_RPC_SET_MIXER_ORDER,
	ENUM_KERNEL_RPC_DEC_PRIVATEINFO,
	ENUM_KERNEL_RPC_ALSA_FASTER,
	ENUM_VIDEO_KERNEL_RPC_PAUSE,
	ENUM_VIDEO_KERNEL_RPC_STOP,
	ENUM_VIDEO_KERNEL_RPC_DESTROY,
	ENUM_VIDEO_KERNEL_RPC_FLUSH,
	ENUM_VIDEO_KERNEL_RPC_Q_PARAMETER,
	ENUM_VIDEO_KERNEL_RPC_CONFIGCHANNELLOWDELAY,
	ENUM_VIDEO_KERNEL_RPC_PRIVATEINFO,
	ENUM_VIDEO_KERNEL_RPC_QUERYDISPLAYWINNEW,
	ENUM_VIDEO_KERNEL_RPC_SETSPEED,
	ENUM_VIDEO_KERNEL_RPC_SETBACKGROUND,
	ENUM_VIDEO_KERNEL_RPC_KEEPCURPIC,
	ENUM_VIDEO_KERNEL_RPC_KEEPCURPIC_FW_MALLOC,
	ENUM_VIDEO_KERNEL_RPC_KEEPCURPICSVP,
	ENUM_VIDEO_KERNEL_RPC_SET_DEINTFLAG,
	ENUM_VIDEO_KERNEL_RPC_CREATEGRAPHICWINDOW,
	ENUM_VIDEO_KERNEL_RPC_DRAWGRAPHICWINDOW,
	ENUM_VIDEO_KERNEL_RPC_MODIFYGRAPHICWINDOW,
	ENUM_VIDEO_KERNEL_RPC_DELETEGRAPHICWINDOW,
	ENUM_VIDEO_KERNEL_RPC_CONFIGUREOSDPALETTE,
	ENUM_VIDEO_KERNEL_RPC_PMIXER_CONFIGUREPLANEMIXER,
	ENUM_VIDEO_KERNEL_RPC_SET_DISPLAY_OUTPUT_FORMAT,
	ENUM_VIDEO_KERNEL_RPC_GET_DISPLAY_OUTPUT_FORMAT,
	ENUM_VIDEO_KERNEL_RPC_SET_ENHANCEDSDR,
	ENUM_KERNEL_RPC_HDMI_EDID_RAW_DATA,
	ENUM_VIDEO_KERNEL_RPC_ConfigWriteBackFlow,
	ENUM_VIDEO_KERNEL_RPC_NPP_Init,
	ENUM_VIDEO_KERNEL_RPC_NPP_Destroy,
	ENUM_KERNEL_RPC_AFW_DEBUGLEVEL,
	ENUM_KERNEL_RPC_DV_ControlPath_Info,
	ENUM_KERNEL_RPC_GET_AFW_DEBUGLEVEL,
	ENUM_KERNEL_RPC_ConfigureDisplayWindowDispZoomWinRatio,
	ENUM_VIDEO_KERNEL_RPC_GET_MIXER_ORDER,
	ENUM_VIDEO_KERNEL_RPC_SET_DISPLAY_OUTPUT_INTERFACE,
	ENUM_VIDEO_KERNEL_RPC_GET_DISPLAY_OUTPUT_INTERFACE,
};

enum VIDEO_VF_TYPE {
	VF_TYPE_VIDEO_MPEG2_DECODER = 0,
	VF_TYPE_VIDEO_MPEG4_DECODER = 1,
	VF_TYPE_VIDEO_DV_DECODER = 2,
	VF_TYPE_VIDEO_H263_DECODER = 3,
	VF_TYPE_VIDEO_H264_DECODER = 4,
	VF_TYPE_VIDEO_VC1_DECODER = 5,
	VF_TYPE_VIDEO_REAL_DECODER = 6,
	VF_TYPE_VIDEO_JPEG_DECODER = 7,
	VF_TYPE_VIDEO_MJPEG_DECODER = 8,
	VF_TYPE_SPU_DECODER = 9,
	VF_TYPE_VIDEO_OUT = 10,
	VF_TYPE_TRANSITION = 11,
	VF_TYPE_THUMBNAIL = 12,
	VF_TYPE_VIDEO_VP6_DECODER = 13,
	VF_TYPE_VIDEO_IMAGE_DECODER = 14,
	VF_TYPE_FLASH = 15,
	VF_TYPE_VIDEO_AVS_DECODER = 16,
	VF_TYPE_MIXER = 17,
	VF_TYPE_VIDEO_VP8_DECODER = 18,
	VF_TYPE_VIDEO_WMV7_DECODER = 19,
	VF_TYPE_VIDEO_WMV8_DECODER = 20,
	VF_TYPE_VIDEO_RAW_DECODER = 21,
	VF_TYPE_VIDEO_THEORA_DECODER = 22,
	VF_TYPE_VIDEO_FJPEG_DECODER = 23,
	VF_TYPE_VIDEO_H265_DECODER = 24,
	VF_TYPE_VIDEO_VP9_DECODER = 25,
	VF_TYPE_VIDEO_H264lv51_DECODER = 26,
	VF_TYPE_VIDEO_CAPTURER = 27,
	VF_TYPE_RAWCONV = 28,
	VF_TYPE_TVD = 29,
	VF_TYPE_VIDEO_ENCODER = 30,
	VF_TYPE_VIDEO_SPLITTER = 31,
	VF_TYPE_VIDEO_AVS2_DECODER = 32,
	VF_TYPE_VIDEO_AV1_DECODER = 33,
};

enum INBAND_CMD_GRAPHIC_FORMAT {
	INBAND_CMD_GRAPHIC_FORMAT_2BIT = 0,
	INBAND_CMD_GRAPHIC_FORMAT_4BIT = 1,
	INBAND_CMD_GRAPHIC_FORMAT_8BIT = 2,
	INBAND_CMD_GRAPHIC_FORMAT_RGB332 = 3,
	INBAND_CMD_GRAPHIC_FORMAT_RGB565 = 4,
	INBAND_CMD_GRAPHIC_FORMAT_ARGB1555 = 5,
	INBAND_CMD_GRAPHIC_FORMAT_ARGB4444 = 6,
	INBAND_CMD_GRAPHIC_FORMAT_ARGB8888 = 7,
	INBAND_CMD_GRAPHIC_FORMAT_YCBCRA4444 = 11,
	INBAND_CMD_GRAPHIC_FORMAT_YCBCRA8888 = 12,
	INBAND_CMD_GRAPHIC_FORMAT_RGBA5551 = 13,
	INBAND_CMD_GRAPHIC_FORMAT_RGBA4444 = 14,
	INBAND_CMD_GRAPHIC_FORMAT_RGBA8888 = 15,
	INBAND_CMD_GRAPHIC_FORMAT_420 = 16,
	INBAND_CMD_GRAPHIC_FORMAT_422 = 17,
	INBAND_CMD_GRAPHIC_FORMAT_RGB323 = 18,
	INBAND_CMD_GRAPHIC_FORMAT_RGB233 = 19,
	INBAND_CMD_GRAPHIC_FORMAT_RGB556 = 20,
	INBAND_CMD_GRAPHIC_FORMAT_RGB655 = 21,
	INBAND_CMD_GRAPHIC_FORMAT_RGB888 = 22,
	INBAND_CMD_GRAPHIC_FORMAT_RGB565_LITTLE  = 36,
	INBAND_CMD_GRAPHIC_FORMAT_ARGB1555_LITTLE = 37,
	INBAND_CMD_GRAPHIC_FORMAT_ARGB4444_LITTLE = 38,
	INBAND_CMD_GRAPHIC_FORMAT_ARGB8888_LITTLE = 39,
	INBAND_CMD_GRAPHIC_FORMAT_YCBCRA4444_LITTLE = 43,
	INBAND_CMD_GRAPHIC_FORMAT_YCBCRA8888_LITTLE = 44,
	INBAND_CMD_GRAPHIC_FORMAT_RGBA5551_LITTLE = 45,
	INBAND_CMD_GRAPHIC_FORMAT_RGBA4444_LITTLE = 46,
	INBAND_CMD_GRAPHIC_FORMAT_RGBA8888_LITTLE = 47,
	INBAND_CMD_GRAPHIC_FORMAT_RGB556_LITTLE = 52,
	INBAND_CMD_GRAPHIC_FORMAT_RGB655_LITTLE = 53,
	INBAND_CMD_GRAPHIC_FORMAT_RGB888_LITTLE = 54,
};

enum INBAND_CMD_GRAPHIC_RGB_ORDER {
	INBAND_CMD_GRAPHIC_COLOR_RGB = 0,
	INBAND_CMD_GRAPHIC_COLOR_BGR = 1,
	INBAND_CMD_GRAPHIC_COLOR_GRB = 2,
	INBAND_CMD_GRAPHIC_COLOR_GBR = 3,
	INBAND_CMD_GRAPHIC_COLOR_RBG = 4,
	INBAND_CMD_GRAPHIC_COLOR_BRG = 5,
};

enum INBAND_CMD_GRAPHIC_3D_MODE {
	INBAND_CMD_GRAPHIC_2D_MODE,
	INBAND_CMD_GRAPHIC_SIDE_BY_SIDE,
	INBAND_CMD_GRAPHIC_TOP_AND_BOTTOM,
	INBAND_CMD_GRAPHIC_FRAME_PACKING,
};

enum VO_STANDARD {
	VO_STANDARD_NTSC_Mi,
	VO_STANDARD_NTSC_J,
	VO_STANDARD_NTSC_443,
	VO_STANDARD_PAL_B,
	VO_STANDARD_PAL_D,
	VO_STANDARD_PAL_G,
	VO_STANDARD_PAL_H,
	VO_STANDARD_PAL_I,
	VO_STANDARD_PAL_N,
	VO_STANDARD_PAL_NC,
	VO_STANDARD_PAL_M,
	VO_STANDARD_PAL_60,
	VO_STANDARD_SECAM,
	VO_STANDARD_HDTV_720P_60,
	VO_STANDARD_HDTV_720P_50,
	VO_STANDARD_HDTV_720P_30,
	VO_STANDARD_HDTV_720P_25,
	VO_STANDARD_HDTV_720P_24,
	VO_STANDARD_HDTV_1080I_60,
	VO_STANDARD_HDTV_1080I_50,
	VO_STANDARD_HDTV_1080P_30,
	VO_STANDARD_HDTV_1080P_25,
	VO_STANDARD_HDTV_1080P_24,
	VO_STANDARD_VGA,
	VO_STANDARD_SVGA,
	VO_STANDARD_HDTV_1080P_60,
	VO_STANDARD_HDTV_1080P_50,
	VO_STANDARD_HDTV_1080I_59,
	VO_STANDARD_HDTV_720P_59,
	VO_STANDARD_HDTV_1080P_23,
	VO_STANDARD_HDTV_1080P_59,
	VO_STANDARD_HDTV_1080P_60_3D,
	VO_STANDARD_HDTV_1080P_50_3D,
	VO_STANDARD_HDTV_1080P_30_3D,
	VO_STANDARD_HDTV_1080P_24_3D,
	VO_STANDARD_HDTV_720P_60_3D,
	VO_STANDARD_HDTV_720P_50_3D,
	VO_STANDARD_HDTV_720P_30_3D,
	VO_STANDARD_HDTV_720P_24_3D,
	VO_STANDARD_HDTV_720P_59_3D,
	VO_STANDARD_HDTV_1080I_60_3D,
	VO_STANDARD_HDTV_1080I_59_3D,
	VO_STANDARD_HDTV_1080I_50_3D,
	VO_STANDARD_HDTV_1080P_23_3D,
	VO_STANDARD_HDTV_2160P_30,
	VO_STANDARD_HDTV_2160P_29,
	VO_STANDARD_HDTV_2160P_25,
	VO_STANDARD_HDTV_2160P_24,
	VO_STANDARD_HDTV_2160P_23,
	VO_STANDARD_HDTV_4096_2160P_24,
	VO_STANDARD_HDTV_2160P_60,
	VO_STANDARD_HDTV_2160P_50,
	VO_STANDARD_HDTV_4096_2160P_25,
	VO_STANDARD_HDTV_4096_2160P_30,
	VO_STANDARD_HDTV_4096_2160P_50,
	VO_STANDARD_HDTV_4096_2160P_60,
	VO_STANDARD_HDTV_2160P_60_420,
	VO_STANDARD_HDTV_2160P_50_420,
	VO_STANDARD_HDTV_4096_2160P_60_420,
	VO_STANDARD_HDTV_4096_2160P_50_420,
	VO_STANDARD_DP_FORMAT_1920_1080P_60,
	VO_STANDARD_DP_FORMAT_2160P_30,
	VO_STANDARD_HDTV_2160P_24_3D,
	VO_STANDARD_HDTV_2160P_23_3D,
	VO_STANDARD_HDTV_2160P_59,
	VO_STANDARD_HDTV_2160P_59_420,
	VO_STANDARD_HDTV_2160P_25_3D,
	VO_STANDARD_HDTV_2160P_30_3D,
	VO_STANDARD_HDTV_2160P_50_3D,
	VO_STANDARD_HDTV_2160P_60_3D,
	VO_STANDARD_HDTV_4096_2160P_24_3D,
	VO_STANDARD_HDTV_4096_2160P_25_3D,
	VO_STANDARD_HDTV_4096_2160P_30_3D,
	VO_STANDARD_HDTV_4096_2160P_50_3D,
	VO_STANDARD_HDTV_4096_2160P_60_3D,
	VO_STANDARD_DP_FORMAT_1280_720P_60,
	VO_STANDARD_DP_FORMAT_3840_2160P_60,
	VO_STANDARD_DP_FORMAT_1024_768P_60,
	VO_STANDARD_HDTV_2160P_50_422_12bit,
	VO_STANDARD_HDTV_2160P_60_422_12bit,
	VO_STANDARD_DP_FORMAT_1280_800P_60,
	VO_STANDARD_DP_FORMAT_1440_900P_60,
	VO_STANDARD_DP_FORMAT_1440_768P_60,
	VO_STANDARD_DP_FORMAT_960_544P_60,
	VO_STANDARD_HDTV_720P_120_3D,
	VO_STANDARD_DP_FORMAT_800_480P_60,
	VO_STANDARD_HDTV_2160P_59_422_12bit,
	VO_STANDARD_DP_FORMAT_800_1280P_60,
	VO_STANDARD_DP_FORMAT_1280_720P_50,
	VO_STANDARD_HDTV_1080P_144,
	VO_STANDARD_HDTV_1024_768P_70,
	VO_STANDARD_DP_FORMAT_1024_600P_60,
	VO_STANDARD_DP_FORMAT_600_1024P_60,
	VO_STANDARD_DSIMIPI_FORMAT_1200_1920P_60,
	VO_STANDARD_HDTV_1080P_120,
	VO_STANDARD_HDTV_720P_P24,
	VO_STANDARD_HDTV_720P_P25,
	VO_STANDARD_HDTV_720P_P30,
	VO_STANDARD_HDTV_720P_P23,
	VO_STANDARD_HDTV_720P_P29,
	VO_STANDARD_DP_FORMAT_1366_768P_60,
	VO_STANDARD_HDTV_1080P_29,
	VO_STANDARD_HDTV_2560_1440P_60,
	VO_STANDARD_HDTV_2560_1080P_60,
	VO_STANDARD_HDTV_1920_720P_60,
	VO_STANDARD_ERROR,
};

struct VO_SIZE {
	unsigned short w;
	unsigned short h;
};

struct vo_rectangle {
	short x;
	short y;
	unsigned short width;
	unsigned short height;
};

enum VO_VIDEO_PLANE {
	VO_VIDEO_PLANE_V1,
	VO_VIDEO_PLANE_V2,
	VO_VIDEO_PLANE_SUB1,
	VO_VIDEO_PLANE_OSD1,
	VO_VIDEO_PLANE_OSD2,
	VO_VIDEO_PLANE_WIN1,
	VO_VIDEO_PLANE_WIN2,
	VO_VIDEO_PLANE_WIN3,
	VO_VIDEO_PLANE_WIN4,
	VO_VIDEO_PLANE_WIN5,
	VO_VIDEO_PLANE_WIN6,
	VO_VIDEO_PLANE_WIN7,
	VO_VIDEO_PLANE_WIN8,
	VO_VIDEO_PLANE_NONE,
};

enum ENUM_WRITEBACK_TYPE {
	BACKGROUND_V1 = 0,
	BACKGROUND_V2 = 1,
	VSYNC_MIXER1 = 2,
	VSYNC_MIXER2 = 3,
	VSYNC_V1 = 4,
	BACKGROUND_NPU_PP = 5,
	VSYNC_V1_NPU_PP = 6,
};


#endif
