#@TYPE: Machine
#@NAME: Realtek Stark and Kent EVM boards
#@DESCRIPTION: Machine configuration for the RTD1619b and RTD1625 boards with Android

MACHINE_FEATURES := "drm mali"
MACHINE_FEATURES += "android"
MACHINE_FEATURES += "panfrost"
MACHINE_FEATURES += "v4l2"
MACHINE_FEATURES += "mipi"
MACHINE_FEATURES += "upstream-bt"
MACHINE_FEATURES += "vendor-wifi"

MACHINEOVERRIDES =. "rtd16xx:"
#require conf/machine/include/arm/armv8-2a/tune-cortexa78.inc
require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc
require conf/machine/include/avengers.inc
require conf/machine/include/overlayfs.inc

UBOOT_CONFIG = "rtd1619b_emmc rtd1625_emmc"
UBOOT_CONFIG[rtd1619b_emmc] = "rtd1619b_emmc_defconfig,,u-boot.itb"
UBOOT_CONFIG[rtd1625_emmc] = "rtd1625_phantom_defconfig,,u-boot.itb"

IMAGE_BOOT_FILES += " \
	yocto.itb \
	u-boot.bin-rtd1619b_emmc \
	u-boot.bin-rtd1625_emmc \
	"

KERNEL_DEVICETREE = " \
	realtek/rtd1619b-bleedingedge-2gb.dtb \
	realtek/rtd1619b-backinblack-2gb.dtb \
	realtek/rtd1619b-rescue.dtb \
	realtek/rtd1501s-phantom-chromium-8gb.dtb \
	realtek/rtd1501-rescue.dtb \
	"

IMAGE_INSTALL:append = " ${@bb.utils.contains('MACHINE_FEATURES', 'drm', 'linux-firmware-rtd1619b linux-firmware-rtd1625', '', d)}"
