// SPDX-License-Identifier: GPL-2.0-only
/*
 * Realtek uncore PMU driver for 1625 register bus
 *
 * Copyright (C) 2025-2026 Realtek Semiconductor Corporation
 * Copyright (C) 2025-2026 Adam Lin <adam_lin@realtek.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see
 * <http://www.gnu.org/licenses/>.
 */
#include <linux/slab.h>
#include <linux/of.h>
#include <linux/of_address.h>

#include "rtk_uncore_pmu.h"
#include "rtk_rbus_pmu.h"

/* target CPU ID */
#define RBUS_ARB_SCPU_ID	(BIT(0) << ARB_CPU_ID_OFFSET)
#define RBUS_ARB_SCPU_RBUS1_ID	(BIT(1) << ARB_CPU_ID_OFFSET)
#define RBUS_ARB_SCPU_RBUS5_ID	(BIT(2) << ARB_CPU_ID_OFFSET)
#define RBUS_ARB_ACPU_ID	(BIT(3) << ARB_CPU_ID_OFFSET)
#define RBUS_ARB_VCPU_ID	(BIT(4) << ARB_CPU_ID_OFFSET)
#define RBUS_ARB_PCPU_ID	(BIT(5) << ARB_CPU_ID_OFFSET)
#define RBUS_ARB_AUCPU0_ID	(BIT(6) << ARB_CPU_ID_OFFSET)
#define RBUS_ARB_AUCPU1_ID	(BIT(7) << ARB_CPU_ID_OFFSET)
#define RBUS_ARB_CPU_ALL_ID	GENMASK(7, 0)

/* target RBUS ID of PRE ARB */
#define RBUS_PRE_ARB_RBUS_ID		BIT(0)
#define RBUS_PRE_ARB_RBUS1_ID		BIT(1)
#define RBUS_PRE_ARB_RBUS2_ID		BIT(2)
#define RBUS_PRE_ARB_RBUS3_ID		BIT(3)
#define RBUS_PRE_ARB_RBUS4_ID		BIT(4)
#define RBUS_PRE_ARB_RBUS5_ID		BIT(5)
#define RBUS_PRE_ARB_RBUS_ALL_ID	GENMASK(5, 0)

#define RBUS_CLIENT_ID(_cpu_id, _rbus_id) \
	((_cpu_id) | (_rbus_id))

/* All Rbus */
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_scpu__rbus_all,
	(RBUS_ARB_SCPU_ID | RBUS_PRE_ARB_RBUS_ALL_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_scpu_rbus1__rbus_all,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_PRE_ARB_RBUS_ALL_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_scpu_rbus5__rbus_all,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_PRE_ARB_RBUS_ALL_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_acpu__rbus_all,
	(RBUS_ARB_ACPU_ID | RBUS_PRE_ARB_RBUS_ALL_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_vcpu__rbus_all,
	(RBUS_ARB_VCPU_ID | RBUS_PRE_ARB_RBUS_ALL_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_pcpu__rbus_all,
	(RBUS_ARB_PCPU_ID | RBUS_PRE_ARB_RBUS_ALL_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_aucpu0__rbus_all,
	(RBUS_ARB_AUCPU0_ID | RBUS_PRE_ARB_RBUS_ALL_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_aucpu1__rbus_all,
	(RBUS_ARB_AUCPU1_ID | RBUS_PRE_ARB_RBUS_ALL_ID), RBUS_PRE_ARB);

/* Custom Rbus */
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_scpu__rbus_custom,
	(RBUS_ARB_SCPU_ID | RBUS_CUSTOM_RANGE_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_scpu_rbus1__rbus_custom,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_CUSTOM_RANGE_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_scpu_rbus5__rbus_custom,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_CUSTOM_RANGE_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_acpu__rbus_custom,
	(RBUS_ARB_ACPU_ID | RBUS_CUSTOM_RANGE_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_vcpu__rbus_custom,
	(RBUS_ARB_VCPU_ID | RBUS_CUSTOM_RANGE_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_pcpu__rbus_custom,
	(RBUS_ARB_PCPU_ID | RBUS_CUSTOM_RANGE_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_aucpu0__rbus_custom,
	(RBUS_ARB_AUCPU0_ID | RBUS_CUSTOM_RANGE_ID), RBUS_PRE_ARB);
RBUS_PRE_ARB_EVENT_GROUP_V4(pre_arb_aucpu1__rbus_custom,
	(RBUS_ARB_AUCPU1_ID | RBUS_CUSTOM_RANGE_ID), RBUS_PRE_ARB);

enum rbus_post_arb_range_id {
	RBUS_POST_ARB_ALL_RANGE_ID = 0,
	RBUS_POST_ARB_VE1_RANGE_ID,
	RBUS_POST_ARB_VE2_RANGE_ID,
	RBUS_POST_ARB_VO_RANGE_ID,
	RBUS_POST_ARB_VI_RANGE_ID,
	RBUS_POST_ARB_VO2_RANGE_ID,
	RBUS_POST_ARB_GPU2D_0_RANGE_ID,
	RBUS_POST_ARB_GPU2D_1_RANGE_ID,
	RBUS_POST_ARB_GPU_RANGE_ID,

	RBUS_POST_ARB_MAX_ID,
};

static struct rtk_pmu_region rbus_1625_post_arb_regions[] = {
	{RBUS_POST_ARB_ALL_RANGE_ID,		0x98000000,	0x986FFFFF},
	{RBUS_POST_ARB_VE1_RANGE_ID,		0x98040000,	0x98043FFF},
	{RBUS_POST_ARB_VE2_RANGE_ID,		0x98044000,	0x98047FFF},
	{RBUS_POST_ARB_VO_RANGE_ID,		0x98080000,	0x98083FFF},
	{RBUS_POST_ARB_VI_RANGE_ID,		0x9812B000,	0x9812BFFF},
	{RBUS_POST_ARB_VO2_RANGE_ID,		0x98145000,	0x98145FFF},
	{RBUS_POST_ARB_GPU2D_0_RANGE_ID,	0x98143000,	0x98143FFF},
	{RBUS_POST_ARB_GPU2D_1_RANGE_ID,	0x98149000,	0x98149FFF},
	{RBUS_POST_ARB_GPU_RANGE_ID,		0x98200000,	0x986F6FFF},
};

/* All Range */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_all,
	(RBUS_ARB_SCPU_ID | RBUS_POST_ARB_ALL_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_all,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_POST_ARB_ALL_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_all,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_POST_ARB_ALL_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_all,
	(RBUS_ARB_ACPU_ID | RBUS_POST_ARB_ALL_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_all,
	(RBUS_ARB_VCPU_ID | RBUS_POST_ARB_ALL_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_all,
	(RBUS_ARB_PCPU_ID | RBUS_POST_ARB_ALL_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_all,
	(RBUS_ARB_AUCPU0_ID | RBUS_POST_ARB_ALL_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_all,
	(RBUS_ARB_AUCPU1_ID | RBUS_POST_ARB_ALL_RANGE_ID), RBUS_POST_ARB);

/* VI */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_vi,
	(RBUS_ARB_SCPU_ID | RBUS_POST_ARB_VI_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_vi,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_POST_ARB_VI_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_vi,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_POST_ARB_VI_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_vi,
	(RBUS_ARB_ACPU_ID | RBUS_POST_ARB_VI_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_vi,
	(RBUS_ARB_VCPU_ID | RBUS_POST_ARB_VI_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_vi,
	(RBUS_ARB_PCPU_ID | RBUS_POST_ARB_VI_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_vi,
	(RBUS_ARB_AUCPU0_ID | RBUS_POST_ARB_VI_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_vi,
	(RBUS_ARB_AUCPU1_ID | RBUS_POST_ARB_VI_RANGE_ID), RBUS_POST_ARB);

/* VE1 */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_ve1,
	(RBUS_ARB_SCPU_ID | RBUS_POST_ARB_VE1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_ve1,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_POST_ARB_VE1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_ve1,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_POST_ARB_VE1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_ve1,
	(RBUS_ARB_ACPU_ID | RBUS_POST_ARB_VE1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_ve1,
	(RBUS_ARB_VCPU_ID | RBUS_POST_ARB_VE1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_ve1,
	(RBUS_ARB_PCPU_ID | RBUS_POST_ARB_VE1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_ve1,
	(RBUS_ARB_AUCPU0_ID | RBUS_POST_ARB_VE1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_ve1,
	(RBUS_ARB_AUCPU1_ID | RBUS_POST_ARB_VE1_RANGE_ID), RBUS_POST_ARB);

/* VE2 */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_ve2,
	(RBUS_ARB_SCPU_ID | RBUS_POST_ARB_VE2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_ve2,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_POST_ARB_VE2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_ve2,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_POST_ARB_VE2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_ve2,
	(RBUS_ARB_ACPU_ID | RBUS_POST_ARB_VE2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_ve2,
	(RBUS_ARB_VCPU_ID | RBUS_POST_ARB_VE2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_ve2,
	(RBUS_ARB_PCPU_ID | RBUS_POST_ARB_VE2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_ve2,
	(RBUS_ARB_AUCPU0_ID | RBUS_POST_ARB_VE2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_ve2,
	(RBUS_ARB_AUCPU1_ID | RBUS_POST_ARB_VE2_RANGE_ID), RBUS_POST_ARB);

/* VO */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_vo,
	(RBUS_ARB_SCPU_ID | RBUS_POST_ARB_VO_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_vo,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_POST_ARB_VO_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_vo,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_POST_ARB_VO_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_vo,
	(RBUS_ARB_ACPU_ID | RBUS_POST_ARB_VO_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_vo,
	(RBUS_ARB_VCPU_ID | RBUS_POST_ARB_VO_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_vo,
	(RBUS_ARB_PCPU_ID | RBUS_POST_ARB_VO_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_vo,
	(RBUS_ARB_AUCPU0_ID | RBUS_POST_ARB_VO_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_vo,
	(RBUS_ARB_AUCPU1_ID | RBUS_POST_ARB_VO_RANGE_ID), RBUS_POST_ARB);

/* VO2 */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_vo2,
	(RBUS_ARB_SCPU_ID | RBUS_POST_ARB_VO2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_vo2,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_POST_ARB_VO2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_vo2,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_POST_ARB_VO2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_vo2,
	(RBUS_ARB_ACPU_ID | RBUS_POST_ARB_VO2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_vo2,
	(RBUS_ARB_VCPU_ID | RBUS_POST_ARB_VO2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_vo2,
	(RBUS_ARB_PCPU_ID | RBUS_POST_ARB_VO2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_vo2,
	(RBUS_ARB_AUCPU0_ID | RBUS_POST_ARB_VO2_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_vo2,
	(RBUS_ARB_AUCPU1_ID | RBUS_POST_ARB_VO2_RANGE_ID), RBUS_POST_ARB);

/* GPU */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_gpu,
	(RBUS_ARB_SCPU_ID | RBUS_POST_ARB_GPU_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_gpu,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_POST_ARB_GPU_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_gpu,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_POST_ARB_GPU_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_gpu,
	(RBUS_ARB_ACPU_ID | RBUS_POST_ARB_GPU_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_gpu,
	(RBUS_ARB_VCPU_ID | RBUS_POST_ARB_GPU_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_gpu,
	(RBUS_ARB_PCPU_ID | RBUS_POST_ARB_GPU_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_gpu,
	(RBUS_ARB_AUCPU0_ID | RBUS_POST_ARB_GPU_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_gpu,
	(RBUS_ARB_AUCPU1_ID | RBUS_POST_ARB_GPU_RANGE_ID), RBUS_POST_ARB);

/* GPU2D_0 */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_gpu2d_0,
	(RBUS_ARB_SCPU_ID | RBUS_POST_ARB_GPU2D_0_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_gpu2d_0,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_POST_ARB_GPU2D_0_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_gpu2d_0,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_POST_ARB_GPU2D_0_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_gpu2d_0,
	(RBUS_ARB_ACPU_ID | RBUS_POST_ARB_GPU2D_0_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_gpu2d_0,
	(RBUS_ARB_VCPU_ID | RBUS_POST_ARB_GPU2D_0_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_gpu2d_0,
	(RBUS_ARB_PCPU_ID | RBUS_POST_ARB_GPU2D_0_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_gpu2d_0,
	(RBUS_ARB_AUCPU0_ID | RBUS_POST_ARB_GPU2D_0_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_gpu2d_0,
	(RBUS_ARB_AUCPU1_ID | RBUS_POST_ARB_GPU2D_0_RANGE_ID), RBUS_POST_ARB);

/* GPU2D_1 */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_gpu2d_1,
	(RBUS_ARB_SCPU_ID | RBUS_POST_ARB_GPU2D_1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_gpu2d_1,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_POST_ARB_GPU2D_1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_gpu2d_1,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_POST_ARB_GPU2D_1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_gpu2d_1,
	(RBUS_ARB_ACPU_ID | RBUS_POST_ARB_GPU2D_1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_gpu2d_1,
	(RBUS_ARB_VCPU_ID | RBUS_POST_ARB_GPU2D_1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_gpu2d_1,
	(RBUS_ARB_PCPU_ID | RBUS_POST_ARB_GPU2D_1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_gpu2d_1,
	(RBUS_ARB_AUCPU0_ID | RBUS_POST_ARB_GPU2D_1_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_gpu2d_1,
	(RBUS_ARB_AUCPU1_ID | RBUS_POST_ARB_GPU2D_1_RANGE_ID), RBUS_POST_ARB);

/* Custom */
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu__rbus_custom,
	(RBUS_ARB_SCPU_ID | RBUS_CUSTOM_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus1__rbus_custom,
	(RBUS_ARB_SCPU_RBUS1_ID | RBUS_CUSTOM_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_scpu_rbus5__rbus_custom,
	(RBUS_ARB_SCPU_RBUS5_ID | RBUS_CUSTOM_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_acpu__rbus_custom,
	(RBUS_ARB_ACPU_ID | RBUS_CUSTOM_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_vcpu__rbus_custom,
	(RBUS_ARB_VCPU_ID | RBUS_CUSTOM_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_pcpu__rbus_custom,
	(RBUS_ARB_PCPU_ID | RBUS_CUSTOM_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu0__rbus_custom,
	(RBUS_ARB_AUCPU0_ID | RBUS_CUSTOM_RANGE_ID), RBUS_POST_ARB);
RBUS_POST_ARB_EVENT_GROUP_V4(post_arb_aucpu1__rbus_custom,
	(RBUS_ARB_AUCPU1_ID | RBUS_CUSTOM_RANGE_ID), RBUS_POST_ARB);

/* driver event */
RBUS_ARB_DRV_EVENT_ATTR(rbus_overflow, RTK_DRV_OVERFLOW);
RBUS_ARB_DRV_EVENT_ATTR(rbus_refresh, RBUS_REFRESH);


static struct attribute *rtk_1625_rbus_event_attrs[] = {
	RBUS_DRV_EVENT_REF(rbus_refresh),
	RBUS_DRV_EVENT_REF(rbus_overflow),

	/* Rbus All */
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_scpu__rbus_all),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_scpu_rbus1__rbus_all),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_scpu_rbus5__rbus_all),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_acpu__rbus_all),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_vcpu__rbus_all),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_pcpu__rbus_all),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_aucpu0__rbus_all),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_aucpu1__rbus_all),

	/* Custom */
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_scpu__rbus_custom),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_scpu_rbus1__rbus_custom),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_scpu_rbus5__rbus_custom),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_acpu__rbus_custom),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_vcpu__rbus_custom),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_pcpu__rbus_custom),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_aucpu0__rbus_custom),
	RBUS_PRE_ARB_EVENT_REF_GROUP_V4(pre_arb_aucpu1__rbus_custom),

	/* All Range */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_all),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_all),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_all),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_all),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_all),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_all),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_all),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_all),

	/* VE1 */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_ve1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_ve1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_ve1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_ve1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_ve1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_ve1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_ve1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_ve1),

	/* VE2 */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_ve2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_ve2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_ve2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_ve2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_ve2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_ve2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_ve2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_ve2),

	/* VO */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_vo),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_vo),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_vo),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_vo),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_vo),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_vo),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_vo),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_vo),

	/* VI */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_vi),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_vi),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_vi),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_vi),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_vi),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_vi),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_vi),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_vi),

	/* VO2 */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_vo2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_vo2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_vo2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_vo2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_vo2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_vo2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_vo2),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_vo2),

	/* GPU2D_0 */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_gpu2d_0),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_gpu2d_0),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_gpu2d_0),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_gpu2d_0),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_gpu2d_0),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_gpu2d_0),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_gpu2d_0),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_gpu2d_0),

	/* GPU2D_1 */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_gpu2d_1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_gpu2d_1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_gpu2d_1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_gpu2d_1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_gpu2d_1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_gpu2d_1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_gpu2d_1),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_gpu2d_1),

	/* GPU */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_gpu),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_gpu),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_gpu),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_gpu),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_gpu),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_gpu),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_gpu),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_gpu),

	/* Custom */
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu__rbus_custom),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus1__rbus_custom),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_scpu_rbus5__rbus_custom),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_acpu__rbus_custom),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_vcpu__rbus_custom),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_pcpu__rbus_custom),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu0__rbus_custom),
	RBUS_POST_ARB_EVENT_REF_GROUP_V4(post_arb_aucpu1__rbus_custom),

	NULL
};

static const unsigned int rtk_1625_rbus_pre_arb_clients[] = {
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,    RBUS_PRE_ARB_RBUS_ALL_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_PRE_ARB_RBUS_ALL_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_PRE_ARB_RBUS_ALL_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,    RBUS_PRE_ARB_RBUS_ALL_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,    RBUS_PRE_ARB_RBUS_ALL_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,    RBUS_PRE_ARB_RBUS_ALL_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,  RBUS_PRE_ARB_RBUS_ALL_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,  RBUS_PRE_ARB_RBUS_ALL_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,	RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,    RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,    RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,    RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,  RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,  RBUS_CUSTOM_RANGE_ID),
};

/* Offset of PRE_ARB PMCG */
static const unsigned long rtk_1625_rbus_pre_arb_pmcgs[] = {
	0x0080, 0x0084, 0x0088, 0x008C, 0x0090, 0x0094,
	0x0098, 0x009C, 0x00A0, 0x00A4,
};

static const unsigned long rtk_1625_rbus_pre_arb_configs[] = {
	0x0040, 0x0044, 0x0048, 0x004C, 0x0050, 0x0054,
	0x0058, 0x005C, 0x0060, 0x0064,
};

static const unsigned int rtk_1625_rbus_post_arb_clients[] = {
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_POST_ARB_ALL_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_POST_ARB_ALL_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_POST_ARB_ALL_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_POST_ARB_ALL_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_POST_ARB_ALL_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_POST_ARB_ALL_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_POST_ARB_ALL_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_POST_ARB_ALL_RANGE_ID),

	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_POST_ARB_VE1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_POST_ARB_VE1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_POST_ARB_VE1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_POST_ARB_VE1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_POST_ARB_VE1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_POST_ARB_VE1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_POST_ARB_VE1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_POST_ARB_VE1_RANGE_ID),

	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_POST_ARB_VE2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_POST_ARB_VE2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_POST_ARB_VE2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_POST_ARB_VE2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_POST_ARB_VE2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_POST_ARB_VE2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_POST_ARB_VE2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_POST_ARB_VE2_RANGE_ID),

	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_POST_ARB_VO_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_POST_ARB_VO_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_POST_ARB_VO_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_POST_ARB_VO_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_POST_ARB_VO_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_POST_ARB_VO_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_POST_ARB_VO_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_POST_ARB_VO_RANGE_ID),

	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_POST_ARB_VI_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_POST_ARB_VI_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_POST_ARB_VI_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_POST_ARB_VI_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_POST_ARB_VI_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_POST_ARB_VI_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_POST_ARB_VI_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_POST_ARB_VI_RANGE_ID),

	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_POST_ARB_VO2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_POST_ARB_VO2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_POST_ARB_VO2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_POST_ARB_VO2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_POST_ARB_VO2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_POST_ARB_VO2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_POST_ARB_VO2_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_POST_ARB_VO2_RANGE_ID),

	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_POST_ARB_GPU2D_0_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_POST_ARB_GPU2D_0_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_POST_ARB_GPU2D_0_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_POST_ARB_GPU2D_0_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_POST_ARB_GPU2D_0_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_POST_ARB_GPU2D_0_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_POST_ARB_GPU2D_0_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_POST_ARB_GPU2D_0_RANGE_ID),

	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_POST_ARB_GPU2D_1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_POST_ARB_GPU2D_1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_POST_ARB_GPU2D_1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_POST_ARB_GPU2D_1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_POST_ARB_GPU2D_1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_POST_ARB_GPU2D_1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_POST_ARB_GPU2D_1_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_POST_ARB_GPU2D_1_RANGE_ID),

	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_POST_ARB_GPU_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_POST_ARB_GPU_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_POST_ARB_GPU_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_POST_ARB_GPU_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_POST_ARB_GPU_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_POST_ARB_GPU_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_POST_ARB_GPU_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_POST_ARB_GPU_RANGE_ID),

	RBUS_CLIENT_ID(RBUS_ARB_SCPU_ID,       RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS1_ID, RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_SCPU_RBUS5_ID, RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_ACPU_ID,       RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_VCPU_ID,       RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_PCPU_ID,       RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU0_ID,     RBUS_CUSTOM_RANGE_ID),
	RBUS_CLIENT_ID(RBUS_ARB_AUCPU1_ID,     RBUS_CUSTOM_RANGE_ID),
};

/* Offset of POST_ARB PMCG */
static const unsigned long rtk_1625_rbus_post_arb_pmcgs[] = {
	0x0200, 0x0204, 0x0208, 0x020C, 0x0210, 0x0214,
	0x0218, 0x021C,
};

static const unsigned long rtk_1625_rbus_post_arb_configs[] = {
	0x0140, 0x0144, 0x0148, 0x014C, 0x0150, 0x0154,
	0x0158, 0x015C
};

static const unsigned int rtk_rbus_drv_ev[] = {
	RTK_DRV_OVERFLOW, RBUS_REFRESH
};

static struct attribute_group rtk_1625_rbus_event_attr_group = {
	.name = "events",
	.attrs = rtk_1625_rbus_event_attrs,
};

static const struct attribute_group *rtk_1625_rbus_attr_groups[] = {
	/* must be Null-terminated */
	[RTK_PMU_ATTR_GROUP__COMMON] = &rtk_pmu_common_attr_group,
	[RTK_PMU_ATTR_GROUP__FORMAT] = &rtk_rbus_format_attr_group,
	[RTK_PMU_ATTR_GROUP__EVENT] = &rtk_1625_rbus_event_attr_group,
	[RTK_PMU_ATTR_GROUP__NUM] = NULL
};

static const struct rtk_pmc_set_meta rtk_1625_rbus_ps_meta[] = {
	{
		.name = "Realtek Rbus PRE_ARB",
		.hw_ver = RTK_RBUS_EV_ORDER_V4,
		.type = PMC_SET__RBUS_PRE_ARB,
		.init = rbus_pmu_ps_init_v2,
		.group_size = RBUS_PMC__V4_PRE_ARB_USAGE_NUM,
		.config_size = 8,
		.config_width = 8,
		.val_mask = (const unsigned int []){
			RTK_PMU_VAL_MASK(32),
			RTK_PMU_VAL_MASK(32),
			RTK_PMU_VAL_MASK(32),
			RTK_PMU_VAL_MASK(32),
		},
		.ov_th = (const unsigned int[]){
			RTK_PMU_OVERFLOW_TH(32),
			RTK_PMU_OVERFLOW_TH(32),
			RTK_PMU_OVERFLOW_TH(32),
			RTK_PMU_OVERFLOW_TH(32),
		},

		.nr_clients = ARRAY_SIZE(rtk_1625_rbus_pre_arb_clients),
		.nr_pmcgs = ARRAY_SIZE(rtk_1625_rbus_pre_arb_pmcgs),
		.nr_configs = ARRAY_SIZE(rtk_1625_rbus_pre_arb_configs),
		.clients = rtk_1625_rbus_pre_arb_clients,
		.pmcgs = rtk_1625_rbus_pre_arb_pmcgs,
		.configs = rtk_1625_rbus_pre_arb_configs,
	},
	{
		.name = "Realtek Rbus POST_ARB",
		.hw_ver = RTK_RBUS_EV_ORDER_V4,
		.type = PMC_SET__RBUS_POST_ARB,
		.init = rbus_pmu_ps_init_v2,
		.group_size = RBUS_PMC__V4_POST_ARB_USAGE_NUM,
		.config_size = 8,
		.config_width = 8,
		.val_mask = (const unsigned int[]){
			RTK_PMU_VAL_MASK(32),
			RTK_PMU_VAL_MASK(32),
			RTK_PMU_VAL_MASK(32),
			RTK_PMU_VAL_MASK(32),
		},
		.ov_th = (const unsigned int[]){
			RTK_PMU_OVERFLOW_TH(32),
			RTK_PMU_OVERFLOW_TH(32),
			RTK_PMU_OVERFLOW_TH(32),
			RTK_PMU_OVERFLOW_TH(32),
		},

		.nr_clients = ARRAY_SIZE(rtk_1625_rbus_post_arb_clients),
		.nr_pmcgs = ARRAY_SIZE(rtk_1625_rbus_post_arb_pmcgs),
		.nr_configs = ARRAY_SIZE(rtk_1625_rbus_post_arb_configs),
		.nr_regions = ARRAY_SIZE(rbus_1625_post_arb_regions),
		.clients = rtk_1625_rbus_post_arb_clients,
		.pmcgs = rtk_1625_rbus_post_arb_pmcgs,
		.configs = rtk_1625_rbus_post_arb_configs,
		.regions = rbus_1625_post_arb_regions,
	},
	{
		.name = "Realtek Rbus Driver",
		.type = PMC_SET__RBUS_ARB_DRV,
		.init = rbus_pmu_ps_drv_init,
		.group_size = 1,
		.config_size = 0,
		.config_width = 0,
		.nr_clients = ARRAY_SIZE(rtk_rbus_drv_ev),
		.nr_pmcgs = RBUS_EV_NUM,
		.nr_configs = 0,
		.clients = rtk_rbus_drv_ev,
		.pmcgs = NULL,
		.configs = NULL,
	},
	{},
};

int rtk_1625_rbus_init(struct rtk_pmu *pmu, struct device_node *dt)
{
	return rtk_rbus_pmu_init_v2(pmu, dt,
			       "rtk_1625_rbus_pmu",
			       rtk_1625_rbus_attr_groups,
			       rtk_1625_rbus_ps_meta,
			       RTK_PMU_META_NR(rtk_1625_rbus_ps_meta));
}
EXPORT_SYMBOL(rtk_1625_rbus_init);
MODULE_LICENSE("GPL");
