# SPDX-License-Identifier: GPL-2.0-only

obj-y += common/
obj-y += cpudvfs/
obj-y += cpuhp/
obj-y += gpu/
obj-y += kent/
obj-y += rtd13xx/
obj-y += rtd13xxd/
obj-y += rtd1325/
obj-y += rtd16xxb/
obj-y += tee_mem/
obj-y += runtime_device/
