/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef _APP_REG_H_INCLUDED_
#define _APP_REG_H_INCLUDED_

/* Base address of APP_0 to APP_5 */
#define APP_0_MIPI_CTRL0_reg                    0x98004000
#define APP_1_MIPI_CTRL0_reg                    0x98004200
#define APP_2_MIPI_CTRL0_reg                    0x98004400
#define APP_3_MIPI_CTRL0_reg                    0x98004600
#define APP_4_MIPI_CTRL0_reg                    0x98004800
#define APP_5_MIPI_CTRL0_reg                    0x98004a00

/* Offset for APP_0 to APP_5 */
#define APP_MIPI_CTRL0                        0x200
#define APP_MIPI_CTRL0_line_mirror_mode_shift              (27)
#define APP_MIPI_CTRL0_line_mirror_mode_mask               (0x8000000)
#define APP_MIPI_CTRL0_line_mirror_mode(data)              (0x8000000&((data)<<27))
#define APP_MIPI_CTRL0_line_mirror_mode_src(data)          ((0x8000000&(data))>>27)
#define APP_MIPI_CTRL0_get_line_mirror_mode(data)          ((0x8000000&(data))>>27)
//this->default: APP_MIPI_CTRL0_line_mirror_mode           0x1
#define APP_MIPI_CTRL0_line_mirror_en_shift              (26)
#define APP_MIPI_CTRL0_line_mirror_en_mask               (0x4000000)
#define APP_MIPI_CTRL0_line_mirror_en(data)              (0x4000000&((data)<<26))
#define APP_MIPI_CTRL0_line_mirror_en_src(data)          ((0x4000000&(data))>>26)
#define APP_MIPI_CTRL0_get_line_mirror_en(data)          ((0x4000000&(data))>>26)
//this->default: APP_MIPI_CTRL0_line_mirror_en           0x0
#define APP_MIPI_CTRL0_yuv422_chroma_ds_en_shift              (25)
#define APP_MIPI_CTRL0_yuv422_chroma_ds_en_mask               (0x2000000)
#define APP_MIPI_CTRL0_yuv422_chroma_ds_en(data)              (0x2000000&((data)<<25))
#define APP_MIPI_CTRL0_yuv422_chroma_ds_en_src(data)          ((0x2000000&(data))>>25)
#define APP_MIPI_CTRL0_get_yuv422_chroma_ds_en(data)          ((0x2000000&(data))>>25)
//this->default: APP_MIPI_CTRL0_yuv422_chroma_ds_en           0x0
#define APP_MIPI_CTRL0_yuv444_chroma_ds_mode_shift              (24)
#define APP_MIPI_CTRL0_yuv444_chroma_ds_mode_mask               (0x1000000)
#define APP_MIPI_CTRL0_yuv444_chroma_ds_mode(data)              (0x1000000&((data)<<24))
#define APP_MIPI_CTRL0_yuv444_chroma_ds_mode_src(data)          ((0x1000000&(data))>>24)
#define APP_MIPI_CTRL0_get_yuv444_chroma_ds_mode(data)          ((0x1000000&(data))>>24)
//this->default: APP_MIPI_CTRL0_yuv444_chroma_ds_mode           0x1
#define APP_MIPI_CTRL0_yuv444_chroma_ds_en_shift              (23)
#define APP_MIPI_CTRL0_yuv444_chroma_ds_en_mask               (0x800000)
#define APP_MIPI_CTRL0_yuv444_chroma_ds_en(data)              (0x800000&((data)<<23))
#define APP_MIPI_CTRL0_yuv444_chroma_ds_en_src(data)          ((0x800000&(data))>>23)
#define APP_MIPI_CTRL0_get_yuv444_chroma_ds_en(data)          ((0x800000&(data))>>23)
//this->default: APP_MIPI_CTRL0_yuv444_chroma_ds_en           0x0
#define APP_MIPI_CTRL0_vs_en_shift              (22)
#define APP_MIPI_CTRL0_vs_en_mask               (0x400000)
#define APP_MIPI_CTRL0_vs_en(data)              (0x400000&((data)<<22))
#define APP_MIPI_CTRL0_vs_en_src(data)          ((0x400000&(data))>>22)
#define APP_MIPI_CTRL0_get_vs_en(data)          ((0x400000&(data))>>22)
//this->default: APP_MIPI_CTRL0_vs_en           0x0
#define APP_MIPI_CTRL0_vs_near_shift              (21)
#define APP_MIPI_CTRL0_vs_near_mask               (0x200000)
#define APP_MIPI_CTRL0_vs_near(data)              (0x200000&((data)<<21))
#define APP_MIPI_CTRL0_vs_near_src(data)          ((0x200000&(data))>>21)
#define APP_MIPI_CTRL0_get_vs_near(data)          ((0x200000&(data))>>21)
//this->default: APP_MIPI_CTRL0_vs_near           0x0
#define APP_MIPI_CTRL0_vs_yodd_shift              (20)
#define APP_MIPI_CTRL0_vs_yodd_mask               (0x100000)
#define APP_MIPI_CTRL0_vs_yodd(data)              (0x100000&((data)<<20))
#define APP_MIPI_CTRL0_vs_yodd_src(data)          ((0x100000&(data))>>20)
#define APP_MIPI_CTRL0_get_vs_yodd(data)          ((0x100000&(data))>>20)
//this->default: APP_MIPI_CTRL0_vs_yodd           0x0
#define APP_MIPI_CTRL0_vs_codd_shift              (19)
#define APP_MIPI_CTRL0_vs_codd_mask               (0x80000)
#define APP_MIPI_CTRL0_vs_codd(data)              (0x80000&((data)<<19))
#define APP_MIPI_CTRL0_vs_codd_src(data)          ((0x80000&(data))>>19)
#define APP_MIPI_CTRL0_get_vs_codd(data)          ((0x80000&(data))>>19)
//this->default: APP_MIPI_CTRL0_vs_codd           0x0
#define APP_MIPI_CTRL0_hs_en_shift              (18)
#define APP_MIPI_CTRL0_hs_en_mask               (0x40000)
#define APP_MIPI_CTRL0_hs_en(data)              (0x40000&((data)<<18))
#define APP_MIPI_CTRL0_hs_en_src(data)          ((0x40000&(data))>>18)
#define APP_MIPI_CTRL0_get_hs_en(data)          ((0x40000&(data))>>18)
//this->default: APP_MIPI_CTRL0_hs_en           0x0
#define APP_MIPI_CTRL0_hs_yodd_shift              (17)
#define APP_MIPI_CTRL0_hs_yodd_mask               (0x20000)
#define APP_MIPI_CTRL0_hs_yodd(data)              (0x20000&((data)<<17))
#define APP_MIPI_CTRL0_hs_yodd_src(data)          ((0x20000&(data))>>17)
#define APP_MIPI_CTRL0_get_hs_yodd(data)          ((0x20000&(data))>>17)
//this->default: APP_MIPI_CTRL0_hs_yodd           0x0
#define APP_MIPI_CTRL0_hs_codd_shift              (16)
#define APP_MIPI_CTRL0_hs_codd_mask               (0x10000)
#define APP_MIPI_CTRL0_hs_codd(data)              (0x10000&((data)<<16))
#define APP_MIPI_CTRL0_hs_codd_src(data)          ((0x10000&(data))>>16)
#define APP_MIPI_CTRL0_get_hs_codd(data)          ((0x10000&(data))>>16)
//this->default: APP_MIPI_CTRL0_hs_codd           0x0
#define APP_MIPI_CTRL0_yuv422_chroma_us_mode_shift              (15)
#define APP_MIPI_CTRL0_yuv422_chroma_us_mode_mask               (0x8000)
#define APP_MIPI_CTRL0_yuv422_chroma_us_mode(data)              (0x8000&((data)<<15))
#define APP_MIPI_CTRL0_yuv422_chroma_us_mode_src(data)          ((0x8000&(data))>>15)
#define APP_MIPI_CTRL0_get_yuv422_chroma_us_mode(data)          ((0x8000&(data))>>15)
//this->default: APP_MIPI_CTRL0_yuv422_chroma_us_mode           0x1
#define APP_MIPI_CTRL0_yuv422_chroma_us_en_shift              (14)
#define APP_MIPI_CTRL0_yuv422_chroma_us_en_mask               (0x4000)
#define APP_MIPI_CTRL0_yuv422_chroma_us_en(data)              (0x4000&((data)<<14))
#define APP_MIPI_CTRL0_yuv422_chroma_us_en_src(data)          ((0x4000&(data))>>14)
#define APP_MIPI_CTRL0_get_yuv422_chroma_us_en(data)          ((0x4000&(data))>>14)
//this->default: APP_MIPI_CTRL0_yuv422_chroma_us_en           0x0
#define APP_MIPI_CTRL0_src_422_seq_shift              (8)
#define APP_MIPI_CTRL0_src_422_seq_mask               (0x300)
#define APP_MIPI_CTRL0_src_422_seq(data)              (0x300&((data)<<8))
#define APP_MIPI_CTRL0_src_422_seq_src(data)          ((0x300&(data))>>8)
#define APP_MIPI_CTRL0_get_src_422_seq(data)          ((0x300&(data))>>8)
//this->default: APP_MIPI_CTRL0_src_422_seq           0x3
#define APP_MIPI_CTRL0_src_fmt_shift              (3)
#define APP_MIPI_CTRL0_src_fmt_mask               (0xf8)
#define APP_MIPI_CTRL0_src_fmt(data)              (0xf8&((data)<<3))
#define APP_MIPI_CTRL0_src_fmt_src(data)          ((0xf8&(data))>>3)
#define APP_MIPI_CTRL0_get_src_fmt(data)          ((0xf8&(data))>>3)
//this->default: APP_MIPI_CTRL0_src_fmt           0x3
#define APP_MIPI_CTRL0_comp_linear_shift              (2)
#define APP_MIPI_CTRL0_comp_linear_mask               (0x4)
#define APP_MIPI_CTRL0_comp_linear(data)              (0x4&((data)<<2))
#define APP_MIPI_CTRL0_comp_linear_src(data)          ((0x4&(data))>>2)
#define APP_MIPI_CTRL0_get_comp_linear(data)          ((0x4&(data))>>2)
//this->default: APP_MIPI_CTRL0_comp_linear           0x0
#define APP_MIPI_CTRL0_sw_rst_shift              (1)
#define APP_MIPI_CTRL0_sw_rst_mask               (0x2)
#define APP_MIPI_CTRL0_sw_rst(data)              (0x2&((data)<<1))
#define APP_MIPI_CTRL0_sw_rst_src(data)          ((0x2&(data))>>1)
#define APP_MIPI_CTRL0_get_sw_rst(data)          ((0x2&(data))>>1)
//this->default: APP_MIPI_CTRL0_sw_rst           0x0
#define APP_MIPI_CTRL0_go_shift              (0)
#define APP_MIPI_CTRL0_go_mask               (0x1)
#define APP_MIPI_CTRL0_go(data)              (0x1&((data)<<0))
#define APP_MIPI_CTRL0_go_src(data)          ((0x1&(data))>>0)
#define APP_MIPI_CTRL0_get_go(data)          ((0x1&(data))>>0)
//this->default: APP_MIPI_CTRL0_go           0x0

#define APP_MIPI_CH_STS                        0x204
#define APP_MIPI_CH_STS_dma_entry_fifo_empty_shift              (19)
#define APP_MIPI_CH_STS_dma_entry_fifo_empty_mask               (0x80000)
#define APP_MIPI_CH_STS_dma_entry_fifo_empty(data)              (0x80000&((data)<<19))
#define APP_MIPI_CH_STS_dma_entry_fifo_empty_src(data)          ((0x80000&(data))>>19)
#define APP_MIPI_CH_STS_get_dma_entry_fifo_empty(data)          ((0x80000&(data))>>19)
//this->default: APP_MIPI_CH_STS_dma_entry_fifo_empty           0x0
#define APP_MIPI_CH_STS_two_frame_without_wdone_shift              (18)
#define APP_MIPI_CH_STS_two_frame_without_wdone_mask               (0x40000)
#define APP_MIPI_CH_STS_two_frame_without_wdone(data)              (0x40000&((data)<<18))
#define APP_MIPI_CH_STS_two_frame_without_wdone_src(data)          ((0x40000&(data))>>18)
#define APP_MIPI_CH_STS_get_two_frame_without_wdone(data)          ((0x40000&(data))>>18)
//this->default: APP_MIPI_CH_STS_two_frame_without_wdone           0x0
#define APP_MIPI_CH_STS_dma_entry_read_idx_shift              (16)
#define APP_MIPI_CH_STS_dma_entry_read_idx_mask               (0x30000)
#define APP_MIPI_CH_STS_dma_entry_read_idx(data)              (0x30000&((data)<<16))
#define APP_MIPI_CH_STS_dma_entry_read_idx_src(data)          ((0x30000&(data))>>16)
#define APP_MIPI_CH_STS_get_dma_entry_read_idx(data)          ((0x30000&(data))>>16)
//this->default: APP_MIPI_CH_STS_dma_entry_read_idx           0x0
#define APP_MIPI_CH_STS_ch_fsm_shift              (13)
#define APP_MIPI_CH_STS_ch_fsm_mask               (0xe000)
#define APP_MIPI_CH_STS_ch_fsm(data)              (0xe000&((data)<<13))
#define APP_MIPI_CH_STS_ch_fsm_src(data)          ((0xe000&(data))>>13)
#define APP_MIPI_CH_STS_get_ch_fsm(data)          ((0xe000&(data))>>13)
//this->default: APP_MIPI_CH_STS_ch_fsm           0x0
#define APP_MIPI_CH_STS_cti_buf_req_shift              (8)
#define APP_MIPI_CH_STS_cti_buf_req_mask               (0x1f00)
#define APP_MIPI_CH_STS_cti_buf_req(data)              (0x1f00&((data)<<8))
#define APP_MIPI_CH_STS_cti_buf_req_src(data)          ((0x1f00&(data))>>8)
#define APP_MIPI_CH_STS_get_cti_buf_req(data)          ((0x1f00&(data))>>8)
//this->default: APP_MIPI_CH_STS_cti_buf_req           0x0
#define APP_MIPI_CH_STS_cti_data_left_cnt_shift              (0)
#define APP_MIPI_CH_STS_cti_data_left_cnt_mask               (0x7f)
#define APP_MIPI_CH_STS_cti_data_left_cnt(data)              (0x7f&((data)<<0))
#define APP_MIPI_CH_STS_cti_data_left_cnt_src(data)          ((0x7f&(data))>>0)
#define APP_MIPI_CH_STS_get_cti_data_left_cnt(data)          ((0x7f&(data))>>0)
//this->default: APP_MIPI_CH_STS_cti_data_left_cnt           0x0

#define APP_MIPI_SIZE1                        0x208
#define APP_MIPI_SIZE1_src_height_shift              (16)
#define APP_MIPI_SIZE1_src_height_mask               (0x1fff0000)
#define APP_MIPI_SIZE1_src_height(data)              (0x1fff0000&((data)<<16))
#define APP_MIPI_SIZE1_src_height_src(data)          ((0x1fff0000&(data))>>16)
#define APP_MIPI_SIZE1_get_src_height(data)          ((0x1fff0000&(data))>>16)
//this->default: APP_MIPI_SIZE1_src_height           0x438
#define APP_MIPI_SIZE1_src_width_shift              (0)
#define APP_MIPI_SIZE1_src_width_mask               (0x1fff)
#define APP_MIPI_SIZE1_src_width(data)              (0x1fff&((data)<<0))
#define APP_MIPI_SIZE1_src_width_src(data)          ((0x1fff&(data))>>0)
#define APP_MIPI_SIZE1_get_src_width(data)          ((0x1fff&(data))>>0)
//this->default: APP_MIPI_SIZE1_src_width           0x780

#define APP_MIPI_LINE_PITCH                        0x20c
#define APP_MIPI_LINE_PITCH_line_pitch_c_shift              (16)
#define APP_MIPI_LINE_PITCH_line_pitch_c_mask               (0xffff0000)
#define APP_MIPI_LINE_PITCH_line_pitch_c(data)              (0xffff0000&((data)<<16))
#define APP_MIPI_LINE_PITCH_line_pitch_c_src(data)          ((0xffff0000&(data))>>16)
#define APP_MIPI_LINE_PITCH_get_line_pitch_c(data)          ((0xffff0000&(data))>>16)
//this->default: APP_MIPI_LINE_PITCH_line_pitch_c           0x780
#define APP_MIPI_LINE_PITCH_line_pitch_y_shift              (0)
#define APP_MIPI_LINE_PITCH_line_pitch_y_mask               (0xffff)
#define APP_MIPI_LINE_PITCH_line_pitch_y(data)              (0xffff&((data)<<0))
#define APP_MIPI_LINE_PITCH_line_pitch_y_src(data)          ((0xffff&(data))>>0)
#define APP_MIPI_LINE_PITCH_get_line_pitch_y(data)          ((0xffff&(data))>>0)
//this->default: APP_MIPI_LINE_PITCH_line_pitch_y           0x780

#define APP_MIPI_SCALER_HSI                        0x210
#define APP_MIPI_SCALER_HSI_hsi_offset_shift              (16)
#define APP_MIPI_SCALER_HSI_hsi_offset_mask               (0xfff0000)
#define APP_MIPI_SCALER_HSI_hsi_offset(data)              (0xfff0000&((data)<<16))
#define APP_MIPI_SCALER_HSI_hsi_offset_src(data)          ((0xfff0000&(data))>>16)
#define APP_MIPI_SCALER_HSI_get_hsi_offset(data)          ((0xfff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSI_hsi_offset           0x0
#define APP_MIPI_SCALER_HSI_hsi_phase_shift              (2)
#define APP_MIPI_SCALER_HSI_hsi_phase_mask               (0xfffc)
#define APP_MIPI_SCALER_HSI_hsi_phase(data)              (0xfffc&((data)<<2))
#define APP_MIPI_SCALER_HSI_hsi_phase_src(data)          ((0xfffc&(data))>>2)
#define APP_MIPI_SCALER_HSI_get_hsi_phase(data)          ((0xfffc&(data))>>2)
//this->default: APP_MIPI_SCALER_HSI_hsi_phase           0x0

#define APP_MIPI_SCALER_HSD                        0x214
#define APP_MIPI_SCALER_HSD_hsd_out_shift              (20)
#define APP_MIPI_SCALER_HSD_hsd_out_mask               (0xfff00000)
#define APP_MIPI_SCALER_HSD_hsd_out(data)              (0xfff00000&((data)<<20))
#define APP_MIPI_SCALER_HSD_hsd_out_src(data)          ((0xfff00000&(data))>>20)
#define APP_MIPI_SCALER_HSD_get_hsd_out(data)          ((0xfff00000&(data))>>20)
//this->default: APP_MIPI_SCALER_HSD_hsd_out           0x0
#define APP_MIPI_SCALER_HSD_hsd_delta_shift              (0)
#define APP_MIPI_SCALER_HSD_hsd_delta_mask               (0x7ffff)
#define APP_MIPI_SCALER_HSD_hsd_delta(data)              (0x7ffff&((data)<<0))
#define APP_MIPI_SCALER_HSD_hsd_delta_src(data)          ((0x7ffff&(data))>>0)
#define APP_MIPI_SCALER_HSD_get_hsd_delta(data)          ((0x7ffff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSD_hsd_delta           0x0

#define APP_MIPI_SCALER_VSI                        0x218
#define APP_MIPI_SCALER_VSI_vsi_offset_shift              (16)
#define APP_MIPI_SCALER_VSI_vsi_offset_mask               (0xfff0000)
#define APP_MIPI_SCALER_VSI_vsi_offset(data)              (0xfff0000&((data)<<16))
#define APP_MIPI_SCALER_VSI_vsi_offset_src(data)          ((0xfff0000&(data))>>16)
#define APP_MIPI_SCALER_VSI_get_vsi_offset(data)          ((0xfff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_VSI_vsi_offset           0x0
#define APP_MIPI_SCALER_VSI_vsi_phase_shift              (2)
#define APP_MIPI_SCALER_VSI_vsi_phase_mask               (0xfffc)
#define APP_MIPI_SCALER_VSI_vsi_phase(data)              (0xfffc&((data)<<2))
#define APP_MIPI_SCALER_VSI_vsi_phase_src(data)          ((0xfffc&(data))>>2)
#define APP_MIPI_SCALER_VSI_get_vsi_phase(data)          ((0xfffc&(data))>>2)
//this->default: APP_MIPI_SCALER_VSI_vsi_phase           0x0

#define APP_MIPI_SCALER_VSD                        0x21c
#define APP_MIPI_SCALER_VSD_vsd_out_shift              (20)
#define APP_MIPI_SCALER_VSD_vsd_out_mask               (0xfff00000)
#define APP_MIPI_SCALER_VSD_vsd_out(data)              (0xfff00000&((data)<<20))
#define APP_MIPI_SCALER_VSD_vsd_out_src(data)          ((0xfff00000&(data))>>20)
#define APP_MIPI_SCALER_VSD_get_vsd_out(data)          ((0xfff00000&(data))>>20)
//this->default: APP_MIPI_SCALER_VSD_vsd_out           0x0
#define APP_MIPI_SCALER_VSD_vsd_delta_shift              (0)
#define APP_MIPI_SCALER_VSD_vsd_delta_mask               (0x7ffff)
#define APP_MIPI_SCALER_VSD_vsd_delta(data)              (0x7ffff&((data)<<0))
#define APP_MIPI_SCALER_VSD_vsd_delta_src(data)          ((0x7ffff&(data))>>0)
#define APP_MIPI_SCALER_VSD_get_vsd_delta(data)          ((0x7ffff&(data))>>0)
//this->default: APP_MIPI_SCALER_VSD_vsd_delta           0x0

#define APP_MIPI_SCALER_HSYC0                        0x220
#define APP_MIPI_SCALER_HSYC0_hsyc0_c1_shift              (16)
#define APP_MIPI_SCALER_HSYC0_hsyc0_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSYC0_hsyc0_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSYC0_hsyc0_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSYC0_get_hsyc0_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSYC0_hsyc0_c1           0x0
#define APP_MIPI_SCALER_HSYC0_hsyc0_c0_shift              (0)
#define APP_MIPI_SCALER_HSYC0_hsyc0_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSYC0_hsyc0_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSYC0_hsyc0_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSYC0_get_hsyc0_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSYC0_hsyc0_c0           0x0

#define APP_MIPI_SCALER_HSYC1                        0x224
#define APP_MIPI_SCALER_HSYC1_hsyc1_c1_shift              (16)
#define APP_MIPI_SCALER_HSYC1_hsyc1_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSYC1_hsyc1_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSYC1_hsyc1_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSYC1_get_hsyc1_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSYC1_hsyc1_c1           0x0
#define APP_MIPI_SCALER_HSYC1_hsyc1_c0_shift              (0)
#define APP_MIPI_SCALER_HSYC1_hsyc1_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSYC1_hsyc1_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSYC1_hsyc1_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSYC1_get_hsyc1_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSYC1_hsyc1_c0           0x0

#define APP_MIPI_SCALER_HSYC2                        0x228
#define APP_MIPI_SCALER_HSYC2_hsyc2_c1_shift              (16)
#define APP_MIPI_SCALER_HSYC2_hsyc2_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSYC2_hsyc2_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSYC2_hsyc2_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSYC2_get_hsyc2_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSYC2_hsyc2_c1           0x0
#define APP_MIPI_SCALER_HSYC2_hsyc2_c0_shift              (0)
#define APP_MIPI_SCALER_HSYC2_hsyc2_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSYC2_hsyc2_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSYC2_hsyc2_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSYC2_get_hsyc2_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSYC2_hsyc2_c0           0x0

#define APP_MIPI_SCALER_HSYC3                        0x22c
#define APP_MIPI_SCALER_HSYC3_hsyc3_c1_shift              (16)
#define APP_MIPI_SCALER_HSYC3_hsyc3_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSYC3_hsyc3_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSYC3_hsyc3_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSYC3_get_hsyc3_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSYC3_hsyc3_c1           0x0
#define APP_MIPI_SCALER_HSYC3_hsyc3_c0_shift              (0)
#define APP_MIPI_SCALER_HSYC3_hsyc3_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSYC3_hsyc3_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSYC3_hsyc3_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSYC3_get_hsyc3_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSYC3_hsyc3_c0           0x0

#define APP_MIPI_SCALER_HSYC4                        0x230
#define APP_MIPI_SCALER_HSYC4_hsyc4_c1_shift              (16)
#define APP_MIPI_SCALER_HSYC4_hsyc4_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSYC4_hsyc4_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSYC4_hsyc4_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSYC4_get_hsyc4_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSYC4_hsyc4_c1           0x0
#define APP_MIPI_SCALER_HSYC4_hsyc4_c0_shift              (0)
#define APP_MIPI_SCALER_HSYC4_hsyc4_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSYC4_hsyc4_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSYC4_hsyc4_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSYC4_get_hsyc4_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSYC4_hsyc4_c0           0x0

#define APP_MIPI_SCALER_HSYC5                        0x234
#define APP_MIPI_SCALER_HSYC5_hsyc5_c1_shift              (16)
#define APP_MIPI_SCALER_HSYC5_hsyc5_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSYC5_hsyc5_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSYC5_hsyc5_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSYC5_get_hsyc5_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSYC5_hsyc5_c1           0x0
#define APP_MIPI_SCALER_HSYC5_hsyc5_c0_shift              (0)
#define APP_MIPI_SCALER_HSYC5_hsyc5_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSYC5_hsyc5_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSYC5_hsyc5_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSYC5_get_hsyc5_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSYC5_hsyc5_c0           0x0

#define APP_MIPI_SCALER_HSYC6                        0x238
#define APP_MIPI_SCALER_HSYC6_hsyc6_c1_shift              (16)
#define APP_MIPI_SCALER_HSYC6_hsyc6_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSYC6_hsyc6_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSYC6_hsyc6_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSYC6_get_hsyc6_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSYC6_hsyc6_c1           0x0
#define APP_MIPI_SCALER_HSYC6_hsyc6_c0_shift              (0)
#define APP_MIPI_SCALER_HSYC6_hsyc6_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSYC6_hsyc6_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSYC6_hsyc6_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSYC6_get_hsyc6_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSYC6_hsyc6_c0           0x0

#define APP_MIPI_SCALER_HSYC7                        0x23c
#define APP_MIPI_SCALER_HSYC7_hsyc7_c1_shift              (16)
#define APP_MIPI_SCALER_HSYC7_hsyc7_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSYC7_hsyc7_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSYC7_hsyc7_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSYC7_get_hsyc7_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSYC7_hsyc7_c1           0x0
#define APP_MIPI_SCALER_HSYC7_hsyc7_c0_shift              (0)
#define APP_MIPI_SCALER_HSYC7_hsyc7_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSYC7_hsyc7_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSYC7_hsyc7_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSYC7_get_hsyc7_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSYC7_hsyc7_c0           0x0

#define APP_MIPI_SCALER_HSCC0                        0x240
#define APP_MIPI_SCALER_HSCC0_hscc0_c1_shift              (16)
#define APP_MIPI_SCALER_HSCC0_hscc0_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSCC0_hscc0_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSCC0_hscc0_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSCC0_get_hscc0_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSCC0_hscc0_c1           0x0
#define APP_MIPI_SCALER_HSCC0_hscc0_c0_shift              (0)
#define APP_MIPI_SCALER_HSCC0_hscc0_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSCC0_hscc0_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSCC0_hscc0_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSCC0_get_hscc0_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSCC0_hscc0_c0           0x0

#define APP_MIPI_SCALER_HSCC1                        0x244
#define APP_MIPI_SCALER_HSCC1_hscc1_c1_shift              (16)
#define APP_MIPI_SCALER_HSCC1_hscc1_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSCC1_hscc1_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSCC1_hscc1_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSCC1_get_hscc1_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSCC1_hscc1_c1           0x0
#define APP_MIPI_SCALER_HSCC1_hscc1_c0_shift              (0)
#define APP_MIPI_SCALER_HSCC1_hscc1_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSCC1_hscc1_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSCC1_hscc1_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSCC1_get_hscc1_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSCC1_hscc1_c0           0x0

#define APP_MIPI_SCALER_HSCC2                        0x248
#define APP_MIPI_SCALER_HSCC2_hscc2_c1_shift              (16)
#define APP_MIPI_SCALER_HSCC2_hscc2_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSCC2_hscc2_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSCC2_hscc2_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSCC2_get_hscc2_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSCC2_hscc2_c1           0x0
#define APP_MIPI_SCALER_HSCC2_hscc2_c0_shift              (0)
#define APP_MIPI_SCALER_HSCC2_hscc2_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSCC2_hscc2_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSCC2_hscc2_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSCC2_get_hscc2_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSCC2_hscc2_c0           0x0

#define APP_MIPI_SCALER_HSCC3                        0x24c
#define APP_MIPI_SCALER_HSCC3_hscc3_c1_shift              (16)
#define APP_MIPI_SCALER_HSCC3_hscc3_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSCC3_hscc3_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSCC3_hscc3_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSCC3_get_hscc3_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSCC3_hscc3_c1           0x0
#define APP_MIPI_SCALER_HSCC3_hscc3_c0_shift              (0)
#define APP_MIPI_SCALER_HSCC3_hscc3_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSCC3_hscc3_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSCC3_hscc3_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSCC3_get_hscc3_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSCC3_hscc3_c0           0x0

#define APP_MIPI_SCALER_HSCC4                        0x250
#define APP_MIPI_SCALER_HSCC4_hscc4_c1_shift              (16)
#define APP_MIPI_SCALER_HSCC4_hscc4_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSCC4_hscc4_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSCC4_hscc4_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSCC4_get_hscc4_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSCC4_hscc4_c1           0x0
#define APP_MIPI_SCALER_HSCC4_hscc4_c0_shift              (0)
#define APP_MIPI_SCALER_HSCC4_hscc4_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSCC4_hscc4_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSCC4_hscc4_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSCC4_get_hscc4_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSCC4_hscc4_c0           0x0

#define APP_MIPI_SCALER_HSCC5                        0x254
#define APP_MIPI_SCALER_HSCC5_hscc5_c1_shift              (16)
#define APP_MIPI_SCALER_HSCC5_hscc5_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSCC5_hscc5_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSCC5_hscc5_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSCC5_get_hscc5_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSCC5_hscc5_c1           0x0
#define APP_MIPI_SCALER_HSCC5_hscc5_c0_shift              (0)
#define APP_MIPI_SCALER_HSCC5_hscc5_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSCC5_hscc5_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSCC5_hscc5_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSCC5_get_hscc5_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSCC5_hscc5_c0           0x0

#define APP_MIPI_SCALER_HSCC6                        0x258
#define APP_MIPI_SCALER_HSCC6_hscc6_c1_shift              (16)
#define APP_MIPI_SCALER_HSCC6_hscc6_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSCC6_hscc6_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSCC6_hscc6_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSCC6_get_hscc6_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSCC6_hscc6_c1           0x0
#define APP_MIPI_SCALER_HSCC6_hscc6_c0_shift              (0)
#define APP_MIPI_SCALER_HSCC6_hscc6_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSCC6_hscc6_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSCC6_hscc6_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSCC6_get_hscc6_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSCC6_hscc6_c0           0x0

#define APP_MIPI_SCALER_HSCC7                        0x25c
#define APP_MIPI_SCALER_HSCC7_hscc7_c1_shift              (16)
#define APP_MIPI_SCALER_HSCC7_hscc7_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_HSCC7_hscc7_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_HSCC7_hscc7_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_HSCC7_get_hscc7_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_HSCC7_hscc7_c1           0x0
#define APP_MIPI_SCALER_HSCC7_hscc7_c0_shift              (0)
#define APP_MIPI_SCALER_HSCC7_hscc7_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_HSCC7_hscc7_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_HSCC7_hscc7_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_HSCC7_get_hscc7_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_HSCC7_hscc7_c0           0x0

#define APP_MIPI_SCALER_VSYC0                        0x260
#define APP_MIPI_SCALER_VSYC0_vsyc0_c1_shift              (16)
#define APP_MIPI_SCALER_VSYC0_vsyc0_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_VSYC0_vsyc0_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_VSYC0_vsyc0_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_VSYC0_get_vsyc0_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_VSYC0_vsyc0_c1           0x0
#define APP_MIPI_SCALER_VSYC0_vsyc0_c0_shift              (0)
#define APP_MIPI_SCALER_VSYC0_vsyc0_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_VSYC0_vsyc0_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_VSYC0_vsyc0_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_VSYC0_get_vsyc0_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_VSYC0_vsyc0_c0           0x0

#define APP_MIPI_SCALER_VSYC1                        0x264
#define APP_MIPI_SCALER_VSYC1_vsyc1_c1_shift              (16)
#define APP_MIPI_SCALER_VSYC1_vsyc1_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_VSYC1_vsyc1_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_VSYC1_vsyc1_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_VSYC1_get_vsyc1_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_VSYC1_vsyc1_c1           0x0
#define APP_MIPI_SCALER_VSYC1_vsyc1_c0_shift              (0)
#define APP_MIPI_SCALER_VSYC1_vsyc1_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_VSYC1_vsyc1_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_VSYC1_vsyc1_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_VSYC1_get_vsyc1_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_VSYC1_vsyc1_c0           0x0

#define APP_MIPI_SCALER_VSYC2                        0x268
#define APP_MIPI_SCALER_VSYC2_vsyc2_c1_shift              (16)
#define APP_MIPI_SCALER_VSYC2_vsyc2_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_VSYC2_vsyc2_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_VSYC2_vsyc2_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_VSYC2_get_vsyc2_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_VSYC2_vsyc2_c1           0x0
#define APP_MIPI_SCALER_VSYC2_vsyc2_c0_shift              (0)
#define APP_MIPI_SCALER_VSYC2_vsyc2_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_VSYC2_vsyc2_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_VSYC2_vsyc2_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_VSYC2_get_vsyc2_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_VSYC2_vsyc2_c0           0x0

#define APP_MIPI_SCALER_VSYC3                        0x26c
#define APP_MIPI_SCALER_VSYC3_vsyc3_c1_shift              (16)
#define APP_MIPI_SCALER_VSYC3_vsyc3_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_VSYC3_vsyc3_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_VSYC3_vsyc3_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_VSYC3_get_vsyc3_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_VSYC3_vsyc3_c1           0x0
#define APP_MIPI_SCALER_VSYC3_vsyc3_c0_shift              (0)
#define APP_MIPI_SCALER_VSYC3_vsyc3_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_VSYC3_vsyc3_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_VSYC3_vsyc3_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_VSYC3_get_vsyc3_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_VSYC3_vsyc3_c0           0x0

#define APP_MIPI_SCALER_VSCC0                        0x270
#define APP_MIPI_SCALER_VSCC0_vscc0_c1_shift              (16)
#define APP_MIPI_SCALER_VSCC0_vscc0_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_VSCC0_vscc0_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_VSCC0_vscc0_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_VSCC0_get_vscc0_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_VSCC0_vscc0_c1           0x0
#define APP_MIPI_SCALER_VSCC0_vscc0_c0_shift              (0)
#define APP_MIPI_SCALER_VSCC0_vscc0_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_VSCC0_vscc0_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_VSCC0_vscc0_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_VSCC0_get_vscc0_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_VSCC0_vscc0_c0           0x0

#define APP_MIPI_SCALER_VSCC1                        0x274
#define APP_MIPI_SCALER_VSCC1_vscc1_c1_shift              (16)
#define APP_MIPI_SCALER_VSCC1_vscc1_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_VSCC1_vscc1_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_VSCC1_vscc1_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_VSCC1_get_vscc1_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_VSCC1_vscc1_c1           0x0
#define APP_MIPI_SCALER_VSCC1_vscc1_c0_shift              (0)
#define APP_MIPI_SCALER_VSCC1_vscc1_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_VSCC1_vscc1_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_VSCC1_vscc1_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_VSCC1_get_vscc1_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_VSCC1_vscc1_c0           0x0

#define APP_MIPI_SCALER_VSCC2                        0x278
#define APP_MIPI_SCALER_VSCC2_vscc2_c1_shift              (16)
#define APP_MIPI_SCALER_VSCC2_vscc2_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_VSCC2_vscc2_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_VSCC2_vscc2_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_VSCC2_get_vscc2_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_VSCC2_vscc2_c1           0x0
#define APP_MIPI_SCALER_VSCC2_vscc2_c0_shift              (0)
#define APP_MIPI_SCALER_VSCC2_vscc2_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_VSCC2_vscc2_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_VSCC2_vscc2_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_VSCC2_get_vscc2_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_VSCC2_vscc2_c0           0x0

#define APP_MIPI_SCALER_VSCC3                        0x27c
#define APP_MIPI_SCALER_VSCC3_vscc3_c1_shift              (16)
#define APP_MIPI_SCALER_VSCC3_vscc3_c1_mask               (0x3fff0000)
#define APP_MIPI_SCALER_VSCC3_vscc3_c1(data)              (0x3fff0000&((data)<<16))
#define APP_MIPI_SCALER_VSCC3_vscc3_c1_src(data)          ((0x3fff0000&(data))>>16)
#define APP_MIPI_SCALER_VSCC3_get_vscc3_c1(data)          ((0x3fff0000&(data))>>16)
//this->default: APP_MIPI_SCALER_VSCC3_vscc3_c1           0x0
#define APP_MIPI_SCALER_VSCC3_vscc3_c0_shift              (0)
#define APP_MIPI_SCALER_VSCC3_vscc3_c0_mask               (0x3fff)
#define APP_MIPI_SCALER_VSCC3_vscc3_c0(data)              (0x3fff&((data)<<0))
#define APP_MIPI_SCALER_VSCC3_vscc3_c0_src(data)          ((0x3fff&(data))>>0)
#define APP_MIPI_SCALER_VSCC3_get_vscc3_c0(data)          ((0x3fff&(data))>>0)
//this->default: APP_MIPI_SCALER_VSCC3_vscc3_c0           0x0

#define APP_DMA_ENTRY_00                        0x280
#define APP_DMA_ENTRY_00_entry0_sa_y_header_shift              (0)
#define APP_DMA_ENTRY_00_entry0_sa_y_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_00_entry0_sa_y_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_00_entry0_sa_y_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_00_get_entry0_sa_y_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_00_entry0_sa_y_header           0x0

#define APP_DMA_ENTRY_01                        0x284
#define APP_DMA_ENTRY_01_entry0_ea_y_header_shift              (0)
#define APP_DMA_ENTRY_01_entry0_ea_y_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_01_entry0_ea_y_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_01_entry0_ea_y_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_01_get_entry0_ea_y_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_01_entry0_ea_y_header           0x0

#define APP_DMA_ENTRY_02                        0x288
#define APP_DMA_ENTRY_02_entry0_sa_y_body_shift              (0)
#define APP_DMA_ENTRY_02_entry0_sa_y_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_02_entry0_sa_y_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_02_entry0_sa_y_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_02_get_entry0_sa_y_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_02_entry0_sa_y_body           0x0

#define APP_DMA_ENTRY_03                        0x28c
#define APP_DMA_ENTRY_03_entry0_ea_y_body_shift              (0)
#define APP_DMA_ENTRY_03_entry0_ea_y_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_03_entry0_ea_y_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_03_entry0_ea_y_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_03_get_entry0_ea_y_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_03_entry0_ea_y_body           0x0

#define APP_DMA_ENTRY_04                        0x290
#define APP_DMA_ENTRY_04_entry0_sa_c_header_shift              (0)
#define APP_DMA_ENTRY_04_entry0_sa_c_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_04_entry0_sa_c_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_04_entry0_sa_c_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_04_get_entry0_sa_c_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_04_entry0_sa_c_header           0x0

#define APP_DMA_ENTRY_05                        0x294
#define APP_DMA_ENTRY_05_entry0_ea_c_header_shift              (0)
#define APP_DMA_ENTRY_05_entry0_ea_c_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_05_entry0_ea_c_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_05_entry0_ea_c_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_05_get_entry0_ea_c_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_05_entry0_ea_c_header           0x0

#define APP_DMA_ENTRY_06                        0x298
#define APP_DMA_ENTRY_06_entry0_sa_c_body_shift              (0)
#define APP_DMA_ENTRY_06_entry0_sa_c_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_06_entry0_sa_c_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_06_entry0_sa_c_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_06_get_entry0_sa_c_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_06_entry0_sa_c_body           0x0

#define APP_DMA_ENTRY_07                        0x29c
#define APP_DMA_ENTRY_07_entry0_ea_c_body_shift              (0)
#define APP_DMA_ENTRY_07_entry0_ea_c_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_07_entry0_ea_c_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_07_entry0_ea_c_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_07_get_entry0_ea_c_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_07_entry0_ea_c_body           0x0

#define APP_DMA_ENTRY_08                        0x2a0
#define APP_DMA_ENTRY_08_entry0_ma_shift              (0)
#define APP_DMA_ENTRY_08_entry0_ma_mask               (0x7fffffff)
#define APP_DMA_ENTRY_08_entry0_ma(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_08_entry0_ma_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_08_get_entry0_ma(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_08_entry0_ma           0x0

#define APP_DMA_ENTRY_09                        0x2a4
#define APP_DMA_ENTRY_09_write_en6_shift              (27)
#define APP_DMA_ENTRY_09_write_en6_mask               (0x8000000)
#define APP_DMA_ENTRY_09_write_en6(data)              (0x8000000&((data)<<27))
#define APP_DMA_ENTRY_09_write_en6_src(data)          ((0x8000000&(data))>>27)
#define APP_DMA_ENTRY_09_get_write_en6(data)          ((0x8000000&(data))>>27)
//this->default: APP_DMA_ENTRY_09_write_en6           0x0
#define APP_DMA_ENTRY_09_entry0_size_mismatch_shift              (25)
#define APP_DMA_ENTRY_09_entry0_size_mismatch_mask               (0x6000000)
#define APP_DMA_ENTRY_09_entry0_size_mismatch(data)              (0x6000000&((data)<<25))
#define APP_DMA_ENTRY_09_entry0_size_mismatch_src(data)          ((0x6000000&(data))>>25)
#define APP_DMA_ENTRY_09_get_entry0_size_mismatch(data)          ((0x6000000&(data))>>25)
//this->default: APP_DMA_ENTRY_09_entry0_size_mismatch           0x0
#define APP_DMA_ENTRY_09_write_en5_shift              (24)
#define APP_DMA_ENTRY_09_write_en5_mask               (0x1000000)
#define APP_DMA_ENTRY_09_write_en5(data)              (0x1000000&((data)<<24))
#define APP_DMA_ENTRY_09_write_en5_src(data)          ((0x1000000&(data))>>24)
#define APP_DMA_ENTRY_09_get_write_en5(data)          ((0x1000000&(data))>>24)
//this->default: APP_DMA_ENTRY_09_write_en5           0x0
#define APP_DMA_ENTRY_09_entry0_ov_range_shift              (20)
#define APP_DMA_ENTRY_09_entry0_ov_range_mask               (0xf00000)
#define APP_DMA_ENTRY_09_entry0_ov_range(data)              (0xf00000&((data)<<20))
#define APP_DMA_ENTRY_09_entry0_ov_range_src(data)          ((0xf00000&(data))>>20)
#define APP_DMA_ENTRY_09_get_entry0_ov_range(data)          ((0xf00000&(data))>>20)
//this->default: APP_DMA_ENTRY_09_entry0_ov_range           0x0
#define APP_DMA_ENTRY_09_write_en4_shift              (16)
#define APP_DMA_ENTRY_09_write_en4_mask               (0x10000)
#define APP_DMA_ENTRY_09_write_en4(data)              (0x10000&((data)<<16))
#define APP_DMA_ENTRY_09_write_en4_src(data)          ((0x10000&(data))>>16)
#define APP_DMA_ENTRY_09_get_write_en4(data)          ((0x10000&(data))>>16)
//this->default: APP_DMA_ENTRY_09_write_en4           0x0
#define APP_DMA_ENTRY_09_entry0_frame_cnt_shift              (8)
#define APP_DMA_ENTRY_09_entry0_frame_cnt_mask               (0xff00)
#define APP_DMA_ENTRY_09_entry0_frame_cnt(data)              (0xff00&((data)<<8))
#define APP_DMA_ENTRY_09_entry0_frame_cnt_src(data)          ((0xff00&(data))>>8)
#define APP_DMA_ENTRY_09_get_entry0_frame_cnt(data)          ((0xff00&(data))>>8)
//this->default: APP_DMA_ENTRY_09_entry0_frame_cnt           0x0
#define APP_DMA_ENTRY_09_write_en3_shift              (5)
#define APP_DMA_ENTRY_09_write_en3_mask               (0x20)
#define APP_DMA_ENTRY_09_write_en3(data)              (0x20&((data)<<5))
#define APP_DMA_ENTRY_09_write_en3_src(data)          ((0x20&(data))>>5)
#define APP_DMA_ENTRY_09_get_write_en3(data)          ((0x20&(data))>>5)
//this->default: APP_DMA_ENTRY_09_write_en3           0x0
#define APP_DMA_ENTRY_09_entry0_done_shift              (4)
#define APP_DMA_ENTRY_09_entry0_done_mask               (0x10)
#define APP_DMA_ENTRY_09_entry0_done(data)              (0x10&((data)<<4))
#define APP_DMA_ENTRY_09_entry0_done_src(data)          ((0x10&(data))>>4)
#define APP_DMA_ENTRY_09_get_entry0_done(data)          ((0x10&(data))>>4)
//this->default: APP_DMA_ENTRY_09_entry0_done           0x0
#define APP_DMA_ENTRY_09_write_en2_shift              (3)
#define APP_DMA_ENTRY_09_write_en2_mask               (0x8)
#define APP_DMA_ENTRY_09_write_en2(data)              (0x8&((data)<<3))
#define APP_DMA_ENTRY_09_write_en2_src(data)          ((0x8&(data))>>3)
#define APP_DMA_ENTRY_09_get_write_en2(data)          ((0x8&(data))>>3)
//this->default: APP_DMA_ENTRY_09_write_en2           0x0
#define APP_DMA_ENTRY_09_entry0_ovf_shift              (2)
#define APP_DMA_ENTRY_09_entry0_ovf_mask               (0x4)
#define APP_DMA_ENTRY_09_entry0_ovf(data)              (0x4&((data)<<2))
#define APP_DMA_ENTRY_09_entry0_ovf_src(data)          ((0x4&(data))>>2)
#define APP_DMA_ENTRY_09_get_entry0_ovf(data)          ((0x4&(data))>>2)
//this->default: APP_DMA_ENTRY_09_entry0_ovf           0x0
#define APP_DMA_ENTRY_09_write_en1_shift              (1)
#define APP_DMA_ENTRY_09_write_en1_mask               (0x2)
#define APP_DMA_ENTRY_09_write_en1(data)              (0x2&((data)<<1))
#define APP_DMA_ENTRY_09_write_en1_src(data)          ((0x2&(data))>>1)
#define APP_DMA_ENTRY_09_get_write_en1(data)          ((0x2&(data))>>1)
//this->default: APP_DMA_ENTRY_09_write_en1           0x0
#define APP_DMA_ENTRY_09_entry0_valid_shift              (0)
#define APP_DMA_ENTRY_09_entry0_valid_mask               (0x1)
#define APP_DMA_ENTRY_09_entry0_valid(data)              (0x1&((data)<<0))
#define APP_DMA_ENTRY_09_entry0_valid_src(data)          ((0x1&(data))>>0)
#define APP_DMA_ENTRY_09_get_entry0_valid(data)          ((0x1&(data))>>0)
//this->default: APP_DMA_ENTRY_09_entry0_valid           0x0

#define APP_DMA_ENTRY_10                        0x2b0
#define APP_DMA_ENTRY_10_entry1_sa_y_header_shift              (0)
#define APP_DMA_ENTRY_10_entry1_sa_y_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_10_entry1_sa_y_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_10_entry1_sa_y_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_10_get_entry1_sa_y_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_10_entry1_sa_y_header           0x0

#define APP_DMA_ENTRY_11                        0x2b4
#define APP_DMA_ENTRY_11_entry1_ea_y_header_shift              (0)
#define APP_DMA_ENTRY_11_entry1_ea_y_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_11_entry1_ea_y_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_11_entry1_ea_y_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_11_get_entry1_ea_y_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_11_entry1_ea_y_header           0x0

#define APP_DMA_ENTRY_12                        0x2b8
#define APP_DMA_ENTRY_12_entry1_sa_y_body_shift              (0)
#define APP_DMA_ENTRY_12_entry1_sa_y_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_12_entry1_sa_y_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_12_entry1_sa_y_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_12_get_entry1_sa_y_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_12_entry1_sa_y_body           0x0

#define APP_DMA_ENTRY_13                        0x2bc
#define APP_DMA_ENTRY_13_entry1_ea_y_body_shift              (0)
#define APP_DMA_ENTRY_13_entry1_ea_y_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_13_entry1_ea_y_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_13_entry1_ea_y_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_13_get_entry1_ea_y_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_13_entry1_ea_y_body           0x0

#define APP_DMA_ENTRY_14                        0x2c0
#define APP_DMA_ENTRY_14_entry1_sa_c_header_shift              (0)
#define APP_DMA_ENTRY_14_entry1_sa_c_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_14_entry1_sa_c_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_14_entry1_sa_c_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_14_get_entry1_sa_c_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_14_entry1_sa_c_header           0x0

#define APP_DMA_ENTRY_15                        0x2c4
#define APP_DMA_ENTRY_15_entry1_ea_c_header_shift              (0)
#define APP_DMA_ENTRY_15_entry1_ea_c_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_15_entry1_ea_c_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_15_entry1_ea_c_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_15_get_entry1_ea_c_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_15_entry1_ea_c_header           0x0

#define APP_DMA_ENTRY_16                        0x2c8
#define APP_DMA_ENTRY_16_entry1_sa_c_body_shift              (0)
#define APP_DMA_ENTRY_16_entry1_sa_c_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_16_entry1_sa_c_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_16_entry1_sa_c_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_16_get_entry1_sa_c_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_16_entry1_sa_c_body           0x0

#define APP_DMA_ENTRY_17                        0x2cc
#define APP_DMA_ENTRY_17_entry1_ea_c_body_shift              (0)
#define APP_DMA_ENTRY_17_entry1_ea_c_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_17_entry1_ea_c_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_17_entry1_ea_c_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_17_get_entry1_ea_c_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_17_entry1_ea_c_body           0x0

#define APP_DMA_ENTRY_18                        0x2d0
#define APP_DMA_ENTRY_18_entry1_ma_shift              (0)
#define APP_DMA_ENTRY_18_entry1_ma_mask               (0x7fffffff)
#define APP_DMA_ENTRY_18_entry1_ma(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_18_entry1_ma_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_18_get_entry1_ma(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_18_entry1_ma           0x0

#define APP_DMA_ENTRY_19                        0x2d4
#define APP_DMA_ENTRY_19_write_en6_shift              (27)
#define APP_DMA_ENTRY_19_write_en6_mask               (0x8000000)
#define APP_DMA_ENTRY_19_write_en6(data)              (0x8000000&((data)<<27))
#define APP_DMA_ENTRY_19_write_en6_src(data)          ((0x8000000&(data))>>27)
#define APP_DMA_ENTRY_19_get_write_en6(data)          ((0x8000000&(data))>>27)
//this->default: APP_DMA_ENTRY_19_write_en6           0x0
#define APP_DMA_ENTRY_19_entry1_size_mismatch_shift              (25)
#define APP_DMA_ENTRY_19_entry1_size_mismatch_mask               (0x6000000)
#define APP_DMA_ENTRY_19_entry1_size_mismatch(data)              (0x6000000&((data)<<25))
#define APP_DMA_ENTRY_19_entry1_size_mismatch_src(data)          ((0x6000000&(data))>>25)
#define APP_DMA_ENTRY_19_get_entry1_size_mismatch(data)          ((0x6000000&(data))>>25)
//this->default: APP_DMA_ENTRY_19_entry1_size_mismatch           0x0
#define APP_DMA_ENTRY_19_write_en5_shift              (24)
#define APP_DMA_ENTRY_19_write_en5_mask               (0x1000000)
#define APP_DMA_ENTRY_19_write_en5(data)              (0x1000000&((data)<<24))
#define APP_DMA_ENTRY_19_write_en5_src(data)          ((0x1000000&(data))>>24)
#define APP_DMA_ENTRY_19_get_write_en5(data)          ((0x1000000&(data))>>24)
//this->default: APP_DMA_ENTRY_19_write_en5           0x0
#define APP_DMA_ENTRY_19_entry1_ov_range_shift              (20)
#define APP_DMA_ENTRY_19_entry1_ov_range_mask               (0xf00000)
#define APP_DMA_ENTRY_19_entry1_ov_range(data)              (0xf00000&((data)<<20))
#define APP_DMA_ENTRY_19_entry1_ov_range_src(data)          ((0xf00000&(data))>>20)
#define APP_DMA_ENTRY_19_get_entry1_ov_range(data)          ((0xf00000&(data))>>20)
//this->default: APP_DMA_ENTRY_19_entry1_ov_range           0x0
#define APP_DMA_ENTRY_19_write_en4_shift              (16)
#define APP_DMA_ENTRY_19_write_en4_mask               (0x10000)
#define APP_DMA_ENTRY_19_write_en4(data)              (0x10000&((data)<<16))
#define APP_DMA_ENTRY_19_write_en4_src(data)          ((0x10000&(data))>>16)
#define APP_DMA_ENTRY_19_get_write_en4(data)          ((0x10000&(data))>>16)
//this->default: APP_DMA_ENTRY_19_write_en4           0x0
#define APP_DMA_ENTRY_19_entry1_frame_cnt_shift              (8)
#define APP_DMA_ENTRY_19_entry1_frame_cnt_mask               (0xff00)
#define APP_DMA_ENTRY_19_entry1_frame_cnt(data)              (0xff00&((data)<<8))
#define APP_DMA_ENTRY_19_entry1_frame_cnt_src(data)          ((0xff00&(data))>>8)
#define APP_DMA_ENTRY_19_get_entry1_frame_cnt(data)          ((0xff00&(data))>>8)
//this->default: APP_DMA_ENTRY_19_entry1_frame_cnt           0x0
#define APP_DMA_ENTRY_19_write_en3_shift              (5)
#define APP_DMA_ENTRY_19_write_en3_mask               (0x20)
#define APP_DMA_ENTRY_19_write_en3(data)              (0x20&((data)<<5))
#define APP_DMA_ENTRY_19_write_en3_src(data)          ((0x20&(data))>>5)
#define APP_DMA_ENTRY_19_get_write_en3(data)          ((0x20&(data))>>5)
//this->default: APP_DMA_ENTRY_19_write_en3           0x0
#define APP_DMA_ENTRY_19_entry1_done_shift              (4)
#define APP_DMA_ENTRY_19_entry1_done_mask               (0x10)
#define APP_DMA_ENTRY_19_entry1_done(data)              (0x10&((data)<<4))
#define APP_DMA_ENTRY_19_entry1_done_src(data)          ((0x10&(data))>>4)
#define APP_DMA_ENTRY_19_get_entry1_done(data)          ((0x10&(data))>>4)
//this->default: APP_DMA_ENTRY_19_entry1_done           0x0
#define APP_DMA_ENTRY_19_write_en2_shift              (3)
#define APP_DMA_ENTRY_19_write_en2_mask               (0x8)
#define APP_DMA_ENTRY_19_write_en2(data)              (0x8&((data)<<3))
#define APP_DMA_ENTRY_19_write_en2_src(data)          ((0x8&(data))>>3)
#define APP_DMA_ENTRY_19_get_write_en2(data)          ((0x8&(data))>>3)
//this->default: APP_DMA_ENTRY_19_write_en2           0x0
#define APP_DMA_ENTRY_19_entry1_ovf_shift              (2)
#define APP_DMA_ENTRY_19_entry1_ovf_mask               (0x4)
#define APP_DMA_ENTRY_19_entry1_ovf(data)              (0x4&((data)<<2))
#define APP_DMA_ENTRY_19_entry1_ovf_src(data)          ((0x4&(data))>>2)
#define APP_DMA_ENTRY_19_get_entry1_ovf(data)          ((0x4&(data))>>2)
//this->default: APP_DMA_ENTRY_19_entry1_ovf           0x0
#define APP_DMA_ENTRY_19_write_en1_shift              (1)
#define APP_DMA_ENTRY_19_write_en1_mask               (0x2)
#define APP_DMA_ENTRY_19_write_en1(data)              (0x2&((data)<<1))
#define APP_DMA_ENTRY_19_write_en1_src(data)          ((0x2&(data))>>1)
#define APP_DMA_ENTRY_19_get_write_en1(data)          ((0x2&(data))>>1)
//this->default: APP_DMA_ENTRY_19_write_en1           0x0
#define APP_DMA_ENTRY_19_entry1_valid_shift              (0)
#define APP_DMA_ENTRY_19_entry1_valid_mask               (0x1)
#define APP_DMA_ENTRY_19_entry1_valid(data)              (0x1&((data)<<0))
#define APP_DMA_ENTRY_19_entry1_valid_src(data)          ((0x1&(data))>>0)
#define APP_DMA_ENTRY_19_get_entry1_valid(data)          ((0x1&(data))>>0)
//this->default: APP_DMA_ENTRY_19_entry1_valid           0x0

#define APP_DMA_ENTRY_20                        0x2e0
#define APP_DMA_ENTRY_20_entry2_sa_y_header_shift              (0)
#define APP_DMA_ENTRY_20_entry2_sa_y_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_20_entry2_sa_y_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_20_entry2_sa_y_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_20_get_entry2_sa_y_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_20_entry2_sa_y_header           0x0

#define APP_DMA_ENTRY_21                        0x2e4
#define APP_DMA_ENTRY_21_entry2_ea_y_header_shift              (0)
#define APP_DMA_ENTRY_21_entry2_ea_y_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_21_entry2_ea_y_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_21_entry2_ea_y_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_21_get_entry2_ea_y_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_21_entry2_ea_y_header           0x0

#define APP_DMA_ENTRY_22                        0x2e8
#define APP_DMA_ENTRY_22_entry2_sa_y_body_shift              (0)
#define APP_DMA_ENTRY_22_entry2_sa_y_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_22_entry2_sa_y_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_22_entry2_sa_y_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_22_get_entry2_sa_y_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_22_entry2_sa_y_body           0x0

#define APP_DMA_ENTRY_23                        0x2ec
#define APP_DMA_ENTRY_23_entry2_ea_y_body_shift              (0)
#define APP_DMA_ENTRY_23_entry2_ea_y_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_23_entry2_ea_y_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_23_entry2_ea_y_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_23_get_entry2_ea_y_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_23_entry2_ea_y_body           0x0

#define APP_DMA_ENTRY_24                        0x2f0
#define APP_DMA_ENTRY_24_entry2_sa_c_header_shift              (0)
#define APP_DMA_ENTRY_24_entry2_sa_c_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_24_entry2_sa_c_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_24_entry2_sa_c_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_24_get_entry2_sa_c_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_24_entry2_sa_c_header           0x0

#define APP_DMA_ENTRY_25                        0x2f4
#define APP_DMA_ENTRY_25_entry2_ea_c_header_shift              (0)
#define APP_DMA_ENTRY_25_entry2_ea_c_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_25_entry2_ea_c_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_25_entry2_ea_c_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_25_get_entry2_ea_c_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_25_entry2_ea_c_header           0x0

#define APP_DMA_ENTRY_26                        0x2f8
#define APP_DMA_ENTRY_26_entry2_sa_c_body_shift              (0)
#define APP_DMA_ENTRY_26_entry2_sa_c_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_26_entry2_sa_c_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_26_entry2_sa_c_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_26_get_entry2_sa_c_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_26_entry2_sa_c_body           0x0

#define APP_DMA_ENTRY_27                        0x2fc
#define APP_DMA_ENTRY_27_entry2_ea_c_body_shift              (0)
#define APP_DMA_ENTRY_27_entry2_ea_c_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_27_entry2_ea_c_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_27_entry2_ea_c_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_27_get_entry2_ea_c_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_27_entry2_ea_c_body           0x0

#define APP_DMA_ENTRY_28                        0x300
#define APP_DMA_ENTRY_28_entry2_ma_shift              (0)
#define APP_DMA_ENTRY_28_entry2_ma_mask               (0x7fffffff)
#define APP_DMA_ENTRY_28_entry2_ma(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_28_entry2_ma_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_28_get_entry2_ma(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_28_entry2_ma           0x0

#define APP_DMA_ENTRY_29                        0x304
#define APP_DMA_ENTRY_29_write_en6_shift              (27)
#define APP_DMA_ENTRY_29_write_en6_mask               (0x8000000)
#define APP_DMA_ENTRY_29_write_en6(data)              (0x8000000&((data)<<27))
#define APP_DMA_ENTRY_29_write_en6_src(data)          ((0x8000000&(data))>>27)
#define APP_DMA_ENTRY_29_get_write_en6(data)          ((0x8000000&(data))>>27)
//this->default: APP_DMA_ENTRY_29_write_en6           0x0
#define APP_DMA_ENTRY_29_entry2_size_mismatch_shift              (25)
#define APP_DMA_ENTRY_29_entry2_size_mismatch_mask               (0x6000000)
#define APP_DMA_ENTRY_29_entry2_size_mismatch(data)              (0x6000000&((data)<<25))
#define APP_DMA_ENTRY_29_entry2_size_mismatch_src(data)          ((0x6000000&(data))>>25)
#define APP_DMA_ENTRY_29_get_entry2_size_mismatch(data)          ((0x6000000&(data))>>25)
//this->default: APP_DMA_ENTRY_29_entry2_size_mismatch           0x0
#define APP_DMA_ENTRY_29_write_en5_shift              (24)
#define APP_DMA_ENTRY_29_write_en5_mask               (0x1000000)
#define APP_DMA_ENTRY_29_write_en5(data)              (0x1000000&((data)<<24))
#define APP_DMA_ENTRY_29_write_en5_src(data)          ((0x1000000&(data))>>24)
#define APP_DMA_ENTRY_29_get_write_en5(data)          ((0x1000000&(data))>>24)
//this->default: APP_DMA_ENTRY_29_write_en5           0x0
#define APP_DMA_ENTRY_29_entry2_ov_range_shift              (20)
#define APP_DMA_ENTRY_29_entry2_ov_range_mask               (0xf00000)
#define APP_DMA_ENTRY_29_entry2_ov_range(data)              (0xf00000&((data)<<20))
#define APP_DMA_ENTRY_29_entry2_ov_range_src(data)          ((0xf00000&(data))>>20)
#define APP_DMA_ENTRY_29_get_entry2_ov_range(data)          ((0xf00000&(data))>>20)
//this->default: APP_DMA_ENTRY_29_entry2_ov_range           0x0
#define APP_DMA_ENTRY_29_write_en4_shift              (16)
#define APP_DMA_ENTRY_29_write_en4_mask               (0x10000)
#define APP_DMA_ENTRY_29_write_en4(data)              (0x10000&((data)<<16))
#define APP_DMA_ENTRY_29_write_en4_src(data)          ((0x10000&(data))>>16)
#define APP_DMA_ENTRY_29_get_write_en4(data)          ((0x10000&(data))>>16)
//this->default: APP_DMA_ENTRY_29_write_en4           0x0
#define APP_DMA_ENTRY_29_entry2_frame_cnt_shift              (8)
#define APP_DMA_ENTRY_29_entry2_frame_cnt_mask               (0xff00)
#define APP_DMA_ENTRY_29_entry2_frame_cnt(data)              (0xff00&((data)<<8))
#define APP_DMA_ENTRY_29_entry2_frame_cnt_src(data)          ((0xff00&(data))>>8)
#define APP_DMA_ENTRY_29_get_entry2_frame_cnt(data)          ((0xff00&(data))>>8)
//this->default: APP_DMA_ENTRY_29_entry2_frame_cnt           0x0
#define APP_DMA_ENTRY_29_write_en3_shift              (5)
#define APP_DMA_ENTRY_29_write_en3_mask               (0x20)
#define APP_DMA_ENTRY_29_write_en3(data)              (0x20&((data)<<5))
#define APP_DMA_ENTRY_29_write_en3_src(data)          ((0x20&(data))>>5)
#define APP_DMA_ENTRY_29_get_write_en3(data)          ((0x20&(data))>>5)
//this->default: APP_DMA_ENTRY_29_write_en3           0x0
#define APP_DMA_ENTRY_29_entry2_done_shift              (4)
#define APP_DMA_ENTRY_29_entry2_done_mask               (0x10)
#define APP_DMA_ENTRY_29_entry2_done(data)              (0x10&((data)<<4))
#define APP_DMA_ENTRY_29_entry2_done_src(data)          ((0x10&(data))>>4)
#define APP_DMA_ENTRY_29_get_entry2_done(data)          ((0x10&(data))>>4)
//this->default: APP_DMA_ENTRY_29_entry2_done           0x0
#define APP_DMA_ENTRY_29_write_en2_shift              (3)
#define APP_DMA_ENTRY_29_write_en2_mask               (0x8)
#define APP_DMA_ENTRY_29_write_en2(data)              (0x8&((data)<<3))
#define APP_DMA_ENTRY_29_write_en2_src(data)          ((0x8&(data))>>3)
#define APP_DMA_ENTRY_29_get_write_en2(data)          ((0x8&(data))>>3)
//this->default: APP_DMA_ENTRY_29_write_en2           0x0
#define APP_DMA_ENTRY_29_entry2_ovf_shift              (2)
#define APP_DMA_ENTRY_29_entry2_ovf_mask               (0x4)
#define APP_DMA_ENTRY_29_entry2_ovf(data)              (0x4&((data)<<2))
#define APP_DMA_ENTRY_29_entry2_ovf_src(data)          ((0x4&(data))>>2)
#define APP_DMA_ENTRY_29_get_entry2_ovf(data)          ((0x4&(data))>>2)
//this->default: APP_DMA_ENTRY_29_entry2_ovf           0x0
#define APP_DMA_ENTRY_29_write_en1_shift              (1)
#define APP_DMA_ENTRY_29_write_en1_mask               (0x2)
#define APP_DMA_ENTRY_29_write_en1(data)              (0x2&((data)<<1))
#define APP_DMA_ENTRY_29_write_en1_src(data)          ((0x2&(data))>>1)
#define APP_DMA_ENTRY_29_get_write_en1(data)          ((0x2&(data))>>1)
//this->default: APP_DMA_ENTRY_29_write_en1           0x0
#define APP_DMA_ENTRY_29_entry2_valid_shift              (0)
#define APP_DMA_ENTRY_29_entry2_valid_mask               (0x1)
#define APP_DMA_ENTRY_29_entry2_valid(data)              (0x1&((data)<<0))
#define APP_DMA_ENTRY_29_entry2_valid_src(data)          ((0x1&(data))>>0)
#define APP_DMA_ENTRY_29_get_entry2_valid(data)          ((0x1&(data))>>0)
//this->default: APP_DMA_ENTRY_29_entry2_valid           0x0

#define APP_DMA_ENTRY_30                        0x310
#define APP_DMA_ENTRY_30_entry3_sa_y_header_shift              (0)
#define APP_DMA_ENTRY_30_entry3_sa_y_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_30_entry3_sa_y_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_30_entry3_sa_y_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_30_get_entry3_sa_y_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_30_entry3_sa_y_header           0x0

#define APP_DMA_ENTRY_31                        0x314
#define APP_DMA_ENTRY_31_entry3_ea_y_header_shift              (0)
#define APP_DMA_ENTRY_31_entry3_ea_y_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_31_entry3_ea_y_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_31_entry3_ea_y_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_31_get_entry3_ea_y_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_31_entry3_ea_y_header           0x0

#define APP_DMA_ENTRY_32                        0x318
#define APP_DMA_ENTRY_32_entry3_sa_y_body_shift              (0)
#define APP_DMA_ENTRY_32_entry3_sa_y_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_32_entry3_sa_y_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_32_entry3_sa_y_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_32_get_entry3_sa_y_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_32_entry3_sa_y_body           0x0

#define APP_DMA_ENTRY_33                        0x31c
#define APP_DMA_ENTRY_33_entry3_ea_y_body_shift              (0)
#define APP_DMA_ENTRY_33_entry3_ea_y_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_33_entry3_ea_y_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_33_entry3_ea_y_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_33_get_entry3_ea_y_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_33_entry3_ea_y_body           0x0

#define APP_DMA_ENTRY_34                        0x320
#define APP_DMA_ENTRY_34_entry3_sa_c_header_shift              (0)
#define APP_DMA_ENTRY_34_entry3_sa_c_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_34_entry3_sa_c_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_34_entry3_sa_c_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_34_get_entry3_sa_c_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_34_entry3_sa_c_header           0x0

#define APP_DMA_ENTRY_35                        0x324
#define APP_DMA_ENTRY_35_entry3_ea_c_header_shift              (0)
#define APP_DMA_ENTRY_35_entry3_ea_c_header_mask               (0x7fffffff)
#define APP_DMA_ENTRY_35_entry3_ea_c_header(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_35_entry3_ea_c_header_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_35_get_entry3_ea_c_header(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_35_entry3_ea_c_header           0x0

#define APP_DMA_ENTRY_36                        0x328
#define APP_DMA_ENTRY_36_entry3_sa_c_body_shift              (0)
#define APP_DMA_ENTRY_36_entry3_sa_c_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_36_entry3_sa_c_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_36_entry3_sa_c_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_36_get_entry3_sa_c_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_36_entry3_sa_c_body           0x0

#define APP_DMA_ENTRY_37                        0x32c
#define APP_DMA_ENTRY_37_entry3_ea_c_body_shift              (0)
#define APP_DMA_ENTRY_37_entry3_ea_c_body_mask               (0x7fffffff)
#define APP_DMA_ENTRY_37_entry3_ea_c_body(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_37_entry3_ea_c_body_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_37_get_entry3_ea_c_body(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_37_entry3_ea_c_body           0x0

#define APP_DMA_ENTRY_38                        0x330
#define APP_DMA_ENTRY_38_entry3_ma_shift              (0)
#define APP_DMA_ENTRY_38_entry3_ma_mask               (0x7fffffff)
#define APP_DMA_ENTRY_38_entry3_ma(data)              (0x7fffffff&((data)<<0))
#define APP_DMA_ENTRY_38_entry3_ma_src(data)          ((0x7fffffff&(data))>>0)
#define APP_DMA_ENTRY_38_get_entry3_ma(data)          ((0x7fffffff&(data))>>0)
//this->default: APP_DMA_ENTRY_38_entry3_ma           0x0

#define APP_DMA_ENTRY_39                        0x334
#define APP_DMA_ENTRY_39_write_en6_shift              (27)
#define APP_DMA_ENTRY_39_write_en6_mask               (0x8000000)
#define APP_DMA_ENTRY_39_write_en6(data)              (0x8000000&((data)<<27))
#define APP_DMA_ENTRY_39_write_en6_src(data)          ((0x8000000&(data))>>27)
#define APP_DMA_ENTRY_39_get_write_en6(data)          ((0x8000000&(data))>>27)
//this->default: APP_DMA_ENTRY_39_write_en6           0x0
#define APP_DMA_ENTRY_39_entry3_size_mismatch_shift              (25)
#define APP_DMA_ENTRY_39_entry3_size_mismatch_mask               (0x6000000)
#define APP_DMA_ENTRY_39_entry3_size_mismatch(data)              (0x6000000&((data)<<25))
#define APP_DMA_ENTRY_39_entry3_size_mismatch_src(data)          ((0x6000000&(data))>>25)
#define APP_DMA_ENTRY_39_get_entry3_size_mismatch(data)          ((0x6000000&(data))>>25)
//this->default: APP_DMA_ENTRY_39_entry3_size_mismatch           0x0
#define APP_DMA_ENTRY_39_write_en5_shift              (24)
#define APP_DMA_ENTRY_39_write_en5_mask               (0x1000000)
#define APP_DMA_ENTRY_39_write_en5(data)              (0x1000000&((data)<<24))
#define APP_DMA_ENTRY_39_write_en5_src(data)          ((0x1000000&(data))>>24)
#define APP_DMA_ENTRY_39_get_write_en5(data)          ((0x1000000&(data))>>24)
//this->default: APP_DMA_ENTRY_39_write_en5           0x0
#define APP_DMA_ENTRY_39_entry3_ov_range_shift              (20)
#define APP_DMA_ENTRY_39_entry3_ov_range_mask               (0xf00000)
#define APP_DMA_ENTRY_39_entry3_ov_range(data)              (0xf00000&((data)<<20))
#define APP_DMA_ENTRY_39_entry3_ov_range_src(data)          ((0xf00000&(data))>>20)
#define APP_DMA_ENTRY_39_get_entry3_ov_range(data)          ((0xf00000&(data))>>20)
//this->default: APP_DMA_ENTRY_39_entry3_ov_range           0x0
#define APP_DMA_ENTRY_39_write_en4_shift              (16)
#define APP_DMA_ENTRY_39_write_en4_mask               (0x10000)
#define APP_DMA_ENTRY_39_write_en4(data)              (0x10000&((data)<<16))
#define APP_DMA_ENTRY_39_write_en4_src(data)          ((0x10000&(data))>>16)
#define APP_DMA_ENTRY_39_get_write_en4(data)          ((0x10000&(data))>>16)
//this->default: APP_DMA_ENTRY_39_write_en4           0x0
#define APP_DMA_ENTRY_39_entry3_frame_cnt_shift              (8)
#define APP_DMA_ENTRY_39_entry3_frame_cnt_mask               (0xff00)
#define APP_DMA_ENTRY_39_entry3_frame_cnt(data)              (0xff00&((data)<<8))
#define APP_DMA_ENTRY_39_entry3_frame_cnt_src(data)          ((0xff00&(data))>>8)
#define APP_DMA_ENTRY_39_get_entry3_frame_cnt(data)          ((0xff00&(data))>>8)
//this->default: APP_DMA_ENTRY_39_entry3_frame_cnt           0x0
#define APP_DMA_ENTRY_39_write_en3_shift              (5)
#define APP_DMA_ENTRY_39_write_en3_mask               (0x20)
#define APP_DMA_ENTRY_39_write_en3(data)              (0x20&((data)<<5))
#define APP_DMA_ENTRY_39_write_en3_src(data)          ((0x20&(data))>>5)
#define APP_DMA_ENTRY_39_get_write_en3(data)          ((0x20&(data))>>5)
//this->default: APP_DMA_ENTRY_39_write_en3           0x0
#define APP_DMA_ENTRY_39_entry3_done_shift              (4)
#define APP_DMA_ENTRY_39_entry3_done_mask               (0x10)
#define APP_DMA_ENTRY_39_entry3_done(data)              (0x10&((data)<<4))
#define APP_DMA_ENTRY_39_entry3_done_src(data)          ((0x10&(data))>>4)
#define APP_DMA_ENTRY_39_get_entry3_done(data)          ((0x10&(data))>>4)
//this->default: APP_DMA_ENTRY_39_entry3_done           0x0
#define APP_DMA_ENTRY_39_write_en2_shift              (3)
#define APP_DMA_ENTRY_39_write_en2_mask               (0x8)
#define APP_DMA_ENTRY_39_write_en2(data)              (0x8&((data)<<3))
#define APP_DMA_ENTRY_39_write_en2_src(data)          ((0x8&(data))>>3)
#define APP_DMA_ENTRY_39_get_write_en2(data)          ((0x8&(data))>>3)
//this->default: APP_DMA_ENTRY_39_write_en2           0x0
#define APP_DMA_ENTRY_39_entry3_ovf_shift              (2)
#define APP_DMA_ENTRY_39_entry3_ovf_mask               (0x4)
#define APP_DMA_ENTRY_39_entry3_ovf(data)              (0x4&((data)<<2))
#define APP_DMA_ENTRY_39_entry3_ovf_src(data)          ((0x4&(data))>>2)
#define APP_DMA_ENTRY_39_get_entry3_ovf(data)          ((0x4&(data))>>2)
//this->default: APP_DMA_ENTRY_39_entry3_ovf           0x0
#define APP_DMA_ENTRY_39_write_en1_shift              (1)
#define APP_DMA_ENTRY_39_write_en1_mask               (0x2)
#define APP_DMA_ENTRY_39_write_en1(data)              (0x2&((data)<<1))
#define APP_DMA_ENTRY_39_write_en1_src(data)          ((0x2&(data))>>1)
#define APP_DMA_ENTRY_39_get_write_en1(data)          ((0x2&(data))>>1)
//this->default: APP_DMA_ENTRY_39_write_en1           0x0
#define APP_DMA_ENTRY_39_entry3_valid_shift              (0)
#define APP_DMA_ENTRY_39_entry3_valid_mask               (0x1)
#define APP_DMA_ENTRY_39_entry3_valid(data)              (0x1&((data)<<0))
#define APP_DMA_ENTRY_39_entry3_valid_src(data)          ((0x1&(data))>>0)
#define APP_DMA_ENTRY_39_get_entry3_valid(data)          ((0x1&(data))>>0)
//this->default: APP_DMA_ENTRY_39_entry3_valid           0x0

#define APP_COMPENC_0                        0x350
#define APP_COMPENC_0_chroma_max_leaf_nodes_shift              (20)
#define APP_COMPENC_0_chroma_max_leaf_nodes_mask               (0x3f00000)
#define APP_COMPENC_0_chroma_max_leaf_nodes(data)              (0x3f00000&((data)<<20))
#define APP_COMPENC_0_chroma_max_leaf_nodes_src(data)          ((0x3f00000&(data))>>20)
#define APP_COMPENC_0_get_chroma_max_leaf_nodes(data)          ((0x3f00000&(data))>>20)
//this->default: APP_COMPENC_0_chroma_max_leaf_nodes           0x37
#define APP_COMPENC_0_chroma_size_shift              (16)
#define APP_COMPENC_0_chroma_size_mask               (0xf0000)
#define APP_COMPENC_0_chroma_size(data)              (0xf0000&((data)<<16))
#define APP_COMPENC_0_chroma_size_src(data)          ((0xf0000&(data))>>16)
#define APP_COMPENC_0_get_chroma_size(data)          ((0xf0000&(data))>>16)
//this->default: APP_COMPENC_0_chroma_size           0x0
#define APP_COMPENC_0_luma_max_leaf_nodes_shift              (4)
#define APP_COMPENC_0_luma_max_leaf_nodes_mask               (0x3f0)
#define APP_COMPENC_0_luma_max_leaf_nodes(data)              (0x3f0&((data)<<4))
#define APP_COMPENC_0_luma_max_leaf_nodes_src(data)          ((0x3f0&(data))>>4)
#define APP_COMPENC_0_get_luma_max_leaf_nodes(data)          ((0x3f0&(data))>>4)
//this->default: APP_COMPENC_0_luma_max_leaf_nodes           0x37
#define APP_COMPENC_0_luma_size_shift              (0)
#define APP_COMPENC_0_luma_size_mask               (0xf)
#define APP_COMPENC_0_luma_size(data)              (0xf&((data)<<0))
#define APP_COMPENC_0_luma_size_src(data)          ((0xf&(data))>>0)
#define APP_COMPENC_0_get_luma_size(data)          ((0xf&(data))>>0)
//this->default: APP_COMPENC_0_luma_size           0x0

#define APP_COMPENC_1                        0x354
#define APP_COMPENC_1_luma_comp_core_irq_shift              (31)
#define APP_COMPENC_1_luma_comp_core_irq_mask               (0x80000000)
#define APP_COMPENC_1_luma_comp_core_irq(data)              (0x80000000&((data)<<31))
#define APP_COMPENC_1_luma_comp_core_irq_src(data)          ((0x80000000&(data))>>31)
#define APP_COMPENC_1_get_luma_comp_core_irq(data)          ((0x80000000&(data))>>31)
//this->default: APP_COMPENC_1_luma_comp_core_irq           0x0
#define APP_COMPENC_1_luma_comp_core_errflag_clr_shift              (8)
#define APP_COMPENC_1_luma_comp_core_errflag_clr_mask               (0xf00)
#define APP_COMPENC_1_luma_comp_core_errflag_clr(data)              (0xf00&((data)<<8))
#define APP_COMPENC_1_luma_comp_core_errflag_clr_src(data)          ((0xf00&(data))>>8)
#define APP_COMPENC_1_get_luma_comp_core_errflag_clr(data)          ((0xf00&(data))>>8)
//this->default: APP_COMPENC_1_luma_comp_core_errflag_clr           0x0
#define APP_COMPENC_1_luma_comp_core_flag2irq_en_shift              (4)
#define APP_COMPENC_1_luma_comp_core_flag2irq_en_mask               (0xf0)
#define APP_COMPENC_1_luma_comp_core_flag2irq_en(data)              (0xf0&((data)<<4))
#define APP_COMPENC_1_luma_comp_core_flag2irq_en_src(data)          ((0xf0&(data))>>4)
#define APP_COMPENC_1_get_luma_comp_core_flag2irq_en(data)          ((0xf0&(data))>>4)
//this->default: APP_COMPENC_1_luma_comp_core_flag2irq_en           0xf
#define APP_COMPENC_1_luma_comp_core_errflag_shift              (0)
#define APP_COMPENC_1_luma_comp_core_errflag_mask               (0xf)
#define APP_COMPENC_1_luma_comp_core_errflag(data)              (0xf&((data)<<0))
#define APP_COMPENC_1_luma_comp_core_errflag_src(data)          ((0xf&(data))>>0)
#define APP_COMPENC_1_get_luma_comp_core_errflag(data)          ((0xf&(data))>>0)
//this->default: APP_COMPENC_1_luma_comp_core_errflag           0x0

#define APP_COMPENC_2                        0x358
#define APP_COMPENC_2_chroma_comp_core_irq_shift              (31)
#define APP_COMPENC_2_chroma_comp_core_irq_mask               (0x80000000)
#define APP_COMPENC_2_chroma_comp_core_irq(data)              (0x80000000&((data)<<31))
#define APP_COMPENC_2_chroma_comp_core_irq_src(data)          ((0x80000000&(data))>>31)
#define APP_COMPENC_2_get_chroma_comp_core_irq(data)          ((0x80000000&(data))>>31)
//this->default: APP_COMPENC_2_chroma_comp_core_irq           0x0
#define APP_COMPENC_2_chroma_comp_core_errflag_clr_shift              (8)
#define APP_COMPENC_2_chroma_comp_core_errflag_clr_mask               (0xf00)
#define APP_COMPENC_2_chroma_comp_core_errflag_clr(data)              (0xf00&((data)<<8))
#define APP_COMPENC_2_chroma_comp_core_errflag_clr_src(data)          ((0xf00&(data))>>8)
#define APP_COMPENC_2_get_chroma_comp_core_errflag_clr(data)          ((0xf00&(data))>>8)
//this->default: APP_COMPENC_2_chroma_comp_core_errflag_clr           0x0
#define APP_COMPENC_2_chroma_comp_core_flag2irq_en_shift              (4)
#define APP_COMPENC_2_chroma_comp_core_flag2irq_en_mask               (0xf0)
#define APP_COMPENC_2_chroma_comp_core_flag2irq_en(data)              (0xf0&((data)<<4))
#define APP_COMPENC_2_chroma_comp_core_flag2irq_en_src(data)          ((0xf0&(data))>>4)
#define APP_COMPENC_2_get_chroma_comp_core_flag2irq_en(data)          ((0xf0&(data))>>4)
//this->default: APP_COMPENC_2_chroma_comp_core_flag2irq_en           0xf
#define APP_COMPENC_2_chroma_comp_core_errflag_shift              (0)
#define APP_COMPENC_2_chroma_comp_core_errflag_mask               (0xf)
#define APP_COMPENC_2_chroma_comp_core_errflag(data)              (0xf&((data)<<0))
#define APP_COMPENC_2_chroma_comp_core_errflag_src(data)          ((0xf&(data))>>0)
#define APP_COMPENC_2_get_chroma_comp_core_errflag(data)          ((0xf&(data))>>0)
//this->default: APP_COMPENC_2_chroma_comp_core_errflag           0x0

#define APP_COMPENC_3                        0x360
#define APP_COMPENC_3_header_pitch_c_shift              (18)
#define APP_COMPENC_3_header_pitch_c_mask               (0xfffc0000)
#define APP_COMPENC_3_header_pitch_c(data)              (0xfffc0000&((data)<<18))
#define APP_COMPENC_3_header_pitch_c_src(data)          ((0xfffc0000&(data))>>18)
#define APP_COMPENC_3_get_header_pitch_c(data)          ((0xfffc0000&(data))>>18)
//this->default: APP_COMPENC_3_header_pitch_c           0x0
#define APP_COMPENC_3_header_pitch_y_shift              (2)
#define APP_COMPENC_3_header_pitch_y_mask               (0xfffc)
#define APP_COMPENC_3_header_pitch_y(data)              (0xfffc&((data)<<2))
#define APP_COMPENC_3_header_pitch_y_src(data)          ((0xfffc&(data))>>2)
#define APP_COMPENC_3_get_header_pitch_y(data)          ((0xfffc&(data))>>2)
//this->default: APP_COMPENC_3_header_pitch_y           0x0

#endif
