obj-$(CONFIG_SND_SOC_REALTEK) += common/
obj-$(CONFIG_SND_SOC_REALTEK_FL3236) += fl3236/
obj-$(CONFIG_SND_SOC_REALTEK) += aio_ctrl/

# machine driver
snd-soc-rtk-hifi-objs := \
       rtk-hifi-machine.o \

obj-$(CONFIG_SND_SOC_RTK_HIFI_MACHINE) += snd-soc-rtk-hifi.o
