/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef _TOP_0_REG_H_INCLUDED_
#define _TOP_0_REG_H_INCLUDED_

#define TOP_0_DMY0_reg                    0x98004000

#define TOP_0_DMY0                        0x000
#define TOP_0_DMY0_dummy0_shift              (0)
#define TOP_0_DMY0_dummy0_mask               (0xffffffff)
#define TOP_0_DMY0_dummy0(data)              (0xffffffff&((data)<<0))
#define TOP_0_DMY0_dummy0_src(data)          ((0xffffffff&(data))>>0)
#define TOP_0_DMY0_get_dummy0(data)          ((0xffffffff&(data))>>0)
//this->default: TOP_0_DMY0_dummy0           0x0

#define TOP_0_DMY1                        0x004
#define TOP_0_DMY1_dummy1_shift              (0)
#define TOP_0_DMY1_dummy1_mask               (0xffffffff)
#define TOP_0_DMY1_dummy1(data)              (0xffffffff&((data)<<0))
#define TOP_0_DMY1_dummy1_src(data)          ((0xffffffff&(data))>>0)
#define TOP_0_DMY1_get_dummy1(data)          ((0xffffffff&(data))>>0)
//this->default: TOP_0_DMY1_dummy1           0xffffffff

#define TOP_0_TIMER                        0x008
#define TOP_0_TIMER_reg_timer_clk_90k_gating_en_shift              (1)
#define TOP_0_TIMER_reg_timer_clk_90k_gating_en_mask               (0x2)
#define TOP_0_TIMER_reg_timer_clk_90k_gating_en(data)              (0x2&((data)<<1))
#define TOP_0_TIMER_reg_timer_clk_90k_gating_en_src(data)          ((0x2&(data))>>1)
#define TOP_0_TIMER_get_reg_timer_clk_90k_gating_en(data)          ((0x2&(data))>>1)
//this->default: TOP_0_TIMER_reg_timer_clk_90k_gating_en           0x1
#define TOP_0_TIMER_reg_clk_90k_en_shift              (0)
#define TOP_0_TIMER_reg_clk_90k_en_mask               (0x1)
#define TOP_0_TIMER_reg_clk_90k_en(data)              (0x1&((data)<<0))
#define TOP_0_TIMER_reg_clk_90k_en_src(data)          ((0x1&(data))>>0)
#define TOP_0_TIMER_get_reg_clk_90k_en(data)          ((0x1&(data))>>0)
//this->default: TOP_0_TIMER_reg_clk_90k_en           0x1

#define TOP_0_INTEN_SCPU_0                        0x010
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch5_shift              (30)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch5_mask               (0x40000000)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch5(data)              (0x40000000&((data)<<30))
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch5_src(data)          ((0x40000000&(data))>>30)
#define TOP_0_INTEN_SCPU_0_get_entry_invalid_scpu_inten_ch5(data)          ((0x40000000&(data))>>30)
//this->default: TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch5           0x0
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch4_shift              (29)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch4_mask               (0x20000000)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch4(data)              (0x20000000&((data)<<29))
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch4_src(data)          ((0x20000000&(data))>>29)
#define TOP_0_INTEN_SCPU_0_get_entry_invalid_scpu_inten_ch4(data)          ((0x20000000&(data))>>29)
//this->default: TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch4           0x0
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch3_shift              (28)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch3_mask               (0x10000000)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch3(data)              (0x10000000&((data)<<28))
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch3_src(data)          ((0x10000000&(data))>>28)
#define TOP_0_INTEN_SCPU_0_get_entry_invalid_scpu_inten_ch3(data)          ((0x10000000&(data))>>28)
//this->default: TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch3           0x0
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch2_shift              (27)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch2_mask               (0x8000000)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch2(data)              (0x8000000&((data)<<27))
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch2_src(data)          ((0x8000000&(data))>>27)
#define TOP_0_INTEN_SCPU_0_get_entry_invalid_scpu_inten_ch2(data)          ((0x8000000&(data))>>27)
//this->default: TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch2           0x0
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch1_shift              (26)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch1_mask               (0x4000000)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch1(data)              (0x4000000&((data)<<26))
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch1_src(data)          ((0x4000000&(data))>>26)
#define TOP_0_INTEN_SCPU_0_get_entry_invalid_scpu_inten_ch1(data)          ((0x4000000&(data))>>26)
//this->default: TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch1           0x0
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch0_shift              (25)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch0_mask               (0x2000000)
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch0(data)              (0x2000000&((data)<<25))
#define TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch0_src(data)          ((0x2000000&(data))>>25)
#define TOP_0_INTEN_SCPU_0_get_entry_invalid_scpu_inten_ch0(data)          ((0x2000000&(data))>>25)
//this->default: TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ch0           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e3_shift              (24)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e3_mask               (0x1000000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e3(data)              (0x1000000&((data)<<24))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e3_src(data)          ((0x1000000&(data))>>24)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch5e3(data)          ((0x1000000&(data))>>24)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e3           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e2_shift              (23)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e2_mask               (0x800000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e2(data)              (0x800000&((data)<<23))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e2_src(data)          ((0x800000&(data))>>23)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch5e2(data)          ((0x800000&(data))>>23)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e2           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e1_shift              (22)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e1_mask               (0x400000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e1(data)              (0x400000&((data)<<22))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e1_src(data)          ((0x400000&(data))>>22)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch5e1(data)          ((0x400000&(data))>>22)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e1           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e0_shift              (21)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e0_mask               (0x200000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e0(data)              (0x200000&((data)<<21))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e0_src(data)          ((0x200000&(data))>>21)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch5e0(data)          ((0x200000&(data))>>21)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch5e0           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e3_shift              (20)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e3_mask               (0x100000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e3(data)              (0x100000&((data)<<20))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e3_src(data)          ((0x100000&(data))>>20)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch4e3(data)          ((0x100000&(data))>>20)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e3           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e2_shift              (19)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e2_mask               (0x80000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e2(data)              (0x80000&((data)<<19))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e2_src(data)          ((0x80000&(data))>>19)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch4e2(data)          ((0x80000&(data))>>19)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e2           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e1_shift              (18)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e1_mask               (0x40000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e1(data)              (0x40000&((data)<<18))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e1_src(data)          ((0x40000&(data))>>18)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch4e1(data)          ((0x40000&(data))>>18)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e1           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e0_shift              (17)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e0_mask               (0x20000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e0(data)              (0x20000&((data)<<17))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e0_src(data)          ((0x20000&(data))>>17)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch4e0(data)          ((0x20000&(data))>>17)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch4e0           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e3_shift              (16)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e3_mask               (0x10000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e3(data)              (0x10000&((data)<<16))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e3_src(data)          ((0x10000&(data))>>16)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch3e3(data)          ((0x10000&(data))>>16)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e3           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e2_shift              (15)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e2_mask               (0x8000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e2(data)              (0x8000&((data)<<15))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e2_src(data)          ((0x8000&(data))>>15)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch3e2(data)          ((0x8000&(data))>>15)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e2           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e1_shift              (14)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e1_mask               (0x4000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e1(data)              (0x4000&((data)<<14))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e1_src(data)          ((0x4000&(data))>>14)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch3e1(data)          ((0x4000&(data))>>14)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e1           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e0_shift              (13)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e0_mask               (0x2000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e0(data)              (0x2000&((data)<<13))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e0_src(data)          ((0x2000&(data))>>13)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch3e0(data)          ((0x2000&(data))>>13)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch3e0           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e3_shift              (12)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e3_mask               (0x1000)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e3(data)              (0x1000&((data)<<12))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e3_src(data)          ((0x1000&(data))>>12)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch2e3(data)          ((0x1000&(data))>>12)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e3           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e2_shift              (11)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e2_mask               (0x800)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e2(data)              (0x800&((data)<<11))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e2_src(data)          ((0x800&(data))>>11)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch2e2(data)          ((0x800&(data))>>11)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e2           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e1_shift              (10)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e1_mask               (0x400)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e1(data)              (0x400&((data)<<10))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e1_src(data)          ((0x400&(data))>>10)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch2e1(data)          ((0x400&(data))>>10)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e1           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e0_shift              (9)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e0_mask               (0x200)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e0(data)              (0x200&((data)<<9))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e0_src(data)          ((0x200&(data))>>9)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch2e0(data)          ((0x200&(data))>>9)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch2e0           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e3_shift              (8)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e3_mask               (0x100)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e3(data)              (0x100&((data)<<8))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e3_src(data)          ((0x100&(data))>>8)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch1e3(data)          ((0x100&(data))>>8)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e3           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e2_shift              (7)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e2_mask               (0x80)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e2(data)              (0x80&((data)<<7))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e2_src(data)          ((0x80&(data))>>7)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch1e2(data)          ((0x80&(data))>>7)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e2           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e1_shift              (6)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e1_mask               (0x40)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e1(data)              (0x40&((data)<<6))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e1_src(data)          ((0x40&(data))>>6)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch1e1(data)          ((0x40&(data))>>6)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e1           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e0_shift              (5)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e0_mask               (0x20)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e0(data)              (0x20&((data)<<5))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e0_src(data)          ((0x20&(data))>>5)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch1e0(data)          ((0x20&(data))>>5)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch1e0           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e3_shift              (4)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e3_mask               (0x10)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e3(data)              (0x10&((data)<<4))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e3_src(data)          ((0x10&(data))>>4)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch0e3(data)          ((0x10&(data))>>4)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e3           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e2_shift              (3)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e2_mask               (0x8)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e2(data)              (0x8&((data)<<3))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e2_src(data)          ((0x8&(data))>>3)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch0e2(data)          ((0x8&(data))>>3)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e2           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e1_shift              (2)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e1_mask               (0x4)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e1(data)              (0x4&((data)<<2))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e1_src(data)          ((0x4&(data))>>2)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch0e1(data)          ((0x4&(data))>>2)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e1           0x0
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e0_shift              (1)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e0_mask               (0x2)
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e0(data)              (0x2&((data)<<1))
#define TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e0_src(data)          ((0x2&(data))>>1)
#define TOP_0_INTEN_SCPU_0_get_ovf_scpu_inten_ch0e0(data)          ((0x2&(data))>>1)
//this->default: TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ch0e0           0x0

#define TOP_0_INTEN_SCPU_0_err_inten_mask(ch) \
	(TOP_0_INTEN_SCPU_0_entry_invalid_scpu_inten_ ## ch ## _mask | \
	TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ ## ch ## e3_mask | \
	TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ ## ch ## e2_mask | \
	TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ ## ch ## e1_mask | \
	TOP_0_INTEN_SCPU_0_ovf_scpu_inten_ ## ch ## e0_mask)

#define TOP_0_INTEN_SCPU_1                        0x014
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e3_shift              (24)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e3_mask               (0x1000000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e3(data)              (0x1000000&((data)<<24))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e3_src(data)          ((0x1000000&(data))>>24)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch5e3(data)          ((0x1000000&(data))>>24)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e3           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e2_shift              (23)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e2_mask               (0x800000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e2(data)              (0x800000&((data)<<23))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e2_src(data)          ((0x800000&(data))>>23)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch5e2(data)          ((0x800000&(data))>>23)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e2           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e1_shift              (22)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e1_mask               (0x400000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e1(data)              (0x400000&((data)<<22))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e1_src(data)          ((0x400000&(data))>>22)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch5e1(data)          ((0x400000&(data))>>22)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e1           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e0_shift              (21)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e0_mask               (0x200000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e0(data)              (0x200000&((data)<<21))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e0_src(data)          ((0x200000&(data))>>21)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch5e0(data)          ((0x200000&(data))>>21)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e0           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e3_shift              (20)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e3_mask               (0x100000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e3(data)              (0x100000&((data)<<20))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e3_src(data)          ((0x100000&(data))>>20)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch4e3(data)          ((0x100000&(data))>>20)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e3           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e2_shift              (19)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e2_mask               (0x80000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e2(data)              (0x80000&((data)<<19))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e2_src(data)          ((0x80000&(data))>>19)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch4e2(data)          ((0x80000&(data))>>19)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e2           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e1_shift              (18)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e1_mask               (0x40000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e1(data)              (0x40000&((data)<<18))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e1_src(data)          ((0x40000&(data))>>18)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch4e1(data)          ((0x40000&(data))>>18)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e1           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e0_shift              (17)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e0_mask               (0x20000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e0(data)              (0x20000&((data)<<17))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e0_src(data)          ((0x20000&(data))>>17)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch4e0(data)          ((0x20000&(data))>>17)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e0           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e3_shift              (16)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e3_mask               (0x10000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e3(data)              (0x10000&((data)<<16))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e3_src(data)          ((0x10000&(data))>>16)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch3e3(data)          ((0x10000&(data))>>16)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e3           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e2_shift              (15)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e2_mask               (0x8000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e2(data)              (0x8000&((data)<<15))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e2_src(data)          ((0x8000&(data))>>15)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch3e2(data)          ((0x8000&(data))>>15)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e2           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e1_shift              (14)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e1_mask               (0x4000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e1(data)              (0x4000&((data)<<14))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e1_src(data)          ((0x4000&(data))>>14)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch3e1(data)          ((0x4000&(data))>>14)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e1           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e0_shift              (13)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e0_mask               (0x2000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e0(data)              (0x2000&((data)<<13))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e0_src(data)          ((0x2000&(data))>>13)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch3e0(data)          ((0x2000&(data))>>13)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e0           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e3_shift              (12)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e3_mask               (0x1000)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e3(data)              (0x1000&((data)<<12))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e3_src(data)          ((0x1000&(data))>>12)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch2e3(data)          ((0x1000&(data))>>12)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e3           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e2_shift              (11)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e2_mask               (0x800)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e2(data)              (0x800&((data)<<11))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e2_src(data)          ((0x800&(data))>>11)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch2e2(data)          ((0x800&(data))>>11)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e2           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e1_shift              (10)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e1_mask               (0x400)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e1(data)              (0x400&((data)<<10))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e1_src(data)          ((0x400&(data))>>10)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch2e1(data)          ((0x400&(data))>>10)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e1           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e0_shift              (9)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e0_mask               (0x200)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e0(data)              (0x200&((data)<<9))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e0_src(data)          ((0x200&(data))>>9)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch2e0(data)          ((0x200&(data))>>9)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e0           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e3_shift              (8)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e3_mask               (0x100)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e3(data)              (0x100&((data)<<8))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e3_src(data)          ((0x100&(data))>>8)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch1e3(data)          ((0x100&(data))>>8)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e3           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e2_shift              (7)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e2_mask               (0x80)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e2(data)              (0x80&((data)<<7))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e2_src(data)          ((0x80&(data))>>7)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch1e2(data)          ((0x80&(data))>>7)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e2           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e1_shift              (6)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e1_mask               (0x40)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e1(data)              (0x40&((data)<<6))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e1_src(data)          ((0x40&(data))>>6)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch1e1(data)          ((0x40&(data))>>6)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e1           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e0_shift              (5)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e0_mask               (0x20)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e0(data)              (0x20&((data)<<5))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e0_src(data)          ((0x20&(data))>>5)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch1e0(data)          ((0x20&(data))>>5)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e0           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e3_shift              (4)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e3_mask               (0x10)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e3(data)              (0x10&((data)<<4))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e3_src(data)          ((0x10&(data))>>4)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch0e3(data)          ((0x10&(data))>>4)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e3           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e2_shift              (3)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e2_mask               (0x8)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e2(data)              (0x8&((data)<<3))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e2_src(data)          ((0x8&(data))>>3)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch0e2(data)          ((0x8&(data))>>3)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e2           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e1_shift              (2)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e1_mask               (0x4)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e1(data)              (0x4&((data)<<2))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e1_src(data)          ((0x4&(data))>>2)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch0e1(data)          ((0x4&(data))>>2)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e1           0x0
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e0_shift              (1)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e0_mask               (0x2)
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e0(data)              (0x2&((data)<<1))
#define TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e0_src(data)          ((0x2&(data))>>1)
#define TOP_0_INTEN_SCPU_1_get_done_scpu_inten_ch0e0(data)          ((0x2&(data))>>1)
//this->default: TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e0           0x0

#define TOP_0_INTEN_SCPU_1_done_inten_mask(ch) \
	(TOP_0_INTEN_SCPU_1_done_scpu_inten_ ## ch ## e3_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ ## ch ## e2_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ ## ch ## e1_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ ## ch ## e0_mask)

#define TOP_0_INTEN_SCPU_1_done_inten_ch5_mask \
	(TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e3_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e2_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e1_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch5e0_mask)
#define TOP_0_INTEN_SCPU_1_done_inten_ch4_mask \
	(TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e3_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e2_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e1_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch4e0_mask)
#define TOP_0_INTEN_SCPU_1_done_inten_ch3_mask \
	(TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e3_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e2_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e1_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch3e0_mask)
#define TOP_0_INTEN_SCPU_1_done_inten_ch2_mask \
	(TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e3_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e2_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e1_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch2e0_mask)
#define TOP_0_INTEN_SCPU_1_done_inten_ch1_mask \
	(TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e3_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e2_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e1_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch1e0_mask)
#define TOP_0_INTEN_SCPU_1_done_inten_ch0_mask \
	(TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e3_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e2_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e1_mask | \
	TOP_0_INTEN_SCPU_1_done_scpu_inten_ch0e0_mask)

#define TOP_0_INT_STS_SCPU_0                        0x020
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch5_shift              (30)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch5_mask               (0x40000000)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch5(data)              (0x40000000&((data)<<30))
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch5_src(data)          ((0x40000000&(data))>>30)
#define TOP_0_INT_STS_SCPU_0_get_scpu_entry_invalid_sts_ch5(data)          ((0x40000000&(data))>>30)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch5           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch4_shift              (29)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch4_mask               (0x20000000)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch4(data)              (0x20000000&((data)<<29))
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch4_src(data)          ((0x20000000&(data))>>29)
#define TOP_0_INT_STS_SCPU_0_get_scpu_entry_invalid_sts_ch4(data)          ((0x20000000&(data))>>29)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch4           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch3_shift              (28)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch3_mask               (0x10000000)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch3(data)              (0x10000000&((data)<<28))
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch3_src(data)          ((0x10000000&(data))>>28)
#define TOP_0_INT_STS_SCPU_0_get_scpu_entry_invalid_sts_ch3(data)          ((0x10000000&(data))>>28)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch3           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch2_shift              (27)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch2_mask               (0x8000000)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch2(data)              (0x8000000&((data)<<27))
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch2_src(data)          ((0x8000000&(data))>>27)
#define TOP_0_INT_STS_SCPU_0_get_scpu_entry_invalid_sts_ch2(data)          ((0x8000000&(data))>>27)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch2           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch1_shift              (26)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch1_mask               (0x4000000)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch1(data)              (0x4000000&((data)<<26))
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch1_src(data)          ((0x4000000&(data))>>26)
#define TOP_0_INT_STS_SCPU_0_get_scpu_entry_invalid_sts_ch1(data)          ((0x4000000&(data))>>26)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch1           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch0_shift              (25)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch0_mask               (0x2000000)
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch0(data)              (0x2000000&((data)<<25))
#define TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch0_src(data)          ((0x2000000&(data))>>25)
#define TOP_0_INT_STS_SCPU_0_get_scpu_entry_invalid_sts_ch0(data)          ((0x2000000&(data))>>25)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_entry_invalid_sts_ch0           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e3_shift              (24)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e3_mask               (0x1000000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e3(data)              (0x1000000&((data)<<24))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e3_src(data)          ((0x1000000&(data))>>24)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch5e3(data)          ((0x1000000&(data))>>24)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e3           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e2_shift              (23)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e2_mask               (0x800000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e2(data)              (0x800000&((data)<<23))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e2_src(data)          ((0x800000&(data))>>23)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch5e2(data)          ((0x800000&(data))>>23)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e2           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e1_shift              (22)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e1_mask               (0x400000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e1(data)              (0x400000&((data)<<22))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e1_src(data)          ((0x400000&(data))>>22)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch5e1(data)          ((0x400000&(data))>>22)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e1           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e0_shift              (21)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e0_mask               (0x200000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e0(data)              (0x200000&((data)<<21))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e0_src(data)          ((0x200000&(data))>>21)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch5e0(data)          ((0x200000&(data))>>21)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch5e0           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e3_shift              (20)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e3_mask               (0x100000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e3(data)              (0x100000&((data)<<20))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e3_src(data)          ((0x100000&(data))>>20)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch4e3(data)          ((0x100000&(data))>>20)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e3           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e2_shift              (19)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e2_mask               (0x80000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e2(data)              (0x80000&((data)<<19))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e2_src(data)          ((0x80000&(data))>>19)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch4e2(data)          ((0x80000&(data))>>19)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e2           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e1_shift              (18)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e1_mask               (0x40000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e1(data)              (0x40000&((data)<<18))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e1_src(data)          ((0x40000&(data))>>18)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch4e1(data)          ((0x40000&(data))>>18)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e1           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e0_shift              (17)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e0_mask               (0x20000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e0(data)              (0x20000&((data)<<17))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e0_src(data)          ((0x20000&(data))>>17)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch4e0(data)          ((0x20000&(data))>>17)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch4e0           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e3_shift              (16)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e3_mask               (0x10000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e3(data)              (0x10000&((data)<<16))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e3_src(data)          ((0x10000&(data))>>16)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch3e3(data)          ((0x10000&(data))>>16)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e3           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e2_shift              (15)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e2_mask               (0x8000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e2(data)              (0x8000&((data)<<15))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e2_src(data)          ((0x8000&(data))>>15)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch3e2(data)          ((0x8000&(data))>>15)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e2           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e1_shift              (14)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e1_mask               (0x4000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e1(data)              (0x4000&((data)<<14))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e1_src(data)          ((0x4000&(data))>>14)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch3e1(data)          ((0x4000&(data))>>14)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e1           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e0_shift              (13)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e0_mask               (0x2000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e0(data)              (0x2000&((data)<<13))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e0_src(data)          ((0x2000&(data))>>13)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch3e0(data)          ((0x2000&(data))>>13)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch3e0           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e3_shift              (12)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e3_mask               (0x1000)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e3(data)              (0x1000&((data)<<12))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e3_src(data)          ((0x1000&(data))>>12)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch2e3(data)          ((0x1000&(data))>>12)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e3           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e2_shift              (11)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e2_mask               (0x800)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e2(data)              (0x800&((data)<<11))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e2_src(data)          ((0x800&(data))>>11)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch2e2(data)          ((0x800&(data))>>11)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e2           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e1_shift              (10)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e1_mask               (0x400)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e1(data)              (0x400&((data)<<10))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e1_src(data)          ((0x400&(data))>>10)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch2e1(data)          ((0x400&(data))>>10)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e1           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e0_shift              (9)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e0_mask               (0x200)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e0(data)              (0x200&((data)<<9))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e0_src(data)          ((0x200&(data))>>9)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch2e0(data)          ((0x200&(data))>>9)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch2e0           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e3_shift              (8)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e3_mask               (0x100)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e3(data)              (0x100&((data)<<8))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e3_src(data)          ((0x100&(data))>>8)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch1e3(data)          ((0x100&(data))>>8)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e3           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e2_shift              (7)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e2_mask               (0x80)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e2(data)              (0x80&((data)<<7))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e2_src(data)          ((0x80&(data))>>7)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch1e2(data)          ((0x80&(data))>>7)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e2           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e1_shift              (6)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e1_mask               (0x40)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e1(data)              (0x40&((data)<<6))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e1_src(data)          ((0x40&(data))>>6)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch1e1(data)          ((0x40&(data))>>6)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e1           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e0_shift              (5)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e0_mask               (0x20)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e0(data)              (0x20&((data)<<5))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e0_src(data)          ((0x20&(data))>>5)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch1e0(data)          ((0x20&(data))>>5)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch1e0           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e3_shift              (4)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e3_mask               (0x10)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e3(data)              (0x10&((data)<<4))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e3_src(data)          ((0x10&(data))>>4)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch0e3(data)          ((0x10&(data))>>4)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e3           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e2_shift              (3)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e2_mask               (0x8)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e2(data)              (0x8&((data)<<3))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e2_src(data)          ((0x8&(data))>>3)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch0e2(data)          ((0x8&(data))>>3)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e2           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e1_shift              (2)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e1_mask               (0x4)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e1(data)              (0x4&((data)<<2))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e1_src(data)          ((0x4&(data))>>2)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch0e1(data)          ((0x4&(data))>>2)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e1           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e0_shift              (1)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e0_mask               (0x2)
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e0(data)              (0x2&((data)<<1))
#define TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e0_src(data)          ((0x2&(data))>>1)
#define TOP_0_INT_STS_SCPU_0_get_scpu_ovf_sts_ch0e0(data)          ((0x2&(data))>>1)
//this->default: TOP_0_INT_STS_SCPU_0_scpu_ovf_sts_ch0e0           0x0
#define TOP_0_INT_STS_SCPU_0_write_data_shift              (0)
#define TOP_0_INT_STS_SCPU_0_write_data_mask               (0x1)
#define TOP_0_INT_STS_SCPU_0_write_data(data)              (0x1&((data)<<0))
#define TOP_0_INT_STS_SCPU_0_write_data_src(data)          ((0x1&(data))>>0)
#define TOP_0_INT_STS_SCPU_0_get_write_data(data)          ((0x1&(data))>>0)
//this->default: TOP_0_INT_STS_SCPU_0_write_data           0x0
#define TOP_0_INT_STS_SCPU_0_scpu_error_sts_ch5_mask        (0x41E00000)
#define TOP_0_INT_STS_SCPU_0_scpu_error_sts_ch4_mask        (0x201E0000)
#define TOP_0_INT_STS_SCPU_0_scpu_error_sts_ch3_mask        (0x1001E000)
#define TOP_0_INT_STS_SCPU_0_scpu_error_sts_ch2_mask        (0x08001E00)
#define TOP_0_INT_STS_SCPU_0_scpu_error_sts_ch1_mask        (0x040001E0)
#define TOP_0_INT_STS_SCPU_0_scpu_error_sts_ch0_mask        (0x0200001E)

#define TOP_0_INT_STS_SCPU_1                        0x024
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch5_shift            (30)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch5_mask             (0x40000000)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch5(data)            (0x40000000&((data)<<30))
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch5_src(data)        ((0x40000000&(data))>>30)
#define TOP_0_INT_STS_SCPU_1_get_scpu_mismatch_sts_ch5(data)        ((0x40000000&(data))>>30)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch5       0x0
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch4_shift            (29)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch4_mask             (0x20000000)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch4(data)            (0x20000000&((data)<<29))
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch4_src(data)        ((0x20000000&(data))>>29)
#define TOP_0_INT_STS_SCPU_1_get_scpu_mismatch_sts_ch4(data)        ((0x20000000&(data))>>29)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch4       0x0
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch3_shift            (28)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch3_mask             (0x10000000)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch3(data)            (0x10000000&((data)<<28))
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch3_src(data)        ((0x10000000&(data))>>28)
#define TOP_0_INT_STS_SCPU_1_get_scpu_mismatch_sts_ch3(data)        ((0x10000000&(data))>>28)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch3       0x0
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch2_shift            (27)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch2_mask             (0x08000000)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch2(data)            (0x08000000&((data)<<27))
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch2_src(data)        ((0x08000000&(data))>>27)
#define TOP_0_INT_STS_SCPU_1_get_scpu_mismatch_sts_ch2(data)        ((0x08000000&(data))>>27)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch2       0x0
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch1_shift            (26)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch1_mask             (0x04000000)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch1(data)            (0x04000000&((data)<<26))
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch1_src(data)        ((0x04000000&(data))>>26)
#define TOP_0_INT_STS_SCPU_1_get_scpu_mismatch_sts_ch1(data)        ((0x04000000&(data))>>26)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch1       0x0
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch0_shift            (25)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch0_mask             (0x02000000)
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch0(data)            (0x02000000&((data)<<25))
#define TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch0_src(data)        ((0x02000000&(data))>>25)
#define TOP_0_INT_STS_SCPU_1_get_scpu_mismatch_sts_ch0(data)        ((0x02000000&(data))>>25)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_mismatch_sts_ch0       0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e3_shift              (24)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e3_mask               (0x1000000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e3(data)              (0x1000000&((data)<<24))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e3_src(data)          ((0x1000000&(data))>>24)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch5e3(data)          ((0x1000000&(data))>>24)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e3           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e2_shift              (23)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e2_mask               (0x800000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e2(data)              (0x800000&((data)<<23))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e2_src(data)          ((0x800000&(data))>>23)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch5e2(data)          ((0x800000&(data))>>23)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e2           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e1_shift              (22)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e1_mask               (0x400000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e1(data)              (0x400000&((data)<<22))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e1_src(data)          ((0x400000&(data))>>22)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch5e1(data)          ((0x400000&(data))>>22)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e1           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e0_shift              (21)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e0_mask               (0x200000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e0(data)              (0x200000&((data)<<21))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e0_src(data)          ((0x200000&(data))>>21)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch5e0(data)          ((0x200000&(data))>>21)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5e0           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e3_shift              (20)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e3_mask               (0x100000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e3(data)              (0x100000&((data)<<20))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e3_src(data)          ((0x100000&(data))>>20)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch4e3(data)          ((0x100000&(data))>>20)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e3           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e2_shift              (19)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e2_mask               (0x80000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e2(data)              (0x80000&((data)<<19))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e2_src(data)          ((0x80000&(data))>>19)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch4e2(data)          ((0x80000&(data))>>19)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e2           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e1_shift              (18)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e1_mask               (0x40000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e1(data)              (0x40000&((data)<<18))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e1_src(data)          ((0x40000&(data))>>18)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch4e1(data)          ((0x40000&(data))>>18)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e1           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e0_shift              (17)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e0_mask               (0x20000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e0(data)              (0x20000&((data)<<17))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e0_src(data)          ((0x20000&(data))>>17)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch4e0(data)          ((0x20000&(data))>>17)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4e0           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e3_shift              (16)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e3_mask               (0x10000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e3(data)              (0x10000&((data)<<16))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e3_src(data)          ((0x10000&(data))>>16)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch3e3(data)          ((0x10000&(data))>>16)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e3           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e2_shift              (15)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e2_mask               (0x8000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e2(data)              (0x8000&((data)<<15))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e2_src(data)          ((0x8000&(data))>>15)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch3e2(data)          ((0x8000&(data))>>15)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e2           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e1_shift              (14)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e1_mask               (0x4000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e1(data)              (0x4000&((data)<<14))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e1_src(data)          ((0x4000&(data))>>14)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch3e1(data)          ((0x4000&(data))>>14)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e1           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e0_shift              (13)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e0_mask               (0x2000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e0(data)              (0x2000&((data)<<13))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e0_src(data)          ((0x2000&(data))>>13)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch3e0(data)          ((0x2000&(data))>>13)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3e0           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e3_shift              (12)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e3_mask               (0x1000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e3(data)              (0x1000&((data)<<12))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e3_src(data)          ((0x1000&(data))>>12)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch2e3(data)          ((0x1000&(data))>>12)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e3           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e2_shift              (11)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e2_mask               (0x800)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e2(data)              (0x800&((data)<<11))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e2_src(data)          ((0x800&(data))>>11)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch2e2(data)          ((0x800&(data))>>11)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e2           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e1_shift              (10)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e1_mask               (0x400)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e1(data)              (0x400&((data)<<10))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e1_src(data)          ((0x400&(data))>>10)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch2e1(data)          ((0x400&(data))>>10)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e1           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e0_shift              (9)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e0_mask               (0x200)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e0(data)              (0x200&((data)<<9))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e0_src(data)          ((0x200&(data))>>9)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch2e0(data)          ((0x200&(data))>>9)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2e0           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e3_shift              (8)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e3_mask               (0x100)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e3(data)              (0x100&((data)<<8))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e3_src(data)          ((0x100&(data))>>8)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch1e3(data)          ((0x100&(data))>>8)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e3           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e2_shift              (7)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e2_mask               (0x80)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e2(data)              (0x80&((data)<<7))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e2_src(data)          ((0x80&(data))>>7)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch1e2(data)          ((0x80&(data))>>7)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e2           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e1_shift              (6)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e1_mask               (0x40)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e1(data)              (0x40&((data)<<6))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e1_src(data)          ((0x40&(data))>>6)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch1e1(data)          ((0x40&(data))>>6)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e1           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e0_shift              (5)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e0_mask               (0x20)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e0(data)              (0x20&((data)<<5))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e0_src(data)          ((0x20&(data))>>5)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch1e0(data)          ((0x20&(data))>>5)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1e0           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e3_shift              (4)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e3_mask               (0x10)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e3(data)              (0x10&((data)<<4))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e3_src(data)          ((0x10&(data))>>4)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch0e3(data)          ((0x10&(data))>>4)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e3           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e2_shift              (3)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e2_mask               (0x8)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e2(data)              (0x8&((data)<<3))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e2_src(data)          ((0x8&(data))>>3)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch0e2(data)          ((0x8&(data))>>3)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e2           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e1_shift              (2)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e1_mask               (0x4)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e1(data)              (0x4&((data)<<2))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e1_src(data)          ((0x4&(data))>>2)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch0e1(data)          ((0x4&(data))>>2)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e1           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e0_shift              (1)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e0_mask               (0x2)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e0(data)              (0x2&((data)<<1))
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e0_src(data)          ((0x2&(data))>>1)
#define TOP_0_INT_STS_SCPU_1_get_scpu_done_sts_ch0e0(data)          ((0x2&(data))>>1)
//this->default: TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0e0           0x0
#define TOP_0_INT_STS_SCPU_1_write_data_shift              (0)
#define TOP_0_INT_STS_SCPU_1_write_data_mask               (0x1)
#define TOP_0_INT_STS_SCPU_1_write_data(data)              (0x1&((data)<<0))
#define TOP_0_INT_STS_SCPU_1_write_data_src(data)          ((0x1&(data))>>0)
#define TOP_0_INT_STS_SCPU_1_get_write_data(data)          ((0x1&(data))>>0)
//this->default: TOP_0_INT_STS_SCPU_1_write_data           0x0
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_all_mask        (0x01FFFFFE)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch5_mask        (0x01E00000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch4_mask        (0x001E0000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch3_mask        (0x0001E000)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch2_mask        (0x00001E00)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch1_mask        (0x000001E0)
#define TOP_0_INT_STS_SCPU_1_scpu_done_sts_ch0_mask        (0x0000001E)

#define TOP_0_DBG_0                        0x040
#define TOP_0_DBG_0_dbg_en_shift              (8)
#define TOP_0_DBG_0_dbg_en_mask               (0x100)
#define TOP_0_DBG_0_dbg_en(data)              (0x100&((data)<<8))
#define TOP_0_DBG_0_dbg_en_src(data)          ((0x100&(data))>>8)
#define TOP_0_DBG_0_get_dbg_en(data)          ((0x100&(data))>>8)
//this->default: TOP_0_DBG_0_dbg_en           0x0
#define TOP_0_DBG_0_dbg_sel1_shift              (4)
#define TOP_0_DBG_0_dbg_sel1_mask               (0xf0)
#define TOP_0_DBG_0_dbg_sel1(data)              (0xf0&((data)<<4))
#define TOP_0_DBG_0_dbg_sel1_src(data)          ((0xf0&(data))>>4)
#define TOP_0_DBG_0_get_dbg_sel1(data)          ((0xf0&(data))>>4)
//this->default: TOP_0_DBG_0_dbg_sel1           0x0
#define TOP_0_DBG_0_dbg_sel0_shift              (0)
#define TOP_0_DBG_0_dbg_sel0_mask               (0xf)
#define TOP_0_DBG_0_dbg_sel0(data)              (0xf&((data)<<0))
#define TOP_0_DBG_0_dbg_sel0_src(data)          ((0xf&(data))>>0)
#define TOP_0_DBG_0_get_dbg_sel0(data)          ((0xf&(data))>>0)
//this->default: TOP_0_DBG_0_dbg_sel0           0x0

#define TOP_0_CTI_BUF_UTI                        0x044
#define TOP_0_CTI_BUF_UTI_cti_buf_full_num_shift              (16)
#define TOP_0_CTI_BUF_UTI_cti_buf_full_num_mask               (0x1f0000)
#define TOP_0_CTI_BUF_UTI_cti_buf_full_num(data)              (0x1f0000&((data)<<16))
#define TOP_0_CTI_BUF_UTI_cti_buf_full_num_src(data)          ((0x1f0000&(data))>>16)
#define TOP_0_CTI_BUF_UTI_get_cti_buf_full_num(data)          ((0x1f0000&(data))>>16)
//this->default: TOP_0_CTI_BUF_UTI_cti_buf_full_num           0x0
#define TOP_0_CTI_BUF_UTI_cti_buf_max_det_sel_shift              (10)
#define TOP_0_CTI_BUF_UTI_cti_buf_max_det_sel_mask               (0x7c00)
#define TOP_0_CTI_BUF_UTI_cti_buf_max_det_sel(data)              (0x7c00&((data)<<10))
#define TOP_0_CTI_BUF_UTI_cti_buf_max_det_sel_src(data)          ((0x7c00&(data))>>10)
#define TOP_0_CTI_BUF_UTI_get_cti_buf_max_det_sel(data)          ((0x7c00&(data))>>10)
//this->default: TOP_0_CTI_BUF_UTI_cti_buf_max_det_sel           0x0
#define TOP_0_CTI_BUF_UTI_cti_buf_count_clr_shift              (9)
#define TOP_0_CTI_BUF_UTI_cti_buf_count_clr_mask               (0x200)
#define TOP_0_CTI_BUF_UTI_cti_buf_count_clr(data)              (0x200&((data)<<9))
#define TOP_0_CTI_BUF_UTI_cti_buf_count_clr_src(data)          ((0x200&(data))>>9)
#define TOP_0_CTI_BUF_UTI_get_cti_buf_count_clr(data)          ((0x200&(data))>>9)
//this->default: TOP_0_CTI_BUF_UTI_cti_buf_count_clr           0x0
#define TOP_0_CTI_BUF_UTI_cti_buf_max_count_shift              (0)
#define TOP_0_CTI_BUF_UTI_cti_buf_max_count_mask               (0x1ff)
#define TOP_0_CTI_BUF_UTI_cti_buf_max_count(data)              (0x1ff&((data)<<0))
#define TOP_0_CTI_BUF_UTI_cti_buf_max_count_src(data)          ((0x1ff&(data))>>0)
#define TOP_0_CTI_BUF_UTI_get_cti_buf_max_count(data)          ((0x1ff&(data))>>0)
//this->default: TOP_0_CTI_BUF_UTI_cti_buf_max_count           0x0

#define TOP_0_CTI_DBG_0                        0x048
#define TOP_0_CTI_DBG_0_dbg_cti_path_sel_shift              (31)
#define TOP_0_CTI_DBG_0_dbg_cti_path_sel_mask               (0x80000000)
#define TOP_0_CTI_DBG_0_dbg_cti_path_sel(data)              (0x80000000&((data)<<31))
#define TOP_0_CTI_DBG_0_dbg_cti_path_sel_src(data)          ((0x80000000&(data))>>31)
#define TOP_0_CTI_DBG_0_get_dbg_cti_path_sel(data)          ((0x80000000&(data))>>31)
//this->default: TOP_0_CTI_DBG_0_dbg_cti_path_sel           0x0
#define TOP_0_CTI_DBG_0_dbg_cti_addr_shift              (0)
#define TOP_0_CTI_DBG_0_dbg_cti_addr_mask               (0x7fffffff)
#define TOP_0_CTI_DBG_0_dbg_cti_addr(data)              (0x7fffffff&((data)<<0))
#define TOP_0_CTI_DBG_0_dbg_cti_addr_src(data)          ((0x7fffffff&(data))>>0)
#define TOP_0_CTI_DBG_0_get_dbg_cti_addr(data)          ((0x7fffffff&(data))>>0)
//this->default: TOP_0_CTI_DBG_0_dbg_cti_addr           0x0

#define TOP_0_CTI_DBG_1                        0x04c
#define TOP_0_CTI_DBG_1_dbg_cti_ch_shift              (12)
#define TOP_0_CTI_DBG_1_dbg_cti_ch_mask               (0x7000)
#define TOP_0_CTI_DBG_1_dbg_cti_ch(data)              (0x7000&((data)<<12))
#define TOP_0_CTI_DBG_1_dbg_cti_ch_src(data)          ((0x7000&(data))>>12)
#define TOP_0_CTI_DBG_1_get_dbg_cti_ch(data)          ((0x7000&(data))>>12)
//this->default: TOP_0_CTI_DBG_1_dbg_cti_ch           0x0
#define TOP_0_CTI_DBG_1_dbg_cti_trig_shift              (8)
#define TOP_0_CTI_DBG_1_dbg_cti_trig_mask               (0x100)
#define TOP_0_CTI_DBG_1_dbg_cti_trig(data)              (0x100&((data)<<8))
#define TOP_0_CTI_DBG_1_dbg_cti_trig_src(data)          ((0x100&(data))>>8)
#define TOP_0_CTI_DBG_1_get_dbg_cti_trig(data)          ((0x100&(data))>>8)
//this->default: TOP_0_CTI_DBG_1_dbg_cti_trig           0x0
#define TOP_0_CTI_DBG_1_dbg_cti_len_shift              (0)
#define TOP_0_CTI_DBG_1_dbg_cti_len_mask               (0x7f)
#define TOP_0_CTI_DBG_1_dbg_cti_len(data)              (0x7f&((data)<<0))
#define TOP_0_CTI_DBG_1_dbg_cti_len_src(data)          ((0x7f&(data))>>0)
#define TOP_0_CTI_DBG_1_get_dbg_cti_len(data)          ((0x7f&(data))>>0)
//this->default: TOP_0_CTI_DBG_1_dbg_cti_len           0x0

#define TOP_0_COLOR_BAR_0                        0x050
#define TOP_0_COLOR_BAR_0_color_bar_hf_shift              (24)
#define TOP_0_COLOR_BAR_0_color_bar_hf_mask               (0xff000000)
#define TOP_0_COLOR_BAR_0_color_bar_hf(data)              (0xff000000&((data)<<24))
#define TOP_0_COLOR_BAR_0_color_bar_hf_src(data)          ((0xff000000&(data))>>24)
#define TOP_0_COLOR_BAR_0_get_color_bar_hf(data)          ((0xff000000&(data))>>24)
//this->default: TOP_0_COLOR_BAR_0_color_bar_hf           0x6
#define TOP_0_COLOR_BAR_0_color_bar_heigh_shift              (12)
#define TOP_0_COLOR_BAR_0_color_bar_heigh_mask               (0xfff000)
#define TOP_0_COLOR_BAR_0_color_bar_heigh(data)              (0xfff000&((data)<<12))
#define TOP_0_COLOR_BAR_0_color_bar_heigh_src(data)          ((0xfff000&(data))>>12)
#define TOP_0_COLOR_BAR_0_get_color_bar_heigh(data)          ((0xfff000&(data))>>12)
//this->default: TOP_0_COLOR_BAR_0_color_bar_heigh           0xa
#define TOP_0_COLOR_BAR_0_color_bar_width_shift              (0)
#define TOP_0_COLOR_BAR_0_color_bar_width_mask               (0xfff)
#define TOP_0_COLOR_BAR_0_color_bar_width(data)              (0xfff&((data)<<0))
#define TOP_0_COLOR_BAR_0_color_bar_width_src(data)          ((0xfff&(data))>>0)
#define TOP_0_COLOR_BAR_0_get_color_bar_width(data)          ((0xfff&(data))>>0)
//this->default: TOP_0_COLOR_BAR_0_color_bar_width           0x780

#define TOP_0_COLOR_BAR_1                        0x054
#define TOP_0_COLOR_BAR_1_color_bar_sel_shift              (29)
#define TOP_0_COLOR_BAR_1_color_bar_sel_mask               (0x20000000)
#define TOP_0_COLOR_BAR_1_color_bar_sel(data)              (0x20000000&((data)<<29))
#define TOP_0_COLOR_BAR_1_color_bar_sel_src(data)          ((0x20000000&(data))>>29)
#define TOP_0_COLOR_BAR_1_get_color_bar_sel(data)          ((0x20000000&(data))>>29)
//this->default: TOP_0_COLOR_BAR_1_color_bar_sel           0x0
#define TOP_0_COLOR_BAR_1_color_bar_en_shift              (28)
#define TOP_0_COLOR_BAR_1_color_bar_en_mask               (0x10000000)
#define TOP_0_COLOR_BAR_1_color_bar_en(data)              (0x10000000&((data)<<28))
#define TOP_0_COLOR_BAR_1_color_bar_en_src(data)          ((0x10000000&(data))>>28)
#define TOP_0_COLOR_BAR_1_get_color_bar_en(data)          ((0x10000000&(data))>>28)
//this->default: TOP_0_COLOR_BAR_1_color_bar_en           0x0
#define TOP_0_COLOR_BAR_1_color_bar_vb_shift              (24)
#define TOP_0_COLOR_BAR_1_color_bar_vb_mask               (0xf000000)
#define TOP_0_COLOR_BAR_1_color_bar_vb(data)              (0xf000000&((data)<<24))
#define TOP_0_COLOR_BAR_1_color_bar_vb_src(data)          ((0xf000000&(data))>>24)
#define TOP_0_COLOR_BAR_1_get_color_bar_vb(data)          ((0xf000000&(data))>>24)
//this->default: TOP_0_COLOR_BAR_1_color_bar_vb           0x3
#define TOP_0_COLOR_BAR_1_color_bar_vs_shift              (20)
#define TOP_0_COLOR_BAR_1_color_bar_vs_mask               (0xf00000)
#define TOP_0_COLOR_BAR_1_color_bar_vs(data)              (0xf00000&((data)<<20))
#define TOP_0_COLOR_BAR_1_color_bar_vs_src(data)          ((0xf00000&(data))>>20)
#define TOP_0_COLOR_BAR_1_get_color_bar_vs(data)          ((0xf00000&(data))>>20)
//this->default: TOP_0_COLOR_BAR_1_color_bar_vs           0x5
#define TOP_0_COLOR_BAR_1_color_bar_vf_shift              (16)
#define TOP_0_COLOR_BAR_1_color_bar_vf_mask               (0xf0000)
#define TOP_0_COLOR_BAR_1_color_bar_vf(data)              (0xf0000&((data)<<16))
#define TOP_0_COLOR_BAR_1_color_bar_vf_src(data)          ((0xf0000&(data))>>16)
#define TOP_0_COLOR_BAR_1_get_color_bar_vf(data)          ((0xf0000&(data))>>16)
//this->default: TOP_0_COLOR_BAR_1_color_bar_vf           0x2
#define TOP_0_COLOR_BAR_1_color_bar_hb_shift              (8)
#define TOP_0_COLOR_BAR_1_color_bar_hb_mask               (0xff00)
#define TOP_0_COLOR_BAR_1_color_bar_hb(data)              (0xff00&((data)<<8))
#define TOP_0_COLOR_BAR_1_color_bar_hb_src(data)          ((0xff00&(data))>>8)
#define TOP_0_COLOR_BAR_1_get_color_bar_hb(data)          ((0xff00&(data))>>8)
//this->default: TOP_0_COLOR_BAR_1_color_bar_hb           0x8
#define TOP_0_COLOR_BAR_1_color_bar_hs_shift              (0)
#define TOP_0_COLOR_BAR_1_color_bar_hs_mask               (0xff)
#define TOP_0_COLOR_BAR_1_color_bar_hs(data)              (0xff&((data)<<0))
#define TOP_0_COLOR_BAR_1_color_bar_hs_src(data)          ((0xff&(data))>>0)
#define TOP_0_COLOR_BAR_1_get_color_bar_hs(data)          ((0xff&(data))>>0)
//this->default: TOP_0_COLOR_BAR_1_color_bar_hs           0x4

#define TOP_0_CRC                        0x058
#define TOP_0_CRC_crc_enable_shift              (12)
#define TOP_0_CRC_crc_enable_mask               (0x1000)
#define TOP_0_CRC_crc_enable(data)              (0x1000&((data)<<12))
#define TOP_0_CRC_crc_enable_src(data)          ((0x1000&(data))>>12)
#define TOP_0_CRC_get_crc_enable(data)          ((0x1000&(data))>>12)
//this->default: TOP_0_CRC_crc_enable           0x0
#define TOP_0_CRC_crc_ch_sel_shift              (9)
#define TOP_0_CRC_crc_ch_sel_mask               (0xe00)
#define TOP_0_CRC_crc_ch_sel(data)              (0xe00&((data)<<9))
#define TOP_0_CRC_crc_ch_sel_src(data)          ((0xe00&(data))>>9)
#define TOP_0_CRC_get_crc_ch_sel(data)          ((0xe00&(data))>>9)
//this->default: TOP_0_CRC_crc_ch_sel           0x0
#define TOP_0_CRC_crc_stable_shift              (8)
#define TOP_0_CRC_crc_stable_mask               (0x100)
#define TOP_0_CRC_crc_stable(data)              (0x100&((data)<<8))
#define TOP_0_CRC_crc_stable_src(data)          ((0x100&(data))>>8)
#define TOP_0_CRC_get_crc_stable(data)          ((0x100&(data))>>8)
//this->default: TOP_0_CRC_crc_stable           0x0
#define TOP_0_CRC_crc_value_shift              (0)
#define TOP_0_CRC_crc_value_mask               (0xff)
#define TOP_0_CRC_crc_value(data)              (0xff&((data)<<0))
#define TOP_0_CRC_crc_value_src(data)          ((0xff&(data))>>0)
#define TOP_0_CRC_get_crc_value(data)          ((0xff&(data))>>0)
//this->default: TOP_0_CRC_crc_value           0x0

#define TOP_0_SWAP_SEL                        0x060
#define TOP_0_SWAP_SEL_cti_wdata_swap_shift              (4)
#define TOP_0_SWAP_SEL_cti_wdata_swap_mask               (0x30)
#define TOP_0_SWAP_SEL_cti_wdata_swap(data)              (0x30&((data)<<4))
#define TOP_0_SWAP_SEL_cti_wdata_swap_src(data)          ((0x30&(data))>>4)
#define TOP_0_SWAP_SEL_get_cti_wdata_swap(data)          ((0x30&(data))>>4)
//this->default: TOP_0_SWAP_SEL_cti_wdata_swap           0x0
#define TOP_0_SWAP_SEL_reg_metadata_byte_swap_shift              (2)
#define TOP_0_SWAP_SEL_reg_metadata_byte_swap_mask               (0x4)
#define TOP_0_SWAP_SEL_reg_metadata_byte_swap(data)              (0x4&((data)<<2))
#define TOP_0_SWAP_SEL_reg_metadata_byte_swap_src(data)          ((0x4&(data))>>2)
#define TOP_0_SWAP_SEL_get_reg_metadata_byte_swap(data)          ((0x4&(data))>>2)
//this->default: TOP_0_SWAP_SEL_reg_metadata_byte_swap           0x0
#define TOP_0_SWAP_SEL_reg_header_byte_swap_shift              (1)
#define TOP_0_SWAP_SEL_reg_header_byte_swap_mask               (0x2)
#define TOP_0_SWAP_SEL_reg_header_byte_swap(data)              (0x2&((data)<<1))
#define TOP_0_SWAP_SEL_reg_header_byte_swap_src(data)          ((0x2&(data))>>1)
#define TOP_0_SWAP_SEL_get_reg_header_byte_swap(data)          ((0x2&(data))>>1)
//this->default: TOP_0_SWAP_SEL_reg_header_byte_swap           0x0
#define TOP_0_SWAP_SEL_reg_body_byte_swap_shift              (0)
#define TOP_0_SWAP_SEL_reg_body_byte_swap_mask               (0x1)
#define TOP_0_SWAP_SEL_reg_body_byte_swap(data)              (0x1&((data)<<0))
#define TOP_0_SWAP_SEL_reg_body_byte_swap_src(data)          ((0x1&(data))>>0)
#define TOP_0_SWAP_SEL_get_reg_body_byte_swap(data)          ((0x1&(data))>>0)
//this->default: TOP_0_SWAP_SEL_reg_body_byte_swap           0x0

#define TOP_0_DBG_1                        0x064
#define TOP_0_DBG_1_user_byte_mode_patch_shift              (1)
#define TOP_0_DBG_1_user_byte_mode_patch_mask               (0x2)
#define TOP_0_DBG_1_user_byte_mode_patch(data)              (0x2&((data)<<1))
#define TOP_0_DBG_1_user_byte_mode_patch_src(data)          ((0x2&(data))>>1)
#define TOP_0_DBG_1_get_user_byte_mode_patch(data)          ((0x2&(data))>>1)
//this->default: TOP_0_DBG_1_user_byte_mode_patch           0x1
#define TOP_0_DBG_1_icg_bypass_shift              (0)
#define TOP_0_DBG_1_icg_bypass_mask               (0x1)
#define TOP_0_DBG_1_icg_bypass(data)              (0x1&((data)<<0))
#define TOP_0_DBG_1_icg_bypass_src(data)          ((0x1&(data))>>0)
#define TOP_0_DBG_1_get_icg_bypass(data)          ((0x1&(data))>>0)
//this->default: TOP_0_DBG_1_icg_bypass           0x0

#define TOP_0_CTI_URGENT_CTRL                        0x0a0
#define TOP_0_CTI_URGENT_CTRL_qos_enable_shift              (27)
#define TOP_0_CTI_URGENT_CTRL_qos_enable_mask               (0x8000000)
#define TOP_0_CTI_URGENT_CTRL_qos_enable(data)              (0x8000000&((data)<<27))
#define TOP_0_CTI_URGENT_CTRL_qos_enable_src(data)          ((0x8000000&(data))>>27)
#define TOP_0_CTI_URGENT_CTRL_get_qos_enable(data)          ((0x8000000&(data))>>27)
//this->default: TOP_0_CTI_URGENT_CTRL_qos_enable           0x0
#define TOP_0_CTI_URGENT_CTRL_qos_thr_2_shift              (22)
#define TOP_0_CTI_URGENT_CTRL_qos_thr_2_mask               (0x7c00000)
#define TOP_0_CTI_URGENT_CTRL_qos_thr_2(data)              (0x7c00000&((data)<<22))
#define TOP_0_CTI_URGENT_CTRL_qos_thr_2_src(data)          ((0x7c00000&(data))>>22)
#define TOP_0_CTI_URGENT_CTRL_get_qos_thr_2(data)          ((0x7c00000&(data))>>22)
//this->default: TOP_0_CTI_URGENT_CTRL_qos_thr_2           0x0
#define TOP_0_CTI_URGENT_CTRL_qos_thr_1_shift              (17)
#define TOP_0_CTI_URGENT_CTRL_qos_thr_1_mask               (0x3e0000)
#define TOP_0_CTI_URGENT_CTRL_qos_thr_1(data)              (0x3e0000&((data)<<17))
#define TOP_0_CTI_URGENT_CTRL_qos_thr_1_src(data)          ((0x3e0000&(data))>>17)
#define TOP_0_CTI_URGENT_CTRL_get_qos_thr_1(data)          ((0x3e0000&(data))>>17)
//this->default: TOP_0_CTI_URGENT_CTRL_qos_thr_1           0x0
#define TOP_0_CTI_URGENT_CTRL_qos_thr_0_shift              (12)
#define TOP_0_CTI_URGENT_CTRL_qos_thr_0_mask               (0x1f000)
#define TOP_0_CTI_URGENT_CTRL_qos_thr_0(data)              (0x1f000&((data)<<12))
#define TOP_0_CTI_URGENT_CTRL_qos_thr_0_src(data)          ((0x1f000&(data))>>12)
#define TOP_0_CTI_URGENT_CTRL_get_qos_thr_0(data)          ((0x1f000&(data))>>12)
//this->default: TOP_0_CTI_URGENT_CTRL_qos_thr_0           0x0
#define TOP_0_CTI_URGENT_CTRL_urgent_enable_shift              (10)
#define TOP_0_CTI_URGENT_CTRL_urgent_enable_mask               (0x400)
#define TOP_0_CTI_URGENT_CTRL_urgent_enable(data)              (0x400&((data)<<10))
#define TOP_0_CTI_URGENT_CTRL_urgent_enable_src(data)          ((0x400&(data))>>10)
#define TOP_0_CTI_URGENT_CTRL_get_urgent_enable(data)          ((0x400&(data))>>10)
//this->default: TOP_0_CTI_URGENT_CTRL_urgent_enable           0x0
#define TOP_0_CTI_URGENT_CTRL_urgent_thr_high_shift              (5)
#define TOP_0_CTI_URGENT_CTRL_urgent_thr_high_mask               (0x3e0)
#define TOP_0_CTI_URGENT_CTRL_urgent_thr_high(data)              (0x3e0&((data)<<5))
#define TOP_0_CTI_URGENT_CTRL_urgent_thr_high_src(data)          ((0x3e0&(data))>>5)
#define TOP_0_CTI_URGENT_CTRL_get_urgent_thr_high(data)          ((0x3e0&(data))>>5)
//this->default: TOP_0_CTI_URGENT_CTRL_urgent_thr_high           0x0
#define TOP_0_CTI_URGENT_CTRL_urgent_thr_low_shift              (0)
#define TOP_0_CTI_URGENT_CTRL_urgent_thr_low_mask               (0x1f)
#define TOP_0_CTI_URGENT_CTRL_urgent_thr_low(data)              (0x1f&((data)<<0))
#define TOP_0_CTI_URGENT_CTRL_urgent_thr_low_src(data)          ((0x1f&(data))>>0)
#define TOP_0_CTI_URGENT_CTRL_get_urgent_thr_low(data)          ((0x1f&(data))>>0)
//this->default: TOP_0_CTI_URGENT_CTRL_urgent_thr_low           0x0

#endif

