/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Realtek Embedded DisplayPort Register
 *
 * Copyright (c) 2025 Realtek Semiconductor Corp.
 *
 */

#ifndef _RTK_EDP_REG_H
#define _RTK_EDP_REG_H

/**
 * DP_PHY_CTRL : 0x98009400
 */

#define DP_PHY_CTRL		0x000
#define DPTX_ML_PAT_SEL		0x004
#define CUSTOM_PATTERN_0	0x008
#define CUSTOM_PATTERN_1	0x00C
#define CUSTOM_PATTERN_2	0x010
#define CUSTOM_PATTERN_3	0x014
#define CUSTOM_PATTERN_4	0x018
#define CUSTOM_PATTERN_5	0x01C
#define CUSTOM_PATTERN_6	0x020
#define CUSTOM_PATTERN_7	0x024
#define CUSTOM_PATTERN_8	0x028
#define CUSTOM_PATTERN_9	0x02C
#define COMPLIANCE_EYE_PATTERN	0x030
#define DPTX_PHY_CTRL		0x034
#define DPTX_LANE_SWAP		0x038
#define DPTX_8B10B_TST		0x03C
#define DPTX_PHY_DUMMY		0x040
#define RIV0			0x044
#define RIV1			0x048
#define RIV2			0x04C
#define RIV3			0x050
#define RIV4			0x054
#define RIV5			0x058
#define RIV6			0x05C
#define RIV7			0x060
#define DPTX_HDCP_CTRL1		0x0C0
#define DPTX_HDCP_CTRL2		0x0C4
#define DP_HDCP_KEY_DL_PORT	0x0C8
#define DP_HDCP_KEY_OUTPUT	0x0CC
#define AN_BYTE_7		0x0D0
#define AN_BYTE_6		0x0D4
#define AN_BYTE_5		0x0D8
#define AN_BYTE_4		0x0DC
#define AN_BYTE_3		0x0E0
#define AN_BYTE_2		0x0E4
#define AN_BYTE_1		0x0E8
#define AN_BYTE_0		0x0EC
#define M0_BYTE_7		0x0F0
#define M0_BYTE_6		0x0F4
#define M0_BYTE_5		0x0F8
#define M0_BYTE_4		0x0FC
#define M0_BYTE_3		0x100
#define M0_BYTE_2		0x104
#define M0_BYTE_1		0x108
#define M0_BYTE_0		0x10C
#define KM_BYTE_6		0x110
#define KM_BYTE_5		0x114
#define KM_BYTE_4		0x118
#define KM_BYTE_3		0x11C
#define KM_BYTE_2		0x120
#define KM_BYTE_1		0x124
#define KM_BYTE_0		0x128
#define R0_BYTE_MSB		0x12C
#define R0_BYTE_LSB		0x130
#define RI_BYTE_MSB		0x134
#define RI_BYTE_LSB		0x138
#define BKSV_0			0x13C
#define BKSV_1			0x140
#define BKSV_2			0x144
#define BKSV_3			0x148
#define BKSV_4			0x14C
#define HDCP_TX_LIP_H		0x150
#define HDCP_TX_LIP_L		0x154
#define DP_HDCP_TX		0x158
#define DP_HDCP_BIST		0x15C
#define DP_HDCP_AN_SEED		0x160
#define HDCP_IRQ_EVENT		0x164
#define DPTX_HDCP_TST		0x168
#define DP_HDCP_TX_SHA_CTRL	0x16C
#define DP_HDCP_TX_SHA_DATA_3	0x170
#define DP_HDCP_TX_SHA_DATA_2	0x174
#define DP_HDCP_TX_SHA_DATA_1	0x178
#define DP_HDCP_TX_SHA_DATA_0	0x17C
#define DP_HDCP_TX_SHA_OUT_3	0x180
#define DP_HDCP_TX_SHA_OUT_2	0x184
#define DP_HDCP_TX_SHA_OUT_1	0x188
#define DP_HDCP_TX_SHA_OUT_0	0x18C
#define HDCP_ECF_BYTE0		0x190
#define HDCP_ECF_BYTE1		0x194
#define HDCP_ECF_BYTE2		0x198
#define HDCP_ECF_BYTE3		0x19C
#define HDCP_ECF_BYTE4		0x1A0
#define HDCP_ECF_BYTE5		0x1A4
#define HDCP_ECF_BYTE6		0x1A8
#define HDCP_ECF_BYTE7		0x1AC
#define DP_STREAM_1_PBN		0x1B0
#define DP_STREAM_2_PBN		0x1B4
#define DP_STREAM_3_PBN		0x1B8
#define DP_STREAM_4_PBN		0x1BC

/* DP_IP_DP_PHY_CTRL */
#define DP_IP_DP_PHY_CTRL_v2analog_shift			(4)
#define DP_IP_DP_PHY_CTRL_v2analog_mask				(0xf0)
#define DP_IP_DP_PHY_CTRL_v2analog(data)			(0xf0&((data)<<4))
#define DP_IP_DP_PHY_CTRL_lane_num_shift			(2)
#define DP_IP_DP_PHY_CTRL_lane_num_mask				(0xc)
#define DP_IP_DP_PHY_CTRL_lane_num(data)			(0xc&((data)<<2))
#define DP_IP_DP_PHY_CTRL_mst_en_shift				(1)
#define DP_IP_DP_PHY_CTRL_mst_en_mask				(0x2)
#define DP_IP_DP_PHY_CTRL_mst_en(data)				(0x2&((data)<<1))
#define DP_IP_DP_PHY_CTRL_phy_reset_shift			(0)
#define DP_IP_DP_PHY_CTRL_phy_reset_mask			(0x1)
#define DP_IP_DP_PHY_CTRL_phy_reset(data)			(0x1&((data)<<0))
/* DP_IP_DPTX_PHY_CTRL */
#define DP_IP_DPTX_PHY_CTRL_hw_measure_en_shift		(7)
#define DP_IP_DPTX_PHY_CTRL_hw_measure_en_mask		(0x80)
#define DP_IP_DPTX_PHY_CTRL_hw_measure_en(data)		(0x80&((data)<<7))
#define DP_IP_DPTX_PHY_CTRL_sr_insert_en_shift		(4)
#define DP_IP_DPTX_PHY_CTRL_sr_insert_en_mask		(0x10)
#define DP_IP_DPTX_PHY_CTRL_sr_insert_en(data)		(0x10&((data)<<4))
#define DP_IP_DPTX_PHY_CTRL_dptx_skew_en_shift		(2)
#define DP_IP_DPTX_PHY_CTRL_dptx_skew_en_mask		(0x4)
#define DP_IP_DPTX_PHY_CTRL_dptx_skew_en(data)		(0x4&((data)<<2))
#define DP_IP_DPTX_PHY_CTRL_dptx_scb_mode_shift		(1)
#define DP_IP_DPTX_PHY_CTRL_dptx_scb_mode_mask		(0x2)
#define DP_IP_DPTX_PHY_CTRL_dptx_scb_mode(data)		(0x2&((data)<<1))
#define DP_IP_DPTX_PHY_CTRL_dptx_scb_en_shift		(0)
#define DP_IP_DPTX_PHY_CTRL_dptx_scb_en_mask		(0x1)
#define DP_IP_DPTX_PHY_CTRL_dptx_scb_en(data)		(0x1&((data)<<0))
/* DP_IP_DPTX_ML_PAT_SEL */
#define DP_IP_DPTX_ML_PAT_SEL_tx_ml_pat_sel_shift			(4)
#define DP_IP_DPTX_ML_PAT_SEL_tx_ml_pat_sel_mask			(0xf0)
#define DP_IP_DPTX_ML_PAT_SEL_tx_ml_pat_sel(data)			(0xf0&((data)<<4))
#define DP_IP_DPTX_ML_PAT_SEL_switch_pattern_auto_shift		(3)
#define DP_IP_DPTX_ML_PAT_SEL_switch_pattern_auto_mask		(0x8)
#define DP_IP_DPTX_ML_PAT_SEL_switch_pattern_auto(data)		(0x8&((data)<<3))
#define DP_IP_DPTX_ML_PAT_SEL_prbs_reverse_shift			(2)
#define DP_IP_DPTX_ML_PAT_SEL_prbs_reverse_mask				(0x4)
#define DP_IP_DPTX_ML_PAT_SEL_prbs_reverse(data)			(0x4&((data)<<2))
#define DP_IP_DPTX_ML_PAT_SEL_tx_ml_pat_sel_en_shift		(1)
#define DP_IP_DPTX_ML_PAT_SEL_tx_ml_pat_sel_en_mask			(0x2)
#define DP_IP_DPTX_ML_PAT_SEL_tx_ml_pat_sel_en(data)		(0x2&((data)<<1))
#define DP_IP_DPTX_ML_PAT_SEL_pat_sel_dbuf_shift			(0)
#define DP_IP_DPTX_ML_PAT_SEL_pat_sel_dbuf_mask				(0x1)
#define DP_IP_DPTX_ML_PAT_SEL_pat_sel_dbuf(data)			(0x1&((data)<<0))

/**
 * HPD_CTRL
 */

#define HPD_CTRL 0x1C0
#define HPD_IRQ 0x1C4
#define HPD_IRQ_EN 0x1C8
#define HPD_TIMER1 0x1CC
#define HPD_TIMER2 0x1D0
#define HPD_TIMER3 0x1D4
#define HPD_TIMER4 0x1D8
#define HPD_TIMER5 0x1DC
#define HPD_TIMER6 0x1E0
#define HPD_TIMER7 0x1E4
#define HPD_LONG0 0x1E8
#define HPD_LONG1 0x1EC
#define HPD_STATE 0x1F0
#define RESERVED_0 0x1f4
#define RESERVED_1 0x1f8

/**
 * HDCP_AES_CIPHER_KEY_15
 */

#define HDCP_AES_CIPHER_KEY_15	0x200
#define HDCP_AES_CIPHER_KEY_14	0x204
#define HDCP_AES_CIPHER_KEY_13	0x208
#define HDCP_AES_CIPHER_KEY_12	0x20C
#define HDCP_AES_CIPHER_KEY_11	0x210
#define HDCP_AES_CIPHER_KEY_10	0x214
#define HDCP_AES_CIPHER_KEY_9	0x218
#define HDCP_AES_CIPHER_KEY_8	0x21C
#define HDCP_AES_CIPHER_KEY_7	0x220
#define HDCP_AES_CIPHER_KEY_6	0x224
#define HDCP_AES_CIPHER_KEY_5	0x228
#define HDCP_AES_CIPHER_KEY_4	0x22C
#define HDCP_AES_CIPHER_KEY_3	0x230
#define HDCP_AES_CIPHER_KEY_2	0x234
#define HDCP_AES_CIPHER_KEY_1	0x238
#define HDCP_AES_CIPHER_KEY_0	0x23C
#define HDCP22_CTRL		0x240
#define HDCP22_TYPE_AES_0	0x244
#define HDCP22_TYPE_AES_1	0x248
#define DUMMY_1			0x268
#define DUMMY_2			0x26C
#define DUMMY_3			0x270

/**
 * DP_MAC_CTRL
 */

#define DP_MAC_CTRL			0x280
#define DP_RESET_CTRL			0x284
#define DP_DEBUG_CTRL			0x288
#define DPTX_IRQ_CTRL			0x28C
#define PG_FIFO_CTRL			0x290
#define MAX_WL				0x294
#define LFIFO_WL			0x298
#define PG_INTERRUPT_CTRL		0x29C
#define MN_VID_AUTO_EN_1		0x2A0
#define MN_M_VID_H			0x2A4
#define MN_M_VID_M			0x2A8
#define MN_M_VID_L			0x2AC
#define MN_N_VID_H			0x2B0
#define MN_N_VID_M			0x2B4
#define MN_N_VID_L			0x2B8
#define MVID_AUTO_H			0x2BC
#define MVID_AUTO_M			0x2C0
#define MVID_AUTO_L			0x2C4
#define NVID_ASYNC_M			0x2C8
#define NVID_ASYNC_L			0x2CC
#define MSA_CTRL			0x2D0
#define MSA_MISC0			0x2D4
#define MN_STRM_ATTR_MISC1		0x2D8
#define MN_STRM_ATTR_HTT_M		0x2DC
#define MN_STRM_ATTR_HTT_L		0x2E0
#define MN_STRM_ATTR_HST_M		0x2E4
#define MN_STRM_ATTR_HST_L		0x2E8
#define MN_STRM_ATTR_HWD_M		0x2EC
#define MN_STRM_ATTR_HWD_L		0x2F0
#define MN_STRM_ATTR_HSW_M		0x2F4
#define MN_STRM_ATTR_HSW_L		0x2F8
#define MN_STRM_ATTR_VTTE_M		0x2FC
#define MN_STRM_ATTR_VTTE_L		0x300
#define MN_STRM_ATTR_VST_M		0x304
#define MN_STRM_ATTR_VST_L		0x308
#define MN_STRM_ATTR_VHT_M		0x30C
#define MN_STRM_ATTR_VHT_L		0x310
#define MN_STRM_ATTR_VSW_M		0x314
#define MN_STRM_ATTR_VSW_L		0x318
#define VBID				0x31C
#define VBID_FW_CTL			0x320
#define ARBITER_CTRL			0x324
#define V_DATA_PER_LINE0		0x328
#define V_DATA_PER_LINE1		0x32C
#define TU_SIZE				0x330
#define TU_DATA_SIZE0			0x334
#define TU_DATA_SIZE1			0x338
#define HDEALY0				0x33C
#define HDEALY1				0x340
#define AUTO_HDEALY0			0x344
#define AUTO_HDEALY1			0x348
#define LFIFO_WL_SET			0x34C
#define ARBITER_SEC_END_CNT_HB		0x350
#define ARBITER_SEC_END_CNT_LB		0x354
#define ARBITER_DEBUG			0x358
#define DPTX_CTSFIFO_CTRL		0x35C
#define DPTX_CTSFIFO_RSV1		0x360
#define DPTX_TOP_CTL			0x364
#define DPTX_TOP_RSV1			0x368
#define DPTX_TOP_RSV2			0x36C
#define ARBITER_MIN_H_BLANK_WIDTH_HB	0x370
#define ARBITER_MIN_H_BLANK_WIDTH_LB	0x374
#define ARBITER_INTERRUPT_CTRL		0x378
#define VESA_FMT_REGEN			0x37C
#define DPTX_CLK_GEN			0x380
#define PG_MBIST_CTRL			0x384
#define PG_DRF_MBIST_CTRL		0x388
#define ARBITER_SEC_IDLE_END_CNT	0x3C0
#define DPTX_TOP_RSV3			0x3E0
#define DPTX_TOP_RSV4			0x3E4
#define DPTX_TOP_RSV5			0x3E8
#define DPTX_TOP_RSV6			0x3EC
#define DPTX_TOP_RSV7			0x3F0
#define DPTX_TOP_RSV8			0x3F4
#define DPTX_TOP_RSV9			0x3F8
#define DPTX_TOP_RSV10			0x3FC

/* DP_IP_MN_STRM_ATTR_HTT_M */
#define DP_IP_MN_STRM_ATTR_HTT_M_htotal_15_8_shift		(0)
#define DP_IP_MN_STRM_ATTR_HTT_M_htotal_15_8_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_HTT_M_htotal_15_8(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_HTT_L */
#define DP_IP_MN_STRM_ATTR_HTT_L_htotal_7_0_shift		(0)
#define DP_IP_MN_STRM_ATTR_HTT_L_htotal_7_0_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_HTT_L_htotal_7_0(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_HST_M */
#define DP_IP_MN_STRM_ATTR_HST_M_hstart_15_8_shift		(0)
#define DP_IP_MN_STRM_ATTR_HST_M_hstart_15_8_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_HST_M_hstart_15_8(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_HST_L */
#define DP_IP_MN_STRM_ATTR_HST_L_hstart_7_0_shift		(0)
#define DP_IP_MN_STRM_ATTR_HST_L_hstart_7_0_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_HST_L_hstart_7_0(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_HWD_M */
#define DP_IP_MN_STRM_ATTR_HWD_M_hwidth_15_8_shift		(0)
#define DP_IP_MN_STRM_ATTR_HWD_M_hwidth_15_8_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_HWD_M_hwidth_15_8(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_HWD_L */
#define DP_IP_MN_STRM_ATTR_HWD_L_hwidth_7_0_shift		(0)
#define DP_IP_MN_STRM_ATTR_HWD_L_hwidth_7_0_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_HWD_L_hwidth_7_0(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_HSW_M */
#define DP_IP_MN_STRM_ATTR_HSW_M_hsp_shift				(7)
#define DP_IP_MN_STRM_ATTR_HSW_M_hsp_mask				(0x80)
#define DP_IP_MN_STRM_ATTR_HSW_M_hsp(data)				(0x80&((data)<<7))
#define DP_IP_MN_STRM_ATTR_HSW_M_hsw_14_8_shift			(0)
#define DP_IP_MN_STRM_ATTR_HSW_M_hsw_14_8_mask			(0x7f)
#define DP_IP_MN_STRM_ATTR_HSW_M_hsw_14_8(data)			(0x7f&((data)<<0))
/* DP_IP_MN_STRM_ATTR_HSW_L */
#define DP_IP_MN_STRM_ATTR_HSW_L_hsw_7_0_shift			(0)
#define DP_IP_MN_STRM_ATTR_HSW_L_hsw_7_0_mask			(0xff)
#define DP_IP_MN_STRM_ATTR_HSW_L_hsw_7_0(data)			(0xff&((data)<<0))
/* MN_STRM_ATTR_VTTE_M */
#define DP_IP_MN_STRM_ATTR_VTTE_M_vtotal_15_8_shift		(0)
#define DP_IP_MN_STRM_ATTR_VTTE_M_vtotal_15_8_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_VTTE_M_vtotal_15_8(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_VTTE_L */
#define DP_IP_MN_STRM_ATTR_VTTE_L_vtotal_7_0_shift		(0)
#define DP_IP_MN_STRM_ATTR_VTTE_L_vtotal_7_0_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_VTTE_L_vtotal_7_0(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_VST_M */
#define DP_IP_MN_STRM_ATTR_VST_M_vstart_15_8_shift		(0)
#define DP_IP_MN_STRM_ATTR_VST_M_vstart_15_8_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_VST_M_vstart_15_8(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_VST_L */
#define DP_IP_MN_STRM_ATTR_VST_L_vstart_7_0_shift		(0)
#define DP_IP_MN_STRM_ATTR_VST_L_vstart_7_0_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_VST_L_vstart_7_0(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_VHT_M */
#define DP_IP_MN_STRM_ATTR_VHT_M_vheight_15_8_shift		(0)
#define DP_IP_MN_STRM_ATTR_VHT_M_vheight_15_8_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_VHT_M_vheight_15_8(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_VHT_L */
#define DP_IP_MN_STRM_ATTR_VHT_L_vheight_7_0_shift		(0)
#define DP_IP_MN_STRM_ATTR_VHT_L_vheight_7_0_mask		(0xff)
#define DP_IP_MN_STRM_ATTR_VHT_L_vheight_7_0(data)		(0xff&((data)<<0))
/* DP_IP_MN_STRM_ATTR_VSW_M */
#define DP_IP_MN_STRM_ATTR_VSW_M_vsp_shift				(7)
#define DP_IP_MN_STRM_ATTR_VSW_M_vsp_mask				(0x80)
#define DP_IP_MN_STRM_ATTR_VSW_M_vsp(data)				(0x80&((data)<<7))
#define DP_IP_MN_STRM_ATTR_VSW_M_vsw_14_8_shift			(0)
#define DP_IP_MN_STRM_ATTR_VSW_M_vsw_14_8_mask			(0x7f)
#define DP_IP_MN_STRM_ATTR_VSW_M_vsw_14_8(data)			(0x7f&((data)<<0))
/* DP_IP_MN_STRM_ATTR_VSW_L */
#define DP_IP_MN_STRM_ATTR_VSW_L_vsw_7_0_shift			(0)
#define DP_IP_MN_STRM_ATTR_VSW_L_vsw_7_0_mask			(0xff)
#define DP_IP_MN_STRM_ATTR_VSW_L_vsw_7_0(data)			(0xff&((data)<<0))
/* DP_IP_MN_M_VID_H */
#define DP_IP_MN_M_VID_H_mvid_23_16_shift				(0)
#define DP_IP_MN_M_VID_H_mvid_23_16_mask				(0xff)
#define DP_IP_MN_M_VID_H_mvid_23_16(data)				(0xff&((data)<<0))
/* DP_IP_MN_M_VID_M */
#define DP_IP_MN_M_VID_M_mvid_15_8_shift				(0)
#define DP_IP_MN_M_VID_M_mvid_15_8_mask					(0xff)
#define DP_IP_MN_M_VID_M_mvid_15_8(data)				(0xff&((data)<<0))
/* DP_IP_MN_M_VID_L */
#define DP_IP_MN_M_VID_L_mvid_7_0_shift					(0)
#define DP_IP_MN_M_VID_L_mvid_7_0_mask					(0xff)
#define DP_IP_MN_M_VID_L_mvid_7_0(data)					(0xff&((data)<<0))
/* DP_IP_MN_N_VID_H */
#define DP_IP_MN_N_VID_H_nvid_23_16_shift				(0)
#define DP_IP_MN_N_VID_H_nvid_23_16_mask				(0xff)
#define DP_IP_MN_N_VID_H_nvid_23_16(data)				(0xff&((data)<<0))
/* DP_IP_MN_N_VID_M */
#define DP_IP_MN_N_VID_M_nvid_15_8_shift				(0)
#define DP_IP_MN_N_VID_M_nvid_15_8_mask					(0xff)
#define DP_IP_MN_N_VID_M_nvid_15_8(data)				(0xff&((data)<<0))
/* DP_IP_MN_N_VID_L */
#define DP_IP_MN_N_VID_L_nvid_7_0_shift					(0)
#define DP_IP_MN_N_VID_L_nvid_7_0_mask					(0xff)
#define DP_IP_MN_N_VID_L_nvid_7_0(data)					(0xff&((data)<<0))
/* DP_IP_MN_VID_AUTO_EN_1  */
#define DP_IP_MN_VID_AUTO_EN_1_mn_vid_auto_en_shift		(7)
#define DP_IP_MN_VID_AUTO_EN_1_mn_vid_auto_en_mask		(0x80)
#define DP_IP_MN_VID_AUTO_EN_1_mn_vid_auto_en(data)		(0x80&((data)<<7))
#define DP_IP_MN_VID_AUTO_EN_1_mn_vid_db_shift			(6)
#define DP_IP_MN_VID_AUTO_EN_1_mn_vid_db_mask			(0x40)
#define DP_IP_MN_VID_AUTO_EN_1_mn_vid_db(data)			(0x40&((data)<<6))
/* DP_IP_MSA_MISC0 */
#define DP_IP_MSA_MISC0_colorbit_shift					(5)
#define DP_IP_MSA_MISC0_colorbit_mask					(0xe0)
#define DP_IP_MSA_MISC0_colorbit(data)					(0xe0&((data)<<5))
#define DP_IP_MSA_MISC0_ycc_col_shift					(4)
#define DP_IP_MSA_MISC0_ycc_col_mask					(0x10)
#define DP_IP_MSA_MISC0_ycc_col(data)					(0x10&((data)<<4))
#define DP_IP_MSA_MISC0_dyn_range_shift					(3)
#define DP_IP_MSA_MISC0_dyn_range_mask					(0x8)
#define DP_IP_MSA_MISC0_dyn_range(data)					(0x8&((data)<<3))
#define DP_IP_MSA_MISC0_component_format_shift			(1)
#define DP_IP_MSA_MISC0_component_format_mask			(0x6)
#define DP_IP_MSA_MISC0_component_format(data)			(0x6&((data)<<1))
#define DP_IP_MSA_MISC0_sync_clk_en_shift				(0)
#define DP_IP_MSA_MISC0_sync_clk_en_mask				(0x1)
#define DP_IP_MSA_MISC0_sync_clk_en(data)				(0x1&((data)<<0))
/* DP_IP_MSA_CTRL */
#define DP_IP_MSA_CTRL_msa_db_shift						(7)
#define DP_IP_MSA_CTRL_msa_db_mask						(0x80)
#define DP_IP_MSA_CTRL_msa_db(data)						(0x80&((data)<<7))
#define DP_IP_MSA_CTRL_msa_db_vblank_shift				(6)
#define DP_IP_MSA_CTRL_msa_db_vblank_mask				(0x40)
#define DP_IP_MSA_CTRL_msa_db_vblank(data)				(0x40&((data)<<6))
/* DP_IP_V_DATA_PER_LINE0 */
#define DP_IP_V_DATA_PER_LINE0_v_data_per_line_14_8_shift	(0)
#define DP_IP_V_DATA_PER_LINE0_v_data_per_line_14_8_mask	(0x7f)
#define DP_IP_V_DATA_PER_LINE0_v_data_per_line_14_8(data)	(0x7f&((data)<<0))
/* DP_IP_V_DATA_PER_LINE1 */
#define DP_IP_V_DATA_PER_LINE1_v_data_per_line_7_0_shift	(0)
#define DP_IP_V_DATA_PER_LINE1_v_data_per_line_7_0_mask		(0xff)
#define DP_IP_V_DATA_PER_LINE1_v_data_per_line_7_0(data)	(0xff&((data)<<0))
/* DP_IP_TU_DATA_SIZE0 */
#define DP_IP_TU_DATA_SIZE0_tu_data_size_9_3_shift			(0)
#define DP_IP_TU_DATA_SIZE0_tu_data_size_9_3_mask			(0x7f)
#define DP_IP_TU_DATA_SIZE0_tu_data_size_9_3(data)			(0x7f&((data)<<0))
/* DP_IP_TU_DATA_SIZE1 */
#define DP_IP_TU_DATA_SIZE1_tu_data_size_2_0_shift			(0)
#define DP_IP_TU_DATA_SIZE1_tu_data_size_2_0_mask			(0x7)
#define DP_IP_TU_DATA_SIZE1_tu_data_size_2_0(data)			(0x7&((data)<<0))
/* DP_IP_HDEALY0 */
#define DP_IP_HDEALY0_hdelay_14_8_shift						(0)
#define DP_IP_HDEALY0_hdelay_14_8_mask						(0x7f)
#define DP_IP_HDEALY0_hdelay_14_8(data)						(0x7f&((data)<<0))
/* DP_IP_HDEALY1 */
#define DP_IP_HDEALY1_hdelay_7_0_shift						(0)
#define DP_IP_HDEALY1_hdelay_7_0_mask						(0xff)
#define DP_IP_HDEALY1_hdelay_7_0(data)						(0xff&((data)<<0))
/* DP_IP_LFIFO_WL_SET */
#define DP_IP_LFIFO_WL_SET_wl_mid_regen_shift				(7)
#define DP_IP_LFIFO_WL_SET_wl_mid_regen_mask				(0x80)
#define DP_IP_LFIFO_WL_SET_wl_mid_regen(data)				(0x80&((data)<<7))
#define DP_IP_LFIFO_WL_SET_wl_mid_set_shift					(0)
#define DP_IP_LFIFO_WL_SET_wl_mid_set_mask					(0x7f)
#define DP_IP_LFIFO_WL_SET_wl_mid_set(data)					(0x7f&((data)<<0))
/* DP_IP_DP_MAC_CTRL */
#define DP_IP_DP_MAC_CTRL_enhance_md_shift					(2)
#define DP_IP_DP_MAC_CTRL_enhance_md_mask					(0x4)
#define DP_IP_DP_MAC_CTRL_enhance_md(data)					(0x4&((data)<<2))
#define DP_IP_DP_MAC_CTRL_lane_num_shift					(0)
#define DP_IP_DP_MAC_CTRL_lane_num_mask						(0x3)
#define DP_IP_DP_MAC_CTRL_lane_num(data)					(0x3&((data)<<0))
/* DP_IP_ARBITER_SEC_END_CNT_HB */
#define DP_IP_ARBITER_SEC_END_CNT_HB_sec_end_cnt_14_8_shift	(0)
#define DP_IP_ARBITER_SEC_END_CNT_HB_sec_end_cnt_14_8_mask	(0x7f)
#define DP_IP_ARBITER_SEC_END_CNT_HB_sec_end_cnt_14_8(data)	(0x7f&((data)<<0))
/* DP_IP_ARBITER_SEC_END_CNT_LB */
#define DP_IP_ARBITER_SEC_END_CNT_LB_sec_end_cnt_7_0_shift	(0)
#define DP_IP_ARBITER_SEC_END_CNT_LB_sec_end_cnt_7_0_mask	(0xff)
#define DP_IP_ARBITER_SEC_END_CNT_LB_sec_end_cnt_7_0(data)	(0xff&((data)<<0))
/* DP_IP_ARBITER_CTRL */
#define DP_IP_ARBITER_CTRL_vactive_md_shift					(1)
#define DP_IP_ARBITER_CTRL_vactive_md_mask					(0x2)
#define DP_IP_ARBITER_CTRL_vactive_md(data)					(0x2&((data)<<1))
#define DP_IP_ARBITER_CTRL_arbiter_en_shift					(0)
#define DP_IP_ARBITER_CTRL_arbiter_en_mask					(0x1)
#define DP_IP_ARBITER_CTRL_arbiter_en(data)					(0x1&((data)<<0))

/**
 * SEC_FUNCTION_CTRL
 */

#define SEC_FUNCTION_CTRL		0x400
#define SEC_RESERVED_0			0x404
#define SEC_DBUF_CTRL			0x408
#define SEC_DEBUG			0x40C
#define SEC_PSR_DB0			0x410
#define SEC_PSR_DB1			0x414
#define SEC_PSR_DB2			0x418
#define SEC_PSR_DB3			0x41C
#define SEC_PSR_DB4			0x420
#define SEC_PSR_DB5			0x424
#define SEC_PSR_DB6			0x428
#define SEC_PSR_DB7			0x42C
#define SEC_PSR_DB8			0x430
#define SEC_PSR_DB9			0x434
#define SEC_PSR_DB10			0x438
#define SEC_PSR_DB11			0x43C
#define SEC_PSR_DB12			0x440
#define SEC_PSR_DB13			0x444
#define SEC_PSR_DB14			0x448
#define SEC_PSR_DB15			0x44C
#define SEC_RESERVED_1			0x450
#define SEC_RESERVED_2			0x454
#define SEC_RESERVED_3			0x458
#define SEC_RESERVED_4			0x45C
#define AUD_FUNCTION_CTRL1		0x460
#define AUD_PAYLOAD_B3			0x464
#define DP_AUD_ID			0x468
#define SEC_RESERVED_6			0x46C
#define AUD_FIFO_CTRL			0x470
#define AUD_LFIFO_MAX_WL		0x474
#define AUD_LFIFO_WL			0x478
#define AUD_INTERRUPT_CTRL		0x47C
#define AUD_TS_MAUD_H			0x480
#define AUD_TS_MAUD_M			0x484
#define AUD_TS_MAUD_L			0x488
#define AUD_TS_NAUD_H			0x48C
#define AUD_TS_NAUD_M			0x490
#define AUD_TS_NAUD_L			0x494
#define SEC_INFO_AUD_DB0		0x498
#define SEC_INFO_AUD_DB1		0x49C
#define SEC_INFO_AUD_DB2		0x4A0
#define SEC_INFO_AUD_DB3		0x4A4
#define SEC_INFO_AUD_DB4		0x4A8
#define SEC_INFO_AUD_DB5		0x4AC
#define SEC_INFO_AUD_DB6		0x4B0
#define SEC_INFO_AUD_DB7		0x4B4
#define SEC_INFO_AUD_DB8		0x4B8
#define SEC_INFO_AUD_DB9		0x4BC
#define SEC_INFO_AVI_DB0		0x4C0
#define SEC_INFO_AVI_DB1		0x4C4
#define SEC_INFO_AVI_DB2		0x4C8
#define SEC_INFO_AVI_DB3		0x4CC
#define SEC_INFO_AVI_DB4		0x4D0
#define SEC_INFO_AVI_DB5		0x4D4
#define SEC_INFO_AVI_DB6		0x4D8
#define SEC_INFO_AVI_DB7		0x4DC
#define SEC_INFO_AVI_DB8		0x4E0
#define SEC_INFO_AVI_DB9		0x4E4
#define SEC_INFO_AVI_DB10		0x4E8
#define SEC_INFO_AVI_DB11		0x4EC
#define SEC_INFO_AVI_DB12		0x4F0
#define SEC_INFO_MPEG_DB0		0x4F4
#define SEC_INFO_MPEG_DB1		0x4F8
#define SEC_INFO_MPEG_DB2		0x4FC
#define SEC_INFO_MPEG_DB3		0x500
#define SEC_INFO_MPEG_DB4		0x504
#define SEC_INFO_MPEG_DB5		0x508
#define SEC_INFO_MPEG_DB6		0x50C
#define SEC_INFO_MPEG_DB7		0x510
#define SEC_INFO_MPEG_DB8		0x514
#define SEC_INFO_MPEG_DB9		0x518
#define AUD_FUNCTION_CTRL2		0x51C
#define AUD_FUNCTION_CTRL3		0x520
#define MST_SEC_PKT_ID			0x524
#define MST_SEC_PKT_HB3			0x528
#define SEC_RS_DECODE_CTRL		0x52C
#define SEC_AUD_FREQDET_CTRL		0x530
#define SEC_AUD_XCLK_DIV		0x534
#define SEC_AUD_FREQ_TIME		0x538
#define SEC_AUD_SAMPLE_CNT_HB		0x53C
#define SEC_AUD_SAMPLE_CNT_LB		0x540
#define AUD_MBIST_CTRL			0x544
#define AUD_DRF_MBIST_CTRL		0x548
#define DP_INFO_FM_RSV0			0x54C
#define DP_INFO_FM_RSV1			0x550
#define DP_INFO_FM_ADR			0x554
#define DP_INFO_FM_DAT			0x558
#define RESERVED_57			0x55C
#define VSC_RX_DB0			0x560
#define VSC_RX_DB1			0x564
#define VSC_RX_DB2			0x568
#define VSC_RX_DB3			0x56C
#define VSC_RX_DB4			0x570
#define VSC_RX_DB5			0x574
#define VSC_RX_DB6			0x578
#define VSC_RX_DB7			0x57C
#define AUD_FREQ_TH_0			0x580
#define AUD_FREQ_TH_1			0x584
#define AUD_FREQ_TH_2			0x588
#define AUD_FREQ_TH_3			0x58C
#define AUD_FREQ_TH_4			0x590
#define AUD_FREQ_TH_5			0x594
#define AUD_FREQ_TH_6			0x598
#define RESERVED_67			0x59C
#define RESERVED_68			0x5A0
#define RESERVED_69			0x5A4
#define VSC_CTRL_0			0x5A8
#define VSC_RX_HB0			0x5AC
#define VSC_RX_HB1			0x5B0
#define VSC_RX_HB2			0x5B4
#define VSC_RX_HB3			0x5B8
#define SEC_AWD_CTRL			0x5C0
#define SEC_AWD_STATUS_0		0x5C4
#define SEC_IRQ_CTRL0			0x5C8
#define SEC_PH_HB0			0x5CC
#define SEC_PH_HB1			0x5D0
#define SEC_PH_HB2			0x5D4
#define SEC_PH_HB3			0x5D8
#define SEC_PH_PB0			0x5DC
#define SEC_PH_PB1			0x5E0
#define SEC_PH_PB2			0x5E4
#define SEC_PH_PB3			0x5E8
#define SEC_PH_PACKET_TYPE		0x5EC
#define SEC_AWD_STATUS_1		0x600
#define DP_INFO_VAR_EN_M		0x604
#define DP_INFO_VAR_EN_L		0x608
#define DP_INFO_VAR_ST_M		0x60C
#define DP_INFO_VAR_ST_L		0x610
#define CH_STATUS_0			0x614
#define CH_STATUS_1			0x618
#define CH_STATUS_2			0x61C
#define CH_STATUS_3			0x620
#define CH_STATUS_4			0x624
#define DP_AVWD_CTRL0			0x628
#define RESERVED_8B			0x62C
#define RESERVED_8C			0x630
#define RESERVED_8D			0x634
#define RESERVED_8E			0x638
#define DPTX_I2S_CTRL			0x63C
#define SEC_IRQ_CTRL1			0x640
#define DUMMY_95			0x654
#define DUMMY_96			0x658
#define DUMMY_97			0x65C
#define DUMMY_98			0x660
#define DUMMY_99			0x664
#define DUMMY_9A			0x668
#define DUMMY_9B			0x66C
#define DUMMY_9C			0x670

/**
 * DPTX_PHY_CTRL0
 */

#define DPTX_PHY_CTRL0			0x680
#define DPTX_PHY_CTRL1			0x684
#define DPTX_RCV_DET0			0x688
#define DPTX_RCV_DET1			0x68C
#define DPTX_PN_SWAP			0x690
#define DPTX_SFIFO_CTRL0		0x69C
#define DPTX_SFIFO_CTRL1		0x6A0
#define DPTX_SFIFO_LANE_SWAP0		0x6A4
#define DPTX_SFIFO_LANE_SWAP1		0x6A8
#define DPTX_SFIFO_INT_EN		0x6AC

/* DP_IP_DPTX_SFIFO_CTRL0 */
#define DP_IP_DPTX_SFIFO_CTRL0_tx_en_shift			(7)
#define DP_IP_DPTX_SFIFO_CTRL0_tx_en_mask			(0x80)
#define DP_IP_DPTX_SFIFO_CTRL0_tx_en(data)			(0x80&((data)<<7))
#define DP_IP_DPTX_SFIFO_CTRL0_rate_mode_shift		(5)
#define DP_IP_DPTX_SFIFO_CTRL0_rate_mode_mask		(0x60)
#define DP_IP_DPTX_SFIFO_CTRL0_rate_mode(data)		(0x60&((data)<<5))
#define DP_IP_DPTX_SFIFO_CTRL0_fifo_in_flip_shift	(4)
#define DP_IP_DPTX_SFIFO_CTRL0_fifo_in_flip_mask	(0x10)
#define DP_IP_DPTX_SFIFO_CTRL0_fifo_in_flip(data)	(0x10&((data)<<4))
#define DP_IP_DPTX_SFIFO_CTRL0_wovflow_shift		(1)
#define DP_IP_DPTX_SFIFO_CTRL0_wovflow_mask			(0x2)
#define DP_IP_DPTX_SFIFO_CTRL0_wovflow(data)		(0x2&((data)<<1))
#define DP_IP_DPTX_SFIFO_CTRL0_rudflow_shift		(0)
#define DP_IP_DPTX_SFIFO_CTRL0_rudflow_mask			(0x1)
#define DP_IP_DPTX_SFIFO_CTRL0_rudflow(data)		(0x1&((data)<<0))

/**
 * AUX_PHY_0 : 0x98009D80
 */

#define AUX_PHY_0	0x980
#define AUX_PHY_1	0x984
#define AUX_PHY_2	0x988
#define AUX_PHY_3	0x98C
#define AUX_PHY_4	0x990
#define AUX_PHY_5	0x994
#define AUX_PHY_6	0x998
#define AUX_PHY_7	0x99C

/**
 * AUX_TX_CTRL : 0x98009E80
 */

#define AUX_TX_CTRL		0xA80
#define AUX_TIMEOUT		0xA84
#define AUX_FSM_STATUS		0xA88
#define AUXTX_TRAN_CTRL		0xA8C
#define AUXTX_REQ_CMD		0xA90
#define AUXTX_REQ_ADDR_M	0xA94
#define AUXTX_REQ_ADDR_L	0xA98
#define AUXTX_REQ_LEN		0xA9C
#define AUXTX_REQ_DATA		0xAA0
#define AUX_REPLY_CMD		0xAA4
#define AUX_REPLY_DATA		0xAA8
#define AUX_FIFO_CTRL		0xAAC
#define AUX_TX_FIFO_STATUS	0xAB0
#define AUX_FIFO_RD_PTR		0xAB4
#define AUX_FIFO_WR_PTR		0xAB8
#define AUX_RETRY_1		0xABC
#define AUX_RETRY_2		0xAC0
#define AUX_IRQ_EVENT		0xAC4
#define AUX_IRQ_EN		0xAC8
#define AUX_DIG_PHY2		0xBC0
#define AUX_DIG_PHY3		0xBC4
#define AUX_DIG_PHY4		0xBC8
#define AUX_DIG_PHY5		0xBCC
#define AUX_DIG_PHY6		0xBD0
#define AUX_DIG_PHY7		0xBD4
#define AUX_DIG_PHY8		0xBD8
#define AUX_DIG_PHY9		0xBDC
#define AUX_DEBUG		0xBE0

/* edp wrapper */
/**
 * EDPTX_MAIN : 0x98009000
 */
#define EDPTX_MAIN						0x000
#define EDPTX_INTE						0x008
#define EDPTX_CD						0x00c
#define EDPTX_TIMEGEN_CTRL				0x010
#define EDPTX_DH_WIDTH					0x014
#define EDPTX_DH_TOTAL					0x018
#define EDPTX_DH_DEN_START_END			0x01c
#define EDPTX_DV_DEN_START_END_FIELD1	0x020
#define EDPTX_DV_TOTAL					0x028
#define EDPTX_DV_VS_START_END_FIELD1	0x02c
#define EDPTX_DH_VS_ADJ_FIELD1			0x030
#define EDPTX_DV_SYNC_INTE				0x038
#define EDPTX_INTERRUPT_STATUS			0x03c
#define EDPTX_GAMMA_PORT				0x060
#define EDPTX_DSTAT_CTRL_R				0x07c
#define EDPTX_CSC1						0x100
#define EDPTX_CSC2						0x104
#define EDPTX_CSC3						0x108
#define EDPTX_CSC4						0x10c
#define EDPTX_CSC5						0x110
#define EDPTX_CSC6						0x114
#define EDPTX_CSC7						0x118
#define EDPTX_LINK_FREQDET_CTRL			0x200
#define EDPTX_LINK_FREQDET_STATUS		0x204
#define EDPTX_PIXEL_FREQDET_CTRL		0x208
#define EDPTX_PIXEL_FREQDET_STATUS		0x20c
#define EDPTX_DBG_CTRL					0x210

/* EDPTX_DH_WIDTH */
#define EDPTX_DH_WIDTH_dh_width_shift			(0)
#define EDPTX_DH_WIDTH_dh_width_mask			(0x1fff)
#define EDPTX_DH_WIDTH_dh_width(data)			(0x1fff&((data)<<0))
/* EDPTX_DH_TOTAL */
#define EDPTX_DH_TOTAL_dh_total_shift			(16)
#define EDPTX_DH_TOTAL_dh_total_mask			(0x1fff0000)
#define EDPTX_DH_TOTAL_dh_total(data)			(0x1fff0000&((data)<<16))
#define EDPTX_DH_TOTAL_dh_total_last_line_shift	(0)
#define EDPTX_DH_TOTAL_dh_total_last_line_mask	(0x1fff)
#define EDPTX_DH_TOTAL_dh_total_last_line(data)	(0x1fff&((data)<<0))
/* EDPTX_DH_DEN_START_END */
#define EDPTX_DH_DEN_START_END_dh_den_sta_shift	(16)
#define EDPTX_DH_DEN_START_END_dh_den_sta_mask	(0x1fff0000)
#define EDPTX_DH_DEN_START_END_dh_den_sta(data)	(0x1fff0000&((data)<<16))
#define EDPTX_DH_DEN_START_END_dh_den_end_shift	(0)
#define EDPTX_DH_DEN_START_END_dh_den_end_mask	(0x1fff)
#define EDPTX_DH_DEN_START_END_dh_den_end(data)	(0x1fff&((data)<<0))
/* EDPTX_DV_DEN_START_END_FIELD1 */
#define EDPTX_DV_DEN_START_END_FIELD1_dv_den_sta_field1_shift	(16)
#define EDPTX_DV_DEN_START_END_FIELD1_dv_den_sta_field1_mask	(0x1fff0000)
#define EDPTX_DV_DEN_START_END_FIELD1_dv_den_sta_field1(data)	(0x1fff0000&((data)<<16))
#define EDPTX_DV_DEN_START_END_FIELD1_dv_den_end_field1_shift	(0)
#define EDPTX_DV_DEN_START_END_FIELD1_dv_den_end_field1_mask	(0x1fff)
#define EDPTX_DV_DEN_START_END_FIELD1_dv_den_end_field1(data)	(0x1fff&((data)<<0))
/* EDPTX_DV_TOTAL */
#define EDPTX_DV_TOTAL_dv_total_shift			(0)
#define EDPTX_DV_TOTAL_dv_total_mask			(0x1fff)
#define EDPTX_DV_TOTAL_dv_total(data)			(0x1fff&((data)<<0))
/* EDPTX_DV_VS_START_END_FIELD1 */
#define EDPTX_DV_VS_START_END_FIELD1_dv_vs_sta_field1_shift		(16)
#define EDPTX_DV_VS_START_END_FIELD1_dv_vs_sta_field1_mask		(0x1fff0000)
#define EDPTX_DV_VS_START_END_FIELD1_dv_vs_sta_field1(data)		(0x1fff0000&((data)<<16))
#define EDPTX_DV_VS_START_END_FIELD1_dv_vs_end_field1_shift		(0)
#define EDPTX_DV_VS_START_END_FIELD1_dv_vs_end_field1_mask		(0x1fff)
#define EDPTX_DV_VS_START_END_FIELD1_dv_vs_end_field1(data)		(0x1fff&((data)<<0))
/* EDPTX_DH_VS_ADJ_FIELD1 */
#define EDPTX_DH_VS_ADJ_FIELD1_dh_vs_adj_field1_shift			(0)
#define EDPTX_DH_VS_ADJ_FIELD1_dh_vs_adj_field1_mask			(0x1fff)
#define EDPTX_DH_VS_ADJ_FIELD1_dh_vs_adj_field1(data)			(0x1fff&((data)<<0))
/* EDPTX_MAIN */
#define EDPTX_MAIN_frame_sync_mode_shift		(8)
#define EDPTX_MAIN_frame_sync_mode_mask			(0x100)
#define EDPTX_MAIN_frame_sync_mode(data)		(0x100&((data)<<8))
#define EDPTX_MAIN_avg_mode_shift				(7)
#define EDPTX_MAIN_avg_mode_mask				(0x80)
#define EDPTX_MAIN_avg_mode(data)				(0x80&((data)<<7))
#define EDPTX_MAIN_pixel_8bit_shift				(6)
#define EDPTX_MAIN_pixel_8bit_mask				(0x40)
#define EDPTX_MAIN_pixel_8bit(data)				(0x40&((data)<<6))
#define EDPTX_MAIN_color_mode_shift				(4)
#define EDPTX_MAIN_color_mode_mask				(0x30)
#define EDPTX_MAIN_color_mode(data)				(0x30&((data)<<4))
#define EDPTX_MAIN_csc_enable_shift				(0)
#define EDPTX_MAIN_csc_enable_mask				(0x1)
#define EDPTX_MAIN_csc_enable(data)				(0x1&((data)<<0))
/* EDPTX_CSC1 */
#define EDPTX_CSC1_m01_shift			(16)
#define EDPTX_CSC1_m01_mask				(0x3fff0000)
#define EDPTX_CSC1_m01(data)			(0x3fff0000&((data)<<16))
#define EDPTX_CSC1_m00_shift			(0)
#define EDPTX_CSC1_m00_mask				(0x3fff)
#define EDPTX_CSC1_m00(data)			(0x3fff&((data)<<0))
/* EDPTX_CSC2 */
#define EDPTX_CSC2_m10_shift			(16)
#define EDPTX_CSC2_m10_mask				(0x3fff0000)
#define EDPTX_CSC2_m10(data)			(0x3fff0000&((data)<<16))
#define EDPTX_CSC2_m02_shift			(0)
#define EDPTX_CSC2_m02_mask				(0x3fff)
#define EDPTX_CSC2_m02(data)			(0x3fff&((data)<<0))
/* EDPTX_CSC3 */
#define EDPTX_CSC3_m12_shift			(16)
#define EDPTX_CSC3_m12_mask				(0x3fff0000)
#define EDPTX_CSC3_m12(data)			(0x3fff0000&((data)<<16))
#define EDPTX_CSC3_m11_shift			(0)
#define EDPTX_CSC3_m11_mask				(0x3fff)
#define EDPTX_CSC3_m11(data)			(0x3fff&((data)<<0))
/* EDPTX_CSC4 */
#define EDPTX_CSC4_m21_shift			(16)
#define EDPTX_CSC4_m21_mask				(0x3fff0000)
#define EDPTX_CSC4_m21(data)			(0x3fff0000&((data)<<16))
#define EDPTX_CSC4_m20_shift			(0)
#define EDPTX_CSC4_m20_mask				(0x3fff)
#define EDPTX_CSC4_m20(data)			(0x3fff&((data)<<0))
/* EDPTX_CSC5 */
#define EDPTX_CSC5_m22_shift			(0)
#define EDPTX_CSC5_m22_mask				(0x3fff)
#define EDPTX_CSC5_m22(data)			(0x3fff&((data)<<0))
/* EDPTX_CSC6 */
#define EDPTX_CSC6_a1_shift				(16)
#define EDPTX_CSC6_a1_mask				(0x7ff0000)
#define EDPTX_CSC6_a1(data)				(0x7ff0000&((data)<<16))
#define EDPTX_CSC6_a0_shift				(0)
#define EDPTX_CSC6_a0_mask				(0x7ff)
#define EDPTX_CSC6_a0(data)				(0x7ff&((data)<<0))
/* EDPTX_CSC7 */
#define EDPTX_CSC7_a2_shift				(0)
#define EDPTX_CSC7_a2_mask				(0x7ff)
#define EDPTX_CSC7_a2(data)				(0x7ff&((data)<<0))
/* EDPTX_DV_SYNC_INTE */
#define EDPTX_DV_SYNC_INTE_dv_sync_int_shift	(0)
#define EDPTX_DV_SYNC_INTE_dv_sync_int_mask		(0x1fff)
#define EDPTX_DV_SYNC_INTE_dv_sync_int(data)	(0x1fff&((data)<<0))


#endif // _RTK_EDP_REG_H
