/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef _DPRX14_PLL_REG_H_INCLUDED_
#define _DPRX14_PLL_REG_H_INCLUDED_

#define DPRX14_PLL_WDOUT                        0x400
#define DPRX14_PLL_WDOUT_reg_addr               "0x98165400"
#define DPRX14_PLL_WDOUT_REG_PLLDPRX_AID_WDOUT_shift              (1)
#define DPRX14_PLL_WDOUT_REG_PLLDPRX_AID_WDOUT_mask               (0x2)
#define DPRX14_PLL_WDOUT_REG_PLLDPRX_AID_WDOUT(data)              (0x2&((data)<<1))
#define DPRX14_PLL_WDOUT_REG_PLLDPRX_AID_WDOUT_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_WDOUT_get_REG_PLLDPRX_AID_WDOUT(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_WDOUT_REG_PLLDPRX_AID_WDOUT           0x0
#define DPRX14_PLL_WDOUT_REG_PLLDPRX_AUD_WDO_shift              (0)
#define DPRX14_PLL_WDOUT_REG_PLLDPRX_AUD_WDO_mask               (0x1)
#define DPRX14_PLL_WDOUT_REG_PLLDPRX_AUD_WDO(data)              (0x1&((data)<<0))
#define DPRX14_PLL_WDOUT_REG_PLLDPRX_AUD_WDO_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_WDOUT_get_REG_PLLDPRX_AUD_WDO(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_WDOUT_REG_PLLDPRX_AUD_WDO           0x0

#define DPRX14_PLL_AUD_1                        0x404
#define DPRX14_PLL_AUD_1_reg_addr               "0x98165404"
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDOPOW_shift              (31)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDOPOW_mask               (0x80000000)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDOPOW(data)              (0x80000000&((data)<<31))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDOPOW_src(data)          ((0x80000000&(data))>>31)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_LDOPOW(data)          ((0x80000000&(data))>>31)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_LDOPOW           0x0
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_REF2CORE_shift              (30)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_REF2CORE_mask               (0x40000000)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_REF2CORE(data)              (0x40000000&((data)<<30))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_REF2CORE_src(data)          ((0x40000000&(data))>>30)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_LDO_REF2CORE(data)          ((0x40000000&(data))>>30)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_REF2CORE           0x0
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_SEL_shift              (28)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_SEL_mask               (0x30000000)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_SEL(data)              (0x30000000&((data)<<28))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_SEL_src(data)          ((0x30000000&(data))>>28)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_LDO_SEL(data)          ((0x30000000&(data))>>28)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_LDO_SEL           0x1
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_O_shift              (25)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_O_mask               (0xe000000)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_O(data)              (0xe000000&((data)<<25))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_O_src(data)          ((0xe000000&(data))>>25)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_O(data)          ((0xe000000&(data))>>25)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_O           0x0
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_OEB_shift              (24)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_OEB_mask               (0x1000000)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_OEB(data)              (0x1000000&((data)<<24))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_OEB_src(data)          ((0x1000000&(data))>>24)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_OEB(data)          ((0x1000000&(data))>>24)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_OEB           0x1
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RESER_shift              (20)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RESER_mask               (0xf00000)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RESER(data)              (0xf00000&((data)<<20))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RESER_src(data)          ((0xf00000&(data))>>20)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_RESER(data)          ((0xf00000&(data))>>20)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_RESER           0x0
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RS_shift              (16)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RS_mask               (0xf0000)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RS(data)              (0xf0000&((data)<<16))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RS_src(data)          ((0xf0000&(data))>>16)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_RS(data)          ((0xf0000&(data))>>16)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_RS           0x5
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV_shift              (8)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV_mask               (0xff00)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV(data)              (0xff00&((data)<<8))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV_src(data)          ((0xff00&(data))>>8)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_SEL_PREDIV(data)          ((0xff00&(data))>>8)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV           0x0
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV_BPN_shift              (7)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV_BPN_mask               (0x80)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV_BPN(data)              (0x80&((data)<<7))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV_BPN_src(data)          ((0x80&(data))>>7)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_SEL_PREDIV_BPN(data)          ((0x80&(data))>>7)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_SEL_PREDIV_BPN           0x0
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_TESTSEL_shift              (5)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_TESTSEL_mask               (0x60)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_TESTSEL(data)              (0x60&((data)<<5))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_TESTSEL_src(data)          ((0x60&(data))>>5)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_TESTSEL(data)          ((0x60&(data))>>5)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_TESTSEL           0x0
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_WDRST_shift              (4)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_WDRST_mask               (0x10)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_WDRST(data)              (0x10&((data)<<4))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_WDRST_src(data)          ((0x10&(data))>>4)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_WDRST(data)          ((0x10&(data))>>4)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_WDRST           0x1
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_WDSET_shift              (3)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_WDSET_mask               (0x8)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_WDSET(data)              (0x8&((data)<<3))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_WDSET_src(data)          ((0x8&(data))>>3)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_WDSET(data)          ((0x8&(data))>>3)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_WDSET           0x0
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_POW_shift              (2)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_POW_mask               (0x4)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_POW(data)              (0x4&((data)<<2))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_POW_src(data)          ((0x4&(data))>>2)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_POW(data)          ((0x4&(data))>>2)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_POW           0x0
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RSTB_shift              (1)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RSTB_mask               (0x2)
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RSTB(data)              (0x2&((data)<<1))
#define DPRX14_PLL_AUD_1_REG_DPRXPLL_RSTB_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_AUD_1_get_REG_DPRXPLL_RSTB(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_AUD_1_REG_DPRXPLL_RSTB           0x0

#define DPRX14_PLL_AUD_2                        0x408
#define DPRX14_PLL_AUD_2_reg_addr               "0x98165408"
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_BPSPI_shift              (7)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_BPSPI_mask               (0x80)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_BPSPI(data)              (0x80&((data)<<7))
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_BPSPI_src(data)          ((0x80&(data))>>7)
#define DPRX14_PLL_AUD_2_get_REG_DPRXPLL_BPSPI(data)          ((0x80&(data))>>7)
//this->default: DPRX14_PLL_AUD_2_REG_DPRXPLL_BPSPI           0x0
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_CP_shift              (6)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_CP_mask               (0x40)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_CP(data)              (0x40&((data)<<6))
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_CP_src(data)          ((0x40&(data))>>6)
#define DPRX14_PLL_AUD_2_get_REG_DPRXPLL_CP(data)          ((0x40&(data))>>6)
//this->default: DPRX14_PLL_AUD_2_REG_DPRXPLL_CP           0x0
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_DIVMODE_shift              (5)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_DIVMODE_mask               (0x20)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_DIVMODE(data)              (0x20&((data)<<5))
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_DIVMODE_src(data)          ((0x20&(data))>>5)
#define DPRX14_PLL_AUD_2_get_REG_DPRXPLL_DIVMODE(data)          ((0x20&(data))>>5)
//this->default: DPRX14_PLL_AUD_2_REG_DPRXPLL_DIVMODE           0x0
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_ENVCODIV4_shift              (4)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_ENVCODIV4_mask               (0x10)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_ENVCODIV4(data)              (0x10&((data)<<4))
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_ENVCODIV4_src(data)          ((0x10&(data))>>4)
#define DPRX14_PLL_AUD_2_get_REG_DPRXPLL_ENVCODIV4(data)          ((0x10&(data))>>4)
//this->default: DPRX14_PLL_AUD_2_REG_DPRXPLL_ENVCODIV4           0x1
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_FASTSEL_shift              (3)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_FASTSEL_mask               (0x8)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_FASTSEL(data)              (0x8&((data)<<3))
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_FASTSEL_src(data)          ((0x8&(data))>>3)
#define DPRX14_PLL_AUD_2_get_REG_DPRXPLL_FASTSEL(data)          ((0x8&(data))>>3)
//this->default: DPRX14_PLL_AUD_2_REG_DPRXPLL_FASTSEL           0x0
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_IP_shift              (0)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_IP_mask               (0x7)
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_IP(data)              (0x7&((data)<<0))
#define DPRX14_PLL_AUD_2_REG_DPRXPLL_IP_src(data)          ((0x7&(data))>>0)
#define DPRX14_PLL_AUD_2_get_REG_DPRXPLL_IP(data)          ((0x7&(data))>>0)
//this->default: DPRX14_PLL_AUD_2_REG_DPRXPLL_IP           0x0

#define DPRX14_PLL_PLL_SSC_DIG_AUD0                        0x420
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_reg_addr               "0x98165420"
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_DIVMODE_shift              (4)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_DIVMODE_mask               (0x10)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_DIVMODE(data)              (0x10&((data)<<4))
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_DIVMODE_src(data)          ((0x10&(data))>>4)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_get_DIVMODE(data)          ((0x10&(data))>>4)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD0_DIVMODE           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_GRAN_AUTO_RST_shift              (3)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_GRAN_AUTO_RST_mask               (0x8)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_GRAN_AUTO_RST(data)              (0x8&((data)<<3))
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_GRAN_AUTO_RST_src(data)          ((0x8&(data))>>3)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_get_GRAN_AUTO_RST(data)          ((0x8&(data))>>3)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD0_GRAN_AUTO_RST           0x1
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_RSTB_shift              (2)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_RSTB_mask               (0x4)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_RSTB(data)              (0x4&((data)<<2))
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_RSTB_src(data)          ((0x4&(data))>>2)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_get_RSTB(data)          ((0x4&(data))>>2)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD0_RSTB           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_EN_SSC_shift              (1)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_EN_SSC_mask               (0x2)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_EN_SSC(data)              (0x2&((data)<<1))
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_EN_SSC_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_get_EN_SSC(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD0_EN_SSC           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_OC_EN_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_OC_EN_mask               (0x1)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_OC_EN(data)              (0x1&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_OC_EN_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD0_get_OC_EN(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD0_OC_EN           0x0

#define DPRX14_PLL_PLL_SSC_DIG_AUD1                        0x424
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_reg_addr               "0x98165424"
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TMIE_RDY_CKOUT_shift              (30)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TMIE_RDY_CKOUT_mask               (0xc0000000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TMIE_RDY_CKOUT(data)              (0xc0000000&((data)<<30))
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TMIE_RDY_CKOUT_src(data)          ((0xc0000000&(data))>>30)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_get_TMIE_RDY_CKOUT(data)          ((0xc0000000&(data))>>30)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD1_TMIE_RDY_CKOUT           0x2
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME2_RST_WIDTH_shift              (28)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME2_RST_WIDTH_mask               (0x30000000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME2_RST_WIDTH(data)              (0x30000000&((data)<<28))
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME2_RST_WIDTH_src(data)          ((0x30000000&(data))>>28)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_get_TIME2_RST_WIDTH(data)          ((0x30000000&(data))>>28)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME2_RST_WIDTH           0x1
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME0_CK_shift              (24)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME0_CK_mask               (0x7000000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME0_CK(data)              (0x7000000&((data)<<24))
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME0_CK_src(data)          ((0x7000000&(data))>>24)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_get_TIME0_CK(data)          ((0x7000000&(data))>>24)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD1_TIME0_CK           0x3
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_F390K_shift              (22)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_F390K_mask               (0xc00000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_F390K(data)              (0xc00000&((data)<<22))
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_F390K_src(data)          ((0xc00000&(data))>>22)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_get_F390K(data)          ((0xc00000&(data))>>22)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD1_F390K           0x1
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_PLL_EN_shift              (21)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_PLL_EN_mask               (0x200000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_PLL_EN(data)              (0x200000&((data)<<21))
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_PLL_EN_src(data)          ((0x200000&(data))>>21)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_get_PLL_EN(data)          ((0x200000&(data))>>21)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD1_PLL_EN           0x1
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_WD_ENABLE_shift              (20)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_WD_ENABLE_mask               (0x100000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_WD_ENABLE(data)              (0x100000&((data)<<20))
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_WD_ENABLE_src(data)          ((0x100000&(data))>>20)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_get_WD_ENABLE(data)          ((0x100000&(data))>>20)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD1_WD_ENABLE           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_NCODE_T_shift              (11)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_NCODE_T_mask               (0x7f800)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_NCODE_T(data)              (0x7f800&((data)<<11))
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_NCODE_T_src(data)          ((0x7f800&(data))>>11)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_get_NCODE_T(data)          ((0x7f800&(data))>>11)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD1_NCODE_T           0x25
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_FCODE_T_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_FCODE_T_mask               (0x7ff)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_FCODE_T(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_FCODE_T_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD1_get_FCODE_T(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD1_FCODE_T           0x0

#define DPRX14_PLL_PLL_SSC_DIG_AUD2                        0x428
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_reg_addr               "0x98165428"
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_DIVN_shift              (27)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_DIVN_mask               (0x8000000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_DIVN(data)              (0x8000000&((data)<<27))
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_DIVN_src(data)          ((0x8000000&(data))>>27)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_get_REG_BYPASS_DIVN(data)          ((0x8000000&(data))>>27)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_DIVN           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_STEP_SET_shift              (17)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_STEP_SET_mask               (0x7fe0000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_STEP_SET(data)              (0x7fe0000&((data)<<17))
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_STEP_SET_src(data)          ((0x7fe0000&(data))>>17)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_get_REG_OC_STEP_SET(data)          ((0x7fe0000&(data))>>17)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_STEP_SET           0xf
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SEL_OC_MODE_shift              (15)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SEL_OC_MODE_mask               (0x18000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SEL_OC_MODE(data)              (0x18000&((data)<<15))
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SEL_OC_MODE_src(data)          ((0x18000&(data))>>15)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_get_REG_SEL_OC_MODE(data)          ((0x18000&(data))>>15)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SEL_OC_MODE           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_HS_OC_STOP_DIFF_shift              (13)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_HS_OC_STOP_DIFF_mask               (0x6000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_HS_OC_STOP_DIFF(data)              (0x6000&((data)<<13))
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_HS_OC_STOP_DIFF_src(data)          ((0x6000&(data))>>13)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_get_REG_HS_OC_STOP_DIFF(data)          ((0x6000&(data))>>13)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_HS_OC_STOP_DIFF           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_DONE_DELAY_shift              (7)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_DONE_DELAY_mask               (0x1f80)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_DONE_DELAY(data)              (0x1f80&((data)<<7))
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_DONE_DELAY_src(data)          ((0x1f80&(data))>>7)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_get_REG_OC_DONE_DELAY(data)          ((0x1f80&(data))>>7)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_OC_DONE_DELAY           0x3f
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_PI_shift              (6)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_PI_mask               (0x40)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_PI(data)              (0x40&((data)<<6))
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_PI_src(data)          ((0x40&(data))>>6)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_get_REG_BYPASS_PI(data)          ((0x40&(data))>>6)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_BYPASS_PI           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SDM_ORDER_shift              (5)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SDM_ORDER_mask               (0x20)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SDM_ORDER(data)              (0x20&((data)<<5))
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SDM_ORDER_src(data)          ((0x20&(data))>>5)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_get_REG_SDM_ORDER(data)          ((0x20&(data))>>5)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_SDM_ORDER           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_PI_CUR_SEL_shift              (2)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_PI_CUR_SEL_mask               (0x1c)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_PI_CUR_SEL(data)              (0x1c&((data)<<2))
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_PI_CUR_SEL_src(data)          ((0x1c&(data))>>2)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_get_REG_PI_CUR_SEL(data)          ((0x1c&(data))>>2)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_PI_CUR_SEL           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_EN_PI_DEBUG_shift              (1)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_EN_PI_DEBUG_mask               (0x2)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_EN_PI_DEBUG(data)              (0x2&((data)<<1))
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_EN_PI_DEBUG_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_PLL_SSC_DIG_AUD2_get_REG_EN_PI_DEBUG(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD2_REG_EN_PI_DEBUG           0x0

#define DPRX14_PLL_PLL_SSC_DIG_AUD3                        0x42c
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_reg_addr               "0x9816542c"
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_NCODE_SSC_shift              (11)
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_NCODE_SSC_mask               (0x7f800)
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_NCODE_SSC(data)              (0x7f800&((data)<<11))
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_NCODE_SSC_src(data)          ((0x7f800&(data))>>11)
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_get_NCODE_SSC(data)          ((0x7f800&(data))>>11)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD3_NCODE_SSC           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_FCODE_SSC_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_FCODE_SSC_mask               (0x7ff)
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_FCODE_SSC(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_FCODE_SSC_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD3_get_FCODE_SSC(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD3_FCODE_SSC           0x0

#define DPRX14_PLL_PLL_SSC_DIG_AUD4                        0x430
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_reg_addr               "0x98165430"
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_DOT_GRAN_shift              (19)
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_DOT_GRAN_mask               (0x380000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_DOT_GRAN(data)              (0x380000&((data)<<19))
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_DOT_GRAN_src(data)          ((0x380000&(data))>>19)
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_get_DOT_GRAN(data)          ((0x380000&(data))>>19)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD4_DOT_GRAN           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_GRAN_EST_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_GRAN_EST_mask               (0x7ffff)
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_GRAN_EST(data)              (0x7ffff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_GRAN_EST_src(data)          ((0x7ffff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD4_get_GRAN_EST(data)          ((0x7ffff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD4_GRAN_EST           0x0

#define DPRX14_PLL_PLL_SSC_DIG_AUD5                        0x434
#define DPRX14_PLL_PLL_SSC_DIG_AUD5_reg_addr               "0x98165434"
#define DPRX14_PLL_PLL_SSC_DIG_AUD5_MDRST_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD5_MDRST_mask               (0x1)
#define DPRX14_PLL_PLL_SSC_DIG_AUD5_MDRST(data)              (0x1&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_AUD5_MDRST_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD5_get_MDRST(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD5_MDRST           0x0

#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1                        0x440
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_reg_addr               "0x98165440"
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_LOOP_PI_ISEL_shift              (13)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_LOOP_PI_ISEL_mask               (0xe000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_LOOP_PI_ISEL(data)              (0xe000&((data)<<13))
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_LOOP_PI_ISEL_src(data)          ((0xe000&(data))>>13)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_get_LOOP_PI_ISEL(data)          ((0xe000&(data))>>13)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_LOOP_PI_ISEL           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_PHSEL_shift              (8)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_PHSEL_mask               (0x1f00)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_PHSEL(data)              (0x1f00&((data)<<8))
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_PHSEL_src(data)          ((0x1f00&(data))>>8)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_get_PHSEL(data)          ((0x1f00&(data))>>8)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_PHSEL           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_DIVN_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_DIVN_mask               (0xff)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_DIVN(data)              (0xff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_DIVN_src(data)          ((0xff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_get_DIVN(data)          ((0xff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD_DBG1_DIVN           0x0

#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2                        0x444
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_reg_addr               "0x98165444"
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_CLKRDY_shift              (22)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_CLKRDY_mask               (0x400000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_CLKRDY(data)              (0x400000&((data)<<22))
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_CLKRDY_src(data)          ((0x400000&(data))>>22)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_get_CLKRDY(data)          ((0x400000&(data))>>22)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_CLKRDY           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_load_FCW_shift              (21)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_load_FCW_mask               (0x200000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_load_FCW(data)              (0x200000&((data)<<21))
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_load_FCW_src(data)          ((0x200000&(data))>>21)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_get_load_FCW(data)          ((0x200000&(data))>>21)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_load_FCW           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_OC_DONE_shift              (20)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_OC_DONE_mask               (0x100000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_OC_DONE(data)              (0x100000&((data)<<20))
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_OC_DONE_src(data)          ((0x100000&(data))>>20)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_get_OC_DONE(data)          ((0x100000&(data))>>20)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_OC_DONE           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FMOD_shift              (19)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FMOD_mask               (0x80000)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FMOD(data)              (0x80000&((data)<<19))
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FMOD_src(data)          ((0x80000&(data))>>19)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_get_FMOD(data)          ((0x80000&(data))>>19)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FMOD           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_NCODE_DEBUG_shift              (11)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_NCODE_DEBUG_mask               (0x7f800)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_NCODE_DEBUG(data)              (0x7f800&((data)<<11))
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_NCODE_DEBUG_src(data)          ((0x7f800&(data))>>11)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_get_NCODE_DEBUG(data)          ((0x7f800&(data))>>11)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_NCODE_DEBUG           0x0
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FCODE_DEBUG_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FCODE_DEBUG_mask               (0x7ff)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FCODE_DEBUG(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FCODE_DEBUG_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_get_FCODE_DEBUG(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_AUD_DBG2_FCODE_DEBUG           0x0

#define DPRX14_PLL_VID_1                        0x460
#define DPRX14_PLL_VID_1_reg_addr               "0x98165460"
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDOPOW_shift              (31)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDOPOW_mask               (0x80000000)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDOPOW(data)              (0x80000000&((data)<<31))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDOPOW_src(data)          ((0x80000000&(data))>>31)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_LDOPOW(data)          ((0x80000000&(data))>>31)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_LDOPOW           0x0
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_REF2CORE_shift              (30)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_REF2CORE_mask               (0x40000000)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_REF2CORE(data)              (0x40000000&((data)<<30))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_REF2CORE_src(data)          ((0x40000000&(data))>>30)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_LDO_REF2CORE(data)          ((0x40000000&(data))>>30)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_REF2CORE           0x0
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_SEL_shift              (28)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_SEL_mask               (0x30000000)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_SEL(data)              (0x30000000&((data)<<28))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_SEL_src(data)          ((0x30000000&(data))>>28)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_LDO_SEL(data)          ((0x30000000&(data))>>28)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_LDO_SEL           0x1
#define DPRX14_PLL_VID_1_REG_DPRXPLL_O_shift              (25)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_O_mask               (0xe000000)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_O(data)              (0xe000000&((data)<<25))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_O_src(data)          ((0xe000000&(data))>>25)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_O(data)          ((0xe000000&(data))>>25)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_O           0x0
#define DPRX14_PLL_VID_1_REG_DPRXPLL_OEB_shift              (24)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_OEB_mask               (0x1000000)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_OEB(data)              (0x1000000&((data)<<24))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_OEB_src(data)          ((0x1000000&(data))>>24)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_OEB(data)          ((0x1000000&(data))>>24)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_OEB           0x1
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RESER_shift              (20)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RESER_mask               (0xf00000)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RESER(data)              (0xf00000&((data)<<20))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RESER_src(data)          ((0xf00000&(data))>>20)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_RESER(data)          ((0xf00000&(data))>>20)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_RESER           0x0
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RS_shift              (16)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RS_mask               (0xf0000)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RS(data)              (0xf0000&((data)<<16))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RS_src(data)          ((0xf0000&(data))>>16)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_RS(data)          ((0xf0000&(data))>>16)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_RS           0x5
#define DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV_shift              (8)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV_mask               (0xff00)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV(data)              (0xff00&((data)<<8))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV_src(data)          ((0xff00&(data))>>8)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_SEL_PREDIV(data)          ((0xff00&(data))>>8)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV           0x0
#define DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV_BPN_shift              (7)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV_BPN_mask               (0x80)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV_BPN(data)              (0x80&((data)<<7))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV_BPN_src(data)          ((0x80&(data))>>7)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_SEL_PREDIV_BPN(data)          ((0x80&(data))>>7)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_SEL_PREDIV_BPN           0x0
#define DPRX14_PLL_VID_1_REG_DPRXPLL_TESTSEL_shift              (5)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_TESTSEL_mask               (0x60)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_TESTSEL(data)              (0x60&((data)<<5))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_TESTSEL_src(data)          ((0x60&(data))>>5)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_TESTSEL(data)          ((0x60&(data))>>5)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_TESTSEL           0x0
#define DPRX14_PLL_VID_1_REG_DPRXPLL_WDRST_shift              (4)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_WDRST_mask               (0x10)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_WDRST(data)              (0x10&((data)<<4))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_WDRST_src(data)          ((0x10&(data))>>4)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_WDRST(data)          ((0x10&(data))>>4)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_WDRST           0x1
#define DPRX14_PLL_VID_1_REG_DPRXPLL_WDSET_shift              (3)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_WDSET_mask               (0x8)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_WDSET(data)              (0x8&((data)<<3))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_WDSET_src(data)          ((0x8&(data))>>3)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_WDSET(data)          ((0x8&(data))>>3)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_WDSET           0x0
#define DPRX14_PLL_VID_1_REG_DPRXPLL_POW_shift              (2)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_POW_mask               (0x4)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_POW(data)              (0x4&((data)<<2))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_POW_src(data)          ((0x4&(data))>>2)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_POW(data)          ((0x4&(data))>>2)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_POW           0x0
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RSTB_shift              (1)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RSTB_mask               (0x2)
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RSTB(data)              (0x2&((data)<<1))
#define DPRX14_PLL_VID_1_REG_DPRXPLL_RSTB_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_VID_1_get_REG_DPRXPLL_RSTB(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_VID_1_REG_DPRXPLL_RSTB           0x0

#define DPRX14_PLL_VID_2                        0x464
#define DPRX14_PLL_VID_2_reg_addr               "0x98165464"
#define DPRX14_PLL_VID_2_REG_DPRXPLL_BPSPI_shift              (7)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_BPSPI_mask               (0x80)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_BPSPI(data)              (0x80&((data)<<7))
#define DPRX14_PLL_VID_2_REG_DPRXPLL_BPSPI_src(data)          ((0x80&(data))>>7)
#define DPRX14_PLL_VID_2_get_REG_DPRXPLL_BPSPI(data)          ((0x80&(data))>>7)
//this->default: DPRX14_PLL_VID_2_REG_DPRXPLL_BPSPI           0x0
#define DPRX14_PLL_VID_2_REG_DPRXPLL_CP_shift              (6)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_CP_mask               (0x40)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_CP(data)              (0x40&((data)<<6))
#define DPRX14_PLL_VID_2_REG_DPRXPLL_CP_src(data)          ((0x40&(data))>>6)
#define DPRX14_PLL_VID_2_get_REG_DPRXPLL_CP(data)          ((0x40&(data))>>6)
//this->default: DPRX14_PLL_VID_2_REG_DPRXPLL_CP           0x0
#define DPRX14_PLL_VID_2_REG_DPRXPLL_DIVMODE_shift              (5)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_DIVMODE_mask               (0x20)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_DIVMODE(data)              (0x20&((data)<<5))
#define DPRX14_PLL_VID_2_REG_DPRXPLL_DIVMODE_src(data)          ((0x20&(data))>>5)
#define DPRX14_PLL_VID_2_get_REG_DPRXPLL_DIVMODE(data)          ((0x20&(data))>>5)
//this->default: DPRX14_PLL_VID_2_REG_DPRXPLL_DIVMODE           0x0
#define DPRX14_PLL_VID_2_REG_DPRXPLL_ENVCODIV4_shift              (4)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_ENVCODIV4_mask               (0x10)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_ENVCODIV4(data)              (0x10&((data)<<4))
#define DPRX14_PLL_VID_2_REG_DPRXPLL_ENVCODIV4_src(data)          ((0x10&(data))>>4)
#define DPRX14_PLL_VID_2_get_REG_DPRXPLL_ENVCODIV4(data)          ((0x10&(data))>>4)
//this->default: DPRX14_PLL_VID_2_REG_DPRXPLL_ENVCODIV4           0x1
#define DPRX14_PLL_VID_2_REG_DPRXPLL_FASTSEL_shift              (3)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_FASTSEL_mask               (0x8)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_FASTSEL(data)              (0x8&((data)<<3))
#define DPRX14_PLL_VID_2_REG_DPRXPLL_FASTSEL_src(data)          ((0x8&(data))>>3)
#define DPRX14_PLL_VID_2_get_REG_DPRXPLL_FASTSEL(data)          ((0x8&(data))>>3)
//this->default: DPRX14_PLL_VID_2_REG_DPRXPLL_FASTSEL           0x0
#define DPRX14_PLL_VID_2_REG_DPRXPLL_IP_shift              (0)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_IP_mask               (0x7)
#define DPRX14_PLL_VID_2_REG_DPRXPLL_IP(data)              (0x7&((data)<<0))
#define DPRX14_PLL_VID_2_REG_DPRXPLL_IP_src(data)          ((0x7&(data))>>0)
#define DPRX14_PLL_VID_2_get_REG_DPRXPLL_IP(data)          ((0x7&(data))>>0)
//this->default: DPRX14_PLL_VID_2_REG_DPRXPLL_IP           0x0

#define DPRX14_PLL_PLL_SSC_DIG_VID0                        0x480
#define DPRX14_PLL_PLL_SSC_DIG_VID0_reg_addr               "0x98165480"
#define DPRX14_PLL_PLL_SSC_DIG_VID0_DIVMODE_shift              (4)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_DIVMODE_mask               (0x10)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_DIVMODE(data)              (0x10&((data)<<4))
#define DPRX14_PLL_PLL_SSC_DIG_VID0_DIVMODE_src(data)          ((0x10&(data))>>4)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_get_DIVMODE(data)          ((0x10&(data))>>4)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID0_DIVMODE           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID0_GRAN_AUTO_RST_shift              (3)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_GRAN_AUTO_RST_mask               (0x8)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_GRAN_AUTO_RST(data)              (0x8&((data)<<3))
#define DPRX14_PLL_PLL_SSC_DIG_VID0_GRAN_AUTO_RST_src(data)          ((0x8&(data))>>3)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_get_GRAN_AUTO_RST(data)          ((0x8&(data))>>3)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID0_GRAN_AUTO_RST           0x1
#define DPRX14_PLL_PLL_SSC_DIG_VID0_RSTB_shift              (2)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_RSTB_mask               (0x4)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_RSTB(data)              (0x4&((data)<<2))
#define DPRX14_PLL_PLL_SSC_DIG_VID0_RSTB_src(data)          ((0x4&(data))>>2)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_get_RSTB(data)          ((0x4&(data))>>2)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID0_RSTB           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID0_EN_SSC_shift              (1)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_EN_SSC_mask               (0x2)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_EN_SSC(data)              (0x2&((data)<<1))
#define DPRX14_PLL_PLL_SSC_DIG_VID0_EN_SSC_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_get_EN_SSC(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID0_EN_SSC           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID0_OC_EN_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_OC_EN_mask               (0x1)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_OC_EN(data)              (0x1&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_VID0_OC_EN_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_VID0_get_OC_EN(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID0_OC_EN           0x0

#define DPRX14_PLL_PLL_SSC_DIG_VID1                        0x484
#define DPRX14_PLL_PLL_SSC_DIG_VID1_reg_addr               "0x98165484"
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TMIE_RDY_CKOUT_shift              (30)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TMIE_RDY_CKOUT_mask               (0xc0000000)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TMIE_RDY_CKOUT(data)              (0xc0000000&((data)<<30))
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TMIE_RDY_CKOUT_src(data)          ((0xc0000000&(data))>>30)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_get_TMIE_RDY_CKOUT(data)          ((0xc0000000&(data))>>30)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID1_TMIE_RDY_CKOUT           0x2
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TIME2_RST_WIDTH_shift              (28)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TIME2_RST_WIDTH_mask               (0x30000000)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TIME2_RST_WIDTH(data)              (0x30000000&((data)<<28))
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TIME2_RST_WIDTH_src(data)          ((0x30000000&(data))>>28)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_get_TIME2_RST_WIDTH(data)          ((0x30000000&(data))>>28)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID1_TIME2_RST_WIDTH           0x1
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TIME0_CK_shift              (24)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TIME0_CK_mask               (0x7000000)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TIME0_CK(data)              (0x7000000&((data)<<24))
#define DPRX14_PLL_PLL_SSC_DIG_VID1_TIME0_CK_src(data)          ((0x7000000&(data))>>24)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_get_TIME0_CK(data)          ((0x7000000&(data))>>24)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID1_TIME0_CK           0x3
#define DPRX14_PLL_PLL_SSC_DIG_VID1_F390K_shift              (22)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_F390K_mask               (0xc00000)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_F390K(data)              (0xc00000&((data)<<22))
#define DPRX14_PLL_PLL_SSC_DIG_VID1_F390K_src(data)          ((0xc00000&(data))>>22)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_get_F390K(data)          ((0xc00000&(data))>>22)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID1_F390K           0x1
#define DPRX14_PLL_PLL_SSC_DIG_VID1_PLL_EN_shift              (21)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_PLL_EN_mask               (0x200000)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_PLL_EN(data)              (0x200000&((data)<<21))
#define DPRX14_PLL_PLL_SSC_DIG_VID1_PLL_EN_src(data)          ((0x200000&(data))>>21)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_get_PLL_EN(data)          ((0x200000&(data))>>21)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID1_PLL_EN           0x1
#define DPRX14_PLL_PLL_SSC_DIG_VID1_WD_ENABLE_shift              (20)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_WD_ENABLE_mask               (0x100000)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_WD_ENABLE(data)              (0x100000&((data)<<20))
#define DPRX14_PLL_PLL_SSC_DIG_VID1_WD_ENABLE_src(data)          ((0x100000&(data))>>20)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_get_WD_ENABLE(data)          ((0x100000&(data))>>20)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID1_WD_ENABLE           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID1_NCODE_T_shift              (11)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_NCODE_T_mask               (0x7f800)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_NCODE_T(data)              (0x7f800&((data)<<11))
#define DPRX14_PLL_PLL_SSC_DIG_VID1_NCODE_T_src(data)          ((0x7f800&(data))>>11)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_get_NCODE_T(data)          ((0x7f800&(data))>>11)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID1_NCODE_T           0x25
#define DPRX14_PLL_PLL_SSC_DIG_VID1_FCODE_T_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_FCODE_T_mask               (0x7ff)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_FCODE_T(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_VID1_FCODE_T_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_VID1_get_FCODE_T(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID1_FCODE_T           0x0

#define DPRX14_PLL_PLL_SSC_DIG_VID2                        0x488
#define DPRX14_PLL_PLL_SSC_DIG_VID2_reg_addr               "0x98165488"
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_DIVN_shift              (27)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_DIVN_mask               (0x8000000)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_DIVN(data)              (0x8000000&((data)<<27))
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_DIVN_src(data)          ((0x8000000&(data))>>27)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_get_REG_BYPASS_DIVN(data)          ((0x8000000&(data))>>27)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_DIVN           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_STEP_SET_shift              (17)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_STEP_SET_mask               (0x7fe0000)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_STEP_SET(data)              (0x7fe0000&((data)<<17))
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_STEP_SET_src(data)          ((0x7fe0000&(data))>>17)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_get_REG_OC_STEP_SET(data)          ((0x7fe0000&(data))>>17)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_STEP_SET           0xf
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SEL_OC_MODE_shift              (15)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SEL_OC_MODE_mask               (0x18000)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SEL_OC_MODE(data)              (0x18000&((data)<<15))
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SEL_OC_MODE_src(data)          ((0x18000&(data))>>15)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_get_REG_SEL_OC_MODE(data)          ((0x18000&(data))>>15)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SEL_OC_MODE           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_HS_OC_STOP_DIFF_shift              (13)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_HS_OC_STOP_DIFF_mask               (0x6000)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_HS_OC_STOP_DIFF(data)              (0x6000&((data)<<13))
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_HS_OC_STOP_DIFF_src(data)          ((0x6000&(data))>>13)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_get_REG_HS_OC_STOP_DIFF(data)          ((0x6000&(data))>>13)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID2_REG_HS_OC_STOP_DIFF           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_DONE_DELAY_shift              (7)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_DONE_DELAY_mask               (0x1f80)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_DONE_DELAY(data)              (0x1f80&((data)<<7))
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_DONE_DELAY_src(data)          ((0x1f80&(data))>>7)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_get_REG_OC_DONE_DELAY(data)          ((0x1f80&(data))>>7)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID2_REG_OC_DONE_DELAY           0x3f
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_PI_shift              (6)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_PI_mask               (0x40)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_PI(data)              (0x40&((data)<<6))
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_PI_src(data)          ((0x40&(data))>>6)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_get_REG_BYPASS_PI(data)          ((0x40&(data))>>6)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID2_REG_BYPASS_PI           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SDM_ORDER_shift              (5)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SDM_ORDER_mask               (0x20)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SDM_ORDER(data)              (0x20&((data)<<5))
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SDM_ORDER_src(data)          ((0x20&(data))>>5)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_get_REG_SDM_ORDER(data)          ((0x20&(data))>>5)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID2_REG_SDM_ORDER           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_PI_CUR_SEL_shift              (2)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_PI_CUR_SEL_mask               (0x1c)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_PI_CUR_SEL(data)              (0x1c&((data)<<2))
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_PI_CUR_SEL_src(data)          ((0x1c&(data))>>2)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_get_REG_PI_CUR_SEL(data)          ((0x1c&(data))>>2)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID2_REG_PI_CUR_SEL           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_EN_PI_DEBUG_shift              (1)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_EN_PI_DEBUG_mask               (0x2)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_EN_PI_DEBUG(data)              (0x2&((data)<<1))
#define DPRX14_PLL_PLL_SSC_DIG_VID2_REG_EN_PI_DEBUG_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_PLL_SSC_DIG_VID2_get_REG_EN_PI_DEBUG(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID2_REG_EN_PI_DEBUG           0x0

#define DPRX14_PLL_PLL_SSC_DIG_VID3                        0x48c
#define DPRX14_PLL_PLL_SSC_DIG_VID3_reg_addr               "0x9816548c"
#define DPRX14_PLL_PLL_SSC_DIG_VID3_NCODE_SSC_shift              (11)
#define DPRX14_PLL_PLL_SSC_DIG_VID3_NCODE_SSC_mask               (0x7f800)
#define DPRX14_PLL_PLL_SSC_DIG_VID3_NCODE_SSC(data)              (0x7f800&((data)<<11))
#define DPRX14_PLL_PLL_SSC_DIG_VID3_NCODE_SSC_src(data)          ((0x7f800&(data))>>11)
#define DPRX14_PLL_PLL_SSC_DIG_VID3_get_NCODE_SSC(data)          ((0x7f800&(data))>>11)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID3_NCODE_SSC           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID3_FCODE_SSC_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_VID3_FCODE_SSC_mask               (0x7ff)
#define DPRX14_PLL_PLL_SSC_DIG_VID3_FCODE_SSC(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_VID3_FCODE_SSC_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_VID3_get_FCODE_SSC(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID3_FCODE_SSC           0x0

#define DPRX14_PLL_PLL_SSC_DIG_VID4                        0x490
#define DPRX14_PLL_PLL_SSC_DIG_VID4_reg_addr               "0x98165490"
#define DPRX14_PLL_PLL_SSC_DIG_VID4_DOT_GRAN_shift              (19)
#define DPRX14_PLL_PLL_SSC_DIG_VID4_DOT_GRAN_mask               (0x380000)
#define DPRX14_PLL_PLL_SSC_DIG_VID4_DOT_GRAN(data)              (0x380000&((data)<<19))
#define DPRX14_PLL_PLL_SSC_DIG_VID4_DOT_GRAN_src(data)          ((0x380000&(data))>>19)
#define DPRX14_PLL_PLL_SSC_DIG_VID4_get_DOT_GRAN(data)          ((0x380000&(data))>>19)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID4_DOT_GRAN           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID4_GRAN_EST_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_VID4_GRAN_EST_mask               (0x7ffff)
#define DPRX14_PLL_PLL_SSC_DIG_VID4_GRAN_EST(data)              (0x7ffff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_VID4_GRAN_EST_src(data)          ((0x7ffff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_VID4_get_GRAN_EST(data)          ((0x7ffff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID4_GRAN_EST           0x0

#define DPRX14_PLL_PLL_SSC_DIG_VID5                        0x494
#define DPRX14_PLL_PLL_SSC_DIG_VID5_reg_addr               "0x98165494"
#define DPRX14_PLL_PLL_SSC_DIG_VID5_MDRST_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_VID5_MDRST_mask               (0x1)
#define DPRX14_PLL_PLL_SSC_DIG_VID5_MDRST(data)              (0x1&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_VID5_MDRST_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_VID5_get_MDRST(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID5_MDRST           0x0

#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1                        0x4a0
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_reg_addr               "0x981654a0"
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_LOOP_PI_ISEL_shift              (13)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_LOOP_PI_ISEL_mask               (0xe000)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_LOOP_PI_ISEL(data)              (0xe000&((data)<<13))
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_LOOP_PI_ISEL_src(data)          ((0xe000&(data))>>13)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_get_LOOP_PI_ISEL(data)          ((0xe000&(data))>>13)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_LOOP_PI_ISEL           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_PHSEL_shift              (8)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_PHSEL_mask               (0x1f00)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_PHSEL(data)              (0x1f00&((data)<<8))
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_PHSEL_src(data)          ((0x1f00&(data))>>8)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_get_PHSEL(data)          ((0x1f00&(data))>>8)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_PHSEL           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_DIVN_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_DIVN_mask               (0xff)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_DIVN(data)              (0xff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_DIVN_src(data)          ((0xff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_get_DIVN(data)          ((0xff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID_DBG1_DIVN           0x0

#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2                        0x4a4
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_reg_addr               "0x981654a4"
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_CLKRDY_shift              (22)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_CLKRDY_mask               (0x400000)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_CLKRDY(data)              (0x400000&((data)<<22))
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_CLKRDY_src(data)          ((0x400000&(data))>>22)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_get_CLKRDY(data)          ((0x400000&(data))>>22)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_CLKRDY           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_load_FCW_shift              (21)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_load_FCW_mask               (0x200000)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_load_FCW(data)              (0x200000&((data)<<21))
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_load_FCW_src(data)          ((0x200000&(data))>>21)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_get_load_FCW(data)          ((0x200000&(data))>>21)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_load_FCW           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_OC_DONE_shift              (20)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_OC_DONE_mask               (0x100000)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_OC_DONE(data)              (0x100000&((data)<<20))
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_OC_DONE_src(data)          ((0x100000&(data))>>20)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_get_OC_DONE(data)          ((0x100000&(data))>>20)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_OC_DONE           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FMOD_shift              (19)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FMOD_mask               (0x80000)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FMOD(data)              (0x80000&((data)<<19))
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FMOD_src(data)          ((0x80000&(data))>>19)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_get_FMOD(data)          ((0x80000&(data))>>19)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FMOD           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_NCODE_DEBUG_shift              (11)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_NCODE_DEBUG_mask               (0x7f800)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_NCODE_DEBUG(data)              (0x7f800&((data)<<11))
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_NCODE_DEBUG_src(data)          ((0x7f800&(data))>>11)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_get_NCODE_DEBUG(data)          ((0x7f800&(data))>>11)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_NCODE_DEBUG           0x0
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FCODE_DEBUG_shift              (0)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FCODE_DEBUG_mask               (0x7ff)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FCODE_DEBUG(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FCODE_DEBUG_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_get_FCODE_DEBUG(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_PLL_SSC_DIG_VID_DBG2_FCODE_DEBUG           0x0

#define DPRX14_PLL_PLL_SEL                        0x4b0
#define DPRX14_PLL_PLL_SEL_reg_addr               "0x981654b0"
#define DPRX14_PLL_PLL_SEL_ip_oclk_sel_shift              (1)
#define DPRX14_PLL_PLL_SEL_ip_oclk_sel_mask               (0x2)
#define DPRX14_PLL_PLL_SEL_ip_oclk_sel(data)              (0x2&((data)<<1))
#define DPRX14_PLL_PLL_SEL_ip_oclk_sel_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_PLL_SEL_get_ip_oclk_sel(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_PLL_SEL_ip_oclk_sel           0x0
#define DPRX14_PLL_PLL_SEL_ip_dpll_sel_shift              (0)
#define DPRX14_PLL_PLL_SEL_ip_dpll_sel_mask               (0x1)
#define DPRX14_PLL_PLL_SEL_ip_dpll_sel(data)              (0x1&((data)<<0))
#define DPRX14_PLL_PLL_SEL_ip_dpll_sel_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_PLL_SEL_get_ip_dpll_sel(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_PLL_SEL_ip_dpll_sel           0x0

#define DPRX14_PLL_MISC                        0x4b4
#define DPRX14_PLL_MISC_reg_addr               "0x981654b4"
#define DPRX14_PLL_MISC_iso_ana_b_shift              (0)
#define DPRX14_PLL_MISC_iso_ana_b_mask               (0x1)
#define DPRX14_PLL_MISC_iso_ana_b(data)              (0x1&((data)<<0))
#define DPRX14_PLL_MISC_iso_ana_b_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_MISC_get_iso_ana_b(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_MISC_iso_ana_b           0x0

#define DPRX14_PLL_PIX2_DIV_CTRL                        0x450
#define DPRX14_PLL_PIX2_DIV_CTRL_reg_addr               "0x98165450"
#define DPRX14_PLL_PIX2_DIV_CTRL_div_en_shift              (1)
#define DPRX14_PLL_PIX2_DIV_CTRL_div_en_mask               (0x2)
#define DPRX14_PLL_PIX2_DIV_CTRL_div_en(data)              (0x2&((data)<<1))
#define DPRX14_PLL_PIX2_DIV_CTRL_div_en_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_PIX2_DIV_CTRL_get_div_en(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_PIX2_DIV_CTRL_div_en           0x0
#define DPRX14_PLL_PIX2_DIV_CTRL_div_rstn_shift              (0)
#define DPRX14_PLL_PIX2_DIV_CTRL_div_rstn_mask               (0x1)
#define DPRX14_PLL_PIX2_DIV_CTRL_div_rstn(data)              (0x1&((data)<<0))
#define DPRX14_PLL_PIX2_DIV_CTRL_div_rstn_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_PIX2_DIV_CTRL_get_div_rstn(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_PIX2_DIV_CTRL_div_rstn           0x0

#define DPRX14_PLL_RTRAN_DIV_CTRL                        0x454
#define DPRX14_PLL_RTRAN_DIV_CTRL_reg_addr               "0x98165454"
#define DPRX14_PLL_RTRAN_DIV_CTRL_div_en_shift              (1)
#define DPRX14_PLL_RTRAN_DIV_CTRL_div_en_mask               (0x2)
#define DPRX14_PLL_RTRAN_DIV_CTRL_div_en(data)              (0x2&((data)<<1))
#define DPRX14_PLL_RTRAN_DIV_CTRL_div_en_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_RTRAN_DIV_CTRL_get_div_en(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_RTRAN_DIV_CTRL_div_en           0x0
#define DPRX14_PLL_RTRAN_DIV_CTRL_div_rstn_shift              (0)
#define DPRX14_PLL_RTRAN_DIV_CTRL_div_rstn_mask               (0x1)
#define DPRX14_PLL_RTRAN_DIV_CTRL_div_rstn(data)              (0x1&((data)<<0))
#define DPRX14_PLL_RTRAN_DIV_CTRL_div_rstn_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_RTRAN_DIV_CTRL_get_div_rstn(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_RTRAN_DIV_CTRL_div_rstn           0x0

#define DPRX14_PLL_GTRAN_DIV_CTRL                        0x458
#define DPRX14_PLL_GTRAN_DIV_CTRL_reg_addr               "0x98165458"
#define DPRX14_PLL_GTRAN_DIV_CTRL_div_en_shift              (1)
#define DPRX14_PLL_GTRAN_DIV_CTRL_div_en_mask               (0x2)
#define DPRX14_PLL_GTRAN_DIV_CTRL_div_en(data)              (0x2&((data)<<1))
#define DPRX14_PLL_GTRAN_DIV_CTRL_div_en_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_GTRAN_DIV_CTRL_get_div_en(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_GTRAN_DIV_CTRL_div_en           0x0
#define DPRX14_PLL_GTRAN_DIV_CTRL_div_rstn_shift              (0)
#define DPRX14_PLL_GTRAN_DIV_CTRL_div_rstn_mask               (0x1)
#define DPRX14_PLL_GTRAN_DIV_CTRL_div_rstn(data)              (0x1&((data)<<0))
#define DPRX14_PLL_GTRAN_DIV_CTRL_div_rstn_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_GTRAN_DIV_CTRL_get_div_rstn(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_GTRAN_DIV_CTRL_div_rstn           0x0

#define DPRX14_PLL_BTRAN_DIV_CTRL                        0x45c
#define DPRX14_PLL_BTRAN_DIV_CTRL_reg_addr               "0x9816545c"
#define DPRX14_PLL_BTRAN_DIV_CTRL_div_en_shift              (1)
#define DPRX14_PLL_BTRAN_DIV_CTRL_div_en_mask               (0x2)
#define DPRX14_PLL_BTRAN_DIV_CTRL_div_en(data)              (0x2&((data)<<1))
#define DPRX14_PLL_BTRAN_DIV_CTRL_div_en_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_BTRAN_DIV_CTRL_get_div_en(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_BTRAN_DIV_CTRL_div_en           0x0
#define DPRX14_PLL_BTRAN_DIV_CTRL_div_rstn_shift              (0)
#define DPRX14_PLL_BTRAN_DIV_CTRL_div_rstn_mask               (0x1)
#define DPRX14_PLL_BTRAN_DIV_CTRL_div_rstn(data)              (0x1&((data)<<0))
#define DPRX14_PLL_BTRAN_DIV_CTRL_div_rstn_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_BTRAN_DIV_CTRL_get_div_rstn(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_BTRAN_DIV_CTRL_div_rstn           0x0

#define DPRX14_PLL_CKTRAN_DIV_CTRL                        0x470
#define DPRX14_PLL_CKTRAN_DIV_CTRL_reg_addr               "0x98165470"
#define DPRX14_PLL_CKTRAN_DIV_CTRL_div_en_shift              (1)
#define DPRX14_PLL_CKTRAN_DIV_CTRL_div_en_mask               (0x2)
#define DPRX14_PLL_CKTRAN_DIV_CTRL_div_en(data)              (0x2&((data)<<1))
#define DPRX14_PLL_CKTRAN_DIV_CTRL_div_en_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_CKTRAN_DIV_CTRL_get_div_en(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_CKTRAN_DIV_CTRL_div_en           0x0
#define DPRX14_PLL_CKTRAN_DIV_CTRL_div_rstn_shift              (0)
#define DPRX14_PLL_CKTRAN_DIV_CTRL_div_rstn_mask               (0x1)
#define DPRX14_PLL_CKTRAN_DIV_CTRL_div_rstn(data)              (0x1&((data)<<0))
#define DPRX14_PLL_CKTRAN_DIV_CTRL_div_rstn_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_CKTRAN_DIV_CTRL_get_div_rstn(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_CKTRAN_DIV_CTRL_div_rstn           0x0

#define DPRX14_PLL_DPL0_DIV_CTRL                        0x474
#define DPRX14_PLL_DPL0_DIV_CTRL_reg_addr               "0x98165474"
#define DPRX14_PLL_DPL0_DIV_CTRL_div_en_shift              (1)
#define DPRX14_PLL_DPL0_DIV_CTRL_div_en_mask               (0x2)
#define DPRX14_PLL_DPL0_DIV_CTRL_div_en(data)              (0x2&((data)<<1))
#define DPRX14_PLL_DPL0_DIV_CTRL_div_en_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_DPL0_DIV_CTRL_get_div_en(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_DPL0_DIV_CTRL_div_en           0x0
#define DPRX14_PLL_DPL0_DIV_CTRL_div_rstn_shift              (0)
#define DPRX14_PLL_DPL0_DIV_CTRL_div_rstn_mask               (0x1)
#define DPRX14_PLL_DPL0_DIV_CTRL_div_rstn(data)              (0x1&((data)<<0))
#define DPRX14_PLL_DPL0_DIV_CTRL_div_rstn_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_DPL0_DIV_CTRL_get_div_rstn(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_DPL0_DIV_CTRL_div_rstn           0x0

#define DPRX14_PLL_DPL1_DIV_CTRL                        0x478
#define DPRX14_PLL_DPL1_DIV_CTRL_reg_addr               "0x98165478"
#define DPRX14_PLL_DPL1_DIV_CTRL_div_en_shift              (1)
#define DPRX14_PLL_DPL1_DIV_CTRL_div_en_mask               (0x2)
#define DPRX14_PLL_DPL1_DIV_CTRL_div_en(data)              (0x2&((data)<<1))
#define DPRX14_PLL_DPL1_DIV_CTRL_div_en_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_DPL1_DIV_CTRL_get_div_en(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_DPL1_DIV_CTRL_div_en           0x0
#define DPRX14_PLL_DPL1_DIV_CTRL_div_rstn_shift              (0)
#define DPRX14_PLL_DPL1_DIV_CTRL_div_rstn_mask               (0x1)
#define DPRX14_PLL_DPL1_DIV_CTRL_div_rstn(data)              (0x1&((data)<<0))
#define DPRX14_PLL_DPL1_DIV_CTRL_div_rstn_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_DPL1_DIV_CTRL_get_div_rstn(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_DPL1_DIV_CTRL_div_rstn           0x0

#define DPRX14_PLL_DPL2_DIV_CTRL                        0x47c
#define DPRX14_PLL_DPL2_DIV_CTRL_reg_addr               "0x9816547c"
#define DPRX14_PLL_DPL2_DIV_CTRL_div_en_shift              (1)
#define DPRX14_PLL_DPL2_DIV_CTRL_div_en_mask               (0x2)
#define DPRX14_PLL_DPL2_DIV_CTRL_div_en(data)              (0x2&((data)<<1))
#define DPRX14_PLL_DPL2_DIV_CTRL_div_en_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_DPL2_DIV_CTRL_get_div_en(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_DPL2_DIV_CTRL_div_en           0x0
#define DPRX14_PLL_DPL2_DIV_CTRL_div_rstn_shift              (0)
#define DPRX14_PLL_DPL2_DIV_CTRL_div_rstn_mask               (0x1)
#define DPRX14_PLL_DPL2_DIV_CTRL_div_rstn(data)              (0x1&((data)<<0))
#define DPRX14_PLL_DPL2_DIV_CTRL_div_rstn_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_DPL2_DIV_CTRL_get_div_rstn(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_DPL2_DIV_CTRL_div_rstn           0x0

#define DPRX14_PLL_DPL3_DIV_CTRL                        0x4c0
#define DPRX14_PLL_DPL3_DIV_CTRL_reg_addr               "0x981654c0"
#define DPRX14_PLL_DPL3_DIV_CTRL_div_en_shift              (1)
#define DPRX14_PLL_DPL3_DIV_CTRL_div_en_mask               (0x2)
#define DPRX14_PLL_DPL3_DIV_CTRL_div_en(data)              (0x2&((data)<<1))
#define DPRX14_PLL_DPL3_DIV_CTRL_div_en_src(data)          ((0x2&(data))>>1)
#define DPRX14_PLL_DPL3_DIV_CTRL_get_div_en(data)          ((0x2&(data))>>1)
//this->default: DPRX14_PLL_DPL3_DIV_CTRL_div_en           0x0
#define DPRX14_PLL_DPL3_DIV_CTRL_div_rstn_shift              (0)
#define DPRX14_PLL_DPL3_DIV_CTRL_div_rstn_mask               (0x1)
#define DPRX14_PLL_DPL3_DIV_CTRL_div_rstn(data)              (0x1&((data)<<0))
#define DPRX14_PLL_DPL3_DIV_CTRL_div_rstn_src(data)          ((0x1&(data))>>0)
#define DPRX14_PLL_DPL3_DIV_CTRL_get_div_rstn(data)          ((0x1&(data))>>0)
//this->default: DPRX14_PLL_DPL3_DIV_CTRL_div_rstn           0x0

#define DPRX14_PLL_PIX2_DIV_STATUS                        0x4c4
#define DPRX14_PLL_PIX2_DIV_STATUS_reg_addr               "0x981654c4"
#define DPRX14_PLL_PIX2_DIV_STATUS_clkdet_done_shift              (28)
#define DPRX14_PLL_PIX2_DIV_STATUS_clkdet_done_mask               (0x10000000)
#define DPRX14_PLL_PIX2_DIV_STATUS_clkdet_done(data)              (0x10000000&((data)<<28))
#define DPRX14_PLL_PIX2_DIV_STATUS_clkdet_done_src(data)          ((0x10000000&(data))>>28)
#define DPRX14_PLL_PIX2_DIV_STATUS_get_clkdet_done(data)          ((0x10000000&(data))>>28)
//this->default: DPRX14_PLL_PIX2_DIV_STATUS_clkdet_done           0x0
#define DPRX14_PLL_PIX2_DIV_STATUS_clk_count_shift              (11)
#define DPRX14_PLL_PIX2_DIV_STATUS_clk_count_mask               (0xffff800)
#define DPRX14_PLL_PIX2_DIV_STATUS_clk_count(data)              (0xffff800&((data)<<11))
#define DPRX14_PLL_PIX2_DIV_STATUS_clk_count_src(data)          ((0xffff800&(data))>>11)
#define DPRX14_PLL_PIX2_DIV_STATUS_get_clk_count(data)          ((0xffff800&(data))>>11)
//this->default: DPRX14_PLL_PIX2_DIV_STATUS_clk_count           0x0
#define DPRX14_PLL_PIX2_DIV_STATUS_refclk_count_shift              (0)
#define DPRX14_PLL_PIX2_DIV_STATUS_refclk_count_mask               (0x7ff)
#define DPRX14_PLL_PIX2_DIV_STATUS_refclk_count(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_PIX2_DIV_STATUS_refclk_count_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_PIX2_DIV_STATUS_get_refclk_count(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_PIX2_DIV_STATUS_refclk_count           0x0

#define DPRX14_PLL_RTRAN_DIV_STATUS                        0x4c8
#define DPRX14_PLL_RTRAN_DIV_STATUS_reg_addr               "0x981654c8"
#define DPRX14_PLL_RTRAN_DIV_STATUS_clkdet_done_shift              (28)
#define DPRX14_PLL_RTRAN_DIV_STATUS_clkdet_done_mask               (0x10000000)
#define DPRX14_PLL_RTRAN_DIV_STATUS_clkdet_done(data)              (0x10000000&((data)<<28))
#define DPRX14_PLL_RTRAN_DIV_STATUS_clkdet_done_src(data)          ((0x10000000&(data))>>28)
#define DPRX14_PLL_RTRAN_DIV_STATUS_get_clkdet_done(data)          ((0x10000000&(data))>>28)
//this->default: DPRX14_PLL_RTRAN_DIV_STATUS_clkdet_done           0x0
#define DPRX14_PLL_RTRAN_DIV_STATUS_clk_count_shift              (11)
#define DPRX14_PLL_RTRAN_DIV_STATUS_clk_count_mask               (0xffff800)
#define DPRX14_PLL_RTRAN_DIV_STATUS_clk_count(data)              (0xffff800&((data)<<11))
#define DPRX14_PLL_RTRAN_DIV_STATUS_clk_count_src(data)          ((0xffff800&(data))>>11)
#define DPRX14_PLL_RTRAN_DIV_STATUS_get_clk_count(data)          ((0xffff800&(data))>>11)
//this->default: DPRX14_PLL_RTRAN_DIV_STATUS_clk_count           0x0
#define DPRX14_PLL_RTRAN_DIV_STATUS_refclk_count_shift              (0)
#define DPRX14_PLL_RTRAN_DIV_STATUS_refclk_count_mask               (0x7ff)
#define DPRX14_PLL_RTRAN_DIV_STATUS_refclk_count(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_RTRAN_DIV_STATUS_refclk_count_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_RTRAN_DIV_STATUS_get_refclk_count(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_RTRAN_DIV_STATUS_refclk_count           0x0

#define DPRX14_PLL_GTRAN_DIV_STATUS                        0x4cc
#define DPRX14_PLL_GTRAN_DIV_STATUS_reg_addr               "0x981654cc"
#define DPRX14_PLL_GTRAN_DIV_STATUS_clkdet_done_shift              (28)
#define DPRX14_PLL_GTRAN_DIV_STATUS_clkdet_done_mask               (0x10000000)
#define DPRX14_PLL_GTRAN_DIV_STATUS_clkdet_done(data)              (0x10000000&((data)<<28))
#define DPRX14_PLL_GTRAN_DIV_STATUS_clkdet_done_src(data)          ((0x10000000&(data))>>28)
#define DPRX14_PLL_GTRAN_DIV_STATUS_get_clkdet_done(data)          ((0x10000000&(data))>>28)
//this->default: DPRX14_PLL_GTRAN_DIV_STATUS_clkdet_done           0x0
#define DPRX14_PLL_GTRAN_DIV_STATUS_clk_count_shift              (11)
#define DPRX14_PLL_GTRAN_DIV_STATUS_clk_count_mask               (0xffff800)
#define DPRX14_PLL_GTRAN_DIV_STATUS_clk_count(data)              (0xffff800&((data)<<11))
#define DPRX14_PLL_GTRAN_DIV_STATUS_clk_count_src(data)          ((0xffff800&(data))>>11)
#define DPRX14_PLL_GTRAN_DIV_STATUS_get_clk_count(data)          ((0xffff800&(data))>>11)
//this->default: DPRX14_PLL_GTRAN_DIV_STATUS_clk_count           0x0
#define DPRX14_PLL_GTRAN_DIV_STATUS_refclk_count_shift              (0)
#define DPRX14_PLL_GTRAN_DIV_STATUS_refclk_count_mask               (0x7ff)
#define DPRX14_PLL_GTRAN_DIV_STATUS_refclk_count(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_GTRAN_DIV_STATUS_refclk_count_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_GTRAN_DIV_STATUS_get_refclk_count(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_GTRAN_DIV_STATUS_refclk_count           0x0

#define DPRX14_PLL_BTRAN_DIV_STATUS                        0x4d0
#define DPRX14_PLL_BTRAN_DIV_STATUS_reg_addr               "0x981654d0"
#define DPRX14_PLL_BTRAN_DIV_STATUS_clkdet_done_shift              (28)
#define DPRX14_PLL_BTRAN_DIV_STATUS_clkdet_done_mask               (0x10000000)
#define DPRX14_PLL_BTRAN_DIV_STATUS_clkdet_done(data)              (0x10000000&((data)<<28))
#define DPRX14_PLL_BTRAN_DIV_STATUS_clkdet_done_src(data)          ((0x10000000&(data))>>28)
#define DPRX14_PLL_BTRAN_DIV_STATUS_get_clkdet_done(data)          ((0x10000000&(data))>>28)
//this->default: DPRX14_PLL_BTRAN_DIV_STATUS_clkdet_done           0x0
#define DPRX14_PLL_BTRAN_DIV_STATUS_clk_count_shift              (11)
#define DPRX14_PLL_BTRAN_DIV_STATUS_clk_count_mask               (0xffff800)
#define DPRX14_PLL_BTRAN_DIV_STATUS_clk_count(data)              (0xffff800&((data)<<11))
#define DPRX14_PLL_BTRAN_DIV_STATUS_clk_count_src(data)          ((0xffff800&(data))>>11)
#define DPRX14_PLL_BTRAN_DIV_STATUS_get_clk_count(data)          ((0xffff800&(data))>>11)
//this->default: DPRX14_PLL_BTRAN_DIV_STATUS_clk_count           0x0
#define DPRX14_PLL_BTRAN_DIV_STATUS_refclk_count_shift              (0)
#define DPRX14_PLL_BTRAN_DIV_STATUS_refclk_count_mask               (0x7ff)
#define DPRX14_PLL_BTRAN_DIV_STATUS_refclk_count(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_BTRAN_DIV_STATUS_refclk_count_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_BTRAN_DIV_STATUS_get_refclk_count(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_BTRAN_DIV_STATUS_refclk_count           0x0

#define DPRX14_PLL_CKTRAN_DIV_STATUS                        0x4d4
#define DPRX14_PLL_CKTRAN_DIV_STATUS_reg_addr               "0x981654d4"
#define DPRX14_PLL_CKTRAN_DIV_STATUS_clkdet_done_shift              (28)
#define DPRX14_PLL_CKTRAN_DIV_STATUS_clkdet_done_mask               (0x10000000)
#define DPRX14_PLL_CKTRAN_DIV_STATUS_clkdet_done(data)              (0x10000000&((data)<<28))
#define DPRX14_PLL_CKTRAN_DIV_STATUS_clkdet_done_src(data)          ((0x10000000&(data))>>28)
#define DPRX14_PLL_CKTRAN_DIV_STATUS_get_clkdet_done(data)          ((0x10000000&(data))>>28)
//this->default: DPRX14_PLL_CKTRAN_DIV_STATUS_clkdet_done           0x0
#define DPRX14_PLL_CKTRAN_DIV_STATUS_clk_count_shift              (11)
#define DPRX14_PLL_CKTRAN_DIV_STATUS_clk_count_mask               (0xffff800)
#define DPRX14_PLL_CKTRAN_DIV_STATUS_clk_count(data)              (0xffff800&((data)<<11))
#define DPRX14_PLL_CKTRAN_DIV_STATUS_clk_count_src(data)          ((0xffff800&(data))>>11)
#define DPRX14_PLL_CKTRAN_DIV_STATUS_get_clk_count(data)          ((0xffff800&(data))>>11)
//this->default: DPRX14_PLL_CKTRAN_DIV_STATUS_clk_count           0x0
#define DPRX14_PLL_CKTRAN_DIV_STATUS_refclk_count_shift              (0)
#define DPRX14_PLL_CKTRAN_DIV_STATUS_refclk_count_mask               (0x7ff)
#define DPRX14_PLL_CKTRAN_DIV_STATUS_refclk_count(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_CKTRAN_DIV_STATUS_refclk_count_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_CKTRAN_DIV_STATUS_get_refclk_count(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_CKTRAN_DIV_STATUS_refclk_count           0x0

#define DPRX14_PLL_DPL0_DIV_STATUS                        0x4d8
#define DPRX14_PLL_DPL0_DIV_STATUS_reg_addr               "0x981654d8"
#define DPRX14_PLL_DPL0_DIV_STATUS_clkdet_done_shift              (28)
#define DPRX14_PLL_DPL0_DIV_STATUS_clkdet_done_mask               (0x10000000)
#define DPRX14_PLL_DPL0_DIV_STATUS_clkdet_done(data)              (0x10000000&((data)<<28))
#define DPRX14_PLL_DPL0_DIV_STATUS_clkdet_done_src(data)          ((0x10000000&(data))>>28)
#define DPRX14_PLL_DPL0_DIV_STATUS_get_clkdet_done(data)          ((0x10000000&(data))>>28)
//this->default: DPRX14_PLL_DPL0_DIV_STATUS_clkdet_done           0x0
#define DPRX14_PLL_DPL0_DIV_STATUS_clk_count_shift              (11)
#define DPRX14_PLL_DPL0_DIV_STATUS_clk_count_mask               (0xffff800)
#define DPRX14_PLL_DPL0_DIV_STATUS_clk_count(data)              (0xffff800&((data)<<11))
#define DPRX14_PLL_DPL0_DIV_STATUS_clk_count_src(data)          ((0xffff800&(data))>>11)
#define DPRX14_PLL_DPL0_DIV_STATUS_get_clk_count(data)          ((0xffff800&(data))>>11)
//this->default: DPRX14_PLL_DPL0_DIV_STATUS_clk_count           0x0
#define DPRX14_PLL_DPL0_DIV_STATUS_refclk_count_shift              (0)
#define DPRX14_PLL_DPL0_DIV_STATUS_refclk_count_mask               (0x7ff)
#define DPRX14_PLL_DPL0_DIV_STATUS_refclk_count(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_DPL0_DIV_STATUS_refclk_count_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_DPL0_DIV_STATUS_get_refclk_count(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_DPL0_DIV_STATUS_refclk_count           0x0

#define DPRX14_PLL_DPL1_DIV_STATUS                        0x4dc
#define DPRX14_PLL_DPL1_DIV_STATUS_reg_addr               "0x981654dc"
#define DPRX14_PLL_DPL1_DIV_STATUS_clkdet_done_shift              (28)
#define DPRX14_PLL_DPL1_DIV_STATUS_clkdet_done_mask               (0x10000000)
#define DPRX14_PLL_DPL1_DIV_STATUS_clkdet_done(data)              (0x10000000&((data)<<28))
#define DPRX14_PLL_DPL1_DIV_STATUS_clkdet_done_src(data)          ((0x10000000&(data))>>28)
#define DPRX14_PLL_DPL1_DIV_STATUS_get_clkdet_done(data)          ((0x10000000&(data))>>28)
//this->default: DPRX14_PLL_DPL1_DIV_STATUS_clkdet_done           0x0
#define DPRX14_PLL_DPL1_DIV_STATUS_clk_count_shift              (11)
#define DPRX14_PLL_DPL1_DIV_STATUS_clk_count_mask               (0xffff800)
#define DPRX14_PLL_DPL1_DIV_STATUS_clk_count(data)              (0xffff800&((data)<<11))
#define DPRX14_PLL_DPL1_DIV_STATUS_clk_count_src(data)          ((0xffff800&(data))>>11)
#define DPRX14_PLL_DPL1_DIV_STATUS_get_clk_count(data)          ((0xffff800&(data))>>11)
//this->default: DPRX14_PLL_DPL1_DIV_STATUS_clk_count           0x0
#define DPRX14_PLL_DPL1_DIV_STATUS_refclk_count_shift              (0)
#define DPRX14_PLL_DPL1_DIV_STATUS_refclk_count_mask               (0x7ff)
#define DPRX14_PLL_DPL1_DIV_STATUS_refclk_count(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_DPL1_DIV_STATUS_refclk_count_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_DPL1_DIV_STATUS_get_refclk_count(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_DPL1_DIV_STATUS_refclk_count           0x0

#define DPRX14_PLL_DPL2_DIV_STATUS                        0x4e0
#define DPRX14_PLL_DPL2_DIV_STATUS_reg_addr               "0x981654e0"
#define DPRX14_PLL_DPL2_DIV_STATUS_clkdet_done_shift              (28)
#define DPRX14_PLL_DPL2_DIV_STATUS_clkdet_done_mask               (0x10000000)
#define DPRX14_PLL_DPL2_DIV_STATUS_clkdet_done(data)              (0x10000000&((data)<<28))
#define DPRX14_PLL_DPL2_DIV_STATUS_clkdet_done_src(data)          ((0x10000000&(data))>>28)
#define DPRX14_PLL_DPL2_DIV_STATUS_get_clkdet_done(data)          ((0x10000000&(data))>>28)
//this->default: DPRX14_PLL_DPL2_DIV_STATUS_clkdet_done           0x0
#define DPRX14_PLL_DPL2_DIV_STATUS_clk_count_shift              (11)
#define DPRX14_PLL_DPL2_DIV_STATUS_clk_count_mask               (0xffff800)
#define DPRX14_PLL_DPL2_DIV_STATUS_clk_count(data)              (0xffff800&((data)<<11))
#define DPRX14_PLL_DPL2_DIV_STATUS_clk_count_src(data)          ((0xffff800&(data))>>11)
#define DPRX14_PLL_DPL2_DIV_STATUS_get_clk_count(data)          ((0xffff800&(data))>>11)
//this->default: DPRX14_PLL_DPL2_DIV_STATUS_clk_count           0x0
#define DPRX14_PLL_DPL2_DIV_STATUS_refclk_count_shift              (0)
#define DPRX14_PLL_DPL2_DIV_STATUS_refclk_count_mask               (0x7ff)
#define DPRX14_PLL_DPL2_DIV_STATUS_refclk_count(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_DPL2_DIV_STATUS_refclk_count_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_DPL2_DIV_STATUS_get_refclk_count(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_DPL2_DIV_STATUS_refclk_count           0x0

#define DPRX14_PLL_DPL3_DIV_STATUS                        0x4e4
#define DPRX14_PLL_DPL3_DIV_STATUS_reg_addr               "0x981654e4"
#define DPRX14_PLL_DPL3_DIV_STATUS_clkdet_done_shift              (28)
#define DPRX14_PLL_DPL3_DIV_STATUS_clkdet_done_mask               (0x10000000)
#define DPRX14_PLL_DPL3_DIV_STATUS_clkdet_done(data)              (0x10000000&((data)<<28))
#define DPRX14_PLL_DPL3_DIV_STATUS_clkdet_done_src(data)          ((0x10000000&(data))>>28)
#define DPRX14_PLL_DPL3_DIV_STATUS_get_clkdet_done(data)          ((0x10000000&(data))>>28)
//this->default: DPRX14_PLL_DPL3_DIV_STATUS_clkdet_done           0x0
#define DPRX14_PLL_DPL3_DIV_STATUS_clk_count_shift              (11)
#define DPRX14_PLL_DPL3_DIV_STATUS_clk_count_mask               (0xffff800)
#define DPRX14_PLL_DPL3_DIV_STATUS_clk_count(data)              (0xffff800&((data)<<11))
#define DPRX14_PLL_DPL3_DIV_STATUS_clk_count_src(data)          ((0xffff800&(data))>>11)
#define DPRX14_PLL_DPL3_DIV_STATUS_get_clk_count(data)          ((0xffff800&(data))>>11)
//this->default: DPRX14_PLL_DPL3_DIV_STATUS_clk_count           0x0
#define DPRX14_PLL_DPL3_DIV_STATUS_refclk_count_shift              (0)
#define DPRX14_PLL_DPL3_DIV_STATUS_refclk_count_mask               (0x7ff)
#define DPRX14_PLL_DPL3_DIV_STATUS_refclk_count(data)              (0x7ff&((data)<<0))
#define DPRX14_PLL_DPL3_DIV_STATUS_refclk_count_src(data)          ((0x7ff&(data))>>0)
#define DPRX14_PLL_DPL3_DIV_STATUS_get_refclk_count(data)          ((0x7ff&(data))>>0)
//this->default: DPRX14_PLL_DPL3_DIV_STATUS_refclk_count           0x0

#endif
