/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef _DPRX14_DDC_REG_H_INCLUDED_
#define _DPRX14_DDC_REG_H_INCLUDED_

#define DPRX14_DDC1_I2C_CR                        0x600
#define DPRX14_DDC1_I2C_CR_reg_addr               "0x98165600"
#define DPRX14_DDC1_I2C_CR_CMDERR_IE_shift              (7)
#define DPRX14_DDC1_I2C_CR_CMDERR_IE_mask               (0x80)
#define DPRX14_DDC1_I2C_CR_CMDERR_IE(data)              (0x80&((data)<<7))
#define DPRX14_DDC1_I2C_CR_CMDERR_IE_src(data)          ((0x80&(data))>>7)
#define DPRX14_DDC1_I2C_CR_get_CMDERR_IE(data)          ((0x80&(data))>>7)
//this->default: DPRX14_DDC1_I2C_CR_CMDERR_IE           0x0
#define DPRX14_DDC1_I2C_CR_TIMEOUT_EN_shift              (6)
#define DPRX14_DDC1_I2C_CR_TIMEOUT_EN_mask               (0x40)
#define DPRX14_DDC1_I2C_CR_TIMEOUT_EN(data)              (0x40&((data)<<6))
#define DPRX14_DDC1_I2C_CR_TIMEOUT_EN_src(data)          ((0x40&(data))>>6)
#define DPRX14_DDC1_I2C_CR_get_TIMEOUT_EN(data)          ((0x40&(data))>>6)
//this->default: DPRX14_DDC1_I2C_CR_TIMEOUT_EN           0x0
#define DPRX14_DDC1_I2C_CR_DEBOUNCE_MODE_shift              (4)
#define DPRX14_DDC1_I2C_CR_DEBOUNCE_MODE_mask               (0x30)
#define DPRX14_DDC1_I2C_CR_DEBOUNCE_MODE(data)              (0x30&((data)<<4))
#define DPRX14_DDC1_I2C_CR_DEBOUNCE_MODE_src(data)          ((0x30&(data))>>4)
#define DPRX14_DDC1_I2C_CR_get_DEBOUNCE_MODE(data)          ((0x30&(data))>>4)
//this->default: DPRX14_DDC1_I2C_CR_DEBOUNCE_MODE           0x0
#define DPRX14_DDC1_I2C_CR_TIMEOUT_IE_shift              (3)
#define DPRX14_DDC1_I2C_CR_TIMEOUT_IE_mask               (0x8)
#define DPRX14_DDC1_I2C_CR_TIMEOUT_IE(data)              (0x8&((data)<<3))
#define DPRX14_DDC1_I2C_CR_TIMEOUT_IE_src(data)          ((0x8&(data))>>3)
#define DPRX14_DDC1_I2C_CR_get_TIMEOUT_IE(data)          ((0x8&(data))>>3)
//this->default: DPRX14_DDC1_I2C_CR_TIMEOUT_IE           0x0
#define DPRX14_DDC1_I2C_CR_RETIME_M_shift              (0)
#define DPRX14_DDC1_I2C_CR_RETIME_M_mask               (0x7)
#define DPRX14_DDC1_I2C_CR_RETIME_M(data)              (0x7&((data)<<0))
#define DPRX14_DDC1_I2C_CR_RETIME_M_src(data)          ((0x7&(data))>>0)
#define DPRX14_DDC1_I2C_CR_get_RETIME_M(data)          ((0x7&(data))>>0)
//this->default: DPRX14_DDC1_I2C_CR_RETIME_M           0x0

#define DPRX14_DDC1_I2C_SR1                        0x604
#define DPRX14_DDC1_I2C_SR1_reg_addr               "0x98165604"
#define DPRX14_DDC1_I2C_SR1_CMDERR_shift              (7)
#define DPRX14_DDC1_I2C_SR1_CMDERR_mask               (0x80)
#define DPRX14_DDC1_I2C_SR1_CMDERR(data)              (0x80&((data)<<7))
#define DPRX14_DDC1_I2C_SR1_CMDERR_src(data)          ((0x80&(data))>>7)
#define DPRX14_DDC1_I2C_SR1_get_CMDERR(data)          ((0x80&(data))>>7)
//this->default: DPRX14_DDC1_I2C_SR1_CMDERR           0x0
#define DPRX14_DDC1_I2C_SR1_Finish_shift              (4)
#define DPRX14_DDC1_I2C_SR1_Finish_mask               (0x10)
#define DPRX14_DDC1_I2C_SR1_Finish(data)              (0x10&((data)<<4))
#define DPRX14_DDC1_I2C_SR1_Finish_src(data)          ((0x10&(data))>>4)
#define DPRX14_DDC1_I2C_SR1_get_Finish(data)          ((0x10&(data))>>4)
//this->default: DPRX14_DDC1_I2C_SR1_Finish           0x0
#define DPRX14_DDC1_I2C_SR1_timeout_shift              (3)
#define DPRX14_DDC1_I2C_SR1_timeout_mask               (0x8)
#define DPRX14_DDC1_I2C_SR1_timeout(data)              (0x8&((data)<<3))
#define DPRX14_DDC1_I2C_SR1_timeout_src(data)          ((0x8&(data))>>3)
#define DPRX14_DDC1_I2C_SR1_get_timeout(data)          ((0x8&(data))>>3)
//this->default: DPRX14_DDC1_I2C_SR1_timeout           0x0

#define DPRX14_DDC1_I2C_TR                        0x608
#define DPRX14_DDC1_I2C_TR_reg_addr               "0x98165608"
#define DPRX14_DDC1_I2C_TR_timeout_val_shift              (0)
#define DPRX14_DDC1_I2C_TR_timeout_val_mask               (0xff)
#define DPRX14_DDC1_I2C_TR_timeout_val(data)              (0xff&((data)<<0))
#define DPRX14_DDC1_I2C_TR_timeout_val_src(data)          ((0xff&(data))>>0)
#define DPRX14_DDC1_I2C_TR_get_timeout_val(data)          ((0xff&(data))>>0)
//this->default: DPRX14_DDC1_I2C_TR_timeout_val           0x0

#define DPRX14_DDC1_EDID_CR                        0x60c
#define DPRX14_DDC1_EDID_CR_reg_addr               "0x9816560c"
#define DPRX14_DDC1_EDID_CR_EDID_ADDRESS_shift              (5)
#define DPRX14_DDC1_EDID_CR_EDID_ADDRESS_mask               (0xe0)
#define DPRX14_DDC1_EDID_CR_EDID_ADDRESS(data)              (0xe0&((data)<<5))
#define DPRX14_DDC1_EDID_CR_EDID_ADDRESS_src(data)          ((0xe0&(data))>>5)
#define DPRX14_DDC1_EDID_CR_get_EDID_ADDRESS(data)          ((0xe0&(data))>>5)
//this->default: DPRX14_DDC1_EDID_CR_EDID_ADDRESS           0x0
#define DPRX14_DDC1_EDID_CR_FINISH_INT_EN_shift              (4)
#define DPRX14_DDC1_EDID_CR_FINISH_INT_EN_mask               (0x10)
#define DPRX14_DDC1_EDID_CR_FINISH_INT_EN(data)              (0x10&((data)<<4))
#define DPRX14_DDC1_EDID_CR_FINISH_INT_EN_src(data)          ((0x10&(data))>>4)
#define DPRX14_DDC1_EDID_CR_get_FINISH_INT_EN(data)          ((0x10&(data))>>4)
//this->default: DPRX14_DDC1_EDID_CR_FINISH_INT_EN           0x0
#define DPRX14_DDC1_EDID_CR_DDC1_FORCE_shift              (3)
#define DPRX14_DDC1_EDID_CR_DDC1_FORCE_mask               (0x8)
#define DPRX14_DDC1_EDID_CR_DDC1_FORCE(data)              (0x8&((data)<<3))
#define DPRX14_DDC1_EDID_CR_DDC1_FORCE_src(data)          ((0x8&(data))>>3)
#define DPRX14_DDC1_EDID_CR_get_DDC1_FORCE(data)          ((0x8&(data))>>3)
//this->default: DPRX14_DDC1_EDID_CR_DDC1_FORCE           0x0
#define DPRX14_DDC1_EDID_CR_DDC2B_FORCE_shift              (2)
#define DPRX14_DDC1_EDID_CR_DDC2B_FORCE_mask               (0x4)
#define DPRX14_DDC1_EDID_CR_DDC2B_FORCE(data)              (0x4&((data)<<2))
#define DPRX14_DDC1_EDID_CR_DDC2B_FORCE_src(data)          ((0x4&(data))>>2)
#define DPRX14_DDC1_EDID_CR_get_DDC2B_FORCE(data)          ((0x4&(data))>>2)
//this->default: DPRX14_DDC1_EDID_CR_DDC2B_FORCE           0x0
#define DPRX14_DDC1_EDID_CR_EDID_SRWEN_shift              (1)
#define DPRX14_DDC1_EDID_CR_EDID_SRWEN_mask               (0x2)
#define DPRX14_DDC1_EDID_CR_EDID_SRWEN(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_EDID_CR_EDID_SRWEN_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_EDID_CR_get_EDID_SRWEN(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_EDID_CR_EDID_SRWEN           0x0
#define DPRX14_DDC1_EDID_CR_EDID_EN_shift              (0)
#define DPRX14_DDC1_EDID_CR_EDID_EN_mask               (0x1)
#define DPRX14_DDC1_EDID_CR_EDID_EN(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_EDID_CR_EDID_EN_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_EDID_CR_get_EDID_EN(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_EDID_CR_EDID_EN           0x0

#define DPRX14_DDC1_DDC_VCR                        0x610
#define DPRX14_DDC1_DDC_VCR_reg_addr               "0x98165610"
#define DPRX14_DDC1_DDC_VCR_DDC1_VCount_shift              (0)
#define DPRX14_DDC1_DDC_VCR_DDC1_VCount_mask               (0xff)
#define DPRX14_DDC1_DDC_VCR_DDC1_VCount(data)              (0xff&((data)<<0))
#define DPRX14_DDC1_DDC_VCR_DDC1_VCount_src(data)          ((0xff&(data))>>0)
#define DPRX14_DDC1_DDC_VCR_get_DDC1_VCount(data)          ((0xff&(data))>>0)
//this->default: DPRX14_DDC1_DDC_VCR_DDC1_VCount           0x80

#define DPRX14_DDC1_EDID_IMSWSAR                        0x614
#define DPRX14_DDC1_EDID_IMSWSAR_reg_addr               "0x98165614"
#define DPRX14_DDC1_EDID_IMSWSAR_EDID_SADR_shift              (0)
#define DPRX14_DDC1_EDID_IMSWSAR_EDID_SADR_mask               (0x1ff)
#define DPRX14_DDC1_EDID_IMSWSAR_EDID_SADR(data)              (0x1ff&((data)<<0))
#define DPRX14_DDC1_EDID_IMSWSAR_EDID_SADR_src(data)          ((0x1ff&(data))>>0)
#define DPRX14_DDC1_EDID_IMSWSAR_get_EDID_SADR(data)          ((0x1ff&(data))>>0)
//this->default: DPRX14_DDC1_EDID_IMSWSAR_EDID_SADR           0x0

#define DPRX14_DDC1_EDID_IMSWEAR                        0x618
#define DPRX14_DDC1_EDID_IMSWEAR_reg_addr               "0x98165618"
#define DPRX14_DDC1_EDID_IMSWEAR_EDID_EADR_shift              (0)
#define DPRX14_DDC1_EDID_IMSWEAR_EDID_EADR_mask               (0x1ff)
#define DPRX14_DDC1_EDID_IMSWEAR_EDID_EADR(data)              (0x1ff&((data)<<0))
#define DPRX14_DDC1_EDID_IMSWEAR_EDID_EADR_src(data)          ((0x1ff&(data))>>0)
#define DPRX14_DDC1_EDID_IMSWEAR_get_EDID_EADR(data)          ((0x1ff&(data))>>0)
//this->default: DPRX14_DDC1_EDID_IMSWEAR_EDID_EADR           0x0

#define DPRX14_DDC1_EDID_IR                        0x61c
#define DPRX14_DDC1_EDID_IR_reg_addr               "0x9816561c"
#define DPRX14_DDC1_EDID_IR_EDIDMODE_shift              (6)
#define DPRX14_DDC1_EDID_IR_EDIDMODE_mask               (0x40)
#define DPRX14_DDC1_EDID_IR_EDIDMODE(data)              (0x40&((data)<<6))
#define DPRX14_DDC1_EDID_IR_EDIDMODE_src(data)          ((0x40&(data))>>6)
#define DPRX14_DDC1_EDID_IR_get_EDIDMODE(data)          ((0x40&(data))>>6)
//this->default: DPRX14_DDC1_EDID_IR_EDIDMODE           0x0
#define DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS_shift              (5)
#define DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS_mask               (0x20)
#define DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS(data)              (0x20&((data)<<5))
#define DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS_src(data)          ((0x20&(data))>>5)
#define DPRX14_DDC1_EDID_IR_get_EDIDSUBADDRESS(data)          ((0x20&(data))>>5)
//this->default: DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS           0x0
#define DPRX14_DDC1_EDID_IR_EDIDSTOP_shift              (4)
#define DPRX14_DDC1_EDID_IR_EDIDSTOP_mask               (0x10)
#define DPRX14_DDC1_EDID_IR_EDIDSTOP(data)              (0x10&((data)<<4))
#define DPRX14_DDC1_EDID_IR_EDIDSTOP_src(data)          ((0x10&(data))>>4)
#define DPRX14_DDC1_EDID_IR_get_EDIDSTOP(data)          ((0x10&(data))>>4)
//this->default: DPRX14_DDC1_EDID_IR_EDIDSTOP           0x0
#define DPRX14_DDC1_EDID_IR_I2C_M_RD_ST_IE_shift              (3)
#define DPRX14_DDC1_EDID_IR_I2C_M_RD_ST_IE_mask               (0x8)
#define DPRX14_DDC1_EDID_IR_I2C_M_RD_ST_IE(data)              (0x8&((data)<<3))
#define DPRX14_DDC1_EDID_IR_I2C_M_RD_ST_IE_src(data)          ((0x8&(data))>>3)
#define DPRX14_DDC1_EDID_IR_get_I2C_M_RD_ST_IE(data)          ((0x8&(data))>>3)
//this->default: DPRX14_DDC1_EDID_IR_I2C_M_RD_ST_IE           0x0
#define DPRX14_DDC1_EDID_IR_I2C_M_RD_SP_IE_shift              (2)
#define DPRX14_DDC1_EDID_IR_I2C_M_RD_SP_IE_mask               (0x4)
#define DPRX14_DDC1_EDID_IR_I2C_M_RD_SP_IE(data)              (0x4&((data)<<2))
#define DPRX14_DDC1_EDID_IR_I2C_M_RD_SP_IE_src(data)          ((0x4&(data))>>2)
#define DPRX14_DDC1_EDID_IR_get_I2C_M_RD_SP_IE(data)          ((0x4&(data))>>2)
//this->default: DPRX14_DDC1_EDID_IR_I2C_M_RD_SP_IE           0x0
#define DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS_IE_shift              (1)
#define DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS_IE_mask               (0x2)
#define DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS_IE(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS_IE_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_EDID_IR_get_EDIDSUBADDRESS_IE(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_EDID_IR_EDIDSUBADDRESS_IE           0x0
#define DPRX14_DDC1_EDID_IR_EDIDSTOP_IE_shift              (0)
#define DPRX14_DDC1_EDID_IR_EDIDSTOP_IE_mask               (0x1)
#define DPRX14_DDC1_EDID_IR_EDIDSTOP_IE(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_EDID_IR_EDIDSTOP_IE_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_EDID_IR_get_EDIDSTOP_IE(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_EDID_IR_EDIDSTOP_IE           0x0

#define DPRX14_DDC1_DDC_SIR                        0x620
#define DPRX14_DDC1_DDC_SIR_reg_addr               "0x98165620"
#define DPRX14_DDC1_DDC_SIR_EDIDAP_shift              (0)
#define DPRX14_DDC1_DDC_SIR_EDIDAP_mask               (0x1ff)
#define DPRX14_DDC1_DDC_SIR_EDIDAP(data)              (0x1ff&((data)<<0))
#define DPRX14_DDC1_DDC_SIR_EDIDAP_src(data)          ((0x1ff&(data))>>0)
#define DPRX14_DDC1_DDC_SIR_get_EDIDAP(data)          ((0x1ff&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SIR_EDIDAP           0x0

#define DPRX14_DDC1_DDC_SAP                        0x624
#define DPRX14_DDC1_DDC_SAP_reg_addr               "0x98165624"
#define DPRX14_DDC1_DDC_SAP_EDIDDP_shift              (0)
#define DPRX14_DDC1_DDC_SAP_EDIDDP_mask               (0xff)
#define DPRX14_DDC1_DDC_SAP_EDIDDP(data)              (0xff&((data)<<0))
#define DPRX14_DDC1_DDC_SAP_EDIDDP_src(data)          ((0xff&(data))>>0)
#define DPRX14_DDC1_DDC_SAP_get_EDIDDP(data)          ((0xff&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SAP_EDIDDP           0x0

#define DPRX14_DDC1_DDC_BISTCR                        0x628
#define DPRX14_DDC1_DDC_BISTCR_reg_addr               "0x98165628"
#define DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RME_shift              (4)
#define DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RME_mask               (0x10)
#define DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RME(data)              (0x10&((data)<<4))
#define DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RME_src(data)          ((0x10&(data))>>4)
#define DPRX14_DDC1_DDC_BISTCR_get_DDC_BIST_RME(data)          ((0x10&(data))>>4)
//this->default: DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RME           0x0
#define DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RM_shift              (0)
#define DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RM_mask               (0xf)
#define DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RM(data)              (0xf&((data)<<0))
#define DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RM_src(data)          ((0xf&(data))>>0)
#define DPRX14_DDC1_DDC_BISTCR_get_DDC_BIST_RM(data)          ((0xf&(data))>>0)
//this->default: DPRX14_DDC1_DDC_BISTCR_DDC_BIST_RM           0x0

#define DPRX14_DDC1_DDC_SCR                        0x62c
#define DPRX14_DDC1_DDC_SCR_reg_addr               "0x9816562c"
#define DPRX14_DDC1_DDC_SCR_SEGPT_LATIE_shift              (7)
#define DPRX14_DDC1_DDC_SCR_SEGPT_LATIE_mask               (0x80)
#define DPRX14_DDC1_DDC_SCR_SEGPT_LATIE(data)              (0x80&((data)<<7))
#define DPRX14_DDC1_DDC_SCR_SEGPT_LATIE_src(data)          ((0x80&(data))>>7)
#define DPRX14_DDC1_DDC_SCR_get_SEGPT_LATIE(data)          ((0x80&(data))>>7)
//this->default: DPRX14_DDC1_DDC_SCR_SEGPT_LATIE           0x0
#define DPRX14_DDC1_DDC_SCR_Dataoutputdelay_sel_shift              (4)
#define DPRX14_DDC1_DDC_SCR_Dataoutputdelay_sel_mask               (0x70)
#define DPRX14_DDC1_DDC_SCR_Dataoutputdelay_sel(data)              (0x70&((data)<<4))
#define DPRX14_DDC1_DDC_SCR_Dataoutputdelay_sel_src(data)          ((0x70&(data))>>4)
#define DPRX14_DDC1_DDC_SCR_get_Dataoutputdelay_sel(data)          ((0x70&(data))>>4)
//this->default: DPRX14_DDC1_DDC_SCR_Dataoutputdelay_sel           0x0
#define DPRX14_DDC1_DDC_SCR_I2C_M_RD_ST_STS_shift              (2)
#define DPRX14_DDC1_DDC_SCR_I2C_M_RD_ST_STS_mask               (0x4)
#define DPRX14_DDC1_DDC_SCR_I2C_M_RD_ST_STS(data)              (0x4&((data)<<2))
#define DPRX14_DDC1_DDC_SCR_I2C_M_RD_ST_STS_src(data)          ((0x4&(data))>>2)
#define DPRX14_DDC1_DDC_SCR_get_I2C_M_RD_ST_STS(data)          ((0x4&(data))>>2)
//this->default: DPRX14_DDC1_DDC_SCR_I2C_M_RD_ST_STS           0x0
#define DPRX14_DDC1_DDC_SCR_I2C_M_RD_SP_STS_shift              (1)
#define DPRX14_DDC1_DDC_SCR_I2C_M_RD_SP_STS_mask               (0x2)
#define DPRX14_DDC1_DDC_SCR_I2C_M_RD_SP_STS(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_DDC_SCR_I2C_M_RD_SP_STS_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_DDC_SCR_get_I2C_M_RD_SP_STS(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_DDC_SCR_I2C_M_RD_SP_STS           0x0
#define DPRX14_DDC1_DDC_SCR_SGID_EN_shift              (0)
#define DPRX14_DDC1_DDC_SCR_SGID_EN_mask               (0x1)
#define DPRX14_DDC1_DDC_SCR_SGID_EN(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_SCR_SGID_EN_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_SCR_get_SGID_EN(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SCR_SGID_EN           0x0

#define DPRX14_DDC1_DDC_SSAR                        0x630
#define DPRX14_DDC1_DDC_SSAR_reg_addr               "0x98165630"
#define DPRX14_DDC1_DDC_SSAR_SGID_ADDRESS_shift              (1)
#define DPRX14_DDC1_DDC_SSAR_SGID_ADDRESS_mask               (0xfe)
#define DPRX14_DDC1_DDC_SSAR_SGID_ADDRESS(data)              (0xfe&((data)<<1))
#define DPRX14_DDC1_DDC_SSAR_SGID_ADDRESS_src(data)          ((0xfe&(data))>>1)
#define DPRX14_DDC1_DDC_SSAR_get_SGID_ADDRESS(data)          ((0xfe&(data))>>1)
//this->default: DPRX14_DDC1_DDC_SSAR_SGID_ADDRESS           0x30
#define DPRX14_DDC1_DDC_SSAR_SGID_DTRDEN_shift              (0)
#define DPRX14_DDC1_DDC_SSAR_SGID_DTRDEN_mask               (0x1)
#define DPRX14_DDC1_DDC_SSAR_SGID_DTRDEN(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_SSAR_SGID_DTRDEN_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_SSAR_get_SGID_DTRDEN(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SSAR_SGID_DTRDEN           0x0

#define DPRX14_DDC1_DDC_SPR                        0x634
#define DPRX14_DDC1_DDC_SPR_reg_addr               "0x98165634"
#define DPRX14_DDC1_DDC_SPR_SEGPT_LATCHED_shift              (7)
#define DPRX14_DDC1_DDC_SPR_SEGPT_LATCHED_mask               (0x80)
#define DPRX14_DDC1_DDC_SPR_SEGPT_LATCHED(data)              (0x80&((data)<<7))
#define DPRX14_DDC1_DDC_SPR_SEGPT_LATCHED_src(data)          ((0x80&(data))>>7)
#define DPRX14_DDC1_DDC_SPR_get_SEGPT_LATCHED(data)          ((0x80&(data))>>7)
//this->default: DPRX14_DDC1_DDC_SPR_SEGPT_LATCHED           0x0
#define DPRX14_DDC1_DDC_SPR_SEG_PT_shift              (0)
#define DPRX14_DDC1_DDC_SPR_SEG_PT_mask               (0x7f)
#define DPRX14_DDC1_DDC_SPR_SEG_PT(data)              (0x7f&((data)<<0))
#define DPRX14_DDC1_DDC_SPR_SEG_PT_src(data)          ((0x7f&(data))>>0)
#define DPRX14_DDC1_DDC_SPR_get_SEG_PT(data)          ((0x7f&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SPR_SEG_PT           0x0

#define DPRX14_DDC1_DDC_SFCR                        0x638
#define DPRX14_DDC1_DDC_SFCR_reg_addr               "0x98165638"
#define DPRX14_DDC1_DDC_SFCR_SPECIAL_MODE_shift              (3)
#define DPRX14_DDC1_DDC_SFCR_SPECIAL_MODE_mask               (0x8)
#define DPRX14_DDC1_DDC_SFCR_SPECIAL_MODE(data)              (0x8&((data)<<3))
#define DPRX14_DDC1_DDC_SFCR_SPECIAL_MODE_src(data)          ((0x8&(data))>>3)
#define DPRX14_DDC1_DDC_SFCR_get_SPECIAL_MODE(data)          ((0x8&(data))>>3)
//this->default: DPRX14_DDC1_DDC_SFCR_SPECIAL_MODE           0x0
#define DPRX14_DDC1_DDC_SFCR_DOFFPT_RESET_shift              (2)
#define DPRX14_DDC1_DDC_SFCR_DOFFPT_RESET_mask               (0x4)
#define DPRX14_DDC1_DDC_SFCR_DOFFPT_RESET(data)              (0x4&((data)<<2))
#define DPRX14_DDC1_DDC_SFCR_DOFFPT_RESET_src(data)          ((0x4&(data))>>2)
#define DPRX14_DDC1_DDC_SFCR_get_DOFFPT_RESET(data)          ((0x4&(data))>>2)
//this->default: DPRX14_DDC1_DDC_SFCR_DOFFPT_RESET           0x0
#define DPRX14_DDC1_DDC_SFCR_DIFFPT_RESET_shift              (1)
#define DPRX14_DDC1_DDC_SFCR_DIFFPT_RESET_mask               (0x2)
#define DPRX14_DDC1_DDC_SFCR_DIFFPT_RESET(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_DDC_SFCR_DIFFPT_RESET_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_DDC_SFCR_get_DIFFPT_RESET(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_DDC_SFCR_DIFFPT_RESET           0x0
#define DPRX14_DDC1_DDC_SFCR_CIID_EN_shift              (0)
#define DPRX14_DDC1_DDC_SFCR_CIID_EN_mask               (0x1)
#define DPRX14_DDC1_DDC_SFCR_CIID_EN(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_SFCR_CIID_EN_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_SFCR_get_CIID_EN(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFCR_CIID_EN           0x0

#define DPRX14_DDC1_DDC_SFSAR                        0x63c
#define DPRX14_DDC1_DDC_SFSAR_reg_addr               "0x9816563c"
#define DPRX14_DDC1_DDC_SFSAR_CIID_ADDRESS_shift              (1)
#define DPRX14_DDC1_DDC_SFSAR_CIID_ADDRESS_mask               (0xfe)
#define DPRX14_DDC1_DDC_SFSAR_CIID_ADDRESS(data)              (0xfe&((data)<<1))
#define DPRX14_DDC1_DDC_SFSAR_CIID_ADDRESS_src(data)          ((0xfe&(data))>>1)
#define DPRX14_DDC1_DDC_SFSAR_get_CIID_ADDRESS(data)          ((0xfe&(data))>>1)
//this->default: DPRX14_DDC1_DDC_SFSAR_CIID_ADDRESS           0x37
#define DPRX14_DDC1_DDC_SFSAR_CIRWS_CURRENT_shift              (0)
#define DPRX14_DDC1_DDC_SFSAR_CIRWS_CURRENT_mask               (0x1)
#define DPRX14_DDC1_DDC_SFSAR_CIRWS_CURRENT(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_SFSAR_CIRWS_CURRENT_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_SFSAR_get_CIRWS_CURRENT(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFSAR_CIRWS_CURRENT           0x0

#define DPRX14_DDC1_DDC_SFDR                        0x640
#define DPRX14_DDC1_DDC_SFDR_reg_addr               "0x98165640"
#define DPRX14_DDC1_DDC_SFDR_CIIDDP_shift              (0)
#define DPRX14_DDC1_DDC_SFDR_CIIDDP_mask               (0xff)
#define DPRX14_DDC1_DDC_SFDR_CIIDDP(data)              (0xff&((data)<<0))
#define DPRX14_DDC1_DDC_SFDR_CIIDDP_src(data)          ((0xff&(data))>>0)
#define DPRX14_DDC1_DDC_SFDR_get_CIIDDP(data)          ((0xff&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFDR_CIIDDP           0x0

#define DPRX14_DDC1_DDC_SFBSR                        0x644
#define DPRX14_DDC1_DDC_SFBSR_reg_addr               "0x98165644"
#define DPRX14_DDC1_DDC_SFBSR_CIRWS_2ND_shift              (5)
#define DPRX14_DDC1_DDC_SFBSR_CIRWS_2ND_mask               (0x20)
#define DPRX14_DDC1_DDC_SFBSR_CIRWS_2ND(data)              (0x20&((data)<<5))
#define DPRX14_DDC1_DDC_SFBSR_CIRWS_2ND_src(data)          ((0x20&(data))>>5)
#define DPRX14_DDC1_DDC_SFBSR_get_CIRWS_2ND(data)          ((0x20&(data))>>5)
//this->default: DPRX14_DDC1_DDC_SFBSR_CIRWS_2ND           0x0
#define DPRX14_DDC1_DDC_SFBSR_CIRWS_1ST_shift              (4)
#define DPRX14_DDC1_DDC_SFBSR_CIRWS_1ST_mask               (0x10)
#define DPRX14_DDC1_DDC_SFBSR_CIRWS_1ST(data)              (0x10&((data)<<4))
#define DPRX14_DDC1_DDC_SFBSR_CIRWS_1ST_src(data)          ((0x10&(data))>>4)
#define DPRX14_DDC1_DDC_SFBSR_get_CIRWS_1ST(data)          ((0x10&(data))>>4)
//this->default: DPRX14_DDC1_DDC_SFBSR_CIRWS_1ST           0x0
#define DPRX14_DDC1_DDC_SFBSR_CIPPT_2ND_shift              (3)
#define DPRX14_DDC1_DDC_SFBSR_CIPPT_2ND_mask               (0x8)
#define DPRX14_DDC1_DDC_SFBSR_CIPPT_2ND(data)              (0x8&((data)<<3))
#define DPRX14_DDC1_DDC_SFBSR_CIPPT_2ND_src(data)          ((0x8&(data))>>3)
#define DPRX14_DDC1_DDC_SFBSR_get_CIPPT_2ND(data)          ((0x8&(data))>>3)
//this->default: DPRX14_DDC1_DDC_SFBSR_CIPPT_2ND           0x0
#define DPRX14_DDC1_DDC_SFBSR_CISPT_2ND_shift              (2)
#define DPRX14_DDC1_DDC_SFBSR_CISPT_2ND_mask               (0x4)
#define DPRX14_DDC1_DDC_SFBSR_CISPT_2ND(data)              (0x4&((data)<<2))
#define DPRX14_DDC1_DDC_SFBSR_CISPT_2ND_src(data)          ((0x4&(data))>>2)
#define DPRX14_DDC1_DDC_SFBSR_get_CISPT_2ND(data)          ((0x4&(data))>>2)
//this->default: DPRX14_DDC1_DDC_SFBSR_CISPT_2ND           0x0
#define DPRX14_DDC1_DDC_SFBSR_CIPPT_1ST_shift              (1)
#define DPRX14_DDC1_DDC_SFBSR_CIPPT_1ST_mask               (0x2)
#define DPRX14_DDC1_DDC_SFBSR_CIPPT_1ST(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_DDC_SFBSR_CIPPT_1ST_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_DDC_SFBSR_get_CIPPT_1ST(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_DDC_SFBSR_CIPPT_1ST           0x0
#define DPRX14_DDC1_DDC_SFBSR_CISPT_1ST_shift              (0)
#define DPRX14_DDC1_DDC_SFBSR_CISPT_1ST_mask               (0x1)
#define DPRX14_DDC1_DDC_SFBSR_CISPT_1ST(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_SFBSR_CISPT_1ST_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_SFBSR_get_CISPT_1ST(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFBSR_CISPT_1ST           0x0

#define DPRX14_DDC1_DDC_SFIBLR                        0x648
#define DPRX14_DDC1_DDC_SFIBLR_reg_addr               "0x98165648"
#define DPRX14_DDC1_DDC_SFIBLR_FFDI_DLEN_shift              (0)
#define DPRX14_DDC1_DDC_SFIBLR_FFDI_DLEN_mask               (0x1f)
#define DPRX14_DDC1_DDC_SFIBLR_FFDI_DLEN(data)              (0x1f&((data)<<0))
#define DPRX14_DDC1_DDC_SFIBLR_FFDI_DLEN_src(data)          ((0x1f&(data))>>0)
#define DPRX14_DDC1_DDC_SFIBLR_get_FFDI_DLEN(data)          ((0x1f&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFIBLR_FFDI_DLEN           0x0

#define DPRX14_DDC1_DDC_SFIBRWPR                        0x64c
#define DPRX14_DDC1_DDC_SFIBRWPR_reg_addr               "0x9816564c"
#define DPRX14_DDC1_DDC_SFIBRWPR_DIFF_WPT_shift              (4)
#define DPRX14_DDC1_DDC_SFIBRWPR_DIFF_WPT_mask               (0xf0)
#define DPRX14_DDC1_DDC_SFIBRWPR_DIFF_WPT(data)              (0xf0&((data)<<4))
#define DPRX14_DDC1_DDC_SFIBRWPR_DIFF_WPT_src(data)          ((0xf0&(data))>>4)
#define DPRX14_DDC1_DDC_SFIBRWPR_get_DIFF_WPT(data)          ((0xf0&(data))>>4)
//this->default: DPRX14_DDC1_DDC_SFIBRWPR_DIFF_WPT           0x0
#define DPRX14_DDC1_DDC_SFIBRWPR_DIFF_RPT_shift              (0)
#define DPRX14_DDC1_DDC_SFIBRWPR_DIFF_RPT_mask               (0xf)
#define DPRX14_DDC1_DDC_SFIBRWPR_DIFF_RPT(data)              (0xf&((data)<<0))
#define DPRX14_DDC1_DDC_SFIBRWPR_DIFF_RPT_src(data)          ((0xf&(data))>>0)
#define DPRX14_DDC1_DDC_SFIBRWPR_get_DIFF_RPT(data)          ((0xf&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFIBRWPR_DIFF_RPT           0x0

#define DPRX14_DDC1_DDC_SFIBSWPR                        0x650
#define DPRX14_DDC1_DDC_SFIBSWPR_reg_addr               "0x98165650"
#define DPRX14_DDC1_DDC_SFIBSWPR_DIFFSTOP_PT_shift              (0)
#define DPRX14_DDC1_DDC_SFIBSWPR_DIFFSTOP_PT_mask               (0xf)
#define DPRX14_DDC1_DDC_SFIBSWPR_DIFFSTOP_PT(data)              (0xf&((data)<<0))
#define DPRX14_DDC1_DDC_SFIBSWPR_DIFFSTOP_PT_src(data)          ((0xf&(data))>>0)
#define DPRX14_DDC1_DDC_SFIBSWPR_get_DIFFSTOP_PT(data)          ((0xf&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFIBSWPR_DIFFSTOP_PT           0x0

#define DPRX14_DDC1_DDC_SFOBSR                        0x654
#define DPRX14_DDC1_DDC_SFOBSR_reg_addr               "0x98165654"
#define DPRX14_DDC1_DDC_SFOBSR_FFDO_DLEN_shift              (0)
#define DPRX14_DDC1_DDC_SFOBSR_FFDO_DLEN_mask               (0x1f)
#define DPRX14_DDC1_DDC_SFOBSR_FFDO_DLEN(data)              (0x1f&((data)<<0))
#define DPRX14_DDC1_DDC_SFOBSR_FFDO_DLEN_src(data)          ((0x1f&(data))>>0)
#define DPRX14_DDC1_DDC_SFOBSR_get_FFDO_DLEN(data)          ((0x1f&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFOBSR_FFDO_DLEN           0x0

#define DPRX14_DDC1_DDC_SFOBRWPR                        0x658
#define DPRX14_DDC1_DDC_SFOBRWPR_reg_addr               "0x98165658"
#define DPRX14_DDC1_DDC_SFOBRWPR_DOFF_WPT_shift              (4)
#define DPRX14_DDC1_DDC_SFOBRWPR_DOFF_WPT_mask               (0xf0)
#define DPRX14_DDC1_DDC_SFOBRWPR_DOFF_WPT(data)              (0xf0&((data)<<4))
#define DPRX14_DDC1_DDC_SFOBRWPR_DOFF_WPT_src(data)          ((0xf0&(data))>>4)
#define DPRX14_DDC1_DDC_SFOBRWPR_get_DOFF_WPT(data)          ((0xf0&(data))>>4)
//this->default: DPRX14_DDC1_DDC_SFOBRWPR_DOFF_WPT           0x0
#define DPRX14_DDC1_DDC_SFOBRWPR_DOFF_RPT_shift              (0)
#define DPRX14_DDC1_DDC_SFOBRWPR_DOFF_RPT_mask               (0xf)
#define DPRX14_DDC1_DDC_SFOBRWPR_DOFF_RPT(data)              (0xf&((data)<<0))
#define DPRX14_DDC1_DDC_SFOBRWPR_DOFF_RPT_src(data)          ((0xf&(data))>>0)
#define DPRX14_DDC1_DDC_SFOBRWPR_get_DOFF_RPT(data)          ((0xf&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFOBRWPR_DOFF_RPT           0x0

#define DPRX14_DDC1_DDC_SFSR                        0x65c
#define DPRX14_DDC1_DDC_SFSR_reg_addr               "0x9816565c"
#define DPRX14_DDC1_DDC_SFSR_FFDOUF_ST_shift              (7)
#define DPRX14_DDC1_DDC_SFSR_FFDOUF_ST_mask               (0x80)
#define DPRX14_DDC1_DDC_SFSR_FFDOUF_ST(data)              (0x80&((data)<<7))
#define DPRX14_DDC1_DDC_SFSR_FFDOUF_ST_src(data)          ((0x80&(data))>>7)
#define DPRX14_DDC1_DDC_SFSR_get_FFDOUF_ST(data)          ((0x80&(data))>>7)
//this->default: DPRX14_DDC1_DDC_SFSR_FFDOUF_ST           0x0
#define DPRX14_DDC1_DDC_SFSR_FFDIOF_ST_shift              (6)
#define DPRX14_DDC1_DDC_SFSR_FFDIOF_ST_mask               (0x40)
#define DPRX14_DDC1_DDC_SFSR_FFDIOF_ST(data)              (0x40&((data)<<6))
#define DPRX14_DDC1_DDC_SFSR_FFDIOF_ST_src(data)          ((0x40&(data))>>6)
#define DPRX14_DDC1_DDC_SFSR_get_FFDIOF_ST(data)          ((0x40&(data))>>6)
//this->default: DPRX14_DDC1_DDC_SFSR_FFDIOF_ST           0x0
#define DPRX14_DDC1_DDC_SFSR_FFDONF_ST_shift              (5)
#define DPRX14_DDC1_DDC_SFSR_FFDONF_ST_mask               (0x20)
#define DPRX14_DDC1_DDC_SFSR_FFDONF_ST(data)              (0x20&((data)<<5))
#define DPRX14_DDC1_DDC_SFSR_FFDONF_ST_src(data)          ((0x20&(data))>>5)
#define DPRX14_DDC1_DDC_SFSR_get_FFDONF_ST(data)          ((0x20&(data))>>5)
//this->default: DPRX14_DDC1_DDC_SFSR_FFDONF_ST           0x1
#define DPRX14_DDC1_DDC_SFSR_FFDOET_ST_shift              (4)
#define DPRX14_DDC1_DDC_SFSR_FFDOET_ST_mask               (0x10)
#define DPRX14_DDC1_DDC_SFSR_FFDOET_ST(data)              (0x10&((data)<<4))
#define DPRX14_DDC1_DDC_SFSR_FFDOET_ST_src(data)          ((0x10&(data))>>4)
#define DPRX14_DDC1_DDC_SFSR_get_FFDOET_ST(data)          ((0x10&(data))>>4)
//this->default: DPRX14_DDC1_DDC_SFSR_FFDOET_ST           0x1
#define DPRX14_DDC1_DDC_SFSR_FFDIFU_ST_shift              (3)
#define DPRX14_DDC1_DDC_SFSR_FFDIFU_ST_mask               (0x8)
#define DPRX14_DDC1_DDC_SFSR_FFDIFU_ST(data)              (0x8&((data)<<3))
#define DPRX14_DDC1_DDC_SFSR_FFDIFU_ST_src(data)          ((0x8&(data))>>3)
#define DPRX14_DDC1_DDC_SFSR_get_FFDIFU_ST(data)          ((0x8&(data))>>3)
//this->default: DPRX14_DDC1_DDC_SFSR_FFDIFU_ST           0x0
#define DPRX14_DDC1_DDC_SFSR_FFDINE_ST_shift              (2)
#define DPRX14_DDC1_DDC_SFSR_FFDINE_ST_mask               (0x4)
#define DPRX14_DDC1_DDC_SFSR_FFDINE_ST(data)              (0x4&((data)<<2))
#define DPRX14_DDC1_DDC_SFSR_FFDINE_ST_src(data)          ((0x4&(data))>>2)
#define DPRX14_DDC1_DDC_SFSR_get_FFDINE_ST(data)          ((0x4&(data))>>2)
//this->default: DPRX14_DDC1_DDC_SFSR_FFDINE_ST           0x0

#define DPRX14_DDC1_DDC_SFIR                        0x660
#define DPRX14_DDC1_DDC_SFIR_reg_addr               "0x98165660"
#define DPRX14_DDC1_DDC_SFIR_FFDOUF_IE_shift              (7)
#define DPRX14_DDC1_DDC_SFIR_FFDOUF_IE_mask               (0x80)
#define DPRX14_DDC1_DDC_SFIR_FFDOUF_IE(data)              (0x80&((data)<<7))
#define DPRX14_DDC1_DDC_SFIR_FFDOUF_IE_src(data)          ((0x80&(data))>>7)
#define DPRX14_DDC1_DDC_SFIR_get_FFDOUF_IE(data)          ((0x80&(data))>>7)
//this->default: DPRX14_DDC1_DDC_SFIR_FFDOUF_IE           0x0
#define DPRX14_DDC1_DDC_SFIR_FFDIOF_IE_shift              (6)
#define DPRX14_DDC1_DDC_SFIR_FFDIOF_IE_mask               (0x40)
#define DPRX14_DDC1_DDC_SFIR_FFDIOF_IE(data)              (0x40&((data)<<6))
#define DPRX14_DDC1_DDC_SFIR_FFDIOF_IE_src(data)          ((0x40&(data))>>6)
#define DPRX14_DDC1_DDC_SFIR_get_FFDIOF_IE(data)          ((0x40&(data))>>6)
//this->default: DPRX14_DDC1_DDC_SFIR_FFDIOF_IE           0x0
#define DPRX14_DDC1_DDC_SFIR_FFDONF_IE_shift              (5)
#define DPRX14_DDC1_DDC_SFIR_FFDONF_IE_mask               (0x20)
#define DPRX14_DDC1_DDC_SFIR_FFDONF_IE(data)              (0x20&((data)<<5))
#define DPRX14_DDC1_DDC_SFIR_FFDONF_IE_src(data)          ((0x20&(data))>>5)
#define DPRX14_DDC1_DDC_SFIR_get_FFDONF_IE(data)          ((0x20&(data))>>5)
//this->default: DPRX14_DDC1_DDC_SFIR_FFDONF_IE           0x0
#define DPRX14_DDC1_DDC_SFIR_FFDOET_IE_shift              (4)
#define DPRX14_DDC1_DDC_SFIR_FFDOET_IE_mask               (0x10)
#define DPRX14_DDC1_DDC_SFIR_FFDOET_IE(data)              (0x10&((data)<<4))
#define DPRX14_DDC1_DDC_SFIR_FFDOET_IE_src(data)          ((0x10&(data))>>4)
#define DPRX14_DDC1_DDC_SFIR_get_FFDOET_IE(data)          ((0x10&(data))>>4)
//this->default: DPRX14_DDC1_DDC_SFIR_FFDOET_IE           0x0
#define DPRX14_DDC1_DDC_SFIR_FFDIFU_IE_shift              (3)
#define DPRX14_DDC1_DDC_SFIR_FFDIFU_IE_mask               (0x8)
#define DPRX14_DDC1_DDC_SFIR_FFDIFU_IE(data)              (0x8&((data)<<3))
#define DPRX14_DDC1_DDC_SFIR_FFDIFU_IE_src(data)          ((0x8&(data))>>3)
#define DPRX14_DDC1_DDC_SFIR_get_FFDIFU_IE(data)          ((0x8&(data))>>3)
//this->default: DPRX14_DDC1_DDC_SFIR_FFDIFU_IE           0x0
#define DPRX14_DDC1_DDC_SFIR_FFDINE_IE_shift              (2)
#define DPRX14_DDC1_DDC_SFIR_FFDINE_IE_mask               (0x4)
#define DPRX14_DDC1_DDC_SFIR_FFDINE_IE(data)              (0x4&((data)<<2))
#define DPRX14_DDC1_DDC_SFIR_FFDINE_IE_src(data)          ((0x4&(data))>>2)
#define DPRX14_DDC1_DDC_SFIR_get_FFDINE_IE(data)          ((0x4&(data))>>2)
//this->default: DPRX14_DDC1_DDC_SFIR_FFDINE_IE           0x0
#define DPRX14_DDC1_DDC_SFIR_CIPPT_IE_shift              (1)
#define DPRX14_DDC1_DDC_SFIR_CIPPT_IE_mask               (0x2)
#define DPRX14_DDC1_DDC_SFIR_CIPPT_IE(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_DDC_SFIR_CIPPT_IE_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_DDC_SFIR_get_CIPPT_IE(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_DDC_SFIR_CIPPT_IE           0x0
#define DPRX14_DDC1_DDC_SFIR_CISPT_IE_shift              (0)
#define DPRX14_DDC1_DDC_SFIR_CISPT_IE_mask               (0x1)
#define DPRX14_DDC1_DDC_SFIR_CISPT_IE(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_SFIR_CISPT_IE_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_SFIR_get_CISPT_IE(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SFIR_CISPT_IE           0x0

#define DPRX14_DDC1_DDC_FSMS                        0x664
#define DPRX14_DDC1_DDC_FSMS_reg_addr               "0x98165664"
#define DPRX14_DDC1_DDC_FSMS_CMDFSM_ST_shift              (0)
#define DPRX14_DDC1_DDC_FSMS_CMDFSM_ST_mask               (0xff)
#define DPRX14_DDC1_DDC_FSMS_CMDFSM_ST(data)              (0xff&((data)<<0))
#define DPRX14_DDC1_DDC_FSMS_CMDFSM_ST_src(data)          ((0xff&(data))>>0)
#define DPRX14_DDC1_DDC_FSMS_get_CMDFSM_ST(data)          ((0xff&(data))>>0)
//this->default: DPRX14_DDC1_DDC_FSMS_CMDFSM_ST           0x1

#define DPRX14_DDC1_DDC_DUMMY                        0x668
#define DPRX14_DDC1_DDC_DUMMY_reg_addr               "0x98165668"
#define DPRX14_DDC1_DDC_DUMMY_Dummy_shift              (0)
#define DPRX14_DDC1_DDC_DUMMY_Dummy_mask               (0xff)
#define DPRX14_DDC1_DDC_DUMMY_Dummy(data)              (0xff&((data)<<0))
#define DPRX14_DDC1_DDC_DUMMY_Dummy_src(data)          ((0xff&(data))>>0)
#define DPRX14_DDC1_DDC_DUMMY_get_Dummy(data)          ((0xff&(data))>>0)
//this->default: DPRX14_DDC1_DDC_DUMMY_Dummy           0x0

#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN                        0x670
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_reg_addr               "0x98165670"
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_START_IRQ_EN_shift              (1)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_START_IRQ_EN_mask               (0x2)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_START_IRQ_EN(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_START_IRQ_EN_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_get_START_IRQ_EN(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_START_IRQ_EN           0x0
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_STOP_IRQ_EN_shift              (0)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_STOP_IRQ_EN_mask               (0x1)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_STOP_IRQ_EN(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_STOP_IRQ_EN_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_get_STOP_IRQ_EN(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_EDID_SRAM_READ_IRQ_EN_STOP_IRQ_EN           0x0

#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX                        0x674
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_reg_addr               "0x98165674"
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_START_shift              (1)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_START_mask               (0x2)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_START(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_START_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_get_START(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_START           0x0
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_STOP_shift              (0)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_STOP_mask               (0x1)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_STOP(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_STOP_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_get_STOP(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_EDID_SRAM_READ_AUX_STOP           0x0

#define DPRX14_DDC1_DDC_BIST_MODE                        0x678
#define DPRX14_DDC1_DDC_BIST_MODE_reg_addr               "0x98165678"
#define DPRX14_DDC1_DDC_BIST_MODE_DDC_BIST_MODE_shift              (0)
#define DPRX14_DDC1_DDC_BIST_MODE_DDC_BIST_MODE_mask               (0x1)
#define DPRX14_DDC1_DDC_BIST_MODE_DDC_BIST_MODE(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_BIST_MODE_DDC_BIST_MODE_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_BIST_MODE_get_DDC_BIST_MODE(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_BIST_MODE_DDC_BIST_MODE           0x0

#define DPRX14_DDC1_DDC_BIST_DONE                        0x67c
#define DPRX14_DDC1_DDC_BIST_DONE_reg_addr               "0x9816567c"
#define DPRX14_DDC1_DDC_BIST_DONE_DDC_BIST_DONE_shift              (0)
#define DPRX14_DDC1_DDC_BIST_DONE_DDC_BIST_DONE_mask               (0x1)
#define DPRX14_DDC1_DDC_BIST_DONE_DDC_BIST_DONE(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_BIST_DONE_DDC_BIST_DONE_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_BIST_DONE_get_DDC_BIST_DONE(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_BIST_DONE_DDC_BIST_DONE           0x0

#define DPRX14_DDC1_DDC_BIST_FAIL                        0x680
#define DPRX14_DDC1_DDC_BIST_FAIL_reg_addr               "0x98165680"
#define DPRX14_DDC1_DDC_BIST_FAIL_DDC_BIST_FAIL_shift              (0)
#define DPRX14_DDC1_DDC_BIST_FAIL_DDC_BIST_FAIL_mask               (0x1)
#define DPRX14_DDC1_DDC_BIST_FAIL_DDC_BIST_FAIL(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_BIST_FAIL_DDC_BIST_FAIL_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_BIST_FAIL_get_DDC_BIST_FAIL(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_BIST_FAIL_DDC_BIST_FAIL           0x0

#define DPRX14_DDC1_DDC_DRF_MODE                        0x684
#define DPRX14_DDC1_DDC_DRF_MODE_reg_addr               "0x98165684"
#define DPRX14_DDC1_DDC_DRF_MODE_DDC_DRF_MODE_shift              (0)
#define DPRX14_DDC1_DDC_DRF_MODE_DDC_DRF_MODE_mask               (0x1)
#define DPRX14_DDC1_DDC_DRF_MODE_DDC_DRF_MODE(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_DRF_MODE_DDC_DRF_MODE_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_DRF_MODE_get_DDC_DRF_MODE(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_DRF_MODE_DDC_DRF_MODE           0x0

#define DPRX14_DDC1_DDC_DRF_RESUME                        0x688
#define DPRX14_DDC1_DDC_DRF_RESUME_reg_addr               "0x98165688"
#define DPRX14_DDC1_DDC_DRF_RESUME_DDC_DRF_RESUME_shift              (0)
#define DPRX14_DDC1_DDC_DRF_RESUME_DDC_DRF_RESUME_mask               (0x1)
#define DPRX14_DDC1_DDC_DRF_RESUME_DDC_DRF_RESUME(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_DRF_RESUME_DDC_DRF_RESUME_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_DRF_RESUME_get_DDC_DRF_RESUME(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_DRF_RESUME_DDC_DRF_RESUME           0x0

#define DPRX14_DDC1_DDC_DRF_DONE                        0x68c
#define DPRX14_DDC1_DDC_DRF_DONE_reg_addr               "0x9816568c"
#define DPRX14_DDC1_DDC_DRF_DONE_DDC_DRF_DONE_shift              (0)
#define DPRX14_DDC1_DDC_DRF_DONE_DDC_DRF_DONE_mask               (0x1)
#define DPRX14_DDC1_DDC_DRF_DONE_DDC_DRF_DONE(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_DRF_DONE_DDC_DRF_DONE_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_DRF_DONE_get_DDC_DRF_DONE(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_DRF_DONE_DDC_DRF_DONE           0x0

#define DPRX14_DDC1_DDC_DRF_PAUSE                        0x690
#define DPRX14_DDC1_DDC_DRF_PAUSE_reg_addr               "0x98165690"
#define DPRX14_DDC1_DDC_DRF_PAUSE_DDC_DRF_PAUSE_shift              (0)
#define DPRX14_DDC1_DDC_DRF_PAUSE_DDC_DRF_PAUSE_mask               (0x1)
#define DPRX14_DDC1_DDC_DRF_PAUSE_DDC_DRF_PAUSE(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_DRF_PAUSE_DDC_DRF_PAUSE_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_DRF_PAUSE_get_DDC_DRF_PAUSE(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_DRF_PAUSE_DDC_DRF_PAUSE           0x0

#define DPRX14_DDC1_DDC_DRF_FAIL                        0x694
#define DPRX14_DDC1_DDC_DRF_FAIL_reg_addr               "0x98165694"
#define DPRX14_DDC1_DDC_DRF_FAIL_DDC_DRF_FAIL_shift              (0)
#define DPRX14_DDC1_DDC_DRF_FAIL_DDC_DRF_FAIL_mask               (0x1)
#define DPRX14_DDC1_DDC_DRF_FAIL_DDC_DRF_FAIL(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_DRF_FAIL_DDC_DRF_FAIL_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_DRF_FAIL_get_DDC_DRF_FAIL(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_DRF_FAIL_DDC_DRF_FAIL           0x0

#define DPRX14_DDC1_DDC_SRAM_LS_CTRL                        0x6a0
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_reg_addr               "0x981656a0"
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_LS_MODE_SEL_shift              (1)
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_LS_MODE_SEL_mask               (0x2)
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_LS_MODE_SEL(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_LS_MODE_SEL_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_get_DDC_LS_MODE_SEL(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_LS_MODE_SEL           0x0
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_SW_LS_shift              (0)
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_SW_LS_mask               (0x1)
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_SW_LS(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_SW_LS_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_SRAM_LS_CTRL_get_DDC_SW_LS(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SRAM_LS_CTRL_DDC_SW_LS           0x0

#define DPRX14_DDC1_DDC_SRAM_DS_CTRL                        0x6a4
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_reg_addr               "0x981656a4"
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_DS_shift              (1)
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_DS_mask               (0x2)
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_DS(data)              (0x2&((data)<<1))
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_DS_src(data)          ((0x2&(data))>>1)
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_get_DDC_DS(data)          ((0x2&(data))>>1)
//this->default: DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_DS           0x0
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_SD_shift              (0)
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_SD_mask               (0x1)
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_SD(data)              (0x1&((data)<<0))
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_SD_src(data)          ((0x1&(data))>>0)
#define DPRX14_DDC1_DDC_SRAM_DS_CTRL_get_DDC_SD(data)          ((0x1&(data))>>0)
//this->default: DPRX14_DDC1_DDC_SRAM_DS_CTRL_DDC_SD           0x0

#endif