/* SPDX-License-Identifier: GPL-2.0-only */
#include "dprx14_aux_reg.h"
#include "dprx14_mac_ip_reg.h"

#ifndef _DPRX_IP_REG_H_INCLUDED_
#define _DPRX_IP_REG_H_INCLUDED_

#define DPRX_IP_reg                 0x98166000

#define PB_00_HD_DP_SEL               DPRX14_MAC_IP_HD_DP_SEL
#define PB_01_PHY_DIG_RESET_CTRL      DPRX14_MAC_IP_PHY_DIG_RESET_CTRL
#define PB_02_PHY_DIG_RESET2_CTRL     DPRX14_MAC_IP_PHY_DIG_RESET2_CTRL
#define PB_03_LANE_MUX                DPRX14_MAC_IP_LANE_MUX

#define PB_05_SAMPLE_EDGE             DPRX14_MAC_IP_SAMPLE_EDGE
#define PB_06_DECODE_10B8B_ERROR      DPRX14_MAC_IP_DECODE_10B8B_ERROR
#define PB_07_SCRAMBLE_CTRL           DPRX14_MAC_IP_SCRAMBLE_CTRL
#define PB_08_BIST_PATTERN_SEL        DPRX14_MAC_IP_BIST_PATTERN_SEL

#define PB_0B_BIST_PATTERN3           DPRX14_MAC_IP_BIST_PATTERN3
#define PB_0C_BIST_PATTERN4           DPRX14_MAC_IP_BIST_PATTERN4

#define PB_0E_DESKEW_PHY              DPRX14_MAC_IP_DESKEW_PHY

#define PB_17_DP_HDCP_CONTROL         DPRX14_MAC_IP_DP_HDCP_CONTROL
#define PB_18_DP_HDCP_DOWNLOAD_PORT   DPRX14_MAC_IP_DP_HDCP_DOWNLOAD_PORT

#define PB_1A_HDCP_IRQ                DPRX14_MAC_IP_HDCP_IRQ
#define PB_1B_HDCP_INTGT_VRF          DPRX14_MAC_IP_HDCP_INTGT_VRF

#define PB_1E_HDCP_INTGT_VRF_ANS_MSB  DPRX14_MAC_IP_HDCP_INTGT_VRF_ANS_MSB
#define PB_1F_HDCP_INTGT_VRF_ANS_LSB  DPRX14_MAC_IP_HDCP_INTGT_VRF_ANS_LSB
#define PB_20_HDCP_DEBUG              DPRX14_MAC_IP_HDCP_DEBUG

#define PB_4B_DP_COMMA_DET_MANU       DPRX14_MAC_IP_DP_COMMA_DET_MANU

#define PB_50_DP_SIG_DET_0            DPRX14_MAC_IP_DP_SIG_DET_0
#define PB_51_DP_SIG_DET_1            DPRX14_MAC_IP_DP_SIG_DET_1
#define PB_52_DP_SIG_DET_2            DPRX14_MAC_IP_DP_SIG_DET_2
#define PB_53_DP_SIG_DET_3            DPRX14_MAC_IP_DP_SIG_DET_3
#define PB_54_DP_SIG_DET_4            DPRX14_MAC_IP_DP_SIG_DET_4

#define PB_63_HDCP_OTHER              DPRX14_MAC_IP_HDCP_OTHER

#define P0_0B_POWER_CTRL              DPRX14_MAC_IP_DP_MAC0_POWER_CTRL

#define PB5_1E_MAC_DIG_RESET_CTRL     DPRX14_MAC_IP_MAC_DIG_RESET_CTRL
#define PB5_1F_SOURCE_SEL_4           DPRX14_MAC_IP_SOURCE_SEL_4

#define PB5_20_PG_CTRL_0              DPRX14_MAC_IP_PG_CTRL_0
#define PB5_21_PG_CTRL_1              DPRX14_MAC_IP_PG_CTRL_1

#define PB5_26_SRAM_BIST_1            DPRX14_MAC_IP_SRAM_BIST_1

#define PB5_30_DPF_CTRL_0             DPRX14_MAC_IP_DPF_CTRL_0
#define PB5_31_DP_OUTPUT_CTRL         DPRX14_MAC_IP_DP_OUTPUT_CTRL
#define PB5_32_EVBLK2VS_H             DPRX14_MAC_IP_EVBLK2VS_H
#define PB5_33_EVBLK2VS_M             DPRX14_MAC_IP_EVBLK2VS_M
#define PB5_34_EVBLK2VS_L             DPRX14_MAC_IP_EVBLK2VS_L
#define PB5_35_OVBLK2VS_H             DPRX14_MAC_IP_OVBLK2VS_H
#define PB5_36_OVBLK2VS_M             DPRX14_MAC_IP_OVBLK2VS_M
#define PB5_37_OVBLK2VS_L             DPRX14_MAC_IP_OVBLK2VS_L

#define PB5_38_BS2HS_0                DPRX14_MAC_IP_BS2HS_0
#define PB5_39_BS2HS_1                DPRX14_MAC_IP_BS2HS_1
#define PB5_40_VS_FRONT_PORCH         DPRX14_MAC_IP_VS_FRONT_PORCH
#define PB5_41_MN_DPF_HTT_M           DPRX14_MAC_IP_MN_DPF_HTT_M
#define PB5_42_MN_DPF_HTT_L           DPRX14_MAC_IP_MN_DPF_HTT_L
#define PB5_43_MN_DPF_HST_M           DPRX14_MAC_IP_MN_DPF_HST_M
#define PB5_44_MN_DPF_HST_L           DPRX14_MAC_IP_MN_DPF_HST_L
#define PB5_45_MN_DPF_HWD_M           DPRX14_MAC_IP_MN_DPF_HWD_M
#define PB5_46_MN_DPF_HWD_L           DPRX14_MAC_IP_MN_DPF_HWD_L
#define PB5_47_MN_DPF_HSW_M           DPRX14_MAC_IP_MN_DPF_HSW_M
#define PB5_48_MN_DPF_HSW_L           DPRX14_MAC_IP_MN_DPF_HSW_L
#define PB5_49_MN_DPF_VTT_M           DPRX14_MAC_IP_MN_DPF_VTT_M
#define PB5_4A_MN_DPF_VTT_L           DPRX14_MAC_IP_MN_DPF_VTT_L
#define PB5_4B_MN_DPF_VST_M           DPRX14_MAC_IP_MN_DPF_VST_M
#define PB5_4C_MN_DPF_VST_L           DPRX14_MAC_IP_MN_DPF_VST_L
#define PB5_4D_MN_DPF_VHT_M           DPRX14_MAC_IP_MN_DPF_VHT_M
#define PB5_4E_MN_DPF_VHT_L           DPRX14_MAC_IP_MN_DPF_VHT_L
#define PB5_4F_MN_DPF_VSW_M           DPRX14_MAC_IP_MN_DPF_VSW_M
#define PB5_50_MN_DPF_VSW_L           DPRX14_MAC_IP_MN_DPF_VSW_L

#define PB5_51_MN_DPF_BG_RED_M        DPRX14_MAC_IP_MN_DPF_BG_RED_M
#define PB5_52_MN_DPF_BG_RED_L        DPRX14_MAC_IP_MN_DPF_BG_RED_L
#define PB5_53_MN_DPF_BG_GRN_M        DPRX14_MAC_IP_MN_DPF_BG_GRN_M
#define PB5_54_MN_DPF_BG_GRN_L        DPRX14_MAC_IP_MN_DPF_BG_GRN_L
#define PB5_55_MN_DPF_BG_BLU_M        DPRX14_MAC_IP_MN_DPF_BG_BLU_M
#define PB5_56_MN_DPF_BG_BLU_L        DPRX14_MAC_IP_MN_DPF_BG_BLU_L
#define PB5_57_INTERLACE_MODE_CONFIG  DPRX14_MAC_IP_INTERLACE_MODE_CONFIG
#define PB5_58_MN_MEAS_CTRL           DPRX14_MAC_IP_MN_MEAS_CTRL
#define PB5_59_MN_MEAS_VLN_M          DPRX14_MAC_IP_MN_MEAS_VLN_M
#define PB5_5A_MN_MEAS_VLN_L          DPRX14_MAC_IP_MN_MEAS_VLN_L
#define PB5_5B_MN_MEAS_HLN_M          DPRX14_MAC_IP_MN_MEAS_HLN_M
#define PB5_5C_MN_MEAS_HLN_L          DPRX14_MAC_IP_MN_MEAS_HLN_L

#define PB5_70_DP_CRC_CTRL            DPRX14_MAC_IP_DP_CRC_CTRL
#define PB5_71_DP_CRC_R_M             DPRX14_MAC_IP_DP_CRC_R_M
#define PB5_72_DP_CRC_R_L             DPRX14_MAC_IP_DP_CRC_R_L
#define PB5_73_DP_CRC_G_M             DPRX14_MAC_IP_DP_CRC_G_M
#define PB5_74_DP_CRC_G_L             DPRX14_MAC_IP_DP_CRC_G_L
#define PB5_75_DP_CRC_B_M             DPRX14_MAC_IP_DP_CRC_B_M
#define PB5_76_DP_CRC_B_L             DPRX14_MAC_IP_DP_CRC_B_L

#define PB5_90_DP_RSV0                DPRX14_MAC_IP_DP_RSV0
#define PB5_91_DP_RSV1                DPRX14_MAC_IP_DP_RSV1

#define PB5_A2_PLL_OUT_CONTROL        DPRX14_MAC_IP_PLL_OUT_CONTROL
#define PB5_A3_PLL_IN_CONTROL         DPRX14_MAC_IP_PLL_IN_CONTROL

#define PB5_A5_M2PLL_DIVIDER1         DPRX14_MAC_IP_M2PLL_DIVIDER1
#define PB5_A6_M2PLL_0                DPRX14_MAC_IP_M2PLL_0
#define PB5_A7_M2PLL_1                DPRX14_MAC_IP_M2PLL_1
#define PB5_A8_M2PLL_CONTROL          DPRX14_MAC_IP_M2PLL_CONTROL
#define PB5_A9_M2PLL_LDO              DPRX14_MAC_IP_M2PLL_LDO

#define PB5_AC_N_F_CODE_0             DPRX14_MAC_IP_N_F_CODE_0
#define PB5_AD_N_F_CODE_1             DPRX14_MAC_IP_N_F_CODE_1
#define PB5_AE_N_F_CODE_2             DPRX14_MAC_IP_N_F_CODE_2
#define PB5_AF_N_F_CODE_3             DPRX14_MAC_IP_N_F_CODE_3
#define PB5_B0_N_F_CODE_4             DPRX14_MAC_IP_N_F_CODE_4

#define PB5_C5_TRACKING_5             DPRX14_MAC_IP_TRACKING_5

#define PB5_C8_MN_PI_CODE_0           DPRX14_MAC_IP_MN_PI_CODE_0
#define PB5_C9_MN_PI_CODE_1           DPRX14_MAC_IP_MN_PI_CODE_1
#define PB5_CA_MN_PI_CODE_2           DPRX14_MAC_IP_MN_PI_CODE_2
#define PB5_CB_MN_PI_CODE_3           DPRX14_MAC_IP_MN_PI_CODE_3
#define PB5_CC_MN_PI_CODE_4           DPRX14_MAC_IP_MN_PI_CODE_4

#define PB5_D1_MN_PI_CODE_9           DPRX14_MAC_IP_MN_PI_CODE_9
#define PB5_D2_MN_PI_CODE_A           DPRX14_MAC_IP_MN_PI_CODE_A
#define PB5_D3_MN_PI_CODE_B           DPRX14_MAC_IP_MN_PI_CODE_B
#define PB5_D4_MN_PI_CODE_C           DPRX14_MAC_IP_MN_PI_CODE_C

#define PB5_DA_MN_TRACKING_DIVS       DPRX14_MAC_IP_MN_TRACKING_DIVS

#define PB5_E0_VS_TRACK_EN            DPRX14_MAC_IP_VS_TRACK_EN
#define PB5_E1_VS_TRACK_MODE          DPRX14_MAC_IP_VS_TRACK_MODE

#define PB5_E3_VS_TRACK1              DPRX14_MAC_IP_VS_TRACK1
#define PB5_E4_VS_TRACK2              DPRX14_MAC_IP_VS_TRACK2
#define PB5_E5_VS_TRACK3              DPRX14_MAC_IP_VS_TRACK3

#define PB5_EA_HS_TRACKING_NEW_MODE1  DPRX14_MAC_IP_HS_TRACKING_NEW_MODE1
#define PB5_EB_HS_TRACKING_NEW_MODE2  DPRX14_MAC_IP_HS_TRACKING_NEW_MODE2
#define PB5_EC_VBID_MAN_MADE          DPRX14_MAC_IP_VBID_MAN_MADE

#define PB5_EE_P_CODE_SPREAD_0        DPRX14_MAC_IP_P_CODE_SPREAD_0

#define PB5_F0_P_CODE_SPREAD_2        DPRX14_MAC_IP_P_CODE_SPREAD_2

#define PB5_F2_DSC_HTT_0              DPRX14_MAC_IP_DSC_HTT_0


/* D0 DisplayPort Video SEC DATA (Page B6) */
#define PB6_00_MN_STRM_ATTR_CTRL      DPRX14_MAC_IP_MN_STRM_ATTR_CTRL
#define PB6_01_DP_VBID                DPRX14_MAC_IP_DP_VBID
#define PB6_02_MN_STRM_ATTR_MISC      DPRX14_MAC_IP_MN_STRM_ATTR_MISC
#define PB6_03_MN_STRM_ATTR_MISC1     DPRX14_MAC_IP_MN_STRM_ATTR_MISC1

#define PB6_0C_MSA_HWD_0              DPRX14_MAC_IP_MSA_HWD_0
#define PB6_0D_MSA_HWD_1              DPRX14_MAC_IP_MSA_HWD_1

#define PB6_08_MSA_HTT_0              DPRX14_MAC_IP_MSA_HTT_0
#define PB6_09_MSA_HTT_1              DPRX14_MAC_IP_MSA_HTT_1
#define PB6_0A_MSA_HST_0              DPRX14_MAC_IP_MSA_HST_0
#define PB6_0B_MSA_HST_1              DPRX14_MAC_IP_MSA_HST_1

#define PB6_0E_MSA_HSW_0              DPRX14_MAC_IP_MSA_HSW_0
#define PB6_0F_MSA_HSW_1              DPRX14_MAC_IP_MSA_HSW_1
#define PB6_10_MSA_VTTE_0             DPRX14_MAC_IP_MSA_VTTE_0
#define PB6_11_MSA_VTTE_1             DPRX14_MAC_IP_MSA_VTTE_1
#define PB6_12_MSA_VTTO_0             DPRX14_MAC_IP_MSA_VTTO_0
#define PB6_13_MSA_VTTO_1             DPRX14_MAC_IP_MSA_VTTO_1
#define PB6_14_MSA_VST_0              DPRX14_MAC_IP_MSA_VST_0
#define PB6_15_MSA_VST_1              DPRX14_MAC_IP_MSA_VST_1
#define PB6_16_MSA_VHT_0              DPRX14_MAC_IP_MSA_VHT_0
#define PB6_17_MSA_VHT_1              DPRX14_MAC_IP_MSA_VHT_1
#define PB6_18_MSA_VSW_0              DPRX14_MAC_IP_MSA_VSW_0
#define PB6_19_MSA_VSW_1              DPRX14_MAC_IP_MSA_VSW_1
#define PB6_1A_MSA_MVID_0             DPRX14_MAC_IP_MSA_MVID_0
#define PB6_1B_MSA_MVID_1             DPRX14_MAC_IP_MSA_MVID_1
#define PB6_1C_MSA_MVID_2             DPRX14_MAC_IP_MSA_MVID_2
#define PB6_1D_MSA_NVID_0             DPRX14_MAC_IP_MSA_NVID_0
#define PB6_1E_MSA_NVID_1             DPRX14_MAC_IP_MSA_NVID_1
#define PB6_1F_MSA_NVID_2             DPRX14_MAC_IP_MSA_NVID_2

#define PB6_2C_DP_SDP_SPD_MAT_HB1     DPRX14_MAC_IP_DP_SDP_SPD_MAT_HB1
#define PB6_2E_DP_SDP_SPD_HB3         DPRX14_MAC_IP_DP_SDP_SPD_HB3
#define PB6_2F_DP_SDP_SPD_CTRL        DPRX14_MAC_IP_DP_SDP_SPD_CTRL

#define PB6_31_DP_SDP_SPD_CHG         DPRX14_MAC_IP_DP_SDP_SPD_CHG
#define PB6_32_DP_SDP_SPD_ADR         DPRX14_MAC_IP_DP_SDP_SPD_ADR
#define PB6_33_DP_SDP_SPD_DAT         DPRX14_MAC_IP_DP_SDP_SPD_DAT

#define PB6_36_DP_SDP_HDR_INFO_HB3    DPRX14_MAC_IP_DP_SDP_HDR_INFO_HB3

#define PB6_39_DP_SDP_HDR_INFO_ADR    DPRX14_MAC_IP_DP_SDP_HDR_INFO_ADR
#define PB6_3A_DP_SDP_HDR_INFO_DAT    DPRX14_MAC_IP_DP_SDP_HDR_INFO_DAT
#define PB6_3B_DP_GLB_STATUS          DPRX14_MAC_IP_DP_GLB_STATUS
#define PB6_3C_DP_WD_CTRL_0           DPRX14_MAC_IP_DP_WD_CTRL_0
#define PB6_3D_DP_WD_CTRL_1           DPRX14_MAC_IP_DP_WD_CTRL_1
#define PB6_3E_DP_IRQ_CTRL0           DPRX14_MAC_IP_DP_IRQ_CTRL0
#define PB6_3F_DP_IRQ_CTRL1           DPRX14_MAC_IP_DP_IRQ_CTRL1

#define PB6_40_VSC0                   DPRX14_MAC_IP_VSC0
#define PB6_40_VSC1                   DPRX14_MAC_IP_VSC1
#define PB6_42_VSC2                   DPRX14_MAC_IP_VSC2
#define PB6_43_VSC3                   DPRX14_MAC_IP_VSC3
#define PB6_44_VSC4                   DPRX14_MAC_IP_VSC4
#define PB6_45_VSC5                   DPRX14_MAC_IP_VSC5

#define PB6_47_VSC7                   DPRX14_MAC_IP_VSC7
#define PB6_48_VSC8                   DPRX14_MAC_IP_VSC8

#define PB6_E0_SDP_ACM_ISRC_INT       DPRX14_MAC_IP_SDP_ACM_ISRC_INT

#define PB6_E3_SDP_ISRC_0             DPRX14_MAC_IP_SDP_ISRC_0
#define PB6_E4_SDP_ISRC_ADR           DPRX14_MAC_IP_SDP_ISRC_ADR
#define PB6_E5_SDP_ISRC_DATA          DPRX14_MAC_IP_SDP_ISRC_DATA
#define PB6_E6_DP_SDP_ISRC_MAT_HB1    DPRX14_MAC_IP_DP_SDP_ISRC_MAT_HB1

#define PB6_E8_DP_MAC_DYN_MDATA_HB1   DPRX14_MAC_IP_DP_MAC_DYN_MDATA_HB1

#define PB6_F0_DP_SDP_RSV0_MAT_HB1    DPRX14_MAC_IP_DP_SDP_RSV0_MAT_HB1

#define PB6_F3_DP_SDP_RSV0_CTRL       DPRX14_MAC_IP_DP_SDP_RSV0_CTRL
#define PB6_F4_DP_SDP_RSV0_ADR        DPRX14_MAC_IP_DP_SDP_RSV0_ADR

#define PB6_F6_DP_SDP_RSV1_MAT_HB1    DPRX14_MAC_IP_DP_SDP_RSV1_MAT_HB1

#define PB6_F9_DP_SDP_RSV1_CTRL       DPRX14_MAC_IP_DP_SDP_RSV1_CTRL
#define PB6_FA_DP_SDP_RSV1_ADR        DPRX14_MAC_IP_DP_SDP_RSV1_ADR
#define PB6_FC_DP_MAC_DYN_MDATA_HB0   DPRX14_MAC_IP_DP_MAC_DYN_MDATA_HB0

#define PB7_60_DIG_TX_04              DPRX14_AUX_DIG_TX_04
#define PB7_61_AUX_1                  DPRX14_AUX_AUX_1
#define PB7_62_AUX_2                  DPRX14_AUX_AUX_2
#define PB7_63_AUX_3                  DPRX14_AUX_AUX_3
#define PB7_64_AUX_4                  DPRX14_AUX_AUX_4
#define PB7_65_AUX_5                  DPRX14_AUX_AUX_5
#define PB7_66_AUX_6                  DPRX14_AUX_AUX_6
#define PB7_67_DIG_TX_03              DPRX14_AUX_DIG_TX_03

#define PB7_71_AUX_DIG_PHY1           DPRX14_AUX_AUX_DIG_PHY1
#define PB7_72_AUX_DIG_PHY2           DPRX14_AUX_AUX_DIG_PHY2
#define PB7_73_AUX_DIG_PHY3           DPRX14_AUX_AUX_DIG_PHY3
#define PB7_74_AUX_DIG_PHY4           DPRX14_AUX_AUX_DIG_PHY4
#define PB7_75_AUX_DIG_PHY5           DPRX14_AUX_AUX_DIG_PHY5
#define PB7_76_AUX_DIG_PHY6           DPRX14_AUX_AUX_DIG_PHY6
#define PB7_77_AUX_DIG_PHY7           DPRX14_AUX_AUX_DIG_PHY7
#define PB7_78_AUX_DIG_PHY8           DPRX14_AUX_AUX_DIG_PHY8
#define PB7_79_AUX_DIG_PHY9           DPRX14_AUX_AUX_DIG_PHY9
#define PB7_7A_AUX_DIG_PHYA           DPRX14_AUX_AUX_DIG_PHYA

#define PB7_A2_AUX_TIMEOUT_TARGET     DPRX14_AUX_AUX_TIMEOUT_TARGET

#define PB7_B0_AUX_PAYLOAD_CLEAR      DPRX14_AUX_AUX_PAYLOAD_CLEAR

#define PB7_B4_AUX_IRQ_ADDR0_MSB      DPRX14_AUX_AUX_IRQ_ADDR0_MSB
#define PB7_B5_AUX_IRQ_ADDR0_MSB1     DPRX14_AUX_AUX_IRQ_ADDR0_MSB1
#define PB7_B6_AUX_IRQ_ADDR0_LSB      DPRX14_AUX_AUX_IRQ_ADDR0_LSB

#define PB7_BA_AUX_IRQ_ADDR2_MSB      DPRX14_AUX_AUX_IRQ_ADDR2_MSB
#define PB7_BB_AUX_IRQ_ADDR2_MSB1     DPRX14_AUX_AUX_IRQ_ADDR2_MSB1
#define PB7_BC_AUX_IRQ_ADDR2_LSB      DPRX14_AUX_AUX_IRQ_ADDR2_LSB
#define PB7_BD_AUX_IRQ_ADDR3_MSB      DPRX14_AUX_AUX_IRQ_ADDR3_MSB
#define PB7_BE_AUX_IRQ_ADDR3_MSB1     DPRX14_AUX_AUX_IRQ_ADDR3_MSB1
#define PB7_BF_AUX_IRQ_ADDR3_LSB      DPRX14_AUX_AUX_IRQ_ADDR3_LSB
#define PB7_C0_DPCD_CTRL              DPRX14_AUX_DPCD_CTRL
#define PB7_C1_DPCD_ADDR_PORT_H       DPRX14_AUX_DPCD_ADDR_PORT_H
#define PB7_C2_DPCD_ADDR_PORT_M       DPRX14_AUX_DPCD_ADDR_PORT_M
#define PB7_C3_DPCD_ADDR_PORT_L       DPRX14_AUX_DPCD_ADDR_PORT_L
#define PB7_C4_DPCD_DATA_PORT         DPRX14_AUX_DPCD_DATA_PORT

#define PB7_C6_AUX_PHY_DIG2           DPRX14_AUX_AUX_PHY_DIG2
#define PB7_C7_TP1_OCCR               DPRX14_AUX_TP1_OCCR

#define PB7_CC_DPCD_CONFIG_ADDR_FLAG  DPRX14_AUX_DPCD_CONFIG_ADDR_FLAG


#define PB7_D0_AUX_MODE_SET           DPRX14_AUX_AUX_MODE_SET
#define PB7_D1_DP_IIC_SET             DPRX14_AUX_DP_IIC_SET

#define PB7_DA_AUX_FIFO_RST           DPRX14_AUX_AUX_FIFO_RST
#define PB7_DB_AUX_STATUS             DPRX14_AUX_AUX_STATUS
#define PB7_DC_AUX_IRQ_STATUS         DPRX14_AUX_AUX_IRQ_STATUS
#define PB7_DD_AUX_DPCD_IRQ           DPRX14_AUX_AUX_DPCD_IRQ
#define PB7_DE_AUX_DPCD_IRQ_EN        DPRX14_AUX_AUX_DPCD_IRQ_EN

#define PB7_F0_AUX_TX_TIMER           DPRX14_AUX_AUX_TX_TIMER
#define PB7_F1_AUX_TX_TIMER_2         DPRX14_AUX_AUX_TX_TIMER_2

#define PB7_F4_MCUIIC                 DPRX14_AUX_MCUIIC

#endif
