/* SPDX-License-Identifier: GPL-2.0+
 * Copyright (c) 2017-2020 Realtek Semiconductor Corp.
 */

#ifndef SND_HIFI_RPC_H
#define SND_HIFI_RPC_H

#include <sound/pcm.h>
#include <soc/realtek/rtk-krpc-agent.h>

#define S_OK 0x10000000
#define SHMEM_OFFSET 384

#define MAX_CAR_CH 32

enum ENUM_AUDIO_KERNEL_RPC_CMD {
	ENUM_KERNEL_RPC_CREATE_AGENT,   // 0
	ENUM_KERNEL_RPC_INIT_RINGBUF,
	ENUM_KERNEL_RPC_PRIVATEINFO,
	ENUM_KERNEL_RPC_RUN,
	ENUM_KERNEL_RPC_PAUSE,
	ENUM_KERNEL_RPC_SWITCH_FOCUS,   // 5
	ENUM_KERNEL_RPC_MALLOC_ADDR,
	ENUM_KERNEL_RPC_VOLUME_CONTROL,      // AUDIO_CONFIG_COMMAND
	ENUM_KERNEL_RPC_FLUSH,               // AUDIO_RPC_SENDIO
	ENUM_KERNEL_RPC_CONNECT,             // AUDIO_RPC_CONNECTION
	ENUM_KERNEL_RPC_SETREFCLOCK,    // 10     // AUDIO_RPC_REFCLOCK
	ENUM_KERNEL_RPC_DAC_I2S_CONFIG,      // AUDIO_CONFIG_DAC_I2S
	ENUM_KERNEL_RPC_DAC_SPDIF_CONFIG,    // AUDIO_CONFIG_DAC_SPDIF
	ENUM_KERNEL_RPC_HDMI_OUT_EDID,       // AUDIO_HDMI_OUT_EDID_DATA
	ENUM_KERNEL_RPC_HDMI_OUT_EDID2,      // AUDIO_HDMI_OUT_EDID_DATA2
	ENUM_KERNEL_RPC_HDMI_SET,       // 15     // AUDIO_HDMI_SET
	ENUM_KERNEL_RPC_HDMI_MUTE,           //AUDIO_HDMI_MUTE_INFO
	ENUM_KERNEL_RPC_ASK_DBG_MEM_ADDR,
	ENUM_KERNEL_RPC_DESTROY,
	ENUM_KERNEL_RPC_STOP,
	ENUM_KERNEL_RPC_CHECK_READY,     // 20    // check if Audio get memory pool from AP
	ENUM_KERNEL_RPC_GET_MUTE_N_VOLUME,   // get mute and volume level
	ENUM_KERNEL_RPC_EOS,
	ENUM_KERNEL_RPC_ADC0_CONFIG,
	ENUM_KERNEL_RPC_ADC1_CONFIG,
	ENUM_KERNEL_RPC_ADC2_CONFIG,    // 25
#if defined(AUDIO_TV_PLATFORM)
	ENUM_KERNEL_RPC_BBADC_CONFIG,
	ENUM_KERNEL_RPC_I2SI_CONFIG,
	ENUM_KERNEL_RPC_SPDIFI_CONFIG,
#endif // AUDIO_TV_PLATFORM
	ENUM_KERNEL_RPC_HDMI_OUT_VSDB,
	ENUM_VIDEO_KERNEL_RPC_CONFIG_TV_SYSTEM,
	ENUM_VIDEO_KERNEL_RPC_CONFIG_HDMI_INFO_FRAME,
	ENUM_VIDEO_KERNEL_RPC_QUERY_DISPLAY_WIN,
	ENUM_VIDEO_KERNEL_RPC_PP_INIT_PIN,
	ENUM_KERNEL_RPC_INIT_RINGBUF_AO, //need check this enum
	ENUM_VIDEO_KERNEL_RPC_VOUT_EDID_DATA,
	ENUM_KERNEL_RPC_AUDIO_POWER_SET,
	ENUM_VIDEO_KERNEL_RPC_VOUT_VDAC_SET,
	ENUM_VIDEO_KERNEL_RPC_QUERY_CONFIG_TV_SYSTEM,
	ENUM_KERNEL_RPC_AUDIO_CONFIG,
	ENUM_KERNEL_RPC_AIO_PRIVATEINFO,
	ENUM_KERNEL_RPC_QUERY_FW_DEBUG_INFO,
	ENUM_KERNEL_RPC_HDMI_RX_LATENCY_MEM,
	ENUM_KERNEL_RPC_EQ_CONFIG,
	ENUM_VIDEO_KERNEL_RPC_CREATE,
	ENUM_VIDEO_KERNEL_RPC_DISPLAY,
	ENUM_VIDEO_KERNEL_RPC_CONFIGUREDISPLAYWINDOW,
	ENUM_VIDEO_KERNEL_RPC_SETREFCLOCK,
	ENUM_VIDEO_KERNEL_RPC_RUN,
	ENUM_VIDEO_KERNEL_RPC_INITRINGBUFFER,
	ENUM_VIDEO_KERNEL_RPC_SETRESCALEMODE,
	ENUM_VIDEO_KERNEL_RPC_SET_HDMI_VRR,
	ENUM_VIDEO_KERNEL_RPC_CONFIGURE_GRAPHIC_CANVAS,
	ENUM_VIDEO_KERNEL_RPC_SET_MIXER_ORDER,
	ENUM_KERNEL_RPC_DEC_PRIVATEINFO,
	ENUM_KERNEL_RPC_ALSA_FASTER,
	ENUM_VIDEO_KERNEL_RPC_PAUSE,
	ENUM_VIDEO_KERNEL_RPC_STOP,
	ENUM_VIDEO_KERNEL_RPC_DESTROY,
	ENUM_VIDEO_KERNEL_RPC_FLUSH,
	ENUM_VIDEO_KERNEL_RPC_Q_PARAMETER,
	ENUM_VIDEO_KERNEL_RPC_CONFIGCHANNELLOWDELAY,
	ENUM_VIDEO_KERNEL_RPC_PRIVATEINFO,
	ENUM_VIDEO_KERNEL_RPC_QUERYDISPLAYWINNEW,
	ENUM_VIDEO_KERNEL_RPC_SETSPEED,
	ENUM_VIDEO_KERNEL_RPC_SETBACKGROUND,
	ENUM_VIDEO_KERNEL_RPC_KEEPCURPIC,
	ENUM_VIDEO_KERNEL_RPC_KEEPCURPIC_FW_MALLOC,
	ENUM_VIDEO_KERNEL_RPC_KEEPCURPICSVP,
	ENUM_VIDEO_KERNEL_RPC_SET_DEINTFLAG,
	ENUM_VIDEO_KERNEL_RPC_CREATEGRAPHICWINDOW,
	ENUM_VIDEO_KERNEL_RPC_DRAWGRAPHICWINDOW,
	ENUM_VIDEO_KERNEL_RPC_MODIFYGRAPHICWINDOW,
	ENUM_VIDEO_KERNEL_RPC_DELETEGRAPHICWINDOW,
	ENUM_VIDEO_KERNEL_RPC_CONFIGUREOSDPALETTE,
	ENUM_VIDEO_KERNEL_RPC_PMIXER_CONFIGUREPLANEMIXER,
	ENUM_VIDEO_KERNEL_RPC_SET_DISPLAY_OUTPUT_FORMAT,
	ENUM_VIDEO_KERNEL_RPC_GET_DISPLAY_OUTPUT_FORMAT,
	ENUM_VIDEO_KERNEL_RPC_SET_ENHANCEDSDR,
	ENUM_KERNEL_RPC_HDMI_EDID_RAW_DATA,
	ENUM_VIDEO_KERNEL_RPC_ConfigWriteBackFlow,
	ENUM_VIDEO_KERNEL_RPC_NPP_Init,
	ENUM_VIDEO_KERNEL_RPC_NPP_Destroy,
	ENUM_KERNEL_RPC_AFW_DEBUGLEVEL,
	ENUM_KERNEL_RPC_DV_ControlPath_Info,
	ENUM_KERNEL_RPC_GET_AFW_DEBUGLEVEL,
	ENUM_KERNEL_RPC_ConfigureDisplayWindowDispZoomWinRatio,
	ENUM_VIDEO_KERNEL_RPC_GET_MIXER_ORDER,
	ENUM_VIDEO_KERNEL_RPC_SET_DISPLAY_OUTPUT_INTERFACE,
	ENUM_VIDEO_KERNEL_RPC_GET_DISPLAY_OUTPUT_INTERFACE,
	ENUM_KERNEL_RPC_SET_BTPCM_CFG,
	ENUM_KERNEL_RPC_SET_AI_TDM_CFG,
	ENUM_KERNEL_RPC_EXT_EQ_CONFIG,
	ENUM_KERNEL_RPC_AUDIO_MULTI_AO_CONFIG,
	ENUM_KERNEL_RPC_LITE_AO_CREATE,
	ENUM_KERNEL_RPC_LITE_AO_DESTROY,
	ENUM_KERNEL_RPC_PARAM_EQ_CONFIG,
	ENUM_KERNEL_RPC_STEREO_TO_MULTICH_CONFIG,
	ENUM_KERNEL_RPC_LOUDNESS_CONFIG,
	ENUM_KERNEL_RPC_GET_CACHE_CONFIG,
};

enum {
	ENUM_MEMORY_CFG_UNKNOWN = 0,
	ENUM_MEMORY_CFG_ALL_CACHE,
	ENUM_MEMORY_CFG_WITH_UNCACHE,
};

enum AUDIO_MODULE_TYPE {
	AUDIO_OUT = 7,
	AUDIO_IN = 8,
	AUDIO_ENCODER = 9,
	AUDIO_MPEG_ENCODER = 10,
	AUDIO_ALSA_OUT = 12,
	AUDIO_PSEUDO_OUT = 14,
	AUDIO_PP_OUT = 15,
	AUDIO_DECODER = 16,
	AUDIO_UNKNOWN = 17,
	AUDIO_LPCM_ENCODER = 19,
	AUDIO_AAC_ENCODER = 21,
	AUDIO_MP3_ENCODER = 22,
	AUDIO_RV_PARSER = 23,
	AUDIO_AC3_ENCODER = 24,
	AUDIO_VIENNA_OUT = 25,
	AUDIO_DTS_ENCODER = 26,
	AUDIO_VP6_PARSER = 27,
	AUDIO_IN_DEVICE = 28,
	AUDIO_ILBC_ENCODER = 29,
	AUDIO_KARAOKE_MIXER = 30,
	AUDIO_VP8_PARSER = 31,
	AUDIO_SILK_ENCODER = 32,
	AUDIO_G729_ENCODER = 33,
	AUDIO_PCMU_ENCODER = 34,
	AUDIO_PCMA_ENCODER = 35,
	VIDEO_OUT = 36,
	AUDIO_DDP_ENCODER = 37,
	AUDIO_MS_PP = 38,
	AUDIO_MS_DECODER = 39,
	AUDIO_PRE_PROCESSING = 40,
	AUDIO_DAP = 41,
	VIDEO_OUT_SECURE = 42,
	AUDIO_OUT_SECURE = 43,
	AUDIO_MAT_ENCODER = 44,
	VIDEO_OUT_DEINTERLACE_SECURE = 45,
	VIDEO_OUT_CVBS_SECURE = 46,
	VIDEO_OUT_KEEPLAST_SECURE = 47,
	AUDIO_OUT2 = 48,
};

enum AUDIO_IO_PIN {
	BASE_BS_IN = 0,
	EXT_BS_IN = 1,
	PCM_IN = 2,
	BASE_BS_OUT = 3,
	EXT_BS_OUT = 4,
	PCM_OUT = 5,
	SPDIF_IN = 6,
	SPDIF_OUT = 7,
	NON_PCM_OUT = 8,
	INBAND_QUEUE = 9,
	MESSAGE_QUEUE = 10,
	MIC_IN = 11,
	SOUND_EVENT_IN = 12,
	PCM_OUT1 = 13,
	PCM_OUT2 = 14,
	FLASH_AUDIO_PIN_1 = 15,
	FLASH_AUDIO_PIN_2 = 16,
	FLASH_AUDIO_PIN_3 = 17,
	FLASH_AUDIO_PIN_4 = 18,
	FLASH_AUDIO_PIN_5 = 19,
	FLASH_AUDIO_PIN_6 = 20,
	FLASH_AUDIO_PIN_7 = 21,
	FLASH_AUDIO_PIN_8 = 22,
	FLASH_AUDIO_PIN_9 = 23,
	FLASH_AUDIO_PIN_10 = 24,
	FLASH_AUDIO_PIN_11 = 25,
	FLASH_AUDIO_PIN_12 = 26,
	FLASH_AUDIO_PIN_13 = 27,
	FLASH_AUDIO_PIN_14 = 28,
	FLASH_AUDIO_PIN_15 = 29,
	FLASH_AUDIO_PIN_16 = 30,
	ASSOCIATED_PCM_IN = 31,
	EXTERNAL_PCM_IN = 32,
	SYSTEM_PCM_IN = 33,
	APP_PCM_IN = 34,
	DOWNMIX_PCM_OUT = 35,
	RAW_PCM_OUT = 36,
	EXT_PCM_OUT = 37,
	EXT_INBAND_QUEUE = 38,
	NON_PCM_IN = 39,
	DTS_LA_IN0 = 40,
	DTS_LA_IN1 = 41,
	DTS_LA_IN2 = 42,
	DTS_LA_IN3 = 43,
	DTS_LA_IN4 = 44,
	DTS_LA_IN5 = 45,
	DTS_LA_IN6 = 46,
	DTS_LA_IN7 = 47,
	TDM_IN = 48,
	PCM_PACKED_IN = 49,
	APP_PCM_OUT = 50,
	APP_LPCM_OUT = 51,
	DWNSTRM_INBAND_QUEUE = 200,
	EXT_DWNSTRM_INBAND_QUEUE = 201,
	RAWOUT_INFOOUT_QUEUE = 202,
	RAWOUT_INFOIN_QUEUE = 203,
};

enum AUDIO_ENUM_PRIVAETINFO {
	ENUM_PRIVATEINFO_AUDIO_FORMAT_PARSER_CAPABILITY = 0,
	ENUM_PRIVATEINFO_AUDIO_DECODER_CAPABILITY = 1,
	ENUM_PRIVATEINFO_AUDIO_CONFIG_CMD_BS_INFO = 2,
	ENUM_PRIVATEINFO_AUDIO_CHECK_LPCM_ENDIANESS = 3,
	ENUM_PRIVATEINFO_AUDIO_CONFIG_CMD_AO_DELAY_INFO = 4,
	ENUM_PRIVATEINFO_AUDIO_AO_CHANNEL_VOLUME_LEVEL = 5,
	ENUM_PRIVATEINFO_AUDIO_GET_FLASH_PIN = 6,
	ENUM_PRIVATEINFO_AUDIO_RELEASE_FLASH_PIN = 7,
	ENUM_PRIVATEINFO_AUDIO_GET_MUTE_N_VOLUME = 8,
	ENUM_PRIVATEINFO_AUDIO_AO_MONITOR_FULLNESS = 9,
	ENUM_PRIVATEINFO_AUDIO_CONTROL_FLASH_VOLUME = 10,
	ENUM_PRIVATEINFO_AUDIO_CONTROL_DAC_SWITCH = 11,
	ENUM_PRIVATEINFO_AUDIO_PREPROCESS_CONFIG = 12,
	ENUM_PRIVATEINFO_AUDIO_CHECK_SECURITY_ID = 13,
	ENUM_PRIVATEINFO_AUDIO_LOW_DELAY_PARAMETERS = 14,
	ENUM_PRIVATEINFO_AUDIO_SET_NETWORK_JITTER = 15,
	ENUM_PRIVATEINFO_AUDIO_GET_QUEUE_DATA_SIZE = 16,
	ENUM_PRIVATEINFO_AUDIO_GET_SHARE_MEMORY_FROM_ALSA = 17,
	ENUM_PRIVATEINFO_AUDIO_AI_CONNECT_ALSA = 18,
	ENUM_PRIVATEINFO_AUDIO_SET_PCM_FORMAT = 19,
	ENUM_PRIVATEINFO_AUDIO_DO_SELF_DESTROY_FLOW = 20,
	ENUM_PRIVATEINFO_AUDIO_GET_SAMPLING_RATE = 21,
	ENUM_PRIVATEINFO_AUDIO_SLAVE_TIMEOUT_THRESHOLD = 22,
	ENUM_PRIVATEINFO_AUDIO_GET_GLOBAL_AO_INSTANCEID = 23,
	ENUM_PRIVATEINFO_AUDIO_SET_CEC_PARAMETERS = 24,
	ENUM_PRIVATEINFO_AUDIO_INIT_DBG_DUMP_MEM = 25,
	ENUM_PRIVATEINFO_AUDIO_AI_GET_AO_FLASH_PIN = 26,
	ENUM_PRIVATEINFO_AUDIO_AI_SET_AO_FLASH_PIN = 27,
	ENUM_PRIVATEINFO_AUDIO_GET_PP_FREE_PINID = 28,
	ENUM_PRIVATEINFO_AUDIO_HDMI_RX_CONNECT_TO_BT = 29,
	ENUM_PRIVATEINFO_AUDIO_GET_BS_ERR_RATE = 30,
	ENUM_PRIVATEINFO_AUDIO_SET_RESUME_IR_KEYS = 31,
	ENUM_PRIVATEINFO_SET_GSTREAMER_PTS_ACC_MODE = 32,
	ENUM_PRIVATEINFO_AUDIO_GET_BONDING_TYPE = 33,
	ENUM_PRIVATEINFO_AUDIO_SHARE_MEMORY_FOR_PORTING_FIRMWARE = 34,
	ENUM_PRIVATEINFO_AUDIO_SET_DVDPLAYER_AO_VERSION = 35,
	ENUM_PRIVATEINFO_AUDIO_MS_PP_CERT = 36,
	ENUM_PRIVATEINFO_AUDIO_TRIGGER_EVENT = 37,
	ENUM_PRIVATEINFO_AUDIO_AI_NON_PCM_IN = 38,
	ENUM_PRIVATEINFO_OMX_AUDIO_VERSION = 39,
	ENUM_PRIVATEINFO_AUDIO_AI_PAD_IN = 40,
	ENUM_PRIVATEINFO_AUDIO_MS_MAJOR_DECODER_PIN = 41,
	ENUM_PRIVATEINFO_AUDIO_PROVIDE_RAWOUT_LATENCY = 42,
	ENUM_PRIVATEINFO_AUDIO_MS_MIXER_IGNORE_PIN = 43,
	ENUM_PRIVATEINFO_AUDIO_MS_CERTIFICATION_PLATFORM = 44,
	ENUM_PRIVATEINFO_AUDIO_MS_MIXER_PIN_NEW_SEG = 45,
	ENUM_PRIVATEINFO_AUDIO_MS_DEC_DROP_BY_PTS = 46,
	ENUM_PRIVATEINFO_AUDIO_MS_DEC_INIT_PTS_OFFSET = 47,
	ENUM_PRIVATEINFO_AUDIO_MS_PP_OUTPUT_TYPE = 48,
	ENUM_PRIVATEINFO_AUDIO_DTS_ENCODER_CONFIG = 49,
	ENUM_PRIVATEINFO_AUDIO_GET_FW_VERSION = 50,
	ENUM_PRIVATEINFO_AUDIO_DTS_M8_IN_CONFIG = 51,
	ENUM_PRIVATEINFO_AUDIO_DTS_M8_LA_NUM = 52,
	ENUM_PRIVATEINFO_AUDIO_DTS_M8_SET_OUTPUT_FORMAT = 53,
	ENUM_PRIVATEINFO_AUDIO_SET_DRC_CFG = 54,
	ENUM_PRIVATEINFO_AUDIO_DTS_M8_LA_ERROR_MSG = 55,
	ENUM_PRIVATEINFO_GET_B_VALUE = 56,
	ENUM_PRIVATEINFO_AUDIO_ENTER_SUSPEND = 57,
	ENUM_PRIVATEINFO_AUDIO_MPEGH_IN_CONFIG = 58,
	ENUM_PRIVATEINFO_AUDIO_SET_LOW_WATERLEVEL = 59,
};

enum AUDIO_ENUM_AIO_PRIVAETINFO {
	ENUM_PRIVATEINFO_AIO_AO_INTERFACE_SWITCH_CONTROL = 0,
	ENUM_PRIVATEINFO_AIO_AI_INTERFACE_SWITCH_CONTROL = 1,
	ENUM_PRIVATEINFO_AIO_ALSA_DESTROY_AI_FLOW = 2,
	ENUM_PRIVATEINFO_AIO_AI_NONPCM_WRITE_BACK_BS = 3,
	ENUM_PRIVATEINFO_AIO_HDMIRX_LATENCY_MEM = 4,
	ENUM_PRIVATEINFO_AIO_AI_LOOPBACK_AO = 5,
	ENUM_PRIVATEINFO_AIO_AI_LOOPBACK_HDMITX = 6,
	ENUM_PRIVATEINFO_AIO_AI_LOOPBACK_DAC = 7,
	ENUM_PRIVATEINFO_AIO_AI_ADC_ANALOG = 8,
	ENUM_PRIVATEINFO_AIO_AI_MULTIPLE_ADC = 9,
	ENUM_PRIVATEINFO_AIO_AI_ADC_AMIC = 9 + 1,
	ENUM_PRIVATEINFO_AIO_KERNEL_RPC = 9 + 2,
	ENUM_PRIVATEINFO_AIO_SET_SE_CLK = 9 + 3,
	ENUM_PRIVATEINFO_AIO_AI_PRIVATEINFO = 9 + 4,
	ENUM_PRIVATEINFO_AIO_DELIVER_SCPU_FW_PID = 9 + 5,
	ENUM_PRIVATEINFO_AIO_GET_D_VISION_CAPABILITY = 9 + 6,
	ENUM_PRIVATEINFO_AIO_GET_AUDIO_PROCESSING_AI = 9 + 7,
	ENUM_PRIVATEINFO_AIO_AI_GET_HW_VALID = 9 + 8,
	ENUM_PRIVATEINFO_AIO_IS_EARC_C = 9 + 9,
	ENUM_PRIVATEINFO_AIO_AO_FLASH_LPCM = 9 + 10,
	ENUM_PRIVATEINFO_AIO_TRSENC_INFO = 9 + 11,
	ENUM_PRIVATEINFO_AIO_AI_PAUSE_HW = 9 + 12,
	ENUM_PRIVATEINFO_AIO_PCMR_OUT_FORMAT = 9 + 13,
	ENUM_PRIVATEINFO_AIO_SYS_APP_SND_EXIST = 9 + 14,
	ENUM_PRIVATEINFO_AIO_ENC_EOS_INFO = 9 + 15,
	ENUM_PRIVATEINFO_AIO_MSV2_3_PARAM_DOWNMIXED_MODE = 9 + 16,
	ENUM_PRIVATEINFO_AIO_MSV2_3_PARAM_DRC_MODE = 9 + 17,
	ENUM_PRIVATEINFO_AIO_MSV2_3_PARAM_MC_DRC_CUT = 9 + 18,
	ENUM_PRIVATEINFO_AIO_MSV2_3_PARAM_MC_DRC_BOOST = 9 + 19,
	ENUM_PRIVATEINFO_AIO_MSV2_3_PARAM_DMX_DRC_CUT = 9 + 20,
	ENUM_PRIVATEINFO_AIO_MSV2_3_PARAM_DMX_DRC_BOOST = 9 + 21,
	ENUM_PRIVATEINFO_AIO_MSV2_6_NEW_FLOW_OUTPUT_TYPE = 9 + 22,
	ENUM_PRIVATEINFO_AIO_MSV2_6_NEW_FLOW_LISTENING_DAP_TUNING_INFO = 9 + 23,
	ENUM_PRIVATEINFO_AIO_MSV2_6_NEW_FLOW_LISTENING_DAP_TUNING_MAPPING = 9 + 24,
	ENUM_PRIVATEINFO_AIO_MSV2_6_NEW_FLOW_LISTENING_IS_PCMR_SECONDARY_OUT = 9 + 25,
	ENUM_PRIVATEINFO_AIO_MSV2_6_NEW_FLOW_LISTENING_DAP_SPEAKER_LAST_2CH_OUT = 9 + 26,
	ENUM_PRIVATEINFO_AIO_MSV2_3_PARAM_LOUDNESS_EQUIVALENCE_MODE = 9 + 27,
	ENUM_PRIVATEINFO_AIO_MSV2_6_NEW_FLOW_SECONDARY_OUT_CH_NUM = 9 + 28,
	ENUM_PRIVATEINFO_AIO_MSV2_6_HDMI_OUTPUT_TYPE = 9 + 29,
	ENUM_PRIVATEINFO_AIO_AO_PCM_PIN_LPCM = 9 + 30,
	ENUM_PRIVATEINFO_AIO_IS_FORCE_MASTER_REFRESH_RCD = 9 + 31,
	ENUM_PRIVATEINFO_AIO_AO_FLASH_PIN_MIX_CH_MAP = 9 + 32,
	ENUM_PRIVATEINFO_AIO_AO_BT_PCM_INFO = 9 + 33,
	ENUM_PRIVATEINFO_AIO_WISA_SPEAKER_CH_CONFIG = 9 + 34,
	ENUM_PRIVATEINFO_AIO_AI_HW_VOLUME_CTRL = 9 + 35,
	ENUM_PRIVATEINFO_AIO_AI_GLOBAL_CONFIG = 9 + 36,
	ENUM_PRIVATEINFO_AIO_AO_SET_PIN_VSDB = 9 + 37,
	ENUM_PRIVATEINFO_AIO_AO_FLASH_CHANGE_HW_SAMPLE_RATE = 9 + 38,
	ENUM_PRIVATEINFO_AIO_TOTAL_NUM = 9 + 39,
};

enum AUDIO_ENUM_AI_GLOBAL_CONFIG {
	ENUM_AUDIO_AI_GLOBAL_CONFIG_MIC_VOLTAGE = 0,
	ENUM_AUDIO_AI_GLOBAL_CONFIG_HW_MUTE,
	ENUM_AUDIO_AI_GLOBAL_CONFIG_GET_HW_MUTE,
};

enum
{
	ENUM_AO_FLASH_CHANGE_HW_SAMPLE_RATE_DEFAULT = 0,
	ENUM_AO_FLASH_CHANGE_HW_SAMPLE_RATE_ENABLED,
	ENUM_AO_FLASH_CHANGE_HW_SAMPLE_RATE_DISABLED,
};

enum ENUM_AI_PRIVATE_TYPE {
	ENUM_AI_PRIVATE_MUTE = 0,
	ENUM_AI_PRIVATE_WRITE_BACK_SYSTEM,
	ENUM_AI_PRIVATE_HDMI_RX_TO_SET_AO_FLASH,
	ENUM_AI_PRIVATE_HDMI_RX_TO_GET_AO_FLASH,
	ENUM_AI_PRIVATE_HDMI_RX_CONNECT_TO_BT_INFO,
	ENUM_AI_PRIVATE_NON_PCM_IN,
	ENUM_AI_PRIVATE_SET_PAD_SOURCE,
	ENUM_AI_PRIVATE_NONPCM_WRITE_BACK_BS,
	ENUM_AI_PRIVATE_LOOPBACK_AO,
	ENUM_AI_PRIVATE_ADC_ANALOG,
	ENUM_AI_PRIVATE_MULTIPLE_ADC,
	ENUM_AI_PRIVATE_ADC_AMIC,     // 11
	ENUM_AI_PRIVATE_ADC_SWAP,
	ENUM_AI_PRIVATE_ADC_SET_VOLUME,
	ENUM_AI_PRIVATE_AUDIO_PROCESSING,
	ENUM_AI_PRIVATE_VOLUME_CTRL,
	ENUM_AI_PRIVATE_WRITE_BACK_SYSTEM_EXT,
	ENUM_AI_PRIVATE_HDMIRX_AUDIO_INFO_FRAME,
	ENUM_AI_PRIVATE_HACK_1KHZ_WITHOUT_HW = 12 + 6,
	ENUM_AI_PRIVATE_SPDIF_OPTICAL = 12 + 7,
	ENUM_AI_PRIVATE_HDMI_RX = 12 + 8,
	ENUM_AI_PRIVATE_SPDIF_COAXIAL = 12 + 9,
	ENUM_AI_PRIVATE_SPDIF_ARC = 12 + 10,
	ENUM_AI_PRIVATE_ADC_DMIC = 12 + 11,
	ENUM_AI_PRIVATE_TDM = 12 + 12,
	ENUM_AI_PRIVATE_ADC_DMIC_PACK = 12 + 13,
	ENUM_AI_PRIVATE_SELF_FLUSH = 12 + 14,
	ENUM_AI_PRIVATE_CONFIG_PIN_MUX = 12 + 15,
	ENUM_AI_PRIVATE_DUMP_NONPCM = 12 + 16,
	ENUM_AI_PRIVATE_DUAL_DMIC_AND_LOOPBACK = 12 + 17,
	ENUM_AI_PRIVATE_DUAL_DMIC_AND_LOOPBACK_FW = 12 + 18,
	ENUM_AI_PRIVATE_SPEECH_RECOGNITION_FROM_DMIC = 12 + 19,
	ENUM_AI_PRIVATE_SPEECH_RECOGNITION_FROM_DMIC_FW = 12 + 20,
	ENUM_AI_PRIVATE_HDMIRX_INFO_KYLIN = 12 + 21,
	ENUM_AI_PRIVATE_EARC = 12 + 22,
	ENUM_AI_PRIVATE_QUEUE_DELAY = 12 + 23,
	ENUM_AI_PRIVATE_EARC_HW_INIT = 12 + 24,
	ENUM_AI_PRIVATE_PAUSE_HW = 12 + 25,
	ENUM_AI_PRIVATE_RK_LH = 12 + 26,
	ENUM_AI_PRIVATE_MUTE_HW = 12 + 27,
	ENUM_AI_PRIVATE_INIT_ACPU2_RINGBUF = 12 + 28,
	ENUM_AI_PRIVATE_I2S_1 = 12 + 29,
	ENUM_AI_PRIVATE_I2S_2 = 12 + 30,
	ENUM_AI_PRIVATE_I2S_3 = 12 + 31,
	ENUM_AI_PRIVATE_BTPCM = 12 + 32,
	ENUM_AI_PRIVATE_TDM_1 = 12 + 33,
	ENUM_AI_PRIVATE_TDM_2 = 12 + 34,
	ENUM_AI_PRIVATE_TDM_3 = 12 + 35,
	ENUM_AI_PRIVATE_ANGLOG = 12 + 36,
	ENUM_AI_PRIVATE_ANGLOG_1 = 12 + 37,
	ENUM_AI_PRIVATE_STI2S = 12 + 38,
	ENUM_AI_PRIVATE_STI2S_1 = 12 + 39,
	ENUM_AI_PRIVATE_EQ = 12 + 40,
	ENUM_AI_PRIVATE_BEAMFORMING = 12 + 41,
	ENUM_AI_PRIVATE_DPRX = 12 + 42,
	ENUM_AI_PRIVATE_TOTAL_NUM = 12 + 43,
};

enum AUDIO_ENDIANTYPE {
	AUDIO_BIG_ENDIAN        = 0,       // CD,DVD type
	AUDIO_LITTLE_ENDIAN     = 1,
	AUDIO_LPCM_DHMV_TYPE    = 2,       // HDMV type
};

enum ENUM_AUDIO_CHANNEL_OUT_INDEX {
	ENUM_AUDIO_NULL_CHANNEL_INDEX = 0,

	ENUM_AUDIO_LEFT_FRONT_INDEX = 1,            // L
	ENUM_AUDIO_RIGHT_FRONT_INDEX = 2,           // R
	ENUM_AUDIO_CENTER_FRONT_INDEX = 5,          // C
	ENUM_AUDIO_LFE_INDEX = 6,                   // LFE
	ENUM_AUDIO_LEFT_SURROUND_REAR_INDEX = 3,    // Ls or Lsr
	ENUM_AUDIO_RIGHT_SURROUND_REAR_INDEX = 4,   // Rs or Rsr
	ENUM_AUDIO_LEFT_OUTSIDE_FRONT_INDEX = 7,    // ENUM_AUDIO_LEFT_SURROUND_SIDE_INDEX,  Lss
	ENUM_AUDIO_RIGHT_OUTSIDE_FRONT_INDEX = 8,   // ENUM_AUDIO_RIGHT_SURROUND_SIDE_INDEX, Rss
	ENUM_AUDIO_SPDIF_LEFT_CHANNEL_INDEX = 9,
	ENUM_AUDIO_SPDIF_RIGHT_CHANNEL_INDEX = 10,

	ENUM_AUDIO_SURROUND_INDEX = 11,
	ENUM_AUDIO_CENTER_SURROUND_REAR_INDEX = 12,
	ENUM_AUDIO_OverHead_INDEX = 13,

	ENUM_AUDIO_LEFT_SURROUND_INDEX = 14,
	ENUM_AUDIO_RIGHT_SURROUND_INDEX = 15,
	ENUM_AUDIO_LEFT_FRONT_HIGH_INDEX = 16,
	ENUM_AUDIO_RIGHT_FRONT_HIGH_INDEX = 17,
	ENUM_AUDIO_LEFT_INNER_FRONT_INDEX = 18,
	ENUM_AUDIO_RIGHT_INNER_FRONT_INDEX = 19,
	ENUM_AUDIO_LEFT_REAR_INDEX = 20,
	ENUM_AUDIO_RIGHT_REAR_INDEX = 21,
	ENUM_AUDIO_LEFT_SURROUND_DIRECT_INDEX = 22,
	ENUM_AUDIO_RIGHT_SURROUND_DIRECT_INDEX = 23,
	ENUM_AUDIO_CENTER_FRONT_HIGH_INDEX = 24,
	ENUM_AUDIO_LFE2_INDEX = 25,

	ENUM_AUDIO_SPDIF_NON_PCM_TYPE = 256,
	ENUM_AUDIO_ENABLE_DOWNMIX = 257
};

enum {
	ENUM_DT_AO_DAC    = 0,
	ENUM_DT_AO_I2S    = 1,
	ENUM_DT_AO_SPDIF  = 2,
	ENUM_DT_AO_HDMI   = 3,
	ENUM_DT_AO_GLOBAL = 4,
	ENUM_DT_AO_TDM    = 5,
	ENUM_DT_AO_TDM1   = 6,
	ENUM_DT_AO_TDM2   = 7,
	ENUM_DT_AO_I2S1   = 8,
	ENUM_DT_AO_I2S2   = 9,
	ENUM_DT_AO_BTPCM  = 10,
	ENUM_DT_AO_BTPCM_TEST  = 11,
};

enum AUDIO_ENUM_AI_LOOPBACK_DEV {
	ENUM_RPC_AI_LOOPBACK_HDMITX = 0,
	ENUM_RPC_AI_LOOPBACK_DAC = 0 + 1,
	ENUM_RPC_AI_LOOPBACK_FROM_AO_I2S = 0 + 2,
	ENUM_RPC_AI_LOOPBACK_FROM_AO_SPDIF = 0 + 3,
	ENUM_RPC_AI_LOOPBACK_FROM_AO_HDMI = 0 + 4,
	ENUM_RPC_AI_LOOPBACK_TOTAL_NUM = 0 + 5,
};

enum AUDIO_FORMAT_OF_AI_SEND_TO_ALSA {
	AUDIO_ALSA_FORMAT_32BITS_BE_PCM = 0,
	AUDIO_ALSA_FORMAT_16BITS_LE_LPCM = 1,
	AUDIO_ALSA_FORMAT_24BITS_LE_LPCM = 2,
	AUDIO_ALSA_FORMAT_NONE = 3,
	AUDIO_ALSA_FORMAT_32BITS_LE_LPCM = 3 + 1,
	AUDIO_ALSA_FORMAT_TOTAL_NUM = 3 + 2,
};

enum ENUM_I2S_MODE_USER
{
	ENUM_AI_I2S_SHARE = 0,
	ENUM_AI_I2S_MASTER,
	ENUM_AI_I2S_SLAVE,
	ENUM_AI_I2S_SLAVE_ENFORCE,
};

enum ENUM_I2S_MODE {
	ENUM_AI_I2S_PIN_SHARE = 0,  // using AO i2s0
	ENUM_AI_I2S_PIN_INDEPENDENT_MASTER,
	ENUM_AI_I2S_PIN_INDEPENDENT_SLAVE,
	ENUM_AI_I2S_PIN_SHARE_AO_I2S1,  // using AO i2s1
	ENUM_AI_I2S_PIN_SHARE_AO_I2S2,  // using AO i2s2
	ENUM_AI_I2S_PIN_SHARE_AI_I2S0,  // using AI i2s0
	ENUM_AI_I2S_PIN_SLAVE_ENFORCE,  // using AI i2s0
	ENUM_AI_I2S_PIN_SHARE_TOTAL // keep the last
};

enum ENUM_TDM_MODE {
	ENUM_TDM_PIN_SHARE_NONE = 0,
	ENUM_TDM_PIN_SHARE_AO_TDM_0,
	ENUM_TDM_PIN_SHARE_AO_TDM_1,
	ENUM_TDM_PIN_SHARE_AO_TDM_2,
	ENUM_TDM_PIN_SHARE_AI_TDM_0,
};

enum ENUM_TDMIN_FMT {
	ENUM_TDM_FMT_UNKNOWN = 0,
	ENUM_TDM_FMT_I2S,
	ENUM_TDM_FMT_LEFT_JUSTIFIED,
	ENUM_TDM_FMT_MODE_A,
	ENUM_TDM_FMT_MODE_B,
	ENUM_TDM_FMT_MODE_A_NEGTIVE,
	ENUM_TDM_FMT_MODE_B_NEGTIVE
};

enum{
	ENUM_AIN_STI2S_NORMAL_SPLIT = 0,
	ENUM_AIN_STI2S_NORMAL_MUX,
	ENUM_AIN_STI2S_NORMAL_AFE,
	ENUM_AIN_STI2S_BURST_SPLIT,
	ENUM_AIN_STI2S_BURST_MUX,
	ENUM_AIN_STI2S_BURST_AFE,
};

struct rpc_analog_config {
	char adc_voltage;
	char analog_gain_l;
	char digital_gain_l;
	char adc_differential_l;
	char digital_gain_en;
	char digital_gain_r;
	char analog_gain_r;
	char adc_differential_r;
	int rvd[2];
};

struct alsa_latency_info {
	unsigned int latency;
	unsigned int ptsl;
	unsigned int ptsh;
	unsigned int sum; /* latency + ptsL */
	unsigned int decin_wp;
	unsigned int sync;
	unsigned int dec_in_delay;
	unsigned int dec_out_delay;
	unsigned int ao_delay;
	int rvd[8];
};

struct ringbuf_header_ptrs {
	unsigned int *p_magic;
	unsigned int *p_begin_addr;
	unsigned int *p_size;
	unsigned int *p_buffer_id;
	unsigned int *p_write_ptr;
	unsigned int *p_num_read_ptr;
	unsigned int *p_read_ptr;
	int *p_file_offset;
	int *p_requested_file_offset;
	int *p_file_size;
	int *p_seekable;
	struct alsa_latency_info *p_latency;
};

struct rpc_data {
	struct rpc_struct info;
	unsigned int command;
	unsigned int param1;
	unsigned int param2;
};

struct rpc_result {
	unsigned int result;
	int data;
};

struct rpc_aio_ctrl {
	unsigned int bitmap;
	unsigned int i2s_ch;
	unsigned int i2s_mode;
};

struct rpc_privateinfo_result {
	int instance_id;
	volatile int private_info[16];
};

struct rpc_ringbuffer_header {
	int instance_id;
	int pin_id;
	int ringbuffer_header_list[8];
	int read_idx;
	int list_size;
};

struct rpc_tdmin_config {
	int version;
	int data_format;
	int bclk;
	int lrck;
	int sample_rate;
	char i2s_channel_len;
	char slave_mode;
	char channel_num;
	char slot;
	char data_len;
	char tdm_channel_len;
	char pin_share;
	char rvd1[1];
	int rvd[7];
};

struct rpc_create_ao_agent {
	int instance_id;
	int type;
};

struct rpc_connection {
	int src_instance_id;
	int src_pin_id;
	int des_instance_id;
	int des_pin_id;
	int media_type;
	int reserved[27];
};

struct rpc_privateinfo_param {
	int instance_id;
	unsigned int type;
	volatile int private_info[16];
	short parameter[32];
};

struct rtk_rpc_priv {
	struct rtk_krpc_ept_info *ept;

	void *vaddr;
	dma_addr_t paddr;

	struct rpc_data data;
};

int rpc_create_audio_agent(struct rtk_rpc_priv *priv, int pin, int *ao_id);
int rpc_init_ringbuffer_header(struct rtk_rpc_priv *priv,
			      struct rpc_ringbuffer_header *rpc);
int rpc_put_shmem_latency(struct rtk_rpc_priv *priv, int ao_id, int pin, void *p);
int init_ringbuf_header_ptrs(struct ringbuf_header_ptrs *ptrs,
			     void *base, bool cacheable);
int rpc_connect_svc(struct rtk_rpc_priv *priv, int src_id, int src_pin,
		    int des_id, int des_pin);
int rpc_pause_svc(struct rtk_rpc_priv *priv, int id);
int rpc_run_svc(struct rtk_rpc_priv *priv, int id);
int rpc_stop_svc(struct rtk_rpc_priv *priv, int id);
int rpc_destroy_svc(struct rtk_rpc_priv *priv, int id);
int rpc_get_global_ao(struct rtk_rpc_priv *priv, int *ao_id);
int rpc_get_ao_flash_pin(struct rtk_rpc_priv *priv, int ao_id, int *pin);
int rpc_put_ao_flash_pin(struct rtk_rpc_priv *priv, int ao_id, int *pin);
int rpc_set_ao_flash_volume(struct rtk_rpc_priv *priv, int ao_id, int pin, int volume);
int rpc_set_ao_mixidx(struct rtk_rpc_priv *priv, int ao_id, int pin, int *idx);
int rpc_get_chache_config(struct rtk_rpc_priv *priv, int *cacheable);
int rpc_config_ao(struct rtk_rpc_priv *priv, int ao_id, int pin, int *idx,
		  struct snd_pcm_runtime *runtime);
int rpc_ctrl_aio(struct rtk_rpc_priv *priv, int ao_id, struct rpc_aio_ctrl *ctrl);
int rpc_ept_init(struct rtk_rpc_priv *priv);
int rpc_config_dprx_in(struct rtk_rpc_priv *priv, int ai_id, int ao_id, int pin);
int rpc_config_i2s_in(struct rtk_rpc_priv *priv, int ai_id, int id, int mode);
int rpc_config_sti2s_in(struct rtk_rpc_priv *priv, int ai_id);
int rpc_config_pdm_in(struct rtk_rpc_priv *priv, int ai_id);
int rpc_config_tdm_in(struct rtk_rpc_priv *priv, int ai_id, struct rpc_tdmin_config *config);
int rpc_config_adc_in(struct rtk_rpc_priv *priv, struct snd_pcm_runtime *runtime,
		      int ai_id, int path, struct rpc_analog_config *config);
int rpc_config_loopback_in(struct rtk_rpc_priv *priv, int ai_id);
int rpc_ai_connect_alsa(struct rtk_rpc_priv *priv,
			struct snd_pcm_runtime *runtime, int ai_id);
int rpc_destroy_ai_flow(struct rtk_rpc_priv *priv, int ai_id, int configured);

#endif /* SND_HIFI_RPC_H */
