ccflags-y += -I$(srctree)/sound/soc/realtek/common/
ccflags-y += -I$(srctree)/drivers/soc/realtek/common/rpc

obj-$(CONFIG_SND_SOC_REALTEK_NOTIFY) += snd-realtek-notify.o

snd-realtek-notify-y += drv.o
snd-realtek-notify-y += buf.o
snd-realtek-notify-y += rpc.o
